litestar-org/litestar

- tests/unit/test_params.py
This PR adds tests for consistency of behavior of query params between kwargs declared with and without `typing.Annotated`.
These tests were created when debugging #2514, however that issue was solved by PR #2516. I figure we may as well still add the tests.
> test: query param consistency with Annotated

- .github/workflows/ci.yml
- .github/workflows/test.yml
- litestar/channels/backends/redis.py
- litestar/cli/_utils.py
- litestar/constants.py
- litestar/events/emitter.py
- litestar/logging/config.py
- litestar/middleware/authentication.py
- litestar/middleware/base.py
- litestar/params.py
- litestar/routes/base.py
- litestar/security/base.py
- litestar/stores/base.py
- litestar/template/base.py
- litestar/types/protocols.py
- litestar/utils/compat.py
- litestar/utils/predicates.py
- litestar/utils/signature.py
- litestar/utils/version.py
- pyproject.toml
We do a lot of `pragma: no cover` due to coverage only being reported on the highest version of python.
This PR modifies coverage reporting so that we run coverage tests on the lowest and highest supported versions, and combines the coverage reports.
-
-
> build: run code coverage on min and max py vers

- litestar/middleware/logging.py
- tests/unit/test_middleware/test_logging_middleware.py
When structlog is not installed, the body will not get parsed and shown as a byte sequence. This byte sequence is then serialized into a string with the assumption that it is valid UTF-8. This is not always the case, eg. when uploading a file.
Therefore, use backslashreplace to handle invalid UTF-8 sequences.
I don't have a docker version that has the compose command installed, so those tests failed. I've checked that my changes do not cause more tests to fail then before. 
- Uploading binary files no longer causes an exception when request logging is active without structlog installed
- Fixes #2529
> fix: handle non UTF-8 data when logging requests

- litestar/types/callable_types.py
Modifies the definition to use a `TypeVar` bound to `Exception` so that these callables can be annotated to receive `Exception` subclasses.
Closes #2520
> fix: ExceptionHandler type.

- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_serialization_plugin.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_serialization_plugin_marking_fields.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
This PR removes any use of `sync_to_thread=True` from our sqlalchemy examples when there is no blocking IO in the dependency/handler.
Closes #2508
> docs: remove unnecessary use of `sync_to_thread=True`.

- litestar/constants.py
- litestar/middleware/csrf.py
- litestar/response/template.py
- litestar/template/base.py
- tests/unit/test_template/test_csrf_token.py
Current behavior is to add the token directly into scope with a private key, "_csrf_token". However, this causes type errors as scope is a typed dict and does not define that key.
We have an internal namespace inside scope state, this PR refactors csrf token management to use it.
Closes #2499
> refactor: use `{get,set}_litestar_scope_state()` for storing csrf tokens

- .github/workflows/ci.yml
- .github/workflows/test.yml
- Makefile
- litestar/__main__.py
- pdm.lock
- pyproject.toml
This PR adds the [covdefaults](https://github.com/asottile/covdefaults) plugin to our coverage config.
The plugin offers default configs for `[tool.coverage.run]` and `[tool.coverage.report]`.
For "run", the main difference is that it activates branch coverage. This is something I always run on other projects and I think would be a nice addition to our config. Our overall coverage score takes a hit, but it's not as bad as I thought it might be.
For reporting, it adds a `fail_under` value - which we don't currently have as we let sonar handle that. We can override their default of 100, so I set it to 96 which is our current baseline after branch coverage activated.
-
> build: implement covdefaults coverage plugin.

- litestar/_openapi/schema_generation/schema.py
- tests/unit/test_openapi/test_schema.py
PR fixes issue where we were treating an annotation such as `tuple[int, ...]` same as a heterogeneous tuple like `tuple[int, str]`.
Closes #2460
> fix: OpenaAPI handle tuple with ellipsis annotation

- litestar/channels/backends/memory.py
- litestar/channels/backends/redis.py
- tests/unit/test_channels/test_backends.py
Fix an issue with the channels backends where they would poll for new subscribers too frequently when no channel subscriptions were present, resulting in a high CPU load.
Fixes #2503
> fix(channels): Performance issue with polling without subscriptions

- litestar/_openapi/schema_generation/schema.py
- litestar/constants.py
- litestar/contrib/pydantic/pydantic_dto_factory.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/contrib/pydantic/utils.py
- litestar/plugins.py
- litestar/typing.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
- tests/unit/test_plugins.py
Decouple the Pydantic integration from the core logic.
In previous versions, Pydantic integration was baked into the core schema generation, causing issues when trying to run Litestar without it. A recent PR (#2487) surfaced some of these issues, causing an `ImportError` when Pydantic was not installed.
This PR is an attempt to remove all direct references to Pydantic from Litestar's core, although due to other constraints, some of these should be seen as temporary workarounds.
<hr>
One major issue preventing a clean solution here is the merging of the `ParseType` util into `FieldDefinition` that happened in #1912. This causes `FieldDefinition` to require information specific to Pydantic, which is not available to it, since this information is contained within the plugin, …
> fix(pydantic): Decouple Pydantic integration

- docs/tutorials/sqlalchemy/index.rst
fixes issue introduced by https://github.com/litestar-org/litestar/pull/2558
Incorrect: 
```
pip install 'litestar[standard,sqlalchemy] aiosqlite'
```
> ERROR: Invalid requirement: 'litestar[standard,sqlalchemy] aiosqlite'
Correct:
```
pip install 'litestar[standard,sqlalchemy]' aiosqlite
```
> docs: Fix typo in pip install command

- tests/unit/test_contrib/test_pydantic/__init__.py
- tests/unit/test_contrib/test_pydantic/conftest.py
- tests/unit/test_contrib/test_pydantic/test_integration.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py
The `pydantic_version` fixture returns strings of "v1" and "v2", however, we're using `if pydantic_version == "1"` as the branching condition in the tests.
This PR ensures that we are comparing the correct literal value in the tests.
-
> fix: pydantic version selection in tests

- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/schema_generation/utils.py
- litestar/typing.py
- tests/unit/test_openapi/test_schema.py
Existing behavior is to make the schema for every type that is a union with `None` a "one_of" schema, that includes `OpenAPIType.NULL` in the "one_of" types.
https://github.com/litestar-org/litestar/blob/5db8d81fbf24788d38d210e90300e5f0926f830a/litestar/_openapi/schema_generation/schema.py#L319-L340
When a `Literal` or `Enum` type is in a union with `None`, this behavior is not desirable, as we want to have `null` available in the list of available options on the type's schema.
This PR changes literal and enum schema generation so that it can be identified that the types are in a union with `None`, allowing `null` to be included in `Schema.enum` values.
Closes #2546
> fix: openapi schema for literal and enum unions with None.

- litestar/app.py
- litestar/openapi/config.py
- litestar/openapi/spec/components.py
- litestar/openapi/spec/open_api.py
- tests/unit/test_contrib/test_jwt/test_auth.py
- tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py
- tests/unit/test_security/test_security.py
`Litestar.update_openapi_schema()` is called whenever we first generate the openapi schema for an app object, and whenever we register a handler on the app.
Inside, we perform checks to ensure that the `OpenAPI` object has a not-none `components` attribute, and that the components attribute has a not-none `schema` attribute.
This PR modifies the definition of the `OpenAPI` type, and the `Component` type to remove the `None` union and instantiate an instance of the respective instance on construction.
Background to the change is that when addressing uncovered lines of code in the `app.py` module, I was unsure of how to hit this line: https://github.com/litestar-org/litestar/blob/fd06486e2ad4ed0a41636659fec4f093a09e3dd0/litestar/app.py#L835
Then realised that perhaps this whole block of …
> refactor: openapi default values

- litestar/config/response_cache.py
- tests/e2e/test_response_caching.py
- Fixes the bug(s?) in the linked issues by adding the HTTP method to the default key builder function `default_cache_key_builder`. Solution suggested by @provinzkraut  :innocent:
- Changes a few existing test cases that were dependent on the old format of key generation (without the HTTP method)
Closes #2588 and #2573
- Closes #2588 and #2573
> fix(cache): Caching route handlers with the same path but different methods

- litestar/cli/commands/core.py
- tests/unit/test_cli/test_core_commands.py
- tests/unit/test_cli/test_ssl.py
Fix a bug that would cause a uvicorn error when no SSL certificates were provided but the `--reload` or `--workers` options were used.
> fix(CLI): #2613 - SSL certificate feature breaks default no-tls setups when using reload or multiple workers

- litestar/_kwargs/cleanup.py
- litestar/app.py
- litestar/background_tasks.py
- litestar/contrib/jwt/middleware.py
- litestar/controller.py
- litestar/di.py
- litestar/events/listener.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/websocket_handlers/_utils.py
- litestar/handlers/websocket_handlers/listener.py
- litestar/middleware/rate_limit.py
- litestar/router.py
- litestar/routes/asgi.py
- litestar/security/base.py
- litestar/security/session_auth/middleware.py
- litestar/utils/__init__.py
- litestar/utils/helpers.py
- litestar/utils/sync.py
- tests/docker_service_fixtures.py
- tests/examples/test_contrib/test_sqlalchemy/plugins/test_example_apps.py
- tests/unit/test_utils/test_sync.py
- Remove unused functionality from `AsyncCallable`
- Remove `async_partial`
- Introduce `ensure_async_callable` helper function
Previously, we used the `AsyncCallable` to ensure a callable was async, always wrapping the receive callable. This PR moves to the `ensure_async_partial` function which simply returns the original callable if it's already an async callable, and only wraps it in a greatly simplified `AsyncPartial` if necessary.
This removes some layers of indirection and allows us to simplify how we're dealing with the callables passed to us.
-
> refactor(utils): Simplify sync utils

- litestar/_openapi/path_item.py
- litestar/app.py
- litestar/cli/commands/core.py
- litestar/controller.py
- litestar/di.py
- litestar/handlers/asgi_handlers.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/websocket_handlers/listener.py
- litestar/handlers/websocket_handlers/route_handler.py
- litestar/middleware/compression.py
- litestar/routes/asgi.py
- litestar/routes/http.py
- litestar/routes/websocket.py
- litestar/utils/__init__.py
- litestar/utils/helpers.py
- litestar/utils/sync.py
- tests/unit/test_kwargs/test_query_params.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_response/test_response_to_asgi_response.py
- tests/unit/test_signature/test_parsing.py
- tests/unit/test_signature/test_validation.py
- tests/unit/test_utils/test_predicates.py
Remove the `Ref` helper as it is not actually needed, saving us quite a bit of extra attribute lookups and complexity. 
<hr>
*Note: This branch is currently targetting `simplify-async-utils` (#2621) but should be merged into `main` after that branch is merged*
> refactor(utils): Remove `Ref` 

- litestar/_asgi/routing_trie/validate.py
- tests/e2e/test_routing/test_validations.py
Fix a recursion error in the ASGI router's node validation caused by a reference cycle.
- #2629
> fix(router): fix reference cycle in node validation

- pdm.lock
Generated a new `pdm.lock` in order to attempt to resolve the error seen while doing `pdm install`. 
```sh
[KeyError]: ('pydantic', '2.4.2', None, False)
```
> chore: regenerate lock file

- litestar/openapi/controller.py
- This attempts to fix an issue we have in production while using RapiDoc where the path is relative (?) to the open API config path but isnt picked up properly when behind a proxy.
<details>
<summary>Defaults</summary>
</details>
<details>
<summary>using correct path according to NGINX (works)</summary>
</details>
<details>
<summary>Using just the file name because its already going to look at your relative path (works)</summary>
</details>
This is what i've found works, but if this is a proxy issue, me issue, or can be fixed another way please let me know.
-
> fix: adjust rapidoc schema path

- litestar/contrib/pydantic/utils.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- Addresses a regression where there was an attempt to hash specific unhashable values (default literals from a Pydantic model).
- Closes #2635
> fix(openapi): Schema generation partially broken since litestar version 2.3.0

- litestar/_openapi/parameters.py
- litestar/_openapi/responses.py
- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/schema_generation/utils.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/openapi/spec/parameter.py
- litestar/openapi/spec/schema.py
- litestar/typing.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_openapi/test_integration.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_openapi/test_schema.py
- This PR fixes the format in which the examples are generated.
- Fixes #2272.
> fix: correct the format of the OpenAPI examples

- litestar/handlers/http_handlers/base.py
- Fix spacing for exceptions raised
hit these at work at it was a bit jarring
-
> fix: add space to the exception text

- docs/usage/stores.rst
- litestar/stores/memory.py
- Adds clarity around thread-safety and multiprocess-safety for `MemoryStore`.
- Closes issue #2651
> docs: update documentation for MemoryStore

- litestar/dto/field.py
- Adds the missing `write-only` mark string literal to `dto_field()` signature.
-
> fix: add missing mark literal to `dto_field()` signature

- litestar/connection/websocket.py
Modifies `WebSocket.wrapped_receive()` to raise `WebSocketDisconnect` instead of `WebSocketException` where `receive()` is called after a disconnect message has already been received.
-
> refactor: ws receive disconnect exc type

- docs/examples/templating/returning_templates_jinja.py
- docs/examples/templating/returning_templates_mako.py
- docs/examples/templating/returning_templates_minijinja.py
- docs/usage/templating.rst
- litestar/app.py
- litestar/config/app.py
- litestar/contrib/jinja.py
- litestar/contrib/mako.py
- litestar/contrib/minijinja.py
- litestar/response/template.py
- litestar/template/base.py
- tests/examples/test_templating/test_returning_templates.py
- tests/unit/test_contrib/test_minijinja.py
- tests/unit/test_template/test_template.py
- Adds a method to render HTML templates from strings
- Closes #2687
> feat(template): add ``template_str`` for rendering from strings

- Makefile
In the move to PDM in #2357 `make test` was modified to run `pytest tests` from `pytest tests -n auto`.
This appears to have been inadvertent, so this PR changes it back.
-
> chore: `make test` use multiple cores.

- litestar/utils/signature.py
- tests/unit/test_utils/test_signature.py
This PR changes the implementation `_unwrap_implicit_optional_hints()` so that it will flatten or remove any outer optional union, if an inner annotated union exists.
E.g., `Union[Annotated[Union[str, int], ...], NoneType]` becomes `Annotated[Union[str, int, Nonetype], ...]`.
Also, the case where a non-union annotated annotation is wrapped in an optional union, we move the outer union into the annotated type. e.g., the following func def:
```py
def fn(a: Annotated[int, ...] = None) -> ...
```
Will be parsed as `Union[Annotated[int, ...], NoneType]` by `get_type_hints()` prior to py 3.11. We convert it to `Annotated[Union[int, NoneType], ...]`.
Refactors the test suite to test that for any given annotation, after processing, the type argument to annotated is the same as the type that would …
> refactor: improve _unwrap_implicit_optional_hints impl

- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py
Add missing support for Pydantic's URL types (`AnyUrl` and its descendants) for both serialization and OpenAPI schema generation. These types were only partially supported previously; Serialization support was lacking for v1 and v2, and OpenAPI support was missing for v2.
- #2664
> fix(pydantic): Support URL types in OpenAPI and serialization

- tests/examples/test_templating/test_returning_templates.py
Fix a template test case introduced in #2689 that breaks on windows due to line endings
> chore(tests): Fix windows compat test for string template

- litestar/contrib/minijinja.py
- tests/unit/test_contrib/test_minijinja.py
Refactor the error handling of `render_string` to not catch `MiniJinjaTemplateNotFound`, which is not raised at that point, and adjust the test for it.
-
> chore(minijinja): Refactor error handling for `render_string`

- docs/usage/middleware/creating-middleware.rst
Edited the section on responding with middleware to use `litestar.response.redirect.ASGIRedirectResponse` instead of `litestar.response.redirect.Redirect`
Closes #2709
> fix: asgi redirect response in documentation

- .pre-commit-config.yaml
- Makefile
- This PR does the following:
- remove the `install-pdm.py` file that was fetched for installation
- Set the expected .venv directory as a string so that there is no errror printed when there is no existing venv.
- Set commands to run with `pdm run` when possible to ensure they are executed from the venv.
-
> chore: use `pdm run` where possible

- .pre-commit-config.yaml
This change has caused `make lint` and pre-commit in CI to only run two of the hooks.
E.g., https://github.com/litestar-org/litestar/actions/runs/6916362683/job/18816353425#step:6:29
If there is a more nuanced way to solve this then feel free to close this off in favor of another approach.
-
> fix: revert setting "default_stages" in pre-commit

- litestar/_signature/model.py
- tests/unit/test_signature/test_validation.py
This PR corrects an issue where multiple validation errors would receive the same error message in the validation error's "extra" detail.
Closes #2714
> fix: multiple validation error messages

- litestar/_openapi/schema_generation/utils.py
#2475 introduced a new regex with a potential for "catastrophic backtracking" ([SonarCloud analysis](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=litestar-org_litestar&open=AYvgiwx-edsUYnEP43pU)). This is fixed by introducing explicit grouping.
> fix: Explicit grouping for regex in OpenAPI type name normalization

- litestar/_openapi/schema_generation/utils.py
This regex is used to remove superfluous chars from the start and end of the schema keys that we generate for openapi.
Sonar reports two issues to do with the original implementation:
1. a reliability issue to do with operator precedence
2. a security issue to do with backtracking
This PR refactors the regex so that it has less parts and less scope for backtracking.
A follow up to #2706 
-
> refactor: OpenAPI type name trimming regex

- litestar/datastructures/url.py
This PR fixes an issue where mypy would infer the type of `datastructures.URL` to be `Any`. This was caused by the use of the `@lrucache` decorator on `URL.__new__()`. We had ignored the error, however mypy would report:
> litestar/datastructures/url.py:85: error: Unsupported decorated constructor type  [misc]
The fix adds a new `@classmethod`, `URL._new()` which is cached and called from `URL.__new__()`.
-
> fix: typing of datastructures.URL

- litestar/app.py
- litestar/config/app.py
- litestar/template/config.py
- litestar/types/internal_types.py
Currently, this code:
```py
template_config = TemplateConfig(instance=JinjaTemplateEngine())
app = Litestar(route_handlers=[], template_config=template_config)
```
Reports:
```
app.py:10: error: Argument "template_config" to "Litestar" has incompatible type "TemplateConfig[JinjaTemplateEngine]"; expected "Optional[TemplateConfig[TemplateEngineProtocol[Any, Any]]]"  [arg-type]
```
This PR modifies the annotation to use a bound generic instead of directly typing the template engine type as `TemplateEngineProtocol`.
-
> fix: app `template_config` parameter type

- litestar/cli/_utils.py
- tests/unit/test_cli/conftest.py
- tests/unit/test_cli/test_core_commands.py
- This PR allows for registered CLI plugins to be visible in the `help` menus of the click commands.  Without it, you must set the `app` and `app-dir` setting on the command before the extra CLI commands are visible.
-
> feat: set app env on startup

- docs/usage/middleware/builtin-middleware.rst
- [] New code has 100% test coverage
- [] Tests were ran and passed
Removed extra sentence at the end of Rate-Limit Middleware in `/docs/usage/middleware/builtin-middleware.rst`
-
-
> docs: Removed extra sentence in 'Rate-Limit Middleware' Section

- litestar/_kwargs/extractors.py
- tests/unit/test_datastructures/test_upload_file.py
- tests/unit/test_kwargs/test_multipart_data.py
- properly handles multiple file uploads
When multiple files are uploaded, the following logic, causes the creation of a list of lists which is invalid for the type `list[UploadFile]`.
https://github.com/litestar-org/litestar/blob/df00253891b09c8831b2b9025cf7e5471e68ac07/litestar/_kwargs/extractors.py#L353-L354
However, if the annotation is `list[UploadFile]` and only one file is uploaded, then `list(form_values.values())` will give back a list of UploadFile instances due to the logic here:
https://github.com/litestar-org/litestar/blob/df00253891b09c8831b2b9025cf7e5471e68ac07/litestar/_multipart.py#L162
Furthermore, this PR assumes that if multiple files are being uploaded, then all the files will have the same value for "name" within the form data. This is the expected behavior as per …
> fix: correctly handle multiple file upload

- CONTRIBUTING.rst
Add a missing hyphen in the type checking `make` command.
> docs: Fix type checking command in CONTRIBUTING.rst

- litestar/connection/base.py
- litestar/connection/request.py
- litestar/enums.py
- tests/unit/test_connection/test_request.py
To improve the handling of [ASGI extensions](https://asgi.readthedocs.io/en/latest/extensions.html), this PR:
- Introduces an `ASGIExtension` enum, holding the names of ASGI extensions
- Adds a `_server_extensions` attribute to `ASGIConnection`
- Adds a `supports_server_push` attribute to `Request`, allowing to check if it is supported before attempting to push. Additionally, a warning is raised when push is not supported. Optionally, this method can now be configured to raise an exception instead of a warning; This behaviour should be made the default in 3.0
> feat: Improve ASGI extension interface

- litestar/security/jwt/auth.py
- litestar/security/jwt/middleware.py
`contrib.jwt` imports from ` security.jwt` which was importing from `contrib.jwt`, and so on.
This PR removes the `contrib` imports from the main lib.
Closes #2782
> fix: remove imports from `contrib.jwt` from `security.jwt`.

- litestar/_kwargs/dependencies.py
- litestar/di.py
- litestar/utils/__init__.py
- litestar/utils/predicates.py
- tests/unit/test_deprecations.py
- tests/unit/test_di.py
This PR makes it a configuration error to attempt to `use_cache=True` with generator dependencies.
Prior to this implementation, this would result in a 500 error at runtime.
The reason for making this a config error is that after the first use of the generator the cleanup code executes and so subsequent use of the generated value is dubious.
Closes #2771
> fix: raise config error when yield dependencies are cached

- litestar/_openapi/parameters.py
- tests/unit/test_openapi/test_integration.py
Previous behavior would consider two parameters with the same name but declared in different places (eg., header, cookie) as an error.
This PR incorporates the "param_in" value when validating params for openapi spec so that it would only be an error to have differing parameters, of the same name declared in the same place.
Closes #2662
> fix: deduplication of openapi params

- litestar/handlers/base.py
- tests/unit/test_handlers/test_base_handlers/test_validations.py
This PR resolves an issue where a handler would be allowed to be registered with a `DTOData` annotation, but no `dto` defined.
This is now a configuration error.
Closes #2779
> fix: DTOData annotation without DTO

- litestar/_openapi/schema_generation/schema.py
- tests/unit/test_openapi/test_parameters.py
We have been setting properties on the schema object using camelCase names when they are declared with snake_case names.
We've been using this mapping:
https://github.com/litestar-org/litestar/blob/9f6ddf43928c6deb033f18fcec5aed21772192ff/litestar/_openapi/schema_generation/schema.py#L79-L98
...for converting values from the `KwargDefinition` object to the `Schema` object, where the keys are the names on `KwargDefinition` and the values are supposed to be the names on the `Schema` object. Which takes place here:
https://github.com/litestar-org/litestar/blob/9f6ddf43928c6deb033f18fcec5aed21772192ff/litestar/_openapi/schema_generation/schema.py#L640-L647
Note that some of the values in that mapping are pointing to camelCase names, but we define the names as snake_case on the schema type. …
> fix: setting props on schema using camelCase names

- litestar/events/emitter.py
- tests/unit/test_events.py
This PR prevents exceptions raised from within event handlers from closing the event receive stream, and from further propagation beyond the event emitter backend.
When an exception is caught from an event handler, we log it at ERROR level.
Closes #2809
> fix: event handler error breaks stream

- litestar/events/emitter.py
- litestar/events/listener.py
This PR corrects an implementation made in #2810 that prevented listeners from running concurrently.
For #2809
> fix: concurrent event listener execution

- .github/workflows/pr-target.yml
Add an action that ensures `feat`-type PRs cannot be merged into `main` directly. Instead, they should be merge into `develop` or a feature branch.
> ci: validate feature PR target

- docs/index.rst
- litestar/_openapi/datastructures.py
- litestar/_openapi/parameters.py
- litestar/_openapi/plugin.py
- litestar/_openapi/responses.py
- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/schema_generation/utils.py
- tests/examples/test_openapi.py
- tests/helpers.py
- tests/unit/test_contrib/test_attrs/test_schema_plugin.py
- tests/unit/test_contrib/test_attrs/test_schema_spec_generation.py
- tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
- tests/unit/test_contrib/test_repository.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
- tests/unit/test_openapi/test_integration.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_openapi/test_path_item.py
- tests/unit/test_openapi/test_request_body.py
- tests/unit/test_openapi/test_responses.py
- tests/unit/test_openapi/test_schema.py
- tests/unit/test_openapi/test_spec_generation.py
- tests/unit/test_pagination.py
https://github.com/litestar-org/litestar/commit/219355c0e322fab41c921c56ca97d356b7ef868b#diff-6cdcc2ab6bdeda3d72588f3b65db0c437f7ba9cad43892829e75c4d701f9e658R659-R661 introduced a change to the way that keys for the openapi components/schemas object were calculated to address name the possibility of name collisions.
This PR reverts that behavior for the case where a name has no collision, and only introduces extended keys for the case where there are multiple objects with the same name.
To do this, it replaces the pattern of carrying the `components/schemas` section of the openapi document around in the `OpenAPIContext` object, and replaces it with a `SchemaRegistry` object.
The schema registry tracks all schemas created for named objects, and any references to them. Once all schemas are …
> fix: components schema key names

- litestar/_signature/model.py
- tests/unit/test_signature/test_parsing.py
By the time the signature model is parsed, the DTO has already validated and built the object to be injected as `data`, so we don't need the signature model to do it again.
This PR ensures that `data` fields are typed as `Any` on the signature model so that validation doesn't occur twice.
This is a regression introduced in #2088, so I've added an explicit test for it.
Closes #2149
> fix: no signature model data validation if DTO

- .github/workflows/docs.yml
Use `pdm sync` for building docs environment so that pdm won't ever generate a new lock file which causes the subsequent checkout in the `build_docs.py` tool to fail.
Closes #2853
> fix(ci): docs build

- tests/unit/test_logging/test_logging_config.py
Fix some broken test configurations that would cause logs to spill during test runs
> test(logging): Fix logging setup

- tests/examples/test_contrib/test_sqlalchemy/plugins/test_tutorial_example_apps.py
- tests/unit/test_cli/test_cli.py
- tests/unit/test_cli/test_env_resolution.py
This test is flaky and best guess is it has to do with executing across multiple cores. This marker ensures they will run on the same node.
See https://discord.com/channels/919193495116337154/1151927578370768958/threads/1179281714653184122
> test: xdist group cli autodiscovery tests

- litestar/_openapi/plugin.py
- tests/unit/test_openapi/test_integration.py
This PR fixes an issue where the OpenAPI schema generation would fail when there are multiple route handlers for a given path.
Fixes #2863.
> fix(openapi): correctly process routes with multiple route handlers

- litestar/app.py
This PR gives the static files handler a name in the `app.url_for_static_asset` example. A named handler is required for this method to work as expected.
> docs: name the static files handler

- docs/usage/templating.rst
The template engines will escape the created `input` tag automatically. We have to mark them as safe in order to prevent that behavior.
> docs: ensure 'csrf_input' doesn't get escaped

- litestar/_openapi/schema_generation/__init__.py
- litestar/_openapi/schema_generation/plugins/__init__.py
- litestar/_openapi/schema_generation/plugins/dataclass.py
- litestar/_openapi/schema_generation/plugins/pagination.py
- litestar/_openapi/schema_generation/plugins/struct.py
- litestar/_openapi/schema_generation/plugins/typed_dict.py
- litestar/_openapi/schema_generation/schema.py
- litestar/app.py
- litestar/plugins/base.py
- tests/helpers.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
- tests/unit/test_openapi/test_responses.py
- tests/unit/test_openapi/test_schema.py
Instead of having separate methods on the `SchemaCreator` object for types like structs, dataclasses and typeddicts, this PR implements their schema generators as `OpenAPISchemaPlugin` types and adds them to the application's plugins on instantiation.
> refactor: use OpenAPISchemaPlugin for all supported complex types

- .github/workflows/ci.yml
- .github/workflows/test.yml
The latest changes in these actions have broken the way that we upload coverage reports for later combining, before shipping to sonar.
Additionally, in testing different approaches, I hit https://github.com/actions/download-artifact/issues/249 on multiple occasions - an issue I've never noticed with v3 of these actions.
This PR proposes that we remain on v3 until a good solution can be found for the combined coverage issue, and to give a bit of time for v4 issues to be resolved.
> build: revert bump to artifact actions

- litestar/_kwargs/extractors.py
- litestar/routes/http.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_kwargs/test_json_data.py
- tests/unit/test_kwargs/test_msgpack_data.py
This PR allows the kwarg model data extractors to return `Empty` in the case where there is no payload data.
This allows us to remove the `"data"` key from the connection kwargs that are validated per the handler signature, so that default values can be properly applied.
Prior to this fix, a handler like:
```py
@post(path="/", sync_to_thread=False)
def test(data: str = "abc") -> dict:
return {"foo": data}
```
And a request like:
```
$ curl localhost:8000 -X POST
```
would return a client error like:
```json
{"status_code":400,"detail":"Validation failed for POST http://localhost:8000/","extra":[{"message":"Expected `str`, got `null`","key":"data","source":"body"}]}
```
This PR also also allows us to divert from invoking the DTO for deserialization when there is no payload data which would …
> fix: support for empty payload data

- litestar/handlers/http_handlers/_utils.py
- litestar/handlers/http_handlers/base.py
- tests/unit/test_handlers/test_http_handlers/test_validations.py
This PR improves our detection of invalid response annotations for handlers that return a 204 response.
We have always checked that the return type was `NoneType`, now we additionally check if the return type is a subclass of `Response` that has been specialized with `NoneType` as its content.
Closes #2914
> fix: support `Response[None]` for 204 handler

- docs/topics/sync-vs-async.rst
fixed tiny grammar mistake on [docs](https://docs.litestar.dev/2/topics/sync-vs-async.html#when-to-use-an-asynchronous-function)
> docs: correct a tiny grammar mistake

- litestar/logging/config.py
- tests/unit/test_logging/test_logging_config.py
- Currently, `Litestar.get_logger` is `get_logger_placeholder` only when the app initialized by keyword argument `logging_config=None`.
- We using this keyword argument as workaround for an issue like #2862
- `request.logger` is a property that returns `self.app.get_logger()`. It calls `Litestar.get_logger` with no argument. In standard library or picologging, it is allowed and will return root logger.
- code: https://github.com/litestar-org/litestar/blob/d8322b7a588a0a272d8b611d7d0c6ab1d2ccc326/litestar/connection/base.py#L268-L278
- But `get_logger_placeholder` doesn't allow calling it with no argument. So, when you initialize app with no logging_config and try to use `request.logger`, the error is not as intended.
- Actual
```text
TypeError: get_logger_placeholder() missing 1 required …
```
> fix: unintended error message from `get_logger_placeholder()`

- litestar/stores/redis.py
- There is a raw conditional expression to check `Empty` with default value. And I found an utility function `litestar.utils.empty.value_or_default` that does same thing. So I suggest to replace the conditional expression with the function: https://github.com/litestar-org/litestar/blob/8153d5b8b53d3a703f86dae90e765f56f5f4bac8/litestar/utils/empty.py#L14-L26
> refactor: use value_or_default instead of conditional expression

- litestar/middleware/logging.py
PR replaces unnecessary use of `default_factory` with `default` for dataclass fields on the `LoggingMiddlewareConfig` where the default value returned by the factory requires no computation and is immutable.
As far as I understand, By specifying a factory function for a mutable default value, each instance gets its own independent copy of the default value, `preventing unintended sharing of mutable state between instances`. This helps in maintaining encapsulation and avoiding potential side effects that could arise from shared mutable state.
However, in the code, `default_factory was not used for such a purpose`. Therefore, I suggest `using default to avoid misinterpretation of usage`.
> refactor: replace unnecessary use of `default_factory` with `default`

- tests/unit/test_cli/test_core_commands.py
Fix an issue introduced in #2894 that would cause tests to fail if they are not pinned to an xidst worker.
> test(CLI): Fix xdist issue

- docs/reference/concurrency.rst
- litestar/concurrency.py
- litestar/datastructures/upload_file.py
- litestar/file_system.py
- litestar/response/sse.py
- litestar/stores/file.py
- litestar/utils/sync.py
- tests/unit/test_concurrency.py
- Replace `anyio.to_thread.run_sync` with native versions of supported libraries, i.e. [`asyncio.loop.run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) and [`trio.to_thread.run_sync`](https://trio.readthedocs.io/en/stable/reference-core.html#trio.to_thread.run_sync)
- Add `set_asyncio_executor` and `get_asyncio_executor` utility functions to configure the executor used when running synchronous functions
- Add `set_trio_capacity_limiter` and `get_trio_capacity_limiter` utility functions to configure the `trio.CapacityLimiter` used when running synchronous functions
<hr>
Reasons for this change are twofold:
1. Performance improvements. Anyio has some [known performance overhead](https://github.com/agronholm/anyio/discussions/543), and …
> feat(core): Replace `anyio.to_thread.run_sync` with native versions

- pyproject.toml
Suppress a few Pydantic deprecation warnings that have piled up, which we don't want to address until Pydantic v3 is out and we drop support for v1.
> chore: Suppress pydantic deprecation warnings

- litestar/middleware/exceptions/_debug_response.py
- litestar/middleware/exceptions/middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Fix a bug that would cause a `SerializationException` when custom types were present within a `ValidationException`, which would be the case if a Pydantic error was passed verbatim. 
The fix is to pass along the `type_encoders` resolved from the route handler of the originating request.
Fixes #2867.
> fix: #2867 - Ensure `type_encoders` are passed to exception response

- CONTRIBUTING.rst
Fixes tiny bug on the CONTRIBUTING.rst
Currently, just a line above https://docs.litestar.dev/latest/contribution-guide.html#creating-a-new-release, the docs are cut-off after "This is equivalent to:"
After the fix:
> fix: CONTRIBUTING.rst "Automatically execute examples" bug fix

- docs/tutorials/sqlalchemy/0-introduction.rst
in Official docs: [Serialization section ](https://docs.litestar.dev/2/tutorials/sqlalchemy/0-introduction.html#serialization)in SQLAlchemy tutorial seems broken. Minor fix in this PR to pick and highlight relevant lines from code.
> docs: fix serialization example in SQLAlchemy tutorial

- litestar/_kwargs/extractors.py
- tests/unit/test_kwargs/test_multipart_data.py
This applies the same fix as in #2753 except that it iterates though all the fields and performs the check to see if the expected type is a list and converts the value into a list if it's not. 
Fixes #2939.
> fix: handle single file in cases of multiple file uploads

- .github/workflows/pr-target.yml
Adds new CI workflow triggeredon comment to request users update their target base
e.g., if `feat:` is not found in the PR title you get this:
plus a failed CI task (that will need to be mandatory i guess)
> ci: add new feature notifier

- docs/tutorials/dto-tutorial/01-simple-dto-exclude.rst
> docs: fix typo for dto-tutorial/01-simple-dto-exclude

- tests/unit/test_concurrency.py
Bring `litestar.concurrency` to 100% coverage
> test: Improve `litestar.concurrency` coverage

- Makefile
Reintroduce the `-W` flag for `sphinx-build` to treat warnings as errors so we don't accidentally merge PRs that later fail on docs build.
> chore: Re-introduce treating `sphinx-build` warnings as errors

- litestar/_openapi/schema_generation/plugins/struct.py
- tests/unit/test_openapi/test_schema.py
Fix #2971 by checking for union types in the schema plugin as suggested by @peterschutt in [this comment](https://github.com/litestar-org/litestar/issues/2971#issuecomment-1884725385).
The following code would raise an `AttributeError` 
```python
import msgspec
from litestar import get
from litestar.testing import create_test_client
class StructA(msgspec.Struct):
pass
class StructB(msgspec.Struct):
pass
@get("/")
async def handler() -> StructA | StructB:
return StructA()
``` 
and when including `None` in the union of the return value
```python
import msgspec
from litestar import get
from litestar.testing import create_test_client
class StructA(msgspec.Struct):
pass
class StructB(msgspec.Struct):
pass
@get("/")
async def handler() -> StructA | StructB | None:
return StructA()
with …
```
> fix(2971): OpenAPI schema generation fails for Union of Structs when including `None`

- litestar/utils/helpers.py
- In `get_name` helper function, the `value` argument is not necessary to be `Any`. `object`(Top type in Python) is sufficient and safer type annotation.
- And `object` annotation matches with the function's docstring: `value: An arbitrary object.`
---
Reference: https://docs.python.org/3/library/typing.html#the-any-type
> Use [object](https://docs.python.org/3/library/functions.html#object) to indicate that a value could be any type in a typesafe manner. Use [Any](https://docs.python.org/3/library/typing.html#typing.Any) to indicate that a value is dynamically typed.
> refactor: replace Any with object in get_name helper func

- .github/workflows/notify-released-issues.yml
- .github/workflows/notify_released_issues/get_closed_issues.py
- .github/workflows/notify_released_issues/notify.js
- .github/workflows/publish.yml
- .pre-commit-config.yaml
Add a workflow that creates a comment on issues that have been closed once their fix has been released.
We record information about closed issues in our release notes. Once a release has been published, the workflow grabs the changes for the release from the release notes, extracts the issues that have been fixed and uses the GitHub API to create a comment on each issue with a link to the release.
<hr>
I tried making this work via GitHub's API but it turns out that it's not that straightforward so ultimately I decided to simply extract the information from our release notes, which I think is more reliably anyway since we have control over what goes in there.
> ci: Add workflow to notify issues for released fixes

- docs/reference/security/jwt.rst
Added missing title for `reference/security/jwt` docs page.
> docs: Add missing title for `reference/security/jwt`

- .github/workflows/notify_released_issues/notify.js
- .github/workflows/publish.yml
- Make the comment link to the HTML version of the release instead of GitHub's API
- Only notify when a release has been successfully triggered
> ci: Fix release link in released fix notifier

- litestar/app.py
- tests/unit/test_logging/test_structlog_config.py
The last commit auto-merged even though the sonar scan failed.  It looks like I accidentally merged in the previous tests on top of the updates.
This PR re-adds those tests.
> fix: re-add `structlog` tests

- litestar/_kwargs/extractors.py
Refactor the multipart extractor function to not define the extractor inline but use a `partial` instead to bind defaults.
> refactor(extractors): Don't define multipart extractor inline

- litestar/handlers/http_handlers/decorators.py
- litestar/handlers/websocket_handlers/listener.py
- litestar/handlers/websocket_handlers/route_handler.py
Removes unnecessarily repeated Nones in type unions introduced in 619cafb.
> refactor: removed duplicated type hints

- docs/examples/static_files/custom_router.py
- docs/examples/static_files/file_system.py
- docs/examples/static_files/full_example.py
- docs/examples/static_files/html_mode.py
- docs/examples/static_files/passing_options.py
- docs/examples/static_files/route_reverse.py
- docs/examples/static_files/send_as_attachment.py
- docs/examples/static_files/upgrade_from_static_1.py
- docs/examples/static_files/upgrade_from_static_2.py
- docs/usage/static-files.rst
- litestar/app.py
- litestar/static_files/__init__.py
- litestar/static_files/base.py
- litestar/static_files/config.py
- tests/examples/test_static_files.py
- tests/unit/test_static_files/conftest.py
- tests/unit/test_static_files/test_create_static_router.py
- tests/unit/test_static_files/test_file_serving_resolution.py
- tests/unit/test_static_files/test_html_mode.py
- tests/unit/test_static_files/test_static_files_validation.py
Implement static file serving with regular route handlers instead of a specialised ASGI app. At the moment, this is complementary to the usage of `StaticFilesConfig` to keep backwards compatibility.
This achieves a few things:
- Fixes #2629
- Circumvents all of the special casing we have to do in our routing logic for the static files app
- Allows us to drop said special casing when removing the old functionality
- Removes the need for a `static_files_config` on the app
- Removes the need for a special `url_for_static_asset` method on the app since `route_reverse` can be used instead
Additionally:
- Most router options can now be passed to the `create_static_files_router`, allowing further customisation
- A new `resolve_symlinks` flag has been added, defaulting to `True` to keep backwards …
> feat: Implement static file serving with regular route handlers

- litestar/testing/helpers.py
in `create_async_test_client` docstring:
- `TestClient` -> `AsyncTestClient`
- `create_test_client` -> `create_async_test_client`
> docs: Fix create_async_test_client docstring

- docs/usage/openapi.rst
There is an incorrect argument name in the ResponseSpec example in the docs. ResponseSpec has no `model` arg, so when I tried to use this example I got `TypeError: ResponseSpec.__init__() got an unexpected keyword argument 'model'` exception.
The correct arg name seems to be `data_container`, so I've updated the docs accordingly.
> docs: Fix incorrect argument name in OpenApi ResponseSpec example

- litestar/contrib/piccolo.py
- tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py
For Picollo columns with `secret=True` set, mark those columns as `WRITE_ONLY` to prevent the column being included in `return_dto`.
Closes #2976
> feat: sanitize Piccolo columns with secret=True from PydanticDTO output

- codecov.yml
- litestar/cli/_utils.py
- litestar/cli/commands/core.py
- litestar/cli/commands/schema.py
- litestar/cli/commands/sessions.py
- litestar/cli/main.py
- tests/unit/test_cli/test_ssl.py
This PR does the following CLI cleanup items:
- use `find_spec` to set "library found" variables
- Rich click's CLI patcher only needs to run once.  From then on we can import the normal click types.  I've removed a few of these conditional checks.
- Only create the beautifier class when executed
- Typo fix
> fix: simplify conditional logic check for libraries

- .github/workflows/pr-merged.yml
Add a workflow triggered by merged PRs that:
- Closes linked issues if PRs are merged into `develop` (since GitHub doesn't do this automatically)
- Adds a comment to linked issues with a notice about which release the patch will be included in
> ci: Add workflow for merged PRs

- .github/workflows/ci.yml
- litestar/_asgi/asgi_router.py
- pdm.lock
- pyproject.toml
- tests/e2e/test_routing/conftest.py
- tests/e2e/test_routing/test_path_mounting.py
- tests/e2e/test_routing/test_path_resolution.py
As described in #2998, uvicorn change its `root_path` behaviour, which now diverges from most other ASGI servers. To ensure we handle all servers and cases properly I've implemented a fix here and added a few tests against common servers (uvicorn, hypercorn and daphne).
> fix: Handle diverging ASGI `root_path` behaviour

- litestar/response/sse.py
- litestar/types/__init__.py
- litestar/types/helper_types.py
- tests/unit/test_response/test_sse.py
fixes small typing error:
```
error: Argument 1 to "ServerSentEvent" has incompatible type "AsyncIterable[ServerSentEventMessage]"; expected "str | bytes | Iterable[str | bytes] | Iterator[str | bytes] | AsyncIterable[str | bytes] | AsyncIterator[str | bytes]"  [arg-type]
```
inside `test_sse` there was a `Any` I changed to trigger the test then solved it.
> fix: ServerSentEvent typing error

- litestar/_asgi/asgi_router.py
Nginx Unit ASGI server does not set "root_path" in the ASGI scope, which is expected as part of the changes done in #3039. This PR fixes the assumption that the key is always present and instead tries to optionally retrieve it.
Issue originaly reported over at [Discord](https://discord.com/channels/919193495116337154/919193495690936353/1202204676003745792)
```
KeyError on GET /
'root_path'
```
> fix: Handle `KeyError` when `root_path` is not present in ASGI scope

- litestar/datastructures/state.py
- Fixes improperly render API reference docs (https://docs.litestar.dev/latest/reference/datastructures.html#litestar.datastructures.State) for code example.
> fix(docs): fix rendering for code block in state class

- .github/workflows/ci.yml
Codecov stopped supporting uploads without tokens. This PR provides the token explicitly.
> ci: Add codecov token explicitly

- docs/examples/plugins/di_plugin.py
- docs/usage/plugins.rst
- litestar/app.py
- litestar/contrib/pydantic/__init__.py
- litestar/contrib/pydantic/pydantic_di_plugin.py
- litestar/handlers/base.py
- litestar/plugins/__init__.py
- litestar/plugins/base.py
- litestar/plugins/core.py
- pyproject.toml
- tests/e2e/test_dependency_injection/test_injection_of_classes.py
- tests/examples/test_plugins/test_di_plugin.py
- tests/unit/test_contrib/test_attrs/test_inject_attrs_class.py
- tests/unit/test_contrib/test_pydantic/test_inject_pydantic.py
- tests/unit/test_handlers/test_base_handlers/test_resolution.py
- tests/unit/test_plugins/test_base.py
Fixes #2979.
- Implement a new `DIPlugin` class that allows the generation of signatures for arbitrary types where their signature cannot be extracted from the type's `__init__` method
- Implement `PydanticDIPlugin` and `MsgspecDIPlugin` classes to allow using Pydantic and Msgspec enabled classes as dependency providers
> feat(DI): Support externally typed classes as dependency providers

- litestar/app.py
- litestar/connection/base.py
- litestar/utils/scope/state.py
- tests/unit/test_app.py
- tests/unit/test_utils/test_scope.py
Fix a regression introduced in #2751 that would wrongfully assume the `state` key is always present within the ASGI Scope. This is *only* the case when the `Litestar` root application is invoked first, since we enforce such a key there, but the presence of that key is not actually guaranteed by the ASGI spec and some servers, such as hypercorn, do not provide it.
> fix: scope `state` key handling

- litestar/utils/module_loader.py
- tests/unit/test_utils/test_module_loader.py
Adds missing test for the `module_loader` package introduced in #3027.
> test: Add missing `module_loader` tests

- litestar/cli/_utils.py
The `find_spec` function fails to find `rich-click`.  It should be `rich_click`
> fix: change `rich-click` to `rich_click` for `find_spec`

- litestar/utils/scope/state.py
- tests/unit/test_utils/test_scope.py
Fix a regression introduced in #3070 while fixing another regression.
This now leaves the `scope["state"]` handling functionally untouched, to preserve behaviour. The behaviour is still not entirely correct, but it's not something we can fix without introducing breaking changes.
> fix(scope): Revert scope state regression

- tools/sphinx_ext/run_examples.py
There are a lot of cases where the examples fail to come online resulting in the building of the docs to fail as seen [here](https://github.com/litestar-org/litestar/actions/runs/7833425435/job/21374391134?pr=3087). This is due to the port that is being used to run the application ends up being used by another example during sphinx's parallel build. While we get the available port before creating the app in `run_app`, by the time we actually create the subprocess and get uvicorn to run the application, the port might already be in use by another example.
To work around this, we simply keep on retrying with a different port until the application comes online or we exceed an upper limit on the number of retries.
> docs: retry with different ports if examples don't come online

- litestar/app.py
- `Litestar.static_files_config` property is deprecated since 2.6.0 by #2960 
- But `Litestar.__init__` uses the property. I'm not sure that it is intended or not, I can't avoid that deprecated warning from calling `Litestar(...)`.
```
DeprecationWarning: Use of deprecated property 'static_files_config'. Deprecated in litestar 2.6.0. This property will be removed in the next major version. Use create_static_files router instead
```
- I suggest replace the property access to internal attribute in internal code.
> fix: replace deprectated property

- tools/sphinx_ext/run_examples.py
This is just a PR that modifies how `_get_available_port` fetches a free port. It uses the suggestion from [this](https://stackoverflow.com/a/36331860/12502959) StackOverflow answer.
TL;DR - Delegates the responsibility to the host OS to fetch a free port rather than maintaining a list at application level.
Caveat emptor: I believe both the current and suggested implementation have the same problem with regards to *not* being thread / process safe so feel free to close if this is not needed. 🙂
> chore(sphinx): Tweak `_get_available_port`

- litestar/repository/exceptions.py
This PR updates the repository to return `IntegrityError` instead of the now deprecated `ConflictError`
Separately, I think we should consider deprecating this module for version 3.0.
> fix: use `IntegrityError` instead of deprecated `ConflictError`

- litestar/_openapi/responses.py
- litestar/openapi/datastructures.py
- tests/unit/test_openapi/test_responses.py
Fixes #3068
Allows to define custom examples for the responses via `ResponseSpec`.
The examples set this way are always generated locally, for each response:
```json
{
"paths": {
"/": {
"get": {
"responses": {
"200": {
"content": {
"application/json": {
"schema": {...},
"examples": ...
```
Examples that go within the schema definition cannot be set by this.
> feat: Support `ResponseSpec(..., examples=[...])`

- CONTRIBUTING.rst
- litestar/_openapi/responses.py
- litestar/openapi/datastructures.py
- tests/unit/test_openapi/test_responses.py
- tests/unit/test_openapi/test_spec_generation.py
Fixes #3069
Explicitly declaring `responses={...: ResponseSpec(None)}` used to generate OpenAPI `content`, when it should be omitted.
> fix: Generate correct OpenAPI response for `ResponseSpec(None)` (#3069)

- docs/examples/responses/json_suffix_responses.py
- docs/usage/responses.rst
- litestar/response/base.py
- tests/examples/test_responses/test_json_suffix_responses.py
- tests/unit/test_response/test_base_response.py
Giving route handlers a response media type of the form "application/<something>+json" automatically uses json encoding for the response.
Closes #3088
> feat: support "+json"-suffixed response media types

- .pre-commit-config.yaml
Remove prettier from pre-commit. 
It doesn't add a lot of value and has been quite flaky recently, breaking CI and pre-commit in unexpected ways for contributors.
> chore: Remove prettier from pre-commit

- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- litestar/middleware/logging.py
- litestar/middleware/rate_limit.py
- litestar/middleware/session/base.py
- litestar/security/session_auth/auth.py
- litestar/utils/signature.py
- pdm.lock
- pyproject.toml
Replace `blacken-docs` with `ruff format`.
> chore: Replace blacken-docs with ruff

- litestar/app.py
- litestar/middleware/exceptions/middleware.py
- tests/unit/test_app.py
- tests/unit/test_exceptions.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Closes #3082.
Fix a bug where exception classes that had a `status_code` attribute would be treated as Litestar exceptions and details from them would be extracted and added to the exception response.
> fix(3082): Exception handlers extract details from non-litestar exceptions

- litestar/router.py
- tests/e2e/test_router_registration.py
Fixes #3012
It was not possible to re-attach a router instance once it was attached. This
makes that possible.
The router instance now gets deecopied when it's registered to another router.
The application startup performance gets a hit here, but the same approach is
already used for controllers and handlers, so this only harmonizes the
implementation.
> feat: Allow re-usable `Router` instances

- litestar/data_extractors.py
- litestar/middleware/logging.py
- tests/unit/test_data_extractors.py
- tests/unit/test_middleware/test_logging_middleware.py
Gracefully handle malformed request bodies during parsing when using struclog. Instead of erroring out and returning a `500`, simply use the raw body.
Fixes #3063.
> fix(3063): Logging middleware with structlog causes application to return HTTP 500 when request body is malformed

- docs/examples/contrib/piccolo/app.py
- litestar/contrib/piccolo.py
- litestar/dto/_backend.py
- tests/unit/test_dto/test_factory/test_integration.py
Fix an issue where msgspec constraints set in `msgspec.Meta` would not be honoured by the DTO.
In the given example, the `min_length=3` constraint would be ignored by the model generated by `MsgspecDTO`.
```python
from typing import Annotated
import msgspec
from litestar import post, Litestar
from litestar.dto import MsgspecDTO
class Request(msgspec.Struct):
foo: Annotated[str, msgspec.Meta(min_length=3)]
@post("/example/", dto=MsgspecDTO[Request])
async def example(data: Request) -> Request:
return data
```
Constraints like these are now transferred.
Two things to note are:
- For DTOs with `DTOConfig(partial=True)` we cannot transfer the length constraints as they are only supported on fields that as subtypes of `str`, `bytes` or a collection type, but `partial=True` sets all fields as …
> fix(DTO): DTO msgspec meta constraints not being included in transfer model

- tests/unit/test_logging/test_structlog_config.py
Fix a [failing test](https://github.com/litestar-org/litestar/actions/runs/7906235715/job/21580621934#step:7:204) for structlog on windows with tty.
> test: Fix structlog tty test for windows

- litestar/_openapi/schema_generation/schema.py
- tests/examples/test_openapi.py
- tests/unit/test_openapi/test_parameters.py
- Resolved the bug where the description was not set for UUID-based path parameters in OpenAPI due to the reason mentioned in the issue.
Closes #2967
> fix: Description not set for UUID based path parameters in OpenAPI

- CONTRIBUTING.rst
- docs/tutorials/todo-app/1-accessing-the-list.rst
- docs/tutorials/todo-app/2-interacting-with-the-list.rst
- docs/tutorials/todo-app/3-assembling-the-app.rst
Tutorial:
- Use lowercase after colon or semicolon
- Consistently link to True object
- TODO-list -> TODO list
- TODO-item -> TODO item
Contribution Guide:
- Fix typos
- Use lowercase after semicolon
- Update PEP link
- Update Furo to PyData Sphinx Theme
> docs: Fix typos in the tutorial and contribution guide

- litestar/utils/scope/__init__.py
- When using the scope utils the messaging is missing a space
> fix: adjust spacing in deprecation warning

- litestar/static_files/base.py
- litestar/static_files/config.py
- tests/unit/test_static_files/test_create_static_router.py
The `cache_control` that is set on a router created by `create_static_files_router` isn't considered because the return type of the handler function is an async callable so the resolved headers are ignored [here](https://github.com/litestar-org/litestar/blob/3e5c179e714bb074bae13e02d10e2f3f51e24d5c/litestar/handlers/http_handlers/base.py#L489-L492). As a workaround, the cache control header is resolved and passed directly to the `ASGIFileResponse`.
It may have been better for the `StaticFiles.handle` to return a `File` response so that this would be handled as per our normal flow and there would be no need for special casing here. This would also allow the users to provide any headers/cookies they might want to attach to the router. However, this would be a breaking change and this could …
> fix: pass cache control header for static files

- litestar/contrib/pydantic/pydantic_schema_plugin.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
Fix schema generation for `pydantic.SecretStr` and `pydantic.SecretBytes` which, when constrained, would not be recognised as such with Pydantic V2 since they're not subtypes of their respective bases anymore.
Closes #3148.
> fix(OpenAPI): Schema generation for Pydantic v2 constrained secrets

- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/contrib/pydantic/utils.py
- tests/unit/test_contrib/test_pydantic/models.py
- tests/unit/test_contrib/test_pydantic/test_integration.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
Fix a bug that caused a `NameError` when trying to resolve forward references in Pydantic private fields. 
Although we respected private fields in Pydantic and didn't include them in the schema, we still tried to extract their type annotation. This was fixed by not relying on `typing.get_type_hints` to get the type information, but instead using Pydantic's own APIs, allowing us to only extract information about the types of fields we're interested in.
Fixes #3150.
> fix(pydantic): OpenAPI schema generation for Pydantic private attributes (#3150)

- litestar/app.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/http_handlers/decorators.py
- litestar/handlers/websocket_handlers/listener.py
- litestar/router.py
- tests/unit/test_response/test_type_decoders.py
- added `type_decoders` to `__init__` method for handler, routers and decorators to keep consistency with `type_encoders` parameter
- added test  for resolving type decoders
> feat: Add `type_decoders` Router and route handlers

- docs/usage/responses.rst
- added indentation in custom response documentation
Before:
After:
> docs: Add missing indentation in custom response

- litestar/config/app.py
- litestar/controller.py
- litestar/handlers/base.py
- litestar/handlers/websocket_handlers/listener.py
- tests/unit/test_request_class_resolution.py
- tests/unit/test_response/test_type_decoders.py
- tests/unit/test_response_class_resolution.py
- pass `type_decoders` to parent's `__init__` in `WebsocketListenerRouteHandler` init, otherwise `type_decoders` will be `None` 
- add tests and `baby` refactor request and response class resolution tests
- replace params order in docs, `__init__` (`decoders` before `encoders`)
> feat: Pass `type_decoders` in WebsocketListenerRouteHandler

- litestar/contrib/pydantic/utils.py
- litestar/utils/typing.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
A followup to #3151.
Fixes a bug that caused a `NameError` when a Pydantic V1 `GenericModel` has a private attribute of which the type annotation cannot be resolved at the time of schema generation.
Fix is the same as in #3151, just applied to `GenericModel`.
Closes #3150.
> fix(pydantic): Pydantic V1 schema generation for PrivateAttr in GenericModel

- docs/examples/testing/test_set_session_data.py
- litestar/connection/base.py
- litestar/middleware/session/base.py
- litestar/middleware/session/client_side.py
- litestar/middleware/session/server_side.py
- litestar/security/session_auth/middleware.py
- litestar/testing/client/base.py
- litestar/utils/scope/state.py
- tests/unit/test_middleware/test_session/test_middleware.py
- For server side sessions, the session id is now generated before the route handler. Thus, on first visit, a session id will be available inside the route handler's scope instead of afterwards
- A new abstract method `get_session_id` was added to `BaseSessionBackend` since this method will be called for both ClientSideSessions and ServerSideSessions. Only for ServerSideSessions it will return an actual id.
- Using `request.set_session(...)` will return the session id for ServerSideSessions and None for ClientSideSessions
- The session auth MiddlewareWrapper now refers to the Session Middleware via the configured backend, instead of it being hardcoded
Looking forward to your feedback!
Closes #3116
> feat: 3116 enhancement session middleware

- tests/unit/test_middleware/test_rate_limit_middleware.py
- Use `time_machine` in time sensitive rate limit middleware tests
> test: Use time_machine in time sensitive rate limit middleware tests

- litestar/_openapi/plugin.py
- litestar/openapi/config.py
- tests/unit/test_openapi/test_integration.py
- This PR allows for the random seed used for generating the examples in the OpenAPI schema (when `create_examples` is set to `True`) to be configured by the user.
This is related to #3059 however whether this PR is enough to close that issue or not is not confirmed.
> feat: make random seed for openapi example generation configurable

- docs/examples/security/jwt/using_jwt_cookie_auth.py
Use current method signature for the `secure` Cookies flag for `JWTCookieAuth` in the documentation
> docs: reference correct property for `secure` Cookie option

- tests/unit/test_stores.py
- make sure the test has the redis mark
hopefully closes windows and macos only fail in CI
> fix: add the redis mark to appropriate test

- litestar/_openapi/datastructures.py
- tests/unit/test_openapi/test_integration.py
- This PR ensuress that the insertion into the `Components.schemas` dictionary of the OpenAPI spec will be in alphabetical order (based on the normalized name of the `Schema`).
Closes #3059.
> feat: generate openapi components schemas in a deterministic order

- litestar/middleware/cors.py
- tests/unit/test_middleware/test_cors_middleware.py
- Addresses issues outlined on #3178
Closes #3178
> fix: missing cors headers in response

- litestar/response/sse.py
- test_apps/sse/sse.html
- test_apps/sse/sse_empty.py
- from our discussion here https://discord.com/channels/919193495116337154/1213242966592856164 it appears that javascript clients dont "see" an event that has no data, while we explicitly test for this and that httpx-sse receives the event fine in that case.
- the spec https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream is not that clear to me as to whether or not an event without data is ok.
- Considering the EventSource "client" is not ok with it, and that it's so easy DX-wise to make the mistake not explicitely sending it we fix it by defaulting to the empty-string
The added app is just to manually test the fix works, I dont know how we could incorporate it in our test suite given it involves running a server and checkin if the html page yields the …
> fix: sending empty data in sse in js client 

- litestar/serialization/msgspec_hooks.py
- tests/unit/test_response/test_base_response.py
This addresses an issue when serializing `Enums` that was reported in discord.
```shell
Process SpawnProcess-10:
File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
target(sockets=sockets)
File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 62, in run
return asyncio.run(self.serve(sockets=sockets))
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
File …
```
> fix: add default encoders for `Enums` and `EnumMeta`

- litestar/testing/client/async_client.py
- litestar/testing/client/sync_client.py
`TestClient.__enter__` and `AsyncTestClient.__enter__` return `self`. If you inherit `TestClient`, `__enter__` method should return derived class's instance unless override the method. So I think `typing_extensions.Self` could be more flexible return type.
> fix: replace TestClient.__enter__ return type with Self

- litestar/serialization/msgspec_hooks.py
- tests/unit/test_response/test_base_response.py
Reverts litestar-org/litestar#3193
This may need more thought about why the patch was necessary in the first place.
> chore: Revert "fix: add default encoders for `Enums` and `EnumMeta`"

- docs/tutorials/sqlalchemy/2-serialization-plugin.rst
Now, https://docs.litestar.dev/dev/tutorials/sqlalchemy/2-serialization-plugin.html#compare-handlers-before-and-after-serialization-plugin shows the "Before" as lines 79-100:
This is https://github.com/litestar-org/litestar/blob/ef9dbb7a0cc4c7031dbf9a7bff02719d8a65a008/docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_no_plugins.py#L79-L100
We need 10 more lines, 69-100:
https://github.com/litestar-org/litestar/blob/ef9dbb7a0cc4c7031dbf9a7bff02719d8a65a008/docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_no_plugins.py#L69-L100
> docs: fix included line range from example

- litestar/handlers/http_handlers/base.py
- Use memoized `request_class` and `response_class` values
> feat: Use memoized `request_class` and `response_class` values

- docs/usage/dto/0-basic-use.rst
- litestar/app.py
- litestar/dto/base_dto.py
- litestar/handlers/base.py
- tests/unit/test_app.py
- tests/unit/test_dto/test_integration.py
Enable the codegen backend for DTOs introduced in #2388 by default. We have initially hidden this behind a feature flag to see how it works out in production. It's been smooth sailing for about 6 months now so I think we can enable it by default. This gives us enough time to decide if we want to remove the regular backend entirely in 3.0.
> feat(DTO): Enable codegen backend by default

- docs/usage/cli.rst
- litestar/cli/_utils.py
- litestar/cli/commands/core.py
- tests/unit/test_cli/test_core_commands.py
- tests/unit/test_cli/test_env_resolution.py
- Added precedence of CLI parameters over envs
> feat: Added precedence of CLI parameters over envs

- litestar/_openapi/schema_generation/schema.py
- litestar/params.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_openapi/test_request_body.py
This adds sort of a backdoor for modifying the generated OpenAPI spec.
The value is given as `dict[str, Any]` where the key must match with the
keyword parameter name in `Schema`. The values are used to override items in
the generated `Schema` object, so they must be in correct types (ie. not in
dictionary/json format).
The values are added at main level, without recursive merging (because we're
adjusting `Schema` object and not a dictionary). Recursive merge would be much
more work.
Chose not to implement the same for `ResponseSpec` because response models are
generated as schema components, while `ResponseSpec` can be locally different.
Handling the logic of creating new components when `schema_extra` is passed in
`ResponseSpec` would be extra effort, and isn't probably as important as …
> feat: Support `schema_extra` in `Parameter` and `Body`

- litestar/_openapi/responses.py
- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/schema_generation/utils.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/openapi/spec/schema.py
- litestar/typing.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
- tests/unit/test_openapi/test_integration.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_openapi/test_schema.py
The generated `examples` in *JSON schema* objects were formatted as:
```json
"examples": {
"some-id": {
"description": "Lorem ipsum",
"value": "the real beef"
}
}
```
However, above is OpenAPI example format, and must not be used in JSON schema
objects. Schema objects follow different formatting:
```json
"examples": [
"the real beef"
]
```
This is explained in
https://medium.com/apis-you-wont-hate/openapi-v3-1-and-json-schema-2019-09-6862cf3db959
Schema objects spec in
https://spec.openapis.org/oas/v3.1.0#schema-object.
OpenAPI example format spec in
https://spec.openapis.org/oas/v3.1.0#example-object. This is referenced at
least from parameters, media types and components.
The technical change here is to define `Schema.examples` as `list[Any]` instead
of `list[Example]`. Examples can and …
> fix: JSON schema `examples` were OpenAPI formatted

- litestar/logging/config.py
- litestar/logging/standard.py
- tests/helpers.py
- tests/unit/test_logging/test_logging_config.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
- tests/unit/test_middleware/test_logging_middleware.py
- Fix the `queue_listener` handler for Python 3.12
Python 3.12 introduced a new way to configure `QueueHandler` and `QueueListener` via `logging.config.dictConfig()`. This described [here](https://docs.python.org/3/library/logging.config.html#configuring-queuehandler-and-queuelistener).
The listener still needs to be started & stopped, as previously. To do so, I've introduced `LoggingQueueListener`.
And as stated in the doc:
> Any custom queue handler and listener classes will need to be defined with the same initialization signatures as [QueueHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueHandler) and [QueueListener](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.QueueListener).
Closes #2954
> fix(logging): queue_listener handler for Python >= 3.12

- docs/usage/security/guards.rst
This PR documents the behavior of guards placed at the controller and app level being executed for `OPTIONS` requests. 
I don't know if linking to the GitHub issue is the best way to go about this. I'm open to any ideas on how to document this behavior better.
This is related to #2314, but doesn't fix the underlying issue. Instead it documents the issue as well as provides a link to the issue where the users can find a workaround for it.
EDIT: Reword to make sure GitHub doesn't consider the linked issue as being fixed by this PR.
> docs: document guards behavior when placed at controller and app level

- litestar/utils/signature.py
- litestar/utils/typing.py
- tests/unit/test_utils/test_signature.py
- tests/unit/test_utils/test_typing.py
Add a method for typevar expansion on registration
This allows the use of generic route handler and generic controller without relying on forward references.
A self-contained example - which would fail in the previous version:
```Python
from dataclasses import dataclass, field
from typing import Generic, TypeVar
from uuid import UUID, uuid4
from litestar import Controller, Litestar, Router, post
@dataclass
class BookDataClass:
title: str
id: UUID = field(default_factory=uuid4)
@dataclass
class AuthorDataClass:
title: str
id: UUID = field(default_factory=uuid4)
T = TypeVar("T")
class GenericController(Controller, Generic[T]):
model_class: T
def __class_getitem__(cls, model_class: type) -> type:
cls_dict = {"model_class": model_class}
return type(f"GenericController[{model_class.__name__}", …
```
> feat: add typevar expansion

- docs/usage/security/excluding-and-including-endpoints.rst
- docs/usage/security/index.rst
As brought up in [discord](https://discord.com/channels/919193495116337154/919193495690936353/1220376838489112616), this PR updates the docs to include a section that elaborates the use of the `exclude` patterns for `Auth` configurations.
It explains basic use, use of regex for an "inverted exclusion", and how to exclude individual routes. I chose not to update the docstrings of the `Auth` classes, because I think it's clear enough when considering this addition to the docs (which people hopefully check out before using the authentication ;) ).
I also went for plain code block snippets instead of full blown examples, because those would mean a lot of overhead. The use of `Auth`'s is already explained well enough in the other examples. This section just tries to highlight how to use the …
> docs: Add examples for auth `exclude` configuration

- litestar/_kwargs/kwargs_model.py
- tests/unit/test_kwargs/test_path_params.py
This PR cherry picks @guacs' commit from #3223 that fixes the way we construct the exception message when there is a kwarg ambiguity detected for path parameters.
> fix: kwarg ambiguity exc msg for path params

- docs/usage/middleware/builtin-middleware.rst
- Adds client usage example for CSRF middleware.
- Slightly modifies the existing server example to make it more copy pastable. 
- References to external links for some related concepts.
Doc link: https://litestar-org.github.io/litestar-docs-preview/3256/usage/middleware/builtin-middleware.html#csrf
> docs(csrf): Add usage example

- litestar/typing.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
Fixes a regression introduced in 2.7 where an example for a field provided in pydantic's `Field.json_schema_extra` would cause an error.
Closes #3277
-
> fix: pydantic `json_schema_extra` examples.

- litestar/_openapi/schema_generation/schema.py
- tests/unit/test_openapi/test_schema.py
Consider the following:
```python
def get_foo(foo_id: int = 10) -> None:
...
```
In such cases, no `KwargDefinition` is created since there is no metadata provided via `Annotated`. The default is still parsed, and set on the generated `FieldDefinition`, however the `SchemaCreator` currently only considers defaults that are set on `KwargDefinition`.
So in such cases, we should fallback to the default set on the `FieldDefinition` if there is a valid default value.
Fixes #3278.
> fix(openapi): set default on schema from `FieldDefinition`

- litestar/typing.py
- tests/unit/test_typing.py
As discussed in https://github.com/litestar-org/litestar/pull/3280#issuecomment-2026878325, we want to warn about, and eventually disallow specifying parameter defaults in two places. 
To achieve this, 2 warnings are added:
- A deprecation warning if a default is specified when using `Annotated`: `param: Annotated[int, Parameter(..., default=1)]` instead of `param: Annotated[int, Parameter(...)] = 1`
- An additional warning in the above case if two default values are specified which do not match in value: `param: Annotated[int, Parameter(..., default=1)] = 2`
In a future version, the first one should result in an exception at startup, preventing both of these scenarios.
> feat: Warn about ambiguous default values in parameter specifications

- litestar/middleware/exceptions/middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
When using a non-JSON media type (e.g. `text/plain`), `ValidationException`s wouldn't get serialised properly because they would ignore custom `type_encoders`.
The example below would result in a `SerializationException`:
```python
class Foo:
def __init__(self, value: str) -> None:
self.value = value
@get(media_type=MediaType.TEXT)
def handler() -> None:
raise ValidationException(extra={"foo": Foo("bar")})
app = Litestar([handler], type_encoders={Foo: lambda f: f.value})
```
> fix: Custom types cause serialisation error in exception response with non-JSON media-type

- litestar/_openapi/schema_generation/plugins/dataclass.py
- litestar/_openapi/schema_generation/plugins/struct.py
- tests/unit/test_openapi/test_integration.py
Fix a bug that would prevent default values for dataclasses and msgspec.Struct`s to be included in the OpenAPI schema.
```python
@dataclass
class SomeModel:
field_a: str = "default_a"
field_b: str = dataclasses.field(default="default_b")
```
and 
```python
class SomeModel(msgspec.Struct, kw_only=True):
field_a: str = "default_a"
field_b: str = msgspec.field(default="default_b")
```
now generate correct schemas in all cases.
Fix #3201.
> fix(OpenAPI): Ensure default values are always represented in schema for dataclasses and `msgspec.Struct`s

- docs/examples/channels/iter_stream.py
- docs/examples/channels/put_history.py
- docs/examples/channels/run_in_background.py
Fix outdated usage of the `channels.subscribe` method; The `channel.start_subscription` method should be used instead.
> docs(channels): Fix subsriber examples

- litestar/contrib/pydantic/pydantic_dto_factory.py
- litestar/dto/dataclass_dto.py
- litestar/dto/field.py
- litestar/dto/msgspec_dto.py
- tests/unit/test_contrib/test_msgspec.py
- tests/unit/test_contrib/test_pydantic/test_pydantic_dto_factory.py
- tests/unit/test_dto/test_factory/test_dataclass_dto.py
- tests/unit/test_dto/test_factory/test_field.py
E.g.:
```py
class A(Struct):
a: Annotated[int, dto_field("read_only")]
```
Deprecates passing DTOField via pydantic extra, e.g., no longer supported:
```py
class Model(BaseModel):
a: int = Field(**dto_field("read-only"))
```
Closes #2351
> feat: support declaring `DTOField` via `Annotated`

- litestar/enums.py
Add the `TRACE` HTTP method to `HttpMethod` enum
> feat: Add "TRACE" to HttpMethod enum

- litestar/_openapi/path_item.py
- litestar/_openapi/plugin.py
- tests/unit/test_openapi/test_path_item.py
- tests/unit/test_openapi/test_schema.py
Fix a bug that would cause no OpenAPI schema to be generated for paths with path parameters that only differ on the path parameter type. 
Essentially, `/{param:int}` and `/{param:str}` (that is, two paths with the same path parameter name but a different path parmeter type) could not coexist in the same application. Defining them as `/{param:int}` and `/{other_param:str}` or `/{param:int}` and `/{param:int}` (i.e. different names or same type) would result in the correct behaviour. 
Closes #2700.
<hr>
This was caused by the way Litestar handles routing of these; A single route can have multiple route handlers, but requires that all path parameters, if existent, be of the same type. Litestar can also handle routing with parameters of different types, but creates separate routes for this. …
> fix(OpenAPI): Fix OpenAPI schema generation for paths with path parameters of different types on the same path

- .pre-commit-config.yaml
- litestar/_openapi/parameters.py
- pyproject.toml
- tests/unit/test_openapi/test_schema.py
- tests/unit/test_openapi/test_typescript_converter/test_converter.py
Fix a bug where path parameters not consumed by route handlers would not be included in the OpenAPI schema.
```python
from litestar import Litestar, get
@get("/{param:str}")
async def handler() -> None:
pass
```
This could would not include the `{param}` in the schema, yet it is still required to be passed when calling the path. 
Fix #3290.
> fix(OpenAPI): Document unconsumed path parameters

- litestar/contrib/pydantic/pydantic_dto_factory.py
- tests/unit/test_contrib/test_pydantic/__init__.py
- tests/unit/test_contrib/test_pydantic/test_integration.py
This PR simplifies the type that we apply to transfer models for pydantic field types in specific circumstances.
- `JsonValue`: this field type is an instance of `TypeAliasType` at runtime, and contains recursive type definitions. Pydantic allow `list`, `dict`, `str`, `bool`, `int`, `float` and `None`, and the value types of `list` and `dict` are allowed to be the same. We type this as `Any` on the transfer models as this is basically the same thing for msgspec ([ref][1]).
- `EmailStr`. These are typed as `EmailStr` which is a class at runtime which is not a `str`, however they are a string and `if TYPE_CHECKING` is used to get type checkers to play along. If we leave it typed as `EmailStr` and return a `str` from a msgspec decode hook for the type, msgspec fails input validation. So we …
> feat: Pydantic dto non instantiable types

- docs/conf.py
- docs/usage/routing/handlers.rst
- docs/usage/routing/index.rst
- docs/usage/routing/overview.rst
- docs/usage/routing/parameters.rst
- pyproject.toml
- Update `docs/routing/*`
Part of work in #3212
> docs: update `docs/usage/routing/*`

- .pre-commit-config.yaml
- pdm.lock
- pyproject.toml
There are a few changes coming soon in `advanced-alchemy` that touch several components.  While it should not be breaking, it would be best if we pinned the dependency to less than `0.9.0` so that we don't inadvertently cause issues for others.
We can remove this pin once we are sure there are no impacts.
> chore(dep): pin `advanced-alchemy` to < `v0.9.0`

- litestar/_asgi/asgi_router.py
- tests/unit/test_asgi_router.py
An exception raised within an asgi lifespan context manager would result in a "lifespan.startup.failed" message being sent after we've already sent a "lifespan.startup.complete" message. This would cause uvicorn to raise a `STATE_TRANSITION_ERROR` assertion error due to their [check for that condition][1], if asgi lifespan is forced (i.e., with `$ uvicorn test_apps.test_app:app --lifespan on`).
E.g.,
```python-traceback
During handling of the above exception, another exception occurred:
File "/home/peter/.local/share/pdm/venvs/litestar-dj-FOhMr-3.8/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 86, in main
await app(scope, self.receive, self.send)
File "/home/peter/.local/share/pdm/venvs/litestar-dj-FOhMr-3.8/lib/python3.8/site-packages/uvicorn …
```
> fix: asgi lifespan msg after lifespan context exception

- litestar/testing/client/async_client.py
- tests/unit/test_testing/test_test_client.py
- Add async `websocket_connect` to `AsyncTestClient`
> feat: Add async `websocket_connect` to `AsyncTestClient`

- litestar/contrib/pydantic/pydantic_dto_factory.py
This PR fixes a bug introduced in #3296 where it failed to take into account that the `pydantic_v2` variable could be `Empty`.
Closes #3334
-
> fix: bug when pydantic==1.10 is installed

- litestar/_asgi/routing_trie/mapping.py
- litestar/_openapi/parameters.py
- litestar/app.py
- litestar/handlers/base.py
- litestar/routes/base.py
- litestar/routes/http.py
Move the creation of the `KwargsModel` from the routes to the route handlers. Since this operates on the handlers almost exclusively, it makes more sense to have it in there.
> refactor(routing): Move kwargs model creation to handler

- litestar/openapi/controller.py
- tests/unit/test_openapi/test_integration.py
Fixes an `ImproperlyConfiguredException` where an app that explicitly registers an `OpenAPIController` on the application, and implicitly uses the OpenAPI router via the `OpenAPIConfig` object. This was caused by the two different handlers being given the same name as defined in `litestar.constants`.
PR adds a distinct name for use by the handler that serves `openapi.json` on the controller.
Closes #3337
-
> fix: OpenAPI router and controller on same app.

- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
These comments aren't really valid any longer, now that we first attempt any import of a pydantic version at the top of the file. Should have been removed in earlier PR.
-
> chore: tidy up some redundant comments

- litestar/contrib/pydantic/pydantic_dto_factory.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/contrib/pydantic/utils.py
#3347 introduced a new pattern to differentiate between Pydantic v1 and v2 installs, however it relies on using `assert` which is an issue as can optimised away.
This PR changes the approach to manually throw an `ImportError` instead.
Closes #3354
-
> fix: Remove use of asserts for control flow.

- .pre-commit-config.yaml
- litestar/stores/redis.py
- pdm.lock
Updates locked dependencies and pre-commit.
Fixes type error introduced by `types-redis` update.
> chore: Update lockfile and tools

- docs/usage/openapi/ui_plugins.rst
- I noticed that the current Swagger UI link provided in the [Litestar documentation](https://docs.litestar.dev/2/usage/openapi/ui_plugins.html#openapi-ui-plugins) leads to a 404 error page. It would be helpful to update this document with a working URL for the Swagger UI.
> docs: fix broken url; swagger ui

- litestar/dto/base_dto.py
- tests/conftest.py
- tests/helpers.py
- tests/unit/test_dto/test_factory/test_integration.py
Fix schema generated for DTOs where the supported type is wrapped in a generic outer type.
Prior behavior of using the `backend.annotation` as the basis for generating the openapi schema for the represented type is not applicable for the case where the DTO supported type is wrapped in a generic outer object. In that case `backend.annotation` only represents the type of the attribute on the generic type that holds the DTO supported type annotation.
This PR detects the case where we unwrap an outer generic type, and rebuilds the generic annotation in a manner appropriate for schema generation, before generating the schema for the annotation. It does this by substituting the DTOs transfer model for the original model in the original annotations type arguments.
`<tangent>`
This is really …
> fix: schema for generic wrapped return types with DTO

- litestar/typing.py
- tests/unit/test_typing.py
We now only issue a single warning for the case where a default value is supplied via `Parameter()` and not via a regular signature default.
Closes #3372
-
> fix: Ambiguous default warning for no signature default

- litestar/_openapi/parameters.py
- tests/unit/test_openapi/test_schema.py
Consider parameters defined in handler dependencies in order to determine if a path parameter has been consumed for openapi generation purposes.
Fixes an issue where path parameters not consumed by the handler, but consumed by dependencies would cause an `ImproperlyConfiguredException`.
Closes #3369
-
> fix: Path param consumed by dependency treated as unconsumed

- litestar/datastructures/headers.py
- tests/unit/test_datastructures/test_headers.py
I noticed [this](https://github.com/litestar-org/litestar/blob/c3af6c6b5b2b7db9203be17969fd3c9b29b2d540/tests/unit/test_datastructures/test_headers.py#L296) test was breaking when executed standalone or in a particular order. It turns that the test case (added in #1917) never worked in the first place and was only passing because invalid results of the `_get_field_names` classmethod were saved on the class.
Since the caching isn't really needed for performance here I have just removed it and fixed the test.
> fix: Solve a caching issue in `CacheControlHeader`

- tests/e2e/test_middleware/test_middleware_send_wrapper_called_on_error.py
This tests that when a handler raises an exception, we call wrapped versions of the `send()` coroutine.
-
> test: adds a test for middleware behavior

- docs/release-notes/whats-new-3.rst
- litestar/handlers/http_handlers/_utils.py
- litestar/handlers/http_handlers/base.py
- litestar/middleware/exceptions/middleware.py
- litestar/response/base.py
- litestar/response/file.py
- litestar/response/redirect.py
- litestar/response/streaming.py
- litestar/response/template.py
- litestar/routes/http.py
- tests/unit/test_cli/test_core_commands.py
- tests/unit/test_response/test_response_to_asgi_response.py
Remove the deprecated `app` parameter of `Response.to_asgi_response`; Its usage has been replaced internally by `request.app`, and custom response classes can follow the same pattern.
> refactor!: Remove deprecated `app` param of `Response.to_asgi_response`

- docs/release-notes/whats-new-3.rst
- litestar/constants.py
- litestar/utils/__init__.py
- litestar/utils/predicates.py
- litestar/utils/scope/__init__.py
- litestar/utils/scope/state.py
- tests/unit/test_deprecations.py
- tests/unit/test_utils/test_scope.py
Remove the deprecated utility functions, ``get_litestar_scope_state``, ``set_litestar_scope_state``, ``delete_litestar_scope_state``, and ``is_sync_or_async_generator``.
-
> refactor!: Remove deprecated utils

- litestar/app.py
- litestar/middleware/exceptions/middleware.py
- tests/unit/test_middleware/test_cors_middleware.py
Remove `ExceptionHandlerMiddleware`'s dependence on `CORSMiddleware` by making `CORSMiddleware` the outermost middleware in the stack if the app has CORS configured.
This makes responses sent via the exception middleware pass through the CORS middleware send wrapper if CORS is configured, which is behaviourally equal to the current behavior of wrapping the `send` coro inside the exception handler middleware with the CORS middleware send wrapper.
-
> refactor: Make CORS outermost middleware

- litestar/app.py
- litestar/middleware/_internal.py
- litestar/middleware/cors.py
- litestar/testing/helpers.py
- tests/unit/test_deprecations.py
- tests/unit/test_middleware/test_cors_middleware.py
It is used internally, its use is hardcoded and it doesn't work similar to other middleware when added to layers.
Should be implementation detail IMO.
Closes #3403
-
> refactor: deprecate CORSMiddleware from public interface.

- docs/tutorials/repository-tutorial/01-modeling-and-features.rst
Currently, code sample on 'SQLAlchemy Repository Tutorial' is not applicable as-is.
I fixed the sample applicable and self-descriptable.
See docs image below.
> fix: broken sample code on 'SQLAlchemy Repository Tutorial'

- litestar/middleware/_internal.py
- litestar/routes/http.py
- tests/e2e/test_cors/test_cors_allowed_headers.py
- tests/e2e/test_cors/test_cors_allowed_methods.py
- tests/e2e/test_cors/test_cors_credentials.py
- tests/e2e/test_cors/test_cors_for_middleware_exception.py
- tests/e2e/test_cors/test_cors_for_mount.py
- tests/e2e/test_cors/test_cors_for_routing_exception.py
- tests/e2e/test_cors/test_cors_origins.py
- tests/e2e/test_cors/test_custom_options_handlers.py
- tests/e2e/test_cors/test_non_cors_options.py
Move pre-flight response generation from the generated OPTIONS handlers to the CORS middleware.
Fixes case where pre-flight response not applied to mounted ASGI apps.
Fixes the case where a user defined OPTIONS handler may not include CORS logic. In fact, this is they only way we can be sure that we honor CORS pre-flight if the config object is provided.
Adds a stack of CORS e2e tests.
Closes #3402 
-
> refactor: CORS pre-flight response generated by middleware.

- docs/usage/websockets.rst
1. Use the standardised term "WebSocket" instead of alternating between "WebSocket" and "websocket"
2. Fix a few minor grammatical/spelling errors
> docs: Fix WebSockets documentation grammar

- litestar/openapi/spec/base.py
- litestar/openapi/spec/header.py
- tests/e2e/test_openapi/test_spec_headers.py
- tests/unit/test_openapi/test_config.py
Exclude the "name" and "in" fields from openapi schema generated for headers.
Add ``BaseSchemaObject._iter_fields()``  method that allows schema types to define the fields that should be included in their openapi schema representation and override that method for ``OpenAPIHeader``.
Closes #3416
-
> fix: "name" and "in" should not be included in openapi headers

- litestar/plugins/flash.py
Fix import from `contrib.minijinja` without handling for case where dependency is not installed.
Closes #3415
-
> fix: top-level import of optional package

- litestar/plugins/flash.py
Minor refactor that replaces a `try...except...else` with `context.suppress` so that is better in line with certain places where `MissingDependencyException`s are handled. Feel free to close if it's redundant / less impactful. 🙂
> refactor: use contextlib.suppress

- docs/conf.py
Update intersphinx link for advances-alchemy
> docs: Fix intersphinx mapping for advanced-alchemy

- litestar/_asgi/routing_trie/traversal.py
- tests/e2e/test_regular_handler_under_asgi_mount_path.py
Fix an issue where a regular handler under a mounted asgi app would prevent a request from routing through the mounted application if the request path contained the path of the regular handler as a substring.
Closes #3429
-
> fix: regular handler under mounted app

- litestar/logging/config.py
- tests/e2e/test_logging/test_structlog_to_file.py
PR fixes issue with converting `StructLoggingConfig` to dict during call to `configure()` when the config object has a custom logger factory that references a `TextIO` object, which cannot be pickled.
> fix: logging to file with structlog

- litestar/middleware/session/client_side.py
- tests/unit/test_middleware/test_session/test_client_side_backend.py
Fix an issue where the connection session cookie is not cleared if the response session is stored across multiple cookies.
Closes #3441
-
> fix: clear session cookie if new session gt CHUNK_SIZE

- litestar/contrib/pydantic/pydantic_schema_plugin.py
- tests/e2e/test_pydantic.py
Fix issue where a pydantic v1 field annotation is wrapped with `Optional` if it is marked not required, but has a default value.
Closes #3471
-
> fix(pydantic v1): field not optional if default value

- tests/unit/test_static_files/test_static_files_validation.py
A test was directly using `PosixPath`, changed to `Path`.
-
> fix(tests): windows compat error

- litestar/middleware/_internal/exceptions/middleware.py
- litestar/utils/scope/state.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Prevent the app's exception handler middleware from starting a response after one has already started.
When something in the middleware stack raises an exception after a "http.response.start" message has already been sent, we end up with long exception chains that obfuscate the original exception, such as:
```python-traceback
ERROR:    Exception in ASGI application
File "/home/peter/PycharmProjects/litestar/litestar/response/streaming.py", line 134, in send_body
await self._listen_for_disconnect(cancel_scope=task_group.cancel_scope, receive=receive)
File "/home/peter/PycharmProjects/litestar/litestar/response/streaming.py", line 100, in _listen_for_disconnect
await self._listen_for_disconnect(cancel_scope=cancel_scope, receive=receive)
File …
```
> fix: prevent starting multiple responses

- litestar/middleware/logging.py
- tests/e2e/test_middleware/test_logging_middleware_with_multi_body_response.py
Prevent logging middleware from failing with a KeyError when a response sends multiple "http.response.body" messages.
Closes #3477
-
> fix: logging middleware with multi-body response

- .pre-commit-config.yaml
- litestar/cli/__init__.py
- litestar/cli/_utils.py
- litestar/contrib/jinja.py
- litestar/contrib/mako.py
- litestar/contrib/minijinja.py
- litestar/middleware/_internal/exceptions/middleware.py
- litestar/plugins/base.py
- litestar/testing/transport.py
- pdm.lock
- tests/unit/test_cli/test_cli.py
- tests/unit/test_contrib/test_pydantic/test_integration.py
- Addresses violations of new "safe-super" mypy check
- Addresses rich-click deprecation for importing `patch` from `rich_click.cli`
- Fixes test failure caused by `isinstance(command, Group)` no longer holding true after update to rich-click 1.8
-
> chore: upgrade deps and tools

- litestar/dto/_backend.py
- litestar/dto/_codegen_backend.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
Added handling for transferring data from a transfer model, to a DTO supported instance when the DTO supported type is nested in a mapping.
I.e, handles this case:
```py
@dataclass
class NestedDC:
a: int
b: str
@dataclass
class DC:
nested_mapping: Dict[str, NestedDC]
```
Closes #3463
-
> fix(dto): handle dto type nested in mapping

- docs/conf.py
- litestar/pagination.py
- litestar/plugins/sqlalchemy.py
- pdm.lock
- pyproject.toml
- tests/unit/test_plugins/test_sqlalchemy.py
- tests/unit/test_repository/models_bigint.py
- tests/unit/test_repository/models_uuid.py
This PR unpins Advanced Alchemy.
This allows version `0.9.3` to be installed with teh `litestar[sqlalchemy]` command group.
This enables the following:
- A numebr of repository and service optimizations and fixes
- SQLAlchemyQueryRepository from advanced alchemy
- `to_schema` from the `Service` used there (see the fullstack repository for usage details)
However, this AA release also had to integrate it's own copies of the Litesatr `OffsetPagination` dataclass.  Litestar will attempt to use this version of the dataclass when a supported version is installed.  This is implemented similar to how the filters in `filters.py` work currently.
> chore: unpin Advanced Alchemy

- litestar/dto/base_dto.py
- tests/unit/test_dto/test_factory/test_integration.py
Fixes issue where a `BodyKwarg` instance provided as metadata to a data type annotation was ignored for OpenAPI schema generation when the data type is managed by a DTO.
Closes #3505
-
> fix: examples omitted in schema produced by dto

- litestar/_signature/model.py
- litestar/serialization/msgspec_hooks.py
- tests/unit/test_signature/test_validation.py
Fix a bug that would lead to a `TypeError` when subscribed generics were used in a route handler signature and subject to validation.
```python
from typing import Generic, TypeVar
from litestar import get
from litestar.testing import create_test_client
T = TypeVar("T")
class Foo(Generic[T]):
pass
async def provide_foo() -> Foo[str]:
return Foo()
@get("/", dependencies={"foo": provide_foo})
async def something(foo: Foo[str]) -> None:
return None
with create_test_client([something]) as client:
client.get("/")
```
> fix(validation): fix handling validation of subscribed generics

- litestar/static_files/config.py
Running the provided MCVE (with an additional hello_world) results in this: ![image](https://github.com/litestar-org/litestar/assets/75096465/26317388-ce5b-4b9d-a242-5ea4a2a0f53c)
Fixes #3374
> fix: exclude static file from schema

- .github/workflows/pr-labeler.yml
Remove redundant `pull_request` trigger that makes the job run twice and fail for PRs on forks.
> ci: Fix pull request labeller job

- litestar/static_files.py
- tests/unit/test_static_files/test_file_serving_resolution.py
- tests/unit/test_static_files/test_static_files_validation.py
Port the fix for the https://github.com/litestar-org/litestar/security/advisories/GHSA-83pv-qr33-2vcf path traversal vulnerability to 3.0
> fix: Port CVE-2024-32982 path traversal fix to v3.0

- docs/conf.py
- litestar/handlers/http_handlers/decorators.py
- tests/unit/test_handlers/test_http_handlers/test_deprecation.py
Deprecation for the 2.x release line of the semantic route handler classes removed in #3436.
> feat: Deprecate subclassing route handler decorators

- litestar/controller.py
- litestar/router.py
- tests/e2e/test_life_cycle_hooks/test_after_response.py
Remove `Controller` specific logic needed during registration by converting controllers into `Router` instances first.
> refactor: Remove special casing of controllers during registration

- docs/examples/plugins/flash_messages/jinja.py
- docs/examples/plugins/flash_messages/mako.py
- docs/examples/plugins/flash_messages/minijinja.py
- docs/examples/plugins/flash_messages/usage.py
- docs/usage/plugins/flash_messages.rst
The flash messages plugin requires a valid session configuration.  This PR adds a basic configuration to the examples.  Previously, an exception would be raised when executing the examples.
> docs: updated example for flash messages

- litestar/plugins/flash.py
This PR updates the signature for the `flash` function.  Currently, I recent a pyright warning when importing because the signature is partially unknown.
> fix: updated type signature for `flash`

- litestar/logging/config.py
- tests/unit/test_logging/test_logging_config.py
- tests/unit/test_logging/test_structlog_config.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Currently we're logging the exceptions twice: the full one and a truncated one.
This PR tries to improve this, ~~which implies small breaking changes~~.
~~Almost finished but still a WIP, I need some feedback please!~~
Outlines:
* The wording of the log message, when logging an exception, has been updated.
* For structlog, the `traceback` field in the log message (which contained a truncated stacktrace) has been removed. The `exception` field is still around and contains the full stacktrace.
* The option `traceback_line_limit` has been deprecated. The value is now ignored, the full stacktrace will be logged.
⚠️ The former code has been introduced to solve #1294, unfortunately I haven't been able to reproduce the issue. It's not clear in which cases it happened, or if the PR (#1296) fixed …
> fix(logging): do not log exceptions twice, deprecate `traceback_line_limit` and fix `pretty_print_tty`

- litestar/openapi/controller.py
- tests/unit/test_openapi/test_integration.py
Fixes an issue in the OpenAPI YAML schema dump logic of `OpenAPIController` where the endpoint for the OpenAPI YAML schema file returns an empty response if a request has been made to the OpenAPI JSON schema previously due to an incorrect variable check.
Edit from @Alc-Alc: https://discord.com/channels/919193495116337154/919193495690936353/1246024918487793744 explains the need for this
> fix(OpenAPI): YAML schema dump

- litestar/config/csrf.py
- make OPTIONS the default safe method for CSRFConfig
- related [doc](https://developer.mozilla.org/en-US/docs/Glossary/Safe)
- related PR #340
> fix: add OPTIONS to the default safe methods for CSRFConfig

- docs/usage/logging.rst
The warning below states the following:
```
Litestar configures a non-blocking ``QueueListenerHandler`` which
is keyed as ``queue_listener`` in the logging configuration. The above example is using this handler,
which is optimal for async applications. Make sure to use it in your own loggers as in the above example.
```
Just reflect that
> docs(logging): use `queue_listener` as mentioned in the warning

- docs/usage/routing/overview.rst
- docs
Hey! I fixed a typo on the docs where it said "/`" when it should be "/".
Fixes #3550
> fix(docs): fixed typo in routing overview

- docs/reference/concurrency.rst
This PR will change "cli" to "concurrency" in concurrency.rst to fix #2987 
- #2987
> docs: Changed cli to concurrency in concurrency.rst

- docs/examples/contrib/prometheus/using_prometheus_exporter.py
- litestar/contrib/prometheus/config.py
- litestar/contrib/prometheus/middleware.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example.py
Adding new extraction function for prometheus metrics to avoid high cardinality issue in prometheus, eg having metrics GET /v1/users/{id} is preferable over GET /v1/users/1, GET /v1/users/2,GET /v1/users/3
More info about prometheus high cardinality
https://grafana.com/blog/2022/02/15/what-are-cardinality-spikes-and-why-do-they-matter/
> fix(prometheus): capture templated route name for metrics

- litestar/handlers/http_handlers/decorators.py
The deprecation warning is missing a space between "by" and "functional".
When printing to the screen, it would read a single work "byfunctional"
-
> chore(formatting): deprecation warning text for route handler classes

- litestar/testing/client/async_client.py
- litestar/testing/client/base.py
- litestar/testing/client/sync_client.py
- tests/unit/test_connection/test_websocket.py
- tests/unit/test_contrib/test_opentelemetry.py
Fix a bug that caused the `.websocket_connect` methods on `TestClient` and `AsyncTestClient` to not respect the `base_url` set in the client's constructor, and instead would use the static `ws://testerver` URL as a base.
Also removes most of the test client code as it was unneeded and in the way of this fix :)
<hr>
Explanation for the last part: All the extra code we had was just proxying method calls to the `httpx.Client` / `httpx.AsyncClient`, while altering the base URL. Since we already set the base URL on the httpx Client's superclass instance, which in turn does this merging internally, this step isn't needed at all.
> fix(testing): `.websocket_connect` does not respect `base_url`

- docs/conf.py
- litestar/handlers/http_handlers/decorators.py
- tests/unit/test_handlers/test_http_handlers/test_deprecation.py
- The warning being applied to the default handlers was unintended behavior due to subclassing. This PR establishes the intended behavior by defining separate `__init_subclass__`es for the default handlers.
Closes #3552
> fix(warnings): Do not warn for default handlers

- litestar/cli/__init__.py
- litestar/cli/_utils.py
- litestar/cli/commands/core.py
- litestar/cli/commands/schema.py
- litestar/cli/commands/sessions.py
- litestar/cli/main.py
Fix #3534.
Don't call `rich_click.patch` if `rich_click` is installed, and instead use conditional imports to refer to the correct library. External libraries will still be able to make use of `rich_click` implicitly when it's installed by inheriting from `LitestarGroup` / `LitestarExtensionGroup`, which they will by default.
> fix(CLI): Don't call `rich_click.patch` if `rich_click` is installed

- litestar/controller.py
Ignore a type error in `Controller.as_router` that's not really easily fixable otherwise
> fix(typing): "Fix" typing for `Controller.as_router`

- litestar/logging/config.py
- tests/unit/test_logging/test_logging_config.py
I started by refactoring the tests. It might be easier to review this PR commit by commit.
This PR will:
* Fix minor bugs like the one described in https://github.com/orgs/litestar-org/discussions/3482
> What's a bit strange is that I have to provide a "standard" formatter otherwise I get a KeyError:
* Only pass valid values to the `dictConfig` classes
* Deprecate `propagate` at the root `dictConfig` level (this value is only supported at the `Logger` level, it was passed to `dictConfig()` but has no effect AFAIK)
> refactor(logging): improve `LoggingConfig` & deprecate `LoggingConfig.propagate`

- litestar/logging/config.py
Better to always show exceptions by default.
Related to #3541.
> feat(logging): always log exceptions by default

- docs/usage/logging.rst
This is related to #3541 and #3574.
> docs(logging): advise to use `log_exceptions="always"`

- litestar/logging/config.py
- tests/conftest.py
- tests/unit/test_logging/test_logging_config.py
`logging_module` provides a way to switch easily from `logging` to `picologging`.
Closes #3536
> feat(logging): add param `logging_module` to `LoggingConfig`

- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/http_handlers/decorators.py
- litestar/handlers/websocket_handlers/route_handler.py
Related: #
- Add handler name to exceptions raise by _validate_handler_function.
addresses #3548
> feat: add handler name to exceptions in handler validation.

- litestar/_openapi/schema_generation/schema.py
- litestar/typing.py
- litestar/utils/typing.py
- tests/unit/test_openapi/test_parameters.py
When encountering a `typing.NewType` during OpenAPI schema generation, we currently treat it as an opaque type. This PR changes the behaviour such that `typing.NewType`s are always unwrapped during schema generation.
> fix(OpenAPI): Correctly handle `typing.NewType` 

- litestar/middleware/_internal/exceptions/middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
When an handler raises an exception and exception handler returns a Response with a model (e.g. pydantic) object, encode that object with the app type_encoders.
> fix: encode response content object returned from an exception handler.

- docs/conf.py
- tools/sphinx_ext/missing_references.py
Fix a bug in `tools/sphinx_ext/missing_references.py` that would cause the docs build to fail: https://github.com/litestar-org/litestar/actions/runs/9602344070/job/26528903758
> chore(docs): Fix `tools/sphinx_ext/missing_references.py` 

- litestar/_kwargs/dependencies.py
- litestar/_signature/model.py
- litestar/routes/http.py
- litestar/routes/websocket.py
- pyproject.toml
- tests/unit/test_signature/test_validation.py
Fix #3593 by ensuring that the functions used by the signature model itself do not interfere with the signature model created.
> fix(signature): Fix #3593: Ensure signature model internal function signatures don't clash with model signature

- litestar/_openapi/schema_generation/schema.py
- tests/unit/test_openapi/test_parameters.py
Resolves infinite loop in schema generation when a model has an Annotated NewType.
I made the check in `unwrap_new_type()` use the same logic as `is_new_type`.
@provinzkraut do you want to look this over, since you authored the previous PR?  Is there an issue with using `field_definition.annotation` that you were trying to avoid here?
Fixes #3614
> fix(OpenAPI): Correctly handle Annotated NewType

- docs/examples/contrib/prometheus/using_prometheus_exporter_with_extra_configs.py
- Removes typos from the comments in the prometheus exporter example.
> docs: fix typos in examples.contrib.prometheus

- docs/usage/channels.rst
- Fixes the `create_ws_route_handlers` typo in the docs by changing `create_route_handlers=True` to `create_ws_route_handlers=True`
Fixes #3596
> docs: fixed create_ws_route_handlers typo.

- litestar/contrib/pydantic/__init__.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/types/serialization.py
- tests/unit/test_contrib/test_pydantic/test_integration.py
Combines the following stale PRs:
- #3573
- #3327
Closes #3572 and #3147 
Context: https://github.com/litestar-org/litestar/pull/3327#issuecomment-2171148195
> feat(Pydantic): added parameters in pydantic plugin to support strict validation and all the `model_dump` args

- litestar/plugins/flash.py
Currently, the `FlashPlugin` expects the `request` parameter to be a type of `Request`.  However, there's no reason it can't use the parent class `ASGIConnection`. 
Doing this, allows for flash to be called in guards that expect an `ASGIConnection` instead of `Request`:
```python
def requires_active_user(connection: ASGIConnection, _: BaseRouteHandler) -> None:
if connection.user.is_active:
return
msg = "Your user account is inactive."
flash(connection, msg, category="error")
raise PermissionDeniedException(msg)
```
> fix: use `ASGIConnection` instead of `Request` for `flash`

- docs/index.rst
This PR fixes the "Available Issues" link in the sidebar of the litestar docs.
Currently I get redirected to a list of repositories in the litestar org with open issues. Deleting the trailing `=` links to the open issues themselves. I assume the latter was the intended destination.
> docs: fix link to available issues

- litestar/handlers/http_handlers/decorators.py
- tests/unit/test_handlers/test_http_handlers/test_head.py
Fix a bug where the validation of the return annotation for the `head` route handler was too strict and would not allow returning a `Response[None]`.
Fixes #3640.
> fix(handlers): Allow returning `Response[None]` from head route handlers

- litestar/connection/request.py
- tests/unit/test_connection/test_request.py
- tests/unit/test_kwargs/test_multipart_data.py
Fix #3627 by properly handling the creation of `FormMultiDict` where multiple values are given for a single key, to make `Request.form()` match the behaviour of receiving form data via the `data` kwarg.
<hr>
**Before**
```python
@post("/")
async def handler(request: Request) -> Any:
return (await request.form()).getall("foo")
with create_test_client(handler) as client:
print(client.post("/", data={"foo": ["1", "2"]}).json()) # [["1", "2"]]
```
**After**
```python
@post("/")
async def handler(request: Request) -> Any:
return (await request.form()).getall("foo")
with create_test_client(handler) as client:
print(client.post("/", data={"foo": ["1", "2"]}).json()) # ["1", "2"]
```
> fix(connection): Fix creation of FormMultiDict in Request.form to properly handle multi-keys

- docs/examples/parameters/header_and_cookie_parameters.py
- docs/examples/parameters/path_parameters_1.py
Starting from version 2, Pydantic uses `model_validate()` instead of `parse_obj()`. 
https://docs.pydantic.dev/2.8/migration/#changes-to-pydanticbasemodel
I have updated 2 places in the docs where the old deprecated method is used.
> fix: Small docs update.

- docs/usage/dependency-injection.rst
The comment "on the router" was incorrectly placed below the `my_route_handler()`, which could cause confusion. I've moved the comment to the appropriate location above the router configuration for better clarity. 
No functional changes were made.
> docs: Fix misplaced comment in dependency-injection.rst for better clarity

- litestar/dto/_backend.py
- litestar/serialization/msgspec_hooks.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
Fix inconsistent usage of msgspec's `strict` mode in the base DTO backend.
`strict=False` was being used when transferring from builtins, while `strict=True` was used transferring from raw data, causing an unwanted discrepancy in behaviour,
> fix(DTO): Inconsistent use of strict mode 

- litestar/_asgi/asgi_router.py
- litestar/_asgi/routing_trie/mapping.py
- litestar/_asgi/routing_trie/traversal.py
- litestar/_asgi/routing_trie/types.py
- litestar/contrib/prometheus/middleware.py
- litestar/testing/client/base.py
- litestar/testing/request_factory.py
- litestar/types/asgi_types.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example_with_extra_config.py
- tests/unit/test_contrib/test_prometheus.py
I changed previous 1-by-1 replacement logic for `PrometheusMiddleware.group_path=true` with a more robust and slightly faster solution
> fix(prometheus): use path template for prometheus metrics

- .pre-commit-config.yaml
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_before_send_handler.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_dependencies.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_init_plugin_example.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_plugin_example.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_serialization_dto.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_serialization_plugin.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_async_serialization_plugin_marking_fields.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_before_send_handler.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_dependencies.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_init_plugin_example.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_plugin_example.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_serialization_plugin.py
- docs/examples/contrib/sqlalchemy/plugins/sqlalchemy_sync_serialization_plugin_marking_fields.py
- docs/usage/databases/sqlalchemy/plugins/sqlalchemy_plugin.rst
- litestar/plugins/sqlalchemy.py
- pdm.lock
- pyproject.toml
- tests/examples/test_contrib/test_sqlalchemy/plugins/test_example_apps.py
This does this following:
- Uses `litestar.plugins.sqlalchemy` instead of the soon-to-be-deprecated `litestar.contrib.sqlalchemy`
- Unpin Advanced Alchemy
- Updated examples to use the plugins `create_all` functionality
> fix: updated sqlalchemy samples & unpin `advanced-alchemy`

- docs/examples/data_transfer_objects/factory/unknown_fields.py
- docs/usage/dto/1-abstract-dto.rst
- litestar/dto/_backend.py
- litestar/dto/config.py
- tests/examples/test_dto/test_example_apps.py
- tests/unit/test_dto/test_factory/test_integration.py
Add a new config option to `DTOConfig`: `forbid_unknown_fields`.
When set to `True`, a validation error response will be returned if the source data contains fields not defined on the model.
> feat(DTO): introduce `forbid_unknown_fields` config

- docs/conf.py
- docs/examples/security/jwt/custom_token_cls.py
- docs/usage/security/jwt.rst
- litestar/security/jwt/auth.py
- litestar/security/jwt/middleware.py
- litestar/security/jwt/token.py
- tests/unit/test_security/test_jwt/test_auth.py
Support customizing the `Token` class the JWT backends decode the payload into.
- Add new `token_cls` field on the JWT auth config classes
- Add new `token_cls` parameter to JWT auth middlewares
- Switch to using msgspec to convert the JWT payload into tokens, providing type coercion for custom token types without having to override the `Token.decode` method
```python
import dataclasses
import secrets
from typing import Any, Dict
from litestar import Litestar, Request, get
from litestar.connection import ASGIConnection
from litestar.security.jwt import JWTAuth, Token
@dataclasses.dataclass
class CustomToken(Token):
token_flag: bool = False
@dataclasses.dataclass
class User:
id: str
async def retrieve_user_handler(token: CustomToken, connection: ASGIConnection) -> User:
return …
```
> feat(JWT): Custom JWT payload classes

- litestar/contrib/pydantic/pydantic_dto_factory.py
- litestar/dto/base_dto.py
- tests/unit/test_contrib/test_pydantic/test_dto.py
- tests/unit/test_dto/test_factory/test_base_dto.py
Set `forbid_unkown_fields=True` for `PydanticDTOs` where the Pydantic model has an [`extra="forbid"`](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.extra) config.
<hr>
- Add a new `get_config_for_model_type` method to `AbstractDTO`, that allows to customise the base config defined on the DTO factory for a specific model type
- Use `get_config_for_model_type` to set `forbid_unkown_fields=True` for Pydantic models that use the `extra="forbid" config
<hr>
Depends on #3690. Don't merge before that one :)
> feat(DTO): Support `extra="forbid"` model config for `PydanticDTO`

- litestar/utils/module_loader.py
- tests/unit/test_utils/test_module_loader.py
To resolve the issue, we need to update the `module_to_os_path` function to check if the found path is a file. If it is, we should return the parent directory instead. This can be done by using `Path(src.origin).parent` if `src.origin` is a file.
> fix(#3554): correct ``module_to_os_path`` to return directory paths

- docs/usage/middleware/creating-middleware.rst
- docs/usage/security/excluding-and-including-endpoints.rst
- litestar/middleware/_utils.py
- litestar/middleware/authentication.py
- litestar/middleware/base.py
- litestar/middleware/csrf.py
- litestar/utils/warnings.py
- tests/unit/test_middleware/test_base_middleware.py
- tests/unit/test_security/test_security.py
Raise a warning when a middlewares `exclude` pattern greedily matches all paths.
Also document this footgun more prominently.
> feat(middleware): Warn about greedy exclude patterns

- litestar/middleware/csrf.py
- tests/unit/test_middleware/test_csrf_middleware.py
- csrf middleware should skip router entirely on match exclude config
close https://github.com/litestar-org/litestar/issues/3688
> fix: csrf middleware excluding router

- litestar/security/jwt/token.py
- tests/unit/test_security/test_jwt/test_auth.py
Fix a bug introduced in #3692 that would cause a `500` status response to be returned when `ValidationError` was raised during the token payload conversion.
This was caused by the switch to `msgspec` for converting the token payload after decoding and verification, and the lack of error handling for this case.
> fix(JWT): Response with 401 on token payload validation

- docs/conf.py
- docs/examples/security/jwt/custom_decode_payload.py
- docs/examples/security/jwt/verify_issuer_audience.py
- docs/usage/security/jwt.rst
- litestar/security/jwt/auth.py
- litestar/security/jwt/middleware.py
- litestar/security/jwt/token.py
- tests/examples/test_security/test_jwt/test_verify_issuer_audience.py
- tests/unit/test_security/test_jwt/test_auth.py
- tests/unit/test_security/test_jwt/test_token.py
Customise the automatic verification of JWTs.
<hr>
**JWT backend changes**
- Add `accepted_audiences` field
- Add `accepted_issuers` field 
- Add `require_claims` field 
- Add `verify_expiry` field 
- Add `verify_not_before` field 
- Add `strict_audience` field 
**JWT middleware changes**
- Add token_audience` parameter
- Add `token_issuer` parameter
- Add `require_claims` parameter 
- Add `verify_expiry` parameter 
- Add `verify_not_before` parameter 
- Add `strict_audience` parameter 
**Token changes** 
- Add `audience` parameter to `Token.decode`
- Add `issuer` parameter to `Token.decode`
- Add `require_claims` parameter to `Token.decode`
- Add `verify_exp` parameter to `Token.decode`
- Add `verify_nbf` parameter to `Token.decode`
- Add `strict_audience` parameter to `Token.decode`
- …
> feat(JWT): Customised token verification

- .github/workflows/ci.yml
- .github/workflows/test.yml
- litestar/_openapi/schema_generation/schema.py
- litestar/typing.py
- tests/unit/test_openapi/test_schema.py
- tests/unit/test_typing.py
Correctly handle OpenAPI schema generation for type aliases generated with the `type` keyword.
Fixes #3714.
> fix(OpenAPI): Correctly handle `type` keyword

- litestar/typing.py
- tests/unit/test_openapi/test_schema.py
Fix some improperly constructed test cases, where annotated types were constructed as `Annotated[str, annotated_types.LowerCase]` instead of `annotated_types.LowerCase[str]`, which lead to code that handled this incorrect case.
I stumbled across this during another refactor, where I wrote a correct test case that passed without this special code, while the old case was failing.
> refactor(typing): Remove "unpacking" of `annotated_types`

- litestar/_openapi/responses.py
- litestar/openapi/datastructures.py
- tests/unit/test_openapi/test_responses.py
Accept string for the `media_type` parameter of `ResponseSpec`, making it behave the same way as `Response.media_type` does.
Closes #3728.
> feat: Support strings in `media_type` for `ResponseSpec`

- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
Remove some laziness in testing Pydantic private fields, which is currently causing some [failing tests](https://github.com/litestar-org/litestar/actions/runs/10860782969/job/30141813399?pr=3364#step:7:178), due to a change in Pydantic's internals.
> test: Fix tests for pydantic private fields

- tests/unit/test_contrib/test_pydantic/test_integration.py
Follow up #3731, at it seems to still be breaking in some cases. 
These test cases were initially added to ensure we never touch the fields, but Pydantic changed some internals which make it so *they* touch them, causing our invalid annotation to result in an exception. This means we can't use this as a check anymore, but also don't need to.
> test: Fix for Pydantic private fields (2nd attempt)

- docs/release-notes/whats-new-3.rst
- litestar/enums.py
Update the MessagePack media type to the official `application/vnd.msgpack`.
Fixes #3727.
> feat: Update MessagPack media type

- litestar/_kwargs/extractors.py
- litestar/_kwargs/kwargs_model.py
- litestar/_kwargs/types.py
- litestar/routes/http.py
- litestar/routes/websocket.py
- pyproject.toml
- tests/unit/test_kwargs/test_cookie_params.py
- tests/unit/test_kwargs/test_header_params.py
- tests/unit/test_kwargs/test_query_params.py
Fix #3734. 
Ensure all data extractors are properly awaited by removing the delayed `await`
> fix: Fix dangling coroutines in request extraction handling cleanup

- litestar/middleware/csrf.py
- tests/unit/test_middleware/test_csrf_middleware.py
When `httponly` is `True`, it's impossible to set the header.  This fix allows this configruation to correctly validate.
> fix: `httponly` correction in CSRFMiddleware

- litestar/_openapi/datastructures.py
- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/schema_generation/utils.py
- litestar/params.py
- litestar/typing.py
- tests/unit/test_openapi/test_datastructures.py
- tests/unit/test_openapi/test_schema.py
Allow customizing the schema key used for a component in the OpenAPI schema. The motivation is to give the user an escape hatch when we inevitably generate some less than pretty looking names for deeply nested types for the sake of uniqueness.
These supplied key are enforced to be unique, and it is checked that they won't be reused across different types.
<hr>
- Add a new `schema_component_key` to `KwargDefinition` and the `Body` and `Parameter` functions
- Add a friendly error message when keys are not unique / reused across different types
> feat: Allow customizing schema component keys

- docs/usage/security/guards.rst
- litestar/handlers/base.py
- Update guard typing to `ASGIConnection | Request | WebSocket` to better reflect the object type that is passed to this handler
- Adjusted documentation accordingly.
Closes #3356
> docs: Explicitly mention connection classes in guard docs

- litestar/_openapi/datastructures.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_openapi/test_datastructures.py
- tests/unit/test_openapi/test_integration.py
This PR changes OpenAPI schema key generation function [`_get_normalized_schema_key`](https://github.com/litestar-org/litestar/blob/8c4c15bb501879dabaecfbf0af541ac571c08cf3/litestar/_openapi/schema_generation/utils.py#L86) to use valid characters according to the [OpenAPI specification](https://spec.openapis.org/oas/latest.html#fixed-fields-5), section `4.8.7.1`.
The strategy adopted by this PR was to replace sequences of invalid characters with underscores. Examples:
- `Foo[Bar]` -> `Foo_Bar`
- `dict[str, int]` -> `dict_str_int_`
Some tests had to be changed, because they were expecting the use of invalid characters (like square brackets, spaces and colons).
Closes #3630
> fix(OpenAPI): handle invalid schema keys

- litestar/handlers/http_handlers/base.py
- tests/unit/test_handlers/test_http_handlers/test_validations.py
Add an informative error message to help users avoid the common mistake of attempting to use the `body` parameter to receive validated / structured data, by annotating it with a type such as `list[str]`, instead of `bytes`. In such a case, the user will now be instructed to use the `data` parameter instead.
> feat: Raise exception when body parameter is annotated with non-bytes type

- litestar/_openapi/schema_generation/plugins/struct.py
- tests/unit/test_contrib/test_msgspec.py
Fix a bug where we would not include the struct fields implicitly generated by msgspec for its [tagged union](https://jcristharif.com/msgspec/structs.html#tagged-unions) support.
The change consists of an addition to the OpenAPI plugin where the tagged field will be added as a `const` to the schema.
Fix #3659.
> fix(OpenAPI): Correctly handle `msgspec.Struct` tagged unions

- litestar/middleware/csrf.py
- tests/unit/test_middleware/test_csrf_middleware.py
Reverts litestar-org/litestar#3739
This is an incorrect usage of the protocol.  The correct approach is to embed the csrf token within the form or template itself, so that it can be attached to the header.
> fix(revert): `httponly` correction in CSRFMiddleware

- litestar/typing.py
Fix a bug introduced in #3721 that was released with [2.12.0](https://github.com/litestar-org/litestar/releases/tag/v2.12.0) and would cause an `ImportError` when the `annotated_types` package was not installed.
Fixes #3749
> fix(typing): Don't require annotated_types

- litestar/openapi/plugins.py
- tests/unit/test_openapi/test_plugins.py
Supported OpenAPI UI clients will extract the CSRF cookie value and attach it to the request headers if CSRF is enabled on the application.
Scalar (https://github.com/scalar/scalar/discussions/2810), Redoc and (Stoplight) Elements does not seem to support interceptors or some other mechanism to achieve this.
Currently it also sends the header on "safe" methods but for both currently supported UI clients (Swagger and RapiDoc) it's possible to limit this to "unsafe" methods only, if required.
> feat: OpenAPI plugins send CSRF request header

- docs/tutorials/sqlalchemy/3-init-plugin.rst
- Tiny fix in line numbers to emphasise SQLAlchemyInitPlugin and not SQLAlchemySerializationPlugin is being added in this section of the tutorial. 
SQLAlchemySerializationPlugin is currently being highlighted which was the plugin shown in the previous section and is not being added here.
N/A
> fix: (typo) changed emphasis from line 12 to 11 to highlight the correct plugin being added in tutorial

- litestar/middleware/rate_limit.py
- tests/unit/test_middleware/test_rate_limit_middleware.py
When using the rate limit middleware, the response header fields `RateLimit-Remaining` and `RateLimit-Reset` have negative values. This branch fixes the issue.
This might be a breaking change for consumers of an API implemented with litestar.
I split the PR into four commits which might make it easier to review this PR.
Side note: Initially my commits didn't follow the conventional commits guidelines, but pre-commit didn't complain. See point 6 in https://github.com/litestar-org/litestar/blob/main/CONTRIBUTING.rst#workflow
Is this a bug in the pre-commit setup?
> fix: sign bug in rate limit middelware

- litestar/_openapi/schema_generation/schema.py
- litestar/openapi/spec/schema.py
- tests/unit/test_contrib/test_pydantic/test_openapi.py
…when property names from schema_extra are not found.
Address rejection of `schema_extra` values using JSONSchema spec-compliant key names by mapping between the relevant naming conventions.
Fixes #3766
> fix: map JSONSchema spec naming convention to snake_case when names from schema_extra are not found (#3766)

- README.md
- docs/PYPI_README.md
- Remove reference to `litestar-pg-redis-docker`
- Reorder the repos so that the easier example is at the top
- `docs/PYPI_README.md` generated from pre-commit
Closes #3773
> docs(readme): Remove reference to `litestar-pg-redis-docker`

- .devcontainer/Dockerfile
For now it is good to be 3.12
Later it can be updated to 3.13, when it will be supported (not until 3.13.1 in my opinion).
Closes #3789
> chore(devcontainer): Fix python version in devcontainer

- docs/examples/contrib/sqlalchemy/sqlalchemy_async_repository.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_declarative_models.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_extension.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
I've noticed this here: https://docs.litestar.dev/latest/usage/databases/sqlalchemy/models_and_repository.html#basic-controller-integration
> docs: fix typos in `sqlalchemy` examples

- docs/usage/caching.rst
It used to be:
Because the second line of https://github.com/litestar-org/litestar/blob/ad592f68aa8a76e844fee3e0f5d50101ebd9ce25/docs/examples/caching/cache.py#L2 was missing
> docs: fix missing import in `cache` usage

- docs/usage/channels.rst
Right now this code:
Is not really correct, because in case of an exception - it will not execute `await channels.unsubscribe(subscriber, ["foo"])`, which might be unexpected.
There's a similar example above that use the correct form:
> docs: make sure that `channels` use `finally` in all examples

- docs/admonitions/sync-to-thread-info.rst
I failed to understand the current version, so I used https://docs.litestar.dev/2/topics/sync-vs-async.html wording with a bit more verbosity.
> docs: change `sync-to-thread-info.rst` wording about `sync_to_thread`

- docs/usage/dto/1-abstract-dto.rst
`kebab` 🍖 case was missing!
I've also added a note about the argument type for the callback.
> docs: add missing rename strategy to `dto` docs

- .github/workflows/pr-merged.yml
Comments in JS start with `//` and not `#` 😅 
Closes #3810
> chore(ci): fix the `pr_merged.yml` workflow

- litestar/middleware/logging.py
- litestar/testing/websocket_test_session.py
- pyproject.toml
I've enabled more mypy codes:
- `local_partial_types` is needed for compat between `mypy` and `dmypy`
- `truthy-iterable` guards us from this problem:
```python
>>> class I:
...     def __iter__(self):
...         return iter([])
...         
>>> bool(I())
True
```
We had this problem in three places:
```
» pdm run mypy
litestar/middleware/logging.py:106: error: Member "response_log_fields" has type "Iterable[Literal['status_code', 'headers', 'body', 'cookies']]" which can always be true in boolean context. Consider using "Collection[Literal['status_code', 'headers', 'body', 'cookies']]" instead.  [truthy-iterable]
litestar/middleware/logging.py:109: error: Member "request_log_fields" has type "Iterable[Literal['path', 'method', 'content_type', 'headers', 'cookies', 'query', …
```
> chore(mypy): enable more mypy codes

- litestar/contrib/sqlalchemy/__init__.py
- litestar/contrib/sqlalchemy/repository/__init__.py
- pyproject.toml
Docs: https://mypy.readthedocs.io/en/stable/error_code_list2.html#warn-about-variables-that-are-defined-only-in-some-execution-paths-possibly-undefined
Why did I make the code change?
- We handle all names defined in `__all__` via `if` and `elif` branches
- If we somehow forget to handle a name in the future (before this module is removed), it will raise an error
- Users should not be affected by the change
- It will be removed in 3.0 with the warning
- Now mypy is happy :)
> chore(mypy): enable `possibly-undefined` error code

- docs/usage/dto/1-abstract-dto.rst
Link: https://docs.litestar.dev/latest/usage/dto/1-abstract-dto.html#dto-data
There were several issues:
1. Model was renamed to `User` from `Person`
2. There was no 500 error no more
3. Explanation about default field was missing
4. `CreatePerson` should be better named `UserCreate` "noun-verb" to better group models
5. Code highlight was marking wrong lines
> docs: fix `DTO Data` section with a new example

- docs/usage/dto/1-abstract-dto.rst
Right now: https://docs.litestar.dev/latest/usage/dto/1-abstract-dto.html#providing-values-for-nested-data
> docs: fix highlight of code example in "Providing values for nested data"

- docs/usage/htmx.rst
- I added a short intro: what is HTMX? Because not people are familiar with it (I was not for example)
- I also explained what `if request.htmx` means
- Always spell `HTMX` as `HTMX` and not `htmx` or anything else
- Always use `~` instead of duplicating class names
- Use special syntax for notes: `.. note::`
> docs: rewrite htmx guide

- docs/usage/lifecycle-hooks.rst
Just a minor refactoring + one highlight fix.
> docs: refactor "Hooks" usage documentation

- docs/reference/types.rst
It used to be:
After my change:
Note that we still don't expose `asgi_types` module as an implementation detail.
> docs: fix API reference for `asgi_types` scopes

- docs/usage/logging.rst
- docs/usage/middleware/builtin-middleware.rst
Changes:
- More links for everything
- Small wording changes here and there
- Code highlight changes
- Corrected `:class:` usage with `~` instead of duplicating class name
- Better `Brottli` docs and corrected defaults
- Changed several `:doc:` links to be `:ref:`
> docs: rewrite "Builtin middleware" usage

- litestar/_asgi/routing_trie/traversal.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example.py
When `PrometheusConfig.group_path=True` the metrics exporter response content ignores all paths with no path parameters.
- Example for path `/test/litestar` when `group_path=True`
> litestar_request_duration_seconds_bucket{app_name="litestar",le="0.075",method="GET",path="",status_code="200"} 1.0
- Example for path `/test/litestar` when `group_path=False`
> litestar_request_duration_seconds_bucket{app_name="litestar",le="2.5",method="GET",path="/test/litestar",status_code="200"} 1.0
So, when the path has no params return the actual path as template so Prometheus can use it when `group_path=True`.
Added more test cases to cover this case.
> fix(prometheus): fix path template for routes without path parameters

- docs/examples/middleware/base.py
- docs/usage/middleware/creating-middleware.rst
- docs/usage/middleware/using-middleware.rst
Link: https://docs.litestar.dev/latest/usage/middleware/creating-middleware.html
Changes:
- I removed `super().__init__` call for `Protocol`, it should not happen by definition, because `Protocol` cannot have any implementation in `__init__`
- I used `time.monotonic` for timing examples, because it is more fitting for the job, I can use `perf_counter` instead if you wish
- I removed several `if TYPE_CHECKING` blocks, because they made examples more complex to read with no real need
- `logger.info` should be lazy in terms of string format, not eager
- `~` usage, where possible
- `exclude_from_middleware` -> `exclude_from_my_middleware`, because it was not clear if this name was special or not. Now it is clear that it is a user defined name.
And other small fixes here and there :)
> docs: refactor "Custom Middleware" guide

- litestar/testing/client/async_client.py
- litestar/testing/client/sync_client.py
- litestar/testing/life_span_handler.py
- tests/unit/test_testing/test_lifespan_handler.py
Fix a dangling anyio stream in `LifespanHandler`.
Closes #3834.
> fix: LifespanHandler memory stream cleanup

- .pre-commit-config.yaml
- docs/conf.py
- docs/reference/plugins/htmx.rst
- docs/reference/plugins/index.rst
- docs/usage/htmx.rst
- litestar/contrib/htmx/_utils.py
- litestar/contrib/htmx/request.py
- litestar/contrib/htmx/response.py
- litestar/contrib/htmx/types.py
- litestar/datastructures/upload_file.py
- litestar/plugins/htmx.py
- pdm.lock
- pyproject.toml
- tests/unit/test_contrib/test_htmx/test_htmx_deprecations.py
- tests/unit/test_contrib/test_htmx/test_htmx_request.py
- tests/unit/test_template/test_template.py
- tests/unit/test_testing/test_test_client.py
This plugin migrates the HTMX integration to `litestar.plugins.htmx`.  
This logic has been moved to it's own repository named `litestar-htmx`
This is in preparation for 3.0 release where `contrib` will be deprecated.
> feat: implement `HTMX` plugin using `litestar-htmx`

- litestar/contrib/pydantic/pydantic_init_plugin.py
Pydantic's `BaseModel` supports configuration to hide data values when throwing exceptions, via setting `hide_input_in_errors` -- see https://docs.pydantic.dev/2.0/api/config/#pydantic.config.ConfigDict.hide_input_in_errors and https://docs.pydantic.dev/latest/usage/model_config/#hide-input-in-errors (the value is also in 2.0, but not linkable in the non-`latest` version of the documentation build).
At present, Litestar does not honor this configuration when generating exceptions for validation errors, which can lead to sensitive data leaking into logs.
> feat(Pydantic): honor hide_input_in_errors in throwing validation exceptions

- litestar/middleware/logging.py
- litestar/middleware/response_cache.py
I've encountered an issue in sqladmin-litestar-plugin where some ASGI frameworks (such as Starlette) do not include "more_body": false in the "http.response.body" event. According to the ASGI specification, this key should be set to False when there is no additional body content. Litestar expects "more_body" to be explicitly defined, but others might not.
This leads to failures when an ASGI framework mounted on Litestar throws error for the "more_body" key in "http.response.body". 
I have changed it to `message.get('more_body')`as @cofin suggests.
> fix: Safe Handling of "more_body" in ASGI Responses

- litestar/_openapi/schema_generation/schema.py
- litestar/_openapi/typescript_converter/converter.py
- litestar/security/base.py
- pyproject.toml
Docs: https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-expression-is-not-implicitly-true-in-boolean-context-truthy-bool
I am using `# type: ignore[truthy-bool]` for `.components` check, because I see that it is treated specially for some reason (like `pragma: no cover`). Is this correct?
I also removed configs that are part of the `--strict` flag from settings.
> chore(mypy): enable `truthy-bool` error code

- docs/usage/security/abstract-authentication-middleware.rst
- docs/usage/security/jwt.rst
- pdm.lock
- pyproject.toml
- tests/unit/test_contrib/test_opentelemetry.py
> docs: remove references to `python-jose`

- litestar/middleware/rate_limit.py
- tests/unit/test_middleware/test_rate_limit_middleware.py
Fixes https://github.com/litestar-org/litestar/issues/3625
`RateLimitMiddleware` duplicate all `RateLimit-*` headers when handler cache is enabled because it's adding new rate limit headers to the new ones, instead of just updating their values.
```
❯ curl -i http://localhost:8000/
HTTP/1.1 200 OK
date: Tue, 12 Nov 2024 06:50:18 GMT
server: uvicorn
content-type: text/plain; charset=utf-8
content-length: 2
ratelimit-policy: 10; w=60
ratelimit-limit: 10
ratelimit-remaining: -8
ratelimit-reset: -54
ratelimit-policy: 10; w=60
ratelimit-limit: 10
ratelimit-remaining: 0
ratelimit-reset: -49
```
```
❯ curl -i http://localhost:8000/
HTTP/1.1 200 OK
date: Tue, 12 Nov 2024 06:50:18 GMT
server: uvicorn
content-type: text/plain; charset=utf-8
content-length: 2
ratelimit-policy: 10; w=60 …
```
> fix: Duplicate `RateLimit-*` headers with caching

- docs/examples/middleware/base.py
- docs/usage/middleware/creating-middleware.rst
Changes: 
- I'm change indentation of the `await send(message)` expression in `send_wapper` function which was causing the `ERROR:    ASGI callable returned without completing response.`
link: https://docs.litestar.dev/2/usage/middleware/creating-middleware.html#inheriting-abstractmiddleware
> docs:  Changing incorrect indentation in the code example "creating-middleware#inheriting-abstractmiddleware"

- docs/topics/sync-vs-async.rst
> docs: fix the description of when to use the synchronous function

- docs/examples/testing/test_get_session_data.py
- docs/examples/testing/test_get_session_data_async.py
- docs/examples/testing/test_health_check_async.py
- docs/examples/testing/test_health_check_sync.py
- docs/examples/testing/test_set_session_data.py
- docs/examples/testing/test_set_session_data_async.py
- docs/usage/testing.rst
- I added `debug=True` to the sample code for the test files, for display debug stack trace.
Link: https://docs.litestar.dev/latest/usage/testing.html
Closes #3780
> docs: Added debug=True in Testing to display exception stack trace

- litestar/handlers/websocket_handlers/listener.py
- pyproject.toml
- tests/unit/test_handlers/test_websocket_handlers/test_listeners.py
Fixes #3763 
It seems that declaring the actual method is the only way to comply with `mypy` in such cases.
There is a `ruff` rule that forbids empty methods in abstract classes, had to disable that for the relevant module.
> fix(typing): Fix typing in websocket listener class

- docs/examples/plugins/prometheus/using_prometheus_exporter.py
- docs/examples/plugins/prometheus/using_prometheus_exporter_with_extra_configs.py
- docs/reference/plugins/index.rst
- docs/reference/plugins/prometheus.rst
- docs/usage/metrics/prometheus.rst
- litestar/contrib/prometheus/__init__.py
- litestar/contrib/prometheus/config.py
- litestar/contrib/prometheus/controller.py
- litestar/contrib/prometheus/middleware.py
- litestar/plugins/prometheus/__init__.py
- litestar/plugins/prometheus/config.py
- litestar/plugins/prometheus/controller.py
- litestar/plugins/prometheus/middleware.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example.py
- tests/examples/test_contrib/prometheus/test_prometheus_exporter_example_with_extra_config.py
- tests/unit/test_contrib/test_prometheus.py
- tests/unit/test_plugins/test_prometheus.py
feat: deprecate `litestar.contrib.prometheus` in favor of the new location of `litestar.plugins.prometheus`
> feat: move `litestar.contrib.prometheus` to `litestar.plugins.prometheus`

- .pre-commit-config.yaml
- pdm.lock
- pyproject.toml
This PR removes the optional `htmx` group for the project dependencies.  HTMX is a built in feature and is not optional.
> fix: remove optional group for `litestar-htmx`

- litestar/config/app.py
- tests/unit/test_app.py
This adds a `future` flag to `experimental_features` to enable new features that may be otherwise considered breaking.
> feat: add `future` flag to `experimental_features`

- litestar/middleware/_internal/exceptions/middleware.py
- litestar/plugins/pydantic/plugins/schema.py
- pdm.lock
- tests/unit/test_plugins/test_pydantic/test_pydantic_dto_factory.py
Pydantic `>=2.10` breaks because of the way we reference some types in our OpenAPI type map. This can be fixed by including the proper references. This fix is backwards compatible :)
> fix(pydantic): Add moved URL types to type map 

- litestar/contrib/opentelemetry/plugin.py
- This should allow workarounds like OpenTelemetrySingletonMiddleware from https://github.com/litestar-org/litestar/issues/3056
to work with the patching applied in https://github.com/litestar-org/litestar/pull/3689
> fix: patching of otel middleware to work with subclasses

- litestar/_kwargs/extractors.py
- litestar/_multipart.py
- litestar/connection/request.py
- litestar/datastructures/upload_file.py
- pyproject.toml
- tests/unit/test_kwargs/test_multipart_data.py
- uv.lock
Add a streaming multipart parser via the [multipart](https://github.com/defnull/multipart) lib.
This gives us:
- Ability to stream large / larger-than-memory file uploads
- Better / more correct edge case handling
- Still good performance
> feat(core): Streaming multipart parser

- litestar/_kwargs/extractors.py
- litestar/_multipart.py
- litestar/connection/request.py
- litestar/datastructures/multi_dicts.py
- litestar/datastructures/upload_file.py
- litestar/routes/http.py
- litestar/utils/scope/state.py
- pyproject.toml
- tests/e2e/test_routing/conftest.py
- tests/unit/test_datastructures/test_multi_dicts.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_plugins/test_pydantic/test_beanie_integration.py
- Fix `ResourceWarning` from unclosed `UploadFile` instances
- Fix `ResourceWarning` in `run_server` fixture
- Report all warnings as errors unless explicitly silenced
Closes #3835
> fix: resource warnings

- litestar/di.py
Corrected the exception message from "Provider dependency must a callable value" to "Provider dependency must be a callable value". This ensures clarity and proper grammar in error messages.
> fix: typo in exception message for ImproperlyConfiguredException

- litestar/response/redirect.py
- tests/unit/test_response/test_redirect_response.py
Closes https://github.com/litestar-org/litestar/issues/3891.
> feat: add query params to redirect response

- litestar/response/file.py
- tests/unit/test_response/test_file_response.py
Change the implementation of `responses.File` to be able to handle most fsspec implementation's `mtime` equivalent.
This is necessary because fsspec implementations do not have a standardised way to retrieve an `mtime` equivalent; Some report an `mtime`, while some may use a different key (e.g. `Last-Modified`) and others do not report this value at all.
Fixes #3899
> fix(file response): Support varying `mtime` semantics across different fsspec implementations

- docs/conf.py
- docs/reference/stores/index.rst
- docs/reference/stores/valkey.rst
- docs/usage/stores.rst
- litestar/stores/valkey.py
- pyproject.toml
- tests/conftest.py
- tests/docker-compose.yml
- tests/docker_service_fixtures.py
- tests/unit/test_stores.py
- uv.lock
- Adds Valkey as a native store alternative to Redis.
- Adds an optional Litestar install dependency: `litestar[valkey]` which installs `valkey` with `libvalkey` as an optimisation layer.
> feat: add Valkey as a native store

- litestar/datastructures/response_header.py
- litestar/openapi/spec/base.py
- litestar/openapi/spec/header.py
- litestar/openapi/spec/parameter.py
- tests/e2e/test_openapi/test_spec_headers.py
- tests/unit/test_openapi/test_config.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_openapi/test_responses.py
Remove the inclusion of the query-only properties `allowEmptyValue` and `allowReserved` in path, cookie, header parameter and response header schemas.
Fixes #3908
> fix(OpenAPI): Query-only properties included in path, cookie and header parameter schema and response headers (#3908)

- litestar/_signature/model.py
- tests/unit/test_signature/test_validation.py
- Use "path" as the "source" property for an error message if the key is a path parameter
Closes #3919
> feat: use "path" as an error message source

- litestar/logging/config.py
- litestar/logging/picologging.py
- pyproject.toml
- tests/helpers.py
- tests/unit/test_logging/test_logging_config.py
…3.13, etc.)
Picologging does not currently support Python 3.13.  This change proactively adds updates to ensure tests work when picologging is not supported in the python environment.
> fix(picologging): better handle unsupported environments

- litestar/channels/backends/psycopg.py
- pyproject.toml
- tests/unit/test_channels/test_plugin.py
This PR updates the channels backend to use the native psycopg `SQL` API. 
Additionally, it preemptively fixes some new warnings from upcoming pyright and ruff changes
> fix(channels): use `SQL` function for `psycopg`

- Makefile
running `make install` now will result in a broken environment because it tries to install 3.13.  
This can be removed one the 3.13 PR is merged.
> chore(build): prevent python 3.13 from installing

- pyproject.toml
- tests/unit/test_openapi/conftest.py
- tests/unit/test_typing.py
- uv.lock
This un-pins `pytest` from v7 and has the required changes to support pytest 8.
> chore(test): update `pytest` and unpin max version

- litestar/middleware/compression/middleware.py
- tests/unit/test_middleware/test_compression_middleware.py
Fix a few cases where we didn't close resources in the right order, leading to either "unclosed resource" or "I/O on closed file" warnings
> fix(compression middleware): Fix resource handling

- docs/examples/dependency_injection/dependency_validation_error.py
This PR fixes a typo in docs/examples/dependency_injection/dependency_validation_error.py
-
> docs: fix typo in dependency_validation_error

- .github/workflows/ci.yml
- .github/workflows/test.yml
> fix(ci):  Github CI fail due to deprecated action

- docs/examples/application_hooks/after_exception_hook.py
- docs/examples/application_hooks/before_send_hook.py
- docs/examples/application_state/using_application_state.py
- docs/examples/routing/mount_custom_app.py
- docs/examples/routing/mounting_starlette_app.py
- docs/usage/applications.rst
- litestar/app.py
- litestar/connection/base.py
- litestar/handlers/asgi_handlers.py
- litestar/middleware/_internal/cors.py
- litestar/middleware/_internal/exceptions/middleware.py
- litestar/middleware/csrf.py
- litestar/middleware/logging.py
- litestar/middleware/rate_limit.py
- litestar/middleware/response_cache.py
- litestar/routes/asgi.py
- litestar/routes/http.py
- litestar/testing/client/base.py
- litestar/testing/request_factory.py
- litestar/types/asgi_types.py
- litestar/utils/scope/__init__.py
- tests/conftest.py
- tests/unit/test_app.py
- tests/unit/test_handlers/test_asgi_handlers/test_handle_asgi.py
When mounting ASGI apps, there's no guarantee they won't overwrite some key in the `scope` that we rely on, e.g. `scope["app"]`, which is what caused #3934.
To prevent this, I've implemented two things:
1. Do not store the Litestar instance under the generic `app` key, but the more specific `litestar_app` key. I've also added a `Litestar.from_scope` method, which can be used to safely access the current app from the sope
2. Added a new parameter `copy_scope` to the ASGI route handler, which, when set to `True` will copy the scope before calling into the mounted ASGI app. This should make things behave more as expected, since it truly give the called app its own environment without causing any side-effects. Since this change might break some things, I've left it with a default of `None`, …
> fix(ASGI mounts): Prevent accidental scope overrides by mounted ASGI apps

- Makefile
- Remove `--all-extras --dev`, as they're redundant with the default-groups defined here https://github.com/litestar-org/litestar/blob/518af0dda4e1fea75755147fee2a90dee778e121/pyproject.toml#L125
> chore: remove unnecessary flags from install command in Makefile

- Makefile
https://github.com/litestar-org/litestar/pull/3958 wasn't enough 🤦‍♂️  need to pass `--port=0` to let sphinx-autobuild select a port: https://github.com/sphinx-doc/sphinx-autobuild?tab=readme-ov-file#working-on-multiple-projects
> chore: allow sphinx-autobuild to choose port for serving docs

- docs/examples/security/jwt/using_token_revocation.py
- docs/usage/security/jwt.rst
- litestar/security/jwt/auth.py
- litestar/security/jwt/middleware.py
- tests/unit/test_security/test_jwt/test_auth.py
Added support for ```revoked_token_handler``` on same level with ```retrieve_user_handler```,
thought about JWTManager like in ```flask-jwt-extended```, but my solution, i think looks cleaner.
- Added revoked token handler in Auths and Middlewares
- Added tests
- Added usage doc
#2118
> feat(jwt): Added revoked token handler support

- docs/_static/style.css
- Changed mermaid diagrams text color for dark theme to black
#3950
> fix(docs): improve text color for dark theme in mermaid diagrams

- litestar/app.py
- tests/e2e/test_routing/test_route_reverse.py
This allows params of type UUID to be passed as strings (e.g. their hex representation) into route_reverse (just like datetime, Path etc.). I don't know if the test is really necessary, but that is for the maintainers to decide.
Originally I intended to allow int too, but this broke about 20 tests I did not feel confident to fix them all in a reasonable amount of time.
Discussed in [#3968](https://github.com/litestar-org/litestar/issues/3968#issuecomment-2612178106)
> feat: allow route_reverse params of type uuid to be passed as str

- litestar/cli/_utils.py
- tests/unit/test_cli/test_cli.py
• I added new func that output readable errors when --app arg take invalid argument and stop process
I will be glad to receive feedback 😊.
-
Closes #3893
> feat: Make better error message for invalid --app string

- litestar/dto/base_dto.py
- litestar/dto/dataclass_dto.py
- litestar/dto/msgspec_dto.py
- tests/unit/test_contrib/test_msgspec.py
- tests/unit/test_dto/test_factory/test_dataclass_dto.py
> feat(DTOs): Support `@property` fields for msgspec and dataclass

- docs/release-notes/changelog.rst
Apparently there as a glitch in the v2.14.0 release notes tooling, and it included a whole bunch of PRs that didn't belong into that release
> docs: fix v2.14.0 release notes

- docs/tutorials/todo-app/1-accessing-the-list.rst
The URL is missing the default port so it doesn't load correctly. I added it like all the other URLs to 127.0.0.1 on the page.
> docs: Add missing port to url

- docs/usage/stores.rst
In https://docs.litestar.dev/2/usage/stores.html#built-in-stores, `ValkeyStore` is wrongly spelt `ValKeyStore`.
> docs: Fix casing in name of ValkeyStore

- docs/examples/request_data/request_data_8.py
- Updated the Pydantic model configuration in Requests example with multiple files
> docs: Updated the Pydantic model configuration in Requests example with multiple files

- litestar/middleware/rate_limit.py
- I fixed reference based on https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#links-to-external-web-pages
- docs page route: reference/middleware/rate_limit.html
#3998
> docs: #3998 Fix IETF reference

- .github/ISSUE_TEMPLATE/BUG.yml
- .github/ISSUE_TEMPLATE/DOCS.yml
- .github/ISSUE_TEMPLATE/REQUEST.yml
This simple pull request improves GitHub issues templates, as the BUG.yaml was quite frustating when I created #4016
Before:
After:
Summary of changes:
- Changed image upload textarea to a WYSIWYG to allow hosting images on GitHub instead of forcing raw markdown.
- To ensure consistency in the, changed JSON lists to YAML lists.
- Improved descriptions and placeholders
> docs: improve github issue templates

- .github/workflows/ci.yml
Add an 'aggregate' step that fails if one of the matrix jobs from the `test` job fail, so we can target this aggregate job as "required check" instead of the individual matrix jobs. 
This allows us to e.g. have a `3.8` matrix job on one branch but not on the other, while still making the run fail if any of the matrix jobs fails.
> ci: Add aggregate test step to allow for dynamic test matrix jobs to be requried checks

- docs/examples/middleware/abstract_middleware_migration_new.py
- docs/examples/middleware/abstract_middleware_migration_old.py
- docs/examples/middleware/middleware_protocol_migration_new.py
- docs/examples/middleware/middleware_protocol_migration_old.py
- docs/examples/middleware/request_timing.py
- docs/examples/middleware/using_asgi_middleware.py
- docs/usage/middleware/creating-middleware.rst
- litestar/middleware/__init__.py
- litestar/middleware/_utils.py
- litestar/middleware/base.py
- tests/unit/test_middleware/test_base_middleware.py
Add a new base middleware class to facilitate easier configuration and middleware dispatching.
The new `ASGIMiddleware` features the same functionality as the `AbstractMiddleware`, but makes it easier to pass configuration directly to middleware classes without a separate configuration object, allowing to get rid of the `DefineMiddleware` pattern entirely.
<hr> 
If we are to add this, I propose we do so in v2, and migrate existing middlewares to this pattern in v3.
> feat(core): new base middleware

- docs/examples/plugins/init_plugin_protocol.py
- docs/usage/plugins/index.rst
- litestar/_openapi/plugin.py
- litestar/channels/plugin.py
- litestar/contrib/opentelemetry/plugin.py
- litestar/plugins/__init__.py
- litestar/plugins/base.py
- litestar/plugins/flash.py
- litestar/plugins/problem_details.py
- litestar/plugins/pydantic/__init__.py
- litestar/plugins/pydantic/plugins/init.py
- litestar/plugins/structlog.py
- tests/unit/test_plugins/test_base.py
- Add `SerializationPlugin` to replace `SerializationPluginProcotol`
- Add `InitPlugin` to replace `InitPluginProtocol`
These are the only ones for which the protocols don't have a non-protocol equivalent. 
Following the same approach as for other plugins, they inherit their respective protocol for now, to keep type / `isinstance` checks compatible.
> feat: Add `SerializationPlugin` and `InitPlugin` to replace their respective protocols 

- docs/release-notes/2.x-changelog.rst
- docs/release-notes/whats-new-3.rst
- docs/tutorials/sqlalchemy/0-introduction.rst
- docs/usage/cli.rst
- docs/usage/databases/sqlalchemy/plugins/sqlalchemy_serialization_plugin.rst
- litestar/app.py
- litestar/plugins/__init__.py
- litestar/plugins/base.py
- pyproject.toml
- tests/unit/test_app.py
- tests/unit/test_cli/test_cli_plugin.py
- tests/unit/test_plugins/test_base.py
- uv.lock
Remove the deprecated `CLIPluginProtocol` for v3.0.
<hr>
Currently failing because we still need to upgrade AA: https://github.com/litestar-org/advanced-alchemy/pull/399
> feat(plugins)!: Remove `CLIPluginProtocol`

- docs/examples/application_state/using_application_state.py
- docs/release-notes/whats-new-3.rst
- litestar/_asgi/routing_trie/mapping.py
- litestar/types/composite_types.py
- tests/unit/test_asgi/test_routing_trie/test_mapping.py
Remove support for the starlette middleware protocol. 
This was added as a backwards compatibility fix when we transition away from the starlette dependency.
> feat: Remove starlette middleware compat

- docs/tutorials/repository-tutorial/01-modeling-and-features.rst
- docs/tutorials/repository-tutorial/02-repository-introduction.rst
- docs/tutorials/repository-tutorial/03-repository-controller.rst
- docs/tutorials/repository-tutorial/04-repository-other.rst
- docs/usage/channels.rst
- docs/usage/security/guards.rst
By submitting this pull request, I agree to:
"click to expand" was replaced with "click to toggle" as the action both expands and collapses a section, thus the term "toggle" is more suitable as it works both ways.
Not applicable.
> docs: Use "click to toggle" instead of "click to expand"

- litestar/response/streaming.py
Litestar allows passing in a `body` parameter for a streaming response, but this parameter is ignored.
I'm adding a deprecation warning for this parameter, so we can remove it in v3.
> fix: Warn about using streaming responses with a `body`

- docs/examples/middleware/base.py
- litestar/middleware/base.py
Fix a bug introduced in #3996 that would incorrectly issue a deprecation warning if a user subclassed a Litestar built-in middleware which itself subclasses `AbstractMiddleware`.
Fix consists of checking the mro to ensure we're only warning if the subclass has `AbstractMiddleware` as a direct ancestor within the user code.
Fix #4035
> fix: Fix #4035 - incorrect deprecation warning issued when subclassing middlewares

- litestar/middleware/_internal/cors.py
- Some clients sometimes apparently (AFAIK needlessly) check OPTIONS even if they only have CORS-safelisted headers to ask about; I ran into this with [Dio](https://pub.dev/packages/dio). I see no reason to allow I guess?
> fix: check for default headers before appending to cors header failures

- docs/tutorials/repository-tutorial/01-modelling-and-features.rst
- docs/tutorials/repository-tutorial/02-repository-introduction.rst
- docs/tutorials/repository-tutorial/index.rst
- litestar/app.py
- litestar/config/app.py
- litestar/controller.py
- litestar/handlers/base.py
- litestar/router.py
- litestar/testing/helpers.py
By submitting this pull request, I agree to:
Occurrences of "modeling" were replaced with "modelling".
Previously both "modeling" and "modelling" were used.
Not applicable.
> docs: Make the spelling of "modelling" consistent

- docs/examples/testing/test_websocket.py
- docs/usage/testing.rst
- I discovered by accident I could use Litestar built-ins instead of httpx_ws so this adresses it since there is no mention in the docs
> docs: add websockets testing capabilities

- litestar/file_system.py
Hi there!
I have tried to plug MinIO via [create_static_files_router](https://docs.litestar.dev/2/usage/static-files.html#remote-file-systems) 
```
MinioSystem = s3fs.S3FileSystem(
anon=False,
key=settings.MINIO_ROOT_USER,
secret=settings.MINIO_ROOT_PASSWORD,
endpoint_url=settings.minio_url,
)
api_router = Router(
path=settings.API_STR,
route_handlers=[
...
create_static_files_router(
path="/media",
directories=["media"],
file_system=MinioSystem,
resolve_symlinks=False,
),
],
)
app = Litestar(
route_handlers=[api_router],
...
)
```
and after
```
curl 'http://127.0.0.1:8000/api/v1/media/avatars/4884a139-970d-4467-974c-48add111cd10.png'
```
I have recieved this error:
```
...
RuntimeError: Response content shorter than Content-Length
```
I have researched a bit and realized that …
> fix: explicit specification of arguments in FileSystemAdapter open func.

- docs/examples/openapi/generating_examples.py
- docs/getting-started.rst
- docs/release-notes/whats-new-3.rst
- docs/usage/openapi/schema_generation.rst
- pyproject.toml
- uv.lock
Move `polyfactory` from the default dependencies to `polyfactory` extra. It is not used by default anymore and hidden behind an OpenAPI config flag.
> feat: v3 - Make `polyfactory` an optional dependency

- litestar/openapi/spec/security_requirement.py
Finally found the source of the mysterious
```
docstring of builtins.dict:3: ERROR: Unexpected indentation.
docstring of builtins.dict:4: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of builtins.dict:7: ERROR: Unexpected indentation.
docstring of builtins.dict:9: WARNING: Inline strong start-string without end-string.
```
Still no idea *why* that suddenly is an issue but :woman_shrugging:
> docs(v3): fix build error

- docs/getting-started.rst
- docs/release-notes/whats-new-3.rst
- docs/usage/htmx.rst
- pyproject.toml
- uv.lock
Move `litestar-htmx` from a default dependency to the `litestar[htmx]` extra.
> feat: v3 - Move `litestar-htmx` to a package extra

- README.md
- docs/PYPI_README.md
The Discord invite link in the readme is expired.
This is also the case at https://litestar.dev header and footer, but unfortunately I didn't find where the url was sourced from (https://github.com/litestar-org/litestar.dev/blob/0854bdd6c8f9263b67cb561926641781bf291176/page/_templates/landing-page.html#L85).
> docs: Replace expired Discord invite link

- .github/workflows/ci.yml
- .github/workflows/test.yml
- litestar/typing.py
- tests/unit/test_typing.py
- Fix #4088 by handling the diverging `TypeAliasType` introduced in typing-extensions `4.13.0`; This type is no longer backwards compatible, as it is a distinct new type from `typing.TypeAliasType`. We need to check for both types now
- Add a new test job to the CI to test against known diverging versions of `typing-extensions`
> fix(typing): Correctly handle `typing_extensions.TypeAliasType` on `typing-extensions>4.13.0` (fix #4088)

- .github/workflows/ci.yml
To ensure compatibility, run against typing-extension pre-releases as an early warning
> ci: Test against typing-extension pre-releases

- README.md
- docs/PYPI_README.md
- docs/usage/logging.rst
- litestar/logging/config.py
- litestar/middleware/_internal/exceptions/middleware.py
- tests/unit/test_logging/test_logging_config.py
- tests/unit/test_logging/test_structlog_config.py
In the logger configuration, users can specify a set of status codes and exception types for which Litestar will not log the full stack trace.
#4081 
```py
import uvicorn
from litestar import Litestar, get
from litestar.logging import LoggingConfig
@get("/")
async def index() -> str:
return "Hello, world!"
@get("/value-error")
async def value_error() -> None:
raise ValueError("This is a test value error.")  # not log the stack trace
@get("/name-error")
async def name_error() -> None:
raise NameError("This is a test name error.")
app = Litestar(
route_handlers=[index, value_error, name_error],
debug=True,
logging_config=LoggingConfig(
disable_stack_trace={404, ValueError}  # disable_stack_trace: set[Union[int, type[Exception]]]
),
)
if __name__ == "__main__":
uvicorn.run(app=app, …
```
> feat(log): disable stack trace

- docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_init_plugin.py
- docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_plugin.py
- docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_serialization_plugin.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_bulk_operations.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_crud.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_extension.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
- docs/examples/data_transfer_objects/factory/my_lib.py
- docs/examples/pagination/using_offset_pagination_with_sqlalchemy.py
- docs/examples/plugins/sqlalchemy/configure.py
- docs/examples/plugins/sqlalchemy/modelling.py
- docs/examples/plugins/sqlalchemy_init_plugin/sqlalchemy_async.py
- docs/examples/plugins/sqlalchemy_init_plugin/sqlalchemy_sync.py
- docs/tutorials/repository-tutorial/02-repository-introduction.rst
- docs/tutorials/repository-tutorial/04-repository-other.rst
- docs/tutorials/sqlalchemy/2-serialization-plugin.rst
- docs/tutorials/sqlalchemy/3-init-plugin.rst
- docs/tutorials/sqlalchemy/4-final-touches-and-recap.rst
By submitting this pull request, I agree to:
Changes in example code were made to use `litestar.plugins.sqlalchemy` instead of `litestar.contrib.sqlalchemy` as the latter is being depreciated.
Documentation files where the changed files were referenced were updated as well to adjust the referenced lines because:
- amount of lines in the import section were changed in some referenced files that were updated;
- they already were off.
Additionally imports and other relevant parts were included in code example blocks so it could be easily seen what is imported from where.
Not applicable.
> docs: Replace contrib with plugins in example code

- docs/usage/websockets.rst
Docs said `send_websocket_stream` would handle serialization of arbitrary objects when it did not; Only `websocket_stream` does.
> docs: clarify WebSocket `send_websocket_stream` capabilities

- litestar/utils/predicates.py
See https://github.com/python/typing_extensions/issues/586.
We're not using this functionality anymore, so keeping this around just for backwards compatibility.
> fix(typing): Remove usage of private `_AnnotatedAlias`

- docs/usage/dependency-injection.rst
- litestar/_kwargs/cleanup.py
- litestar/routes/http.py
- litestar/routes/websocket.py
- pyproject.toml
- tests/unit/test_kwargs/test_cleanup_group.py
- tests/unit/test_kwargs/test_generator_dependencies.py
- uv.lock
Fix a bug where a dependencies' cleanup was not guaranteed to be called would not be called if an exception was thrown:
- Late during ASGI response rendering
- During cleanup of another dependency when recovering from an exception
<hr>
Refactor the code such that:
- Exceptions are always caught and thrown into dependencies as long as the dependencies are alive
- If the handler raises an exception and during dependency cleanup other exceptions are raised, the sub-exceptions are grouped into an `ExceptionGroup`. This behaviour is now equivalent to regular dependency cleanup
> fix(DI): Ensure dependencies are cleaned up when exception occurrs during cleanup 

- litestar/middleware/base.py
Fix #4149 
- Fixed name of logger in example of custom middleware (ASGIMiddleware)
- litestar-org/litestar#4149
> docs: fixed variable name in ASGIMiddleware code example

- litestar/cli/_utils.py
- tests/unit/test_cli/test_cli.py
Fixes #4129 
Before this PR, if the `--app` CLI option is used, any `ImportErrors` that occur while instantiating the application are assumed to be caused by a bad `--app` argument.  This does not account for cases where the `--app` option is actually fine, but the `ImportError` arose from inside the applicaiton code, and this results in a misleading error message.
This PR adds a check on whether the exception resulted from a failure to import the module named in the `--app` option.  If the error arose while attempting some other import, it is not caught.  This is consistent with the behaviour that occurs when `--app` is not used.
> fix: misleading error message upon ImportError with --app argument to CLI

- litestar/testing/client/subprocess_client.py
- tests/unit/test_testing/test_sub_client/test_subprocess_client.py
Fix #4021 
- Added two new parameters to `run_app` method: `retry_count` and `retry_timeout`
- `run_app` now throws `StartupError` if application doesn't start on time
- litestar-org/litestar#4021
> fix(testing): subprocess client raises exc when fails to start

- litestar/_openapi/schema_generation/schema.py
- tests/unit/test_openapi/test_schema.py
- resolved #4130 
The previous implementation incorrectly treated Python tuples as arrays with items of a single, uniform type.
This change utilizes prefixItems (OpenAPI 3.1+) to correctly specify the type for each element at its specific position when the field is a tuple. This results in a more accurate and modern OpenAPI schema that precisely reflects the Python tuple structure.
Additionally:
- Adjusted assertions in `test_schema_tuple_with_union` as the original expectations seemed incorrect with the proper schema generation.
- Added a new test case `test_schema_tuple`.
> fix(openapi): support prefixItems for tuple schema

- litestar/dto/_backend.py
- litestar/dto/_codegen_backend.py
- litestar/dto/base_dto.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
Add a new `attribute_accessor` property to `AbstractDTO`, which can be used by both the codegen and functional backend to access attributes on an object.
This can be useful to implement DTOs for types that do not adhere to the plain protocol of `obj.data_field` or need to add additional checks, e.g. using `obj.related_field.all()` on a Django model to access related objects, while ensuring no I/O occurs.
> feat(DTO): Add custom attribute accessor callable

- litestar/cli/_utils.py
- tests/unit/test_cli/conftest.py
- tests/unit/test_cli/test_cli_plugin.py
Fix #2783 
The issue was that when the `--help` command was passed, Click did not parse the others incoming arguments (e.g. `--app`), and autodiscovery feature didn't work as planned because the file containing the application was not in the default list (`AUTODISCOVERY_FILE_NAMES`). As a result, we ignored the `--app` argument and didn't loading plugins, which led to plugin commands not appearing in the list.
As a solution, I propose to override the `Group.parse_args` method to manually parse the arguments that tell us where the application is located.
- litestar-org/litestar#2783
> fix(cli): pre parse launch arguments when cli command executed

- litestar/openapi/datastructures.py
- litestar/openapi/plugins.py
- tests/unit/test_openapi/test_plugins.py
Hello! I'm currently work on adding scalar configuration and during work got some questions:
- I start adding config params from [here](https://github.com/scalar/scalar/blob/main/documentation/configuration.md), but not sure about including every param. What should we add?
- Here is MRE for how to work with configuration:
```python
from litestar import Litestar, get
from litestar.openapi.config import OpenAPIConfig
from litestar.openapi.datastructures import ScalarConfig
from litestar.openapi.plugins import ScalarRenderPlugin
scalar_plugin = ScalarRenderPlugin(version="1.19.5", config=ScalarConfig(show_sidebar=False))
@get("/")
async def hello_world() -> dict[str, str]:
"""Keeping the tradition alive with hello world."""
return {"hello": "world"}
app = Litestar( …
```
> feat: add scalar configuration

- litestar/dto/base_dto.py
- tests/unit/test_dto/test_factory/test_integration.py
Fix #3888
Fixed an issue involving incorrect annotations being passed to `FieldDefinition` when handling `Response` class. 
However, I'm not entirely satisfied with this solution. I'd be happy for any suggestions for alternative approaches.
- litestar-org/litestar#3888
> fix(openapi): wrong annotation passed to FieldDefinition (DTO)

- litestar/_openapi/parameters.py
- litestar/params.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_params.py
I've added additional argument to `KwargsDefinition` that allows excluding a parameter from OpenAPI schema.
This change is backward-compatible and I've also verified that it should merge smoothly with v3.
- litestar-org/litestar#4173
> feat(openapi): add option to exclude parameter from schema

- litestar/security/jwt/token.py
- tests/unit/test_security/test_jwt/test_token.py
Allows passing custom JWT headers (e.g., kid) to Token.encode(). This improves flexibility in cases where custom JWT headers (like `kid`) are required.
-
Fixes #4191
> feat(jwt): [#4191] extend Token.encode() to support custom headers

- docs/conf.py
It was renamed: https://redis.readthedocs.io/en/stable/
See link with failed job: https://github.com/litestar-org/litestar/actions/runs/15672088433/job/44152557512
> docs: fix `redis` inventory

- docs/usage/plugins/index.rst
- litestar/plugins/__init__.py
- litestar/plugins/base.py
Adds `ReceiveRoutePlugin` to the `__all__` list to make it available for public import.
This ensures the plugin can be imported directly from the module using:
`from litestar.plugins import ReceiveRoutePlugin`
> feat: Include ReceiveRoutePlugin in base plugins

- litestar/middleware/base.py
Fixes a small documentation error in the AGIMiddleware class for the exclude_path_pattern parameter
-
> docs: fix incorrect parameter name in docstring

- docs/tutorials/repository-tutorial/03-repository-controller.rst
Fix wrong line numbers for code blocks in document
> docs: fix literal include lines in 03-repository-controller

- docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_session_di.py
This PR fixes the type hinting error in the example code in the documentation at [1-provide-session-with-di](https://docs.litestar.dev/2/tutorials/sqlalchemy/1-provide-session-with-di.html).
In my environment (Python 3.13, Pylance), line 79 of the code before the change would prompt:
> Type "Sequence[TodoItem]" is not assignable to return type "list[TodoItem]"
Moreover, according to the context of the documentation, the `list` type hint for the return value of `get_todo_list` is not consistent with the `Sequence` used in the previous document at [0-introduction](https://docs.litestar.dev/2/tutorials/sqlalchemy/0-introduction.html).
> docs: type hint in full_app_with_session_di.py

- litestar/params.py
- tests/unit/test_openapi/test_schema.py
- Adds back missing constraints to OpenAPI for simple (non-union, non-optional, non-nested) field types that specify constraints.
Closes #3999
> fix(OpenAPI): constraint check logic

- litestar/_asgi/routing_trie/traversal.py
- tests/e2e/test_routing/test_path_resolution.py
`MethodNotAllowedException` exceptions raised during routing did not include the [`Allow`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Allow) header, which must be present in a `405 Method Not Allowed` response.
Fixes #4277.
> fix(routing): Ensure a `MethodNotAllowedException` exception during routing properly sets `Allow` header 

- docs/usage/plugins/index.rst
Fixed a documentation error: updated `route.http_methods` to the correct attribute `route.methods` when logging registered routes.
before:
```py
from litestar.plugins import ReceiveRoutePlugin
from litestar.routes import BaseRoute
class RouteLoggerPlugin(ReceiveRoutePlugin):
def receive_route(self, route: BaseRoute) -> None:
print(f"Route registered: {route.path} [{', '.join(route.http_methods)}]")
```
after:
```py
print(f"Route registered: {route.path} [{', '.join(route.methods)}]")
```
> fix: docs[ReceiveRoutePlugin] documentation

- litestar/exceptions/http_exceptions.py
- tests/unit/test_exceptions.py
- For HTTPException, possibly get the value for extra and headers on the class
- #4006
> fix: possibly get httpexception.extra and httpexception.headers from class for v3

- docs/release-notes/changelog.rst
- litestar/datastructures/response_header.py
- litestar/openapi/spec/header.py
- tests/unit/test_openapi/test_responses.py
Remove deprecated `allow_reserved` and `allow_empty_value` property from `ResponseHeader` and `OpenAPIHeader`
> feat!: remove deprecated header properties

- docs/release-notes/changelog.rst
- litestar/template/base.py
- tests/unit/test_deprecations.py
Remove the deprecated ``litestar.template.base.TemplateContext`` type. Its usages should be replaced with `collections.abc.Mapping`
> feat(template)!: Remove deprecated `TemplateContext`

- .github/workflows/cherry-pick-v2.yaml
Add a GitHub action that automatically creates a cherry-pick PR against the `v2`, if a Pull Request with the label `cherry-pick v2` is merged
> ci: Add action to cherry pick into `v2` branch

- litestar/_openapi/responses.py
- tests/unit/test_openapi/test_responses.py
Fix handler returning a `Stream` falsely indicating a file response in the OpenAPI schema:
```json
{
"description": "Stream Response",
"headers": {
"content-length": {
"schema": {
"type": "string"
},
"description": "File size in bytes",
"required": false,
"deprecated": false
},
"last-modified": {
"schema": {
"type": "string",
"format": "date-time"
},
"description": "Last modified data-time in RFC 2822 format",
"required": false,
"deprecated": false
},
"etag": {
"schema": {
"type": "string"
},
"description": "Entity tag",
"required": false,
"deprecated": false
}
}
```
> fix(OpenAPI): Fix `Stream` response being treated as `File` response in OpenAPI schema

- litestar/cli/commands/core.py
- tests/unit/test_cli/test_core_commands.py
- tests/unit/test_cli/test_ssl.py
Closes #4329
When `--reload` is enabled, spawns uvicorn subprocess with a fresh `sys.path`, which loses the `--app-dir` value. To preserve this value in `sys.path`, `--app-dir` must be explicitly passed to the uvicorn subprocess.
- `test_run_command` and `test_arguments_passed` might cover uvicorn parameter passing
> fix(cli): pass the `--app-dir` option to the uvicorn subprocess when the reload option is enabled.

- litestar/plugins/sqlalchemy.py
- tests/unit/test_deprecations.py
- tests/unit/test_kwargs/test_multipart_data.py
- tests/unit/test_kwargs/test_reserved_kwargs_injection.py
Adds deprecation warning for the \`litestar.plugins.sqlalchemy\` module which will be removed in v3.0.
- Related to #4340 which removes this module in v3
- Follows deprecation policy to warn users before removal
- Part of the ongoing migration to advanced-alchemy
- Add module-level deprecation warning to \`litestar.plugins.sqlalchemy\`
- Add test for deprecation warning
Users should update their imports:
```python
from litestar.plugins.sqlalchemy import SQLAlchemyPlugin
from advanced_alchemy.extensions.litestar import SQLAlchemyPlugin
```
> feat: deprecate litestar.plugins.sqlalchemy module for v3 removal

- litestar/utils/predicates.py
Fixes a deprecation warning [introduced in Python 3.14][gh-122875].
I've tested this change with
```console
$ uv run pytest -q tests/unit/test_utils/test_predicates.py::test_is_async_callable
..........                                                                   [100%]
10 passed in 0.10s
```
NA.
[gh-122875]: https://github.com/python/cpython/pull/122875
> fix: Use `inspect.iscoroutinefunction` instead of `asyncio.iscoroutinefunction` to address deprecation warning in Python 3.14+
