.github/workflows/ci.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
starlite/app.py
starlite/enums.py
starlite/handlers.py
starlite/openapi.py
starlite/request.py
starlite/response.py
starlite/routing.py
starlite/testing.py
starlite/types.py
tests/test_app.py
tests/test_dependency_injection.py
tests/test_openapi.py

OpenAPI spec generation

---

.github/workflows/ci.yaml

updated git action to fix pre-commit

---

README.md

Attempting a patch on mobile 👀 
can check out readme on branch: https://github.com/Goldziher/starlite/tree/Discord-link

fix broken discord badge, closes #9

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
docs/usage/0-the-starlite-app.md
docs/usage/1-routers-and-controllers.md
docs/usage/10-openapi.md
docs/usage/11-test.md
docs/usage/2-route-handlers.md
docs/usage/7-guards.md
docs/usage/7-middleware.md
docs/usage/8-authentication.md
docs/usage/8-openapi.md
docs/usage/9-guards.md
pyproject.toml
starlite/__init__.py
starlite/handlers.py
starlite/middleware.py
starlite/request.py
starlite/types.py
tests/test_guards.py

Work in progress - adding docs for middleware, authentication and authorization using guards.

Docs: Middleware, Authentication and Guards (Authorization)

---

docs/usage/3-parameters.md

Most of what I wanted to fix, you apparently fixed last commit :D You had me confused there, hehe.

Fix broken `note` box

---

tests/plugins/sql_alchemy_plugin/test_sql_alchemy_relationships.py

Using as_declarative & declared_attr allows you to modify the Base class. You can then simply generate the table name Automatically using cls. I also added some tests :)

Auto tablenames

---

docs/usage/0-the-starlite-app.md
docs/usage/6-dependency-injection.md

👋 I was going through the docs and noticed this small typo.

Fix a few documentation typos

---

starlite/handlers.py
starlite/openapi/parameters.py
starlite/request.py
starlite/routing.py
tests/handlers/test_http_handlers.py
tests/handlers/test_websocket_handlers.py
tests/middleware/test_authentication.py
tests/openapi/test_parameters.py
tests/test_route.py

This pr aims to remove assert statements and replace them with respective exceptions. 
Asserts don't get run when python is started with `-OO` flag.

Remove assert statements from code

---

tests/test_params.py

This PR adds a xfail tests for #40

test: add xfail test parameter with default value

---

.flake8
starlite/handlers.py
starlite/provide.py
starlite/request.py
starlite/utils/__init__.py
starlite/utils/signature.py
tests/test_dependency_injection.py
tests/test_provide.py

This PR updates DI to allow for recursive depdencies. That is, depdencies that depend on dependency injection themselves.

Add recursive dependency injection

---

README.md

Sorry y'all, found a separate case from the one I found yesterday.. Wish I'd noticed on the first PR.

Remove second faulty "]" from README

---

README.md

updating readme example

---

tests/static_files/test_static_files.py

This pr adds two more tests for `staticfiles`  both of them are failing currently.

Add tests for staticfiles

---

CHANGELOG.md
docs/usage/12-openapi.md
starlite/openapi/controller.py

updated schema path to be more user-friendly

update: changed openapi schema endpoint path

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
docs/css/extra.css
docs/migration.md
docs/usage/0-the-starlite-app.md
docs/usage/1-routers-and-controllers.md
docs/usage/10-plugins.md
docs/usage/11-data-transfer-objects.md
docs/usage/12-openapi.md
docs/usage/14-testing.md
docs/usage/2-route-handlers/1_http_route_handlers.md
docs/usage/3-parameters.md
docs/usage/4-request-body.md
docs/usage/5-responses.md
docs/usage/6-dependency-injection.md
docs/usage/7-middleware.md
docs/usage/8-authentication.md
docs/usage/9-guards.md

ran prettier against all files, also suppressed a typing issue in starlite.app

Prettier precommit hook

---

starlite/app.py
tests/request/test_state.py

This pr fixes the state attribute.

Fix state attribute 

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
poetry.lock

This PR updates the github action pipeline to be more efficent

updated github actions

---

starlite/connection.py
tests/request/test_request.py

fixing request json method for empty payload

fix: 🐛 fixing request json method for empty payload

---

starlite/__init__.py
starlite/logging.py
starlite/queue_listener_handler.py
tests/queue_handler/test_queue_handler.py

Fixes #77 
- Added tests for logging and the resolve handler.

Ts logging non blocking

---

docs/usage/7-middleware.md

Use correct name for Starlette's BaseHTTPMiddleware

---

.gitignore
CONTRIBUTING.md
poetry.lock
pyproject.toml
tox.ini

Instructions in `CONTRIBUTING.md`

Simple tox setup for testing across multiple py versions.

---

.github/workflows/docs.yaml

I think this should get the dark theme right until @dkress59 can rescue us:)

Constrain mkdocs in docs build.

---

.github/workflows/ci.yaml

This PR add the github CodeQL analysis step to CI

add codeql to CI

---

docs/usage/0-the-starlite-app.md
docs/usage/11-data-transfer-objects.md
docs/usage/2-route-handlers/3_asgi_route_handlers.md
docs/usage/4-request-body.md
docs/usage/5-responses.md
docs/usage/6-dependency-injection.md
docs/usage/7-middleware.md
starlite/cache/simple_cache_backend.py
starlite/middleware.py
starlite/plugins/sql_alchemy.py
starlite/template/__init__.py
starlite/template/base.py
starlite/template/jinja.py
starlite/template/mako.py
tests/app/test_middleware_handling.py
tests/request/test_state.py

I ran the intellij code analysis tool and cleaned up some of its findings. The only real issues fixed are some broken links in the docs, the rest of the issues are style related and very minor stuff.

Code Cleanup

---

.pre-commit-config.yaml
docs/usage/7-middleware.md
poetry.lock
starlite/app.py
starlite/asgi.py
starlite/controller.py
starlite/handlers/base.py
starlite/handlers/http.py
starlite/middleware.py
starlite/router.py
starlite/routes.py
starlite/testing.py
starlite/types.py
starlite/utils/model.py
tests/handlers/http/test_to_response.py
tests/middleware/test_middleware_handling.py
tests/request/test_state.py
tests/route/test_validations.py
tests/test_path_resolution.py

This PR addresses the discussion #169. Its currently in draft state - the architecture is in flux and the code is not very clean. Also the tests fail and their failure indicates a problem with the logic which causes the route.handle method not to be evaluated every time. I nonetheless open this now for comments because the changes required here are quite big - and i am not 100% certain about the direction I have taken. So please add comments and lets discuss this.

Add support for layered middleware

---

.github/workflows/docs.yaml
CONTRIBUTING.md
docs/css/extra.css
poetry.lock
pyproject.toml

Fix the color scheme for the documentation

---

.pre-commit-config.yaml
docs/governance-and-contribution.md
docs/usage/12-openapi.md
docs/usage/15-templating.md
docs/usage/17-exceptions.md
docs/usage/7-middleware.md
starlite/dto.py
starlite/plugins/sql_alchemy.py
starlite/testing.py
tests/kwargs/test_validations.py

https://pypi.org/project/codespell

Fix typos discovered by codespell

---

tests/route/test_route_map.py

Adds tests previously requested in #263 
Feel free to merge these or not, given that a new implementation of route resolution is likely forthcoming (Rust or otherwise)

Add tests for `Starlite.construct_route_map`

---

starlite/dto.py

… by breaking nested logic out into helper methods.
Changes no logic, test cov still 100% and existing tests pass.
For #203

Addresses cognitive complexity of `DTOFactory.__call__()`

---

docs/usage/12-openapi.md
poetry.lock
starlite/openapi/controller.py
tests/openapi/test_controller.py
tests/openapi/test_openapi_ui.py

* Support for SwaggerUI
As per #300
* Use built-in copy method
I tested this and it works, great stuff @timwedde 
Please add tests asap.

Support for SwaggerUI (#302)

---

starlite/app.py
starlite/asgi.py
tests/static_files/test_static_files.py

* Prevent adding routes which are below a configured static path
* Avoid replacing multiple strings when stripping the static prefix
See commit messages and added tests for more info

Fix static subpaths

---

poetry.lock
pyproject.toml

Let me know if you're open to this change, it can make setting up the dev environment a little bit easier

Add `pre-commit` to poetry dev dependencies

---

README.md
docs/usage/12-openapi.md
starlite/openapi/controller.py
tests/openapi/test_controller.py

- Adds support for stoplight elements openapi schema visualisation mirroring swagger options.
- Adds respective docs (and fixes a minor typo).

Stoplight elements openapi

---

docs/reference/logging.md
starlite/logging/__init__.py
starlite/logging/picologging.py
starlite/logging/standard.py

For #341
- docstring for LogConfig class and class vars
- docstring for both QueueListenerHandler
- include all in logging.md

Logging reference docs.

---

starlite/app.py
starlite/asgi.py
starlite/config.py
tests/route/test_route_map.py
tests/static_files/test_static_files.py

This PR resovles issue #354 by fixing the handling of static paths, which was broken in one of the refactors apparently.

#issue 354 html mode not working as expected

---

docs/reference/datastructures.md
docs/usage/4-request-data/3-multipart-form-data.md
starlite/__init__.py
starlite/datastructures.py
starlite/openapi/schema.py
starlite/parsers.py
tests/kwargs/test_multipart_data.py
tests/openapi/test_request_body.py

Issue #363: Uploadfile OpenAPI generation raises an exception

---

.flake8
docs/reference/datastructures.md
docs/usage/4-request-data/3-multipart-form-data.md
docs/usage/5-responses/8-streaming-responses.md
starlite/__init__.py
starlite/asgi.py
starlite/connection.py
starlite/datastructures.py
starlite/openapi/parameters.py
starlite/openapi/schema.py
starlite/parsers.py
starlite/response.py
starlite/router.py
starlite/routes/base.py
starlite/signature.py
starlite/utils/url.py
tests/handlers/http/test_to_response.py
tests/kwargs/test_multipart_data.py
tests/openapi/test_request_body.py

This PR refactors path parameter parsing  - after benchmarking the new implementation is roughly 30% faster. 
Note this PR is pointing at the bigger refactor PR.

Refactor: Path Param Parsing

---

.prettierignore
docs/reference/cache.md
docs/reference/dto.md
docs/usage/11-data-transfer-objects.md
starlite/app.py
starlite/cache/base.py
starlite/cache/simple_cache_backend.py
starlite/dto.py

Issue 341 api docs

---

README.md

This PR fixes #335 by adding a link to the example project.

Issue #335 Adds example to readme.

---

starlite/config/compression.py
starlite/middleware/compression/brotli.py
tests/caching/test_response_caching.py
tests/middleware/test_compression_middleware.py

Moves compression config enums into config.compression module.

Fixes missing dependency exception under minimal install for brotli

---

.pre-commit-config.yaml
docs/reference/plugins.md
docs/usage/10-plugins/0-plugins-intro.md
poetry.lock
starlite/app.py
starlite/controller.py
starlite/handlers/asgi.py
starlite/handlers/base.py
starlite/handlers/http.py
starlite/handlers/websocket.py
starlite/middleware/exceptions.py
starlite/openapi/parameters.py
starlite/plugins/base.py
starlite/plugins/piccolo_orm.py
starlite/plugins/sql_alchemy.py
starlite/plugins/tortoise_orm.py
starlite/response.py
starlite/router.py
starlite/testing.py
starlite/types.py
tests/handlers/http/test_kwarg_handling.py
tests/plugins/test_base.py
tests/utils/test_exceptions.py

This PR extends the plugin protocol by adding an `on_app_init` method. 
Resolves #398

Issue #398 extended plugin protocol

---

poetry.lock
starlite/app.py
starlite/datastructures.py
starlite/openapi/request_body.py
starlite/openapi/schema.py
tests/openapi/test_request_body.py

This PR updates the schema generation for UploadFiles - the issue was usage of enum members.
Resovles #396

Issue 396: updated upload file schema

---

starlite/app.py
starlite/config/openapi.py
starlite/controller.py
starlite/handlers/http.py
starlite/openapi/path_item.py
starlite/openapi/utils.py
starlite/router.py
tests/openapi/test_config.py
tests/openapi/test_security_schemes.py

This PR includes the code contributed in #400 by @toudi, I'm extending it to finish the implementation quickly because we have a bug in the `starlite-jwt` due to an oversight on my part...

Issue #400: Add support for OpenAPI Security Scheme

---

README.md
docs/index.md

Adds Example Applications section to README and index.md

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
docs/usage/0-the-starlite-app/1-startup-and-shutdown.md
examples/__init__.py
examples/hello_world.py
examples/startup_and_shutdown.py
examples/tests/test_hello_world.py
examples/tests/test_startup_and_shutdown.py
poetry.lock
pyproject.toml

This PR includes work for a number of testing based issues.
- includes a hello-world example and test
- moves the Startup and Shutdown example from docs into examples/ and adds tests
- adds a test to CI of a minimal starlite application with no extras installed
- adds `brotli` to dev-dependencies and removes requirement to install `full` extras in testing contexts.
Start for #343 
Closes #393 
Closes #428

Adds `examples/` and `examples/tests`.

---

CHANGELOG.md

This PR reorders CHANGELOG.md to descending order.
As the number of releases grows, this puts the more relevant data to the top of the file, making it more user-friendly.

Changes CHANGELOG.md to descending order.

---

starlite/kwargs.py

reducing complexity by splitting function in two parts.
( https://github.com/starlite-api/starlite/issues/203 )

refactor. simplify KwargsModel

---

docs/usage/1-routing/0-routing.md

docs: Remove Rust bindings text

---

.pre-commit-config.yaml
docs/usage/0-the-starlite-app/2-using-application-state.md
examples/tests/test_using_application_state.py
examples/using_application_state.py

Complete example and test for Using Application State usage docs.

---

.pre-commit-config.yaml
poetry.lock
starlite/signature.py
tests/kwargs/test_reserved_kwargs_injection.py
tests/kwargs/test_validations.py

This PR resolves #443 by making the signature model type state as `Any`.

Issue #443: custom state raises validation error

---

CHANGELOG.md
poetry.lock
pyproject.toml
starlite/routes/http.py
tests/handlers/http/test_to_response.py

This PR fixes the `before_request` hooks, which ignored response data being returned - this is a regression from a few releases back.

Fix before request

---

.github/workflows/ci.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
starlite/cache/base.py
starlite/config/template.py
starlite/exceptions/__init__.py
starlite/exceptions/exceptions.py
starlite/exceptions/utils.py
starlite/kwargs.py
starlite/parsers.py
starlite/template/base.py
starlite/utils/exception.py
starlite/utils/model.py
tests/caching/test_config_validation.py
tests/dependency_injection/test_injection_of_generic_models.py
tests/dto_factory/test_dto_factory_model_conversion.py
tests/handlers/http/test_to_response.py
tests/handlers/http/test_validations.py
tests/openapi/utils.py
tests/test_exceptions.py
tests/test_signature.py

This PR adds `pyright` to our pipeline and pre-commit. The configuration in pre-commit has to follow the constraints I discuss here:
https://github.com/microsoft/pyright/issues/3902
The reason for adding this PR is to test and ensure compatibility for #451.

Infrastructure: Add pyright

---

poetry.lock
starlite/testing.py

updated deps

---

starlite/response.py
tests/response/test_serialization.py

In the interest of not leaving this open too long, I'm submitting with the initial ones and a framework that we can add additional ones to relatively quickly.  Let me know if this look ok
Resolves #458

Enhancement: Adds SecretStr, Path, and Enum to built in serializer

---

.pre-commit-config.yaml
docs/reference/connection.md
docs/reference/datastructures.md
docs/usage/4-request-data/3-multipart-form-data.md
poetry.lock
pyproject.toml
starlite/connection.py
starlite/datastructures.py
starlite/parsers.py
tests/kwargs/test_multipart_data.py

This PR resolves #466 .
Note: I incorporated tests from Starlette to ensure we are all good.

Issue 466 update multipart handling

---

tests/conftest.py
tests/middleware/test_session_middleware.py

Added Fixture To Create Session Cookies

---

starlite/testing.py
tests/conftest.py
tests/test_testing.py

Multi Cookie Support For Create Test Request

---

starlite/controller.py
starlite/handlers/base.py
starlite/router.py
tests/test_router_registration.py

Path Resolver For Route Handler Methods On A Controller

---

CONTRIBUTING.md

See issue #484 - this PR adds instructions to `CONTRIBUTING.md` for checking the unit test coverage locally in the development environment.

Update contributions guidelines with instructions to check coverage

---

docs/reference/connection.md
poetry.lock
starlite/app.py
starlite/asgi.py
starlite/connection.py
starlite/middleware/session.py
starlite/testing.py
starlite/types.py
starlite/utils/__init__.py
starlite/utils/scope.py
starlite/utils/sync.py
tests/conftest.py
tests/connection/request/test_request.py
tests/connection/websocket/test_websocket.py
tests/middleware/test_exception_handler_middleware.py
tests/middleware/test_middleware_handling.py
tests/middleware/test_session_middleware.py
tests/routing/test_route_map.py
tests/utils/test_scope.py

Access custom response in session middleware

---

CHANGELOG.md
docs/usage/12-openapi/5-customizing-pydantic-model-schemas.md
examples/openapi/customize_pydantic_model_name.py
examples/tests/openapi/test_customize_pydantic_model_name.py
mkdocs.yml
poetry.lock
pyproject.toml

This PR updates `pydantic-openapi-schema` and adds documentation regarding the new `__schema_name__` attribute.

Add support for `__schema_name__` dunder attribute on pydantic models

---

starlite/middleware/session.py

Remove unnecessary line

---

README.md

added quick start section in readme

---

.pre-commit-config.yaml
docs/usage/14-testing.md
poetry.lock
pyproject.toml
requirements-lint.txt
starlite/testing.py
tests/kwargs/test_multipart_data.py
tests/kwargs/test_reserved_kwargs_injection.py
tests/middleware/test_csrf.py
tests/routing/test_path_resolution.py
tests/test_testing.py

Update Starlette to `0.21.0`

---

.github/workflows/ci.yaml

add python 3.11 to matrix

---

.pre-commit-config.yaml
CHANGELOG.md
docs/usage/2-route-handlers/5-handler-opts.md
mkdocs.yml
poetry.lock
pyproject.toml
starlite/__init__.py
starlite/config/cache.py
starlite/handlers/asgi.py
starlite/handlers/base.py
starlite/handlers/http.py
starlite/handlers/websocket.py
starlite/testing.py
tests/handlers/base/test_opt.py
tests/handlers/http/test_kwarg_handling.py
tests/plugins/test_base.py
tests/test_testing.py

Add route handlers support for **kwargs

---

starlite/connection/websocket.py
starlite/dto.py
starlite/handlers/http.py
starlite/middleware/session.py
starlite/openapi/controller.py

Address various SonarCloud complaints about code complexity and repeated literal strings.

Reduce cognitive complexity

---

CHANGELOG.md
docs/reference/middleware.md
docs/reference/testing.md
docs/usage/7-middleware/3-builtin-middlewares/7-logging-middleware.md
mkdocs.yml
starlite/config/logging.py
starlite/connection/base.py
starlite/connection/request.py
starlite/datastructures.py
starlite/middleware/__init__.py
starlite/middleware/logging.py
starlite/parsers.py
starlite/routes/http.py
starlite/testing.py
starlite/utils/__init__.py
starlite/utils/extractors.py
tests/datastructures/test_background_task.py
tests/logging_config/test_structlog_config.py
tests/middleware/test_logging.py
tests/test_parsers.py
tests/utils/test_extractors.py

Logging Middleware

---

README.md

Fix linting issue introduced by allcontributors bot

---

starlite/testing.py
tests/connection/request/test_starlette_tests.py
tests/handlers/websocket/test_kwarg_handling.py
tests/kwargs/test_cookie_params.py
tests/kwargs/test_layered_params.py
tests/kwargs/test_multipart_data.py
tests/middleware/test_logging.py
tests/middleware/test_session_middleware.py
tests/plugins/piccolo_orm/test_piccolo_orm_plugin_integration.py
tests/utils/test_extractors.py

This PR addresses several pytest warnings appearing throughout the tests, particularly to do with:
- Unawaited coroutines
- Sending bytes in requests using the `data` keyword (should be `content`)
- Sending per-request cookies rather than setting them on the client

Address pytest warnings

---

.pre-commit-config.yaml
commands/__init__.py
commands/cli.py
commands/list_routes.py
poetry.lock
pyproject.toml
tests/test_commands.py

(new PR.   Removed the previous  PR because of some issues.).
"""CLI Add CLI commands using cleo https://github.com/python-poetry/cleo .
New commands should be placed in the commands folder and added in
__init__.py. usage example:
app = Starlite(route_handlers=[hello_world])
if __name__ == '__main__':
from commands.cli import Cli
cli = Cli(app)
cli.run()
"""
usage example:
$ python ./main.py
Console Tool
USAGE
console [-h] [-q] [-v [<...>]] [-V] [--ansi] [--no-ansi] [-n] <command> [<arg1>] ... [<argN>]
ARGUMENTS
<command>              The command to execute
<arg>                  The arguments of the command
GLOBAL OPTIONS
-h (--help)            Display this help message
-q (--quiet)           Do not output any message
-v (--verbose)         Increase the verbosity of messages: "-v" for …

Initial CLI Implementation

---

poetry.lock
pyproject.toml

This change introduces a `picologging` and `structlog` group so that they can be installed as an extra.

Updated install groups

---

.pre-commit-config.yaml
README.md
docs/reference/plugins/1-sqlalchemy-plugin.md
poetry.lock
starlite/config/static_files.py
starlite/handlers/http.py
starlite/kwargs.py
starlite/middleware/session.py
starlite/openapi/parameters.py
starlite/openapi/responses.py
starlite/openapi/schema.py
starlite/plugins/sql_alchemy/config.py
starlite/plugins/sql_alchemy/plugin.py
tests/kwargs/test_layered_params.py
tests/life_cycle_hooks/test_after_response.py

This PR resolves #544 and #545

Make `sessionmaker`, `engine` and `before_send_handler` configurable in `SQLAlchemyPluginConfig`

---

docs/reference/connection/0-asgi-connection.md
docs/reference/connection/1-request.md
docs/reference/connection/2-websocket.md
starlite/connection/base.py
starlite/connection/request.py
starlite/connection/websocket.py
tests/connection/test_base_properties.py

This PR adds a `connection.cache` property getter the gives easy access to the app cache backend.

Add `cache` property getter to `ASGIConnection`

---

docs/usage/15-templating.md
starlite/datastructures/response_containers.py
starlite/handlers/http.py
starlite/response.py
starlite/routes/http.py
tests/handlers/http/test_to_response.py
tests/template/test_template.py

This PR introduces implicit request injection into template context. Injected request will override existing `request` value that user might have passed into context.

Inject request into template context

---

docs/reference/1-app.md
docs/usage/5-responses/5-response-cookies.md
starlite/app.py
starlite/handlers/base.py
starlite/utils/exception.py
tests/kwargs/test_multipart_data.py
tests/routing/test_route_indexing.py
tests/template/test_template.py
tests/test_router_registration.py

This PR addresses and resolves #567

Fix route handler name indexing

---

starlite/routes/http.py
tests/kwargs/test_multipart_data.py

fix support for optional upload file

---

.pre-commit-config.yaml
docs/reference/cache/2-redis-cache.md
docs/reference/cache/3-memcached-cache.md
docs/usage/16-caching.md
mkdocs.yml
poetry.lock
pyproject.toml
starlite/cache/__init__.py
starlite/cache/memcached_cache_backend.py
tests/caching/test_memcached_cache_backend.py

Add memcached cache backend

---

poetry.lock
pyproject.toml
tests/caching/test_cache_wrapper.py
tests/caching/test_response_caching.py
tests/caching/test_simple_cache_backend.py
tests/conftest.py
tests/connection/request/test_request.py
tests/dto_factory/test_dto_factory_model_conversion.py
tests/handlers/http/test_to_response.py
tests/handlers/http/test_validations.py
tests/middleware/test_compression_middleware.py
tests/plugins/piccolo_orm/test_piccolo_orm_plugin_integration.py
tests/plugins/tortoise_orm/test_tortoise_orm_plugin_integration.py
tests/routing/test_path_resolution.py
tests/test_provide.py

Run async tests on trio additionally to asyncio. #581
Mention of official trio-support should maybe added by someone more familiar with the docs than me.

Official trio support. Implement #581

---

README.md

Quoting @provinzkraut in #586
> Mention of official trio-support should maybe added by someone more familiar with the docs than me.
Saw this hadn't been done yet so figured I'd at least add a quick mention to the README in case it's helpful.

Advertise Trio support

---

CHANGELOG.md
poetry.lock
pyproject.toml
starlite/logging/picologging.py

Fix picologging using stdlib StreamHandler

---

starlite/utils/sequence.py

Improve readability in `unique` function

---

docs/migration.md

Fixes a typo `Depend` -> `Depends` (#597)

---

starlite/plugins/sql_alchemy/plugin.py
tests/dto_factory/test_dto_factory_integration.py
tests/dto_factory/test_dto_factory_model_conversion.py
tests/plugins/sql_alchemy_plugin/__init__.py
tests/test_testing.py

SQLAlchemy JSON types mapped to `Union[Dict, List]` on DTOs.

---

docs/reference/config/3-csrf-config.md
docs/reference/middleware/1-authentication-middleware.md
docs/usage/7-middleware/3-builtin-middlewares/3-csrf-middleware.md
starlite/app.py
starlite/config/csrf.py
starlite/middleware/csrf.py
tests/middleware/test_csrf.py

Allow to exclude routes in CSRFMiddleware

---

docs/reference/config/0-app-config.md

Adds `logging_config` to ref docs for `AppConfig`

---

starlite/exceptions/http_exceptions.py
starlite/middleware/exceptions.py
starlite/utils/exception.py

This PR removes the Starlette HTTPException class as a code dependency by making our code more generic. It relates to #634 and #612

Removed starlette HTTPException as code dependency

---

starlite/exceptions/http_exceptions.py
starlite/middleware/exceptions.py
starlite/openapi/path_item.py
starlite/openapi/responses.py
starlite/response/base.py
starlite/routes/asgi.py
starlite/routes/http.py
starlite/routes/websocket.py
starlite/utils/__init__.py
starlite/utils/exception.py
starlite/utils/helpers.py

This PR adds a `get_name` helper. Its part of #612 .

Replace get name

---

starlite/connection/base.py
starlite/exceptions/http_exceptions.py
starlite/middleware/exceptions.py
starlite/openapi/path_item.py
starlite/openapi/responses.py
starlite/parsers.py
starlite/response/base.py
starlite/routes/asgi.py
starlite/routes/http.py
starlite/routes/websocket.py
starlite/utils/__init__.py
starlite/utils/exception.py
starlite/utils/extractors.py
starlite/utils/helpers.py
tests/test_parsers.py

This PR adds a `cookie_string_parser` function. Its part of #612

added cookie parser

---

starlite/types/partial.py
tests/__init__.py
tests/dto_factory/test_dto_factory_partials.py

Fix: `Partial` handling of `ClassVar`.

---

docs/reference/datastructures/3-header.md
docs/usage/5-responses/4-response-headers.md
examples/datastructures/headers/etag.py
examples/datastructures/headers/etag_parsing.py
starlite/app.py
starlite/config/app.py
starlite/controller.py
starlite/datastructures/__init__.py
starlite/datastructures/headers.py
starlite/handlers/http.py
starlite/router.py
tests/datastructures/test_headers.py
tests/response/test_response_headers.py

Add ETag header support as per #632

Add ETag headers (#573)

---

.github/workflows/ci.yaml

switch pipeline to use v3.11

---

tests/caching/test_memcached_cache_backend.py
tests/caching/test_redis_cache_backend.py

On python < 3.8, using `unittest.mock.patch` as a decorator makes async tests not work correctly and produce warnings in 3.7 because the coroutines are not awaited properly. This is fixed by using a fixture that uses patch as a context manager internally.
I'm not sure why this didn't fail CI before, but now it does, so..

Fix mock.patch / async test issues on Python 3.7

---

starlite/connection/base.py
starlite/middleware/session/base.py
starlite/middleware/session/cookie_backend.py
starlite/testing/create_test_client.py
starlite/testing/test_client/client.py
tests/conftest.py
tests/middleware/session/test_middleware.py

This was supported in the previous `SessionMiddleware` and was erroneously removed in #630. Test have been added.

Support setting sessions explicit to `Empty`.

---

starlite/plugins/sql_alchemy/plugin.py
tests/plugins/sql_alchemy_plugin/test_sql_alchemy_relationships.py

Fixes SQLAlchemyPlugin.to_dict() where instance has relationship.

---

starlite/router.py
tests/connection/request/test_request.py
tests/connection/websocket/test_websocket.py
tests/routing/test_route_indexing.py
tests/test_guards.py

Copy function route handlers upon registration

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml

updated pre-commit

---

tests/response/test_file_response.py

Closes #700
Thanks @provinzkraut for fix suggestion.

Fixes flaky test by reading mod time directly from `stat_result`.

---

.github/workflows/ci.yaml

updated ci.yaml

---

starlite/middleware/base.py

I think this is cleaner than the metaclass approach.
The mypy error about assigning to a method has a workaround that is encouraged by mypy maintainer (linked comment in code), and isn't an actual error in python runtime. However, did require a flake8 ignore.

Alternate implementation using `__init_subclass__()`.

---

starlite/middleware/logging.py
starlite/utils/extractors.py

Removes "method" from `ResponseExtractorField`.

---

starlite/kwargs.py
starlite/routes/http.py
starlite/routes/websocket.py
starlite/utils/dependency.py

Improves performance of dependency resolving by executing them concurrently rather than sequentially.

Resolve dependencies concurrently

---

starlite/handlers/asgi.py
starlite/handlers/websocket.py
tests/handlers/asgi/test_handle_asgi_with_future_annotations.py
tests/handlers/websocket/test_handle_websocket_with_future_annotations.py

745 Fix asgi/websocket handlers when __future__.annotations is used

---

starlite/asgi/routing_trie/mapping.py
starlite/types/composite_types.py
starlite/utils/sync.py

remove Starlette `Middleware` type from typing

---

docs/index.md
docs/reference/6-enums.md
docs/reference/middleware/4-compression-middleware.md
docs/usage/0-the-starlite-app/2-using-application-state.md
docs/usage/17-exceptions.md
docs/usage/2-route-handlers/0-route-handlers-concept.md
docs/usage/7-middleware/2-creating-middleware/1-using-middleware-protocol.md
docs/usage/7-middleware/2-creating-middleware/2-using-abstract-middleware.md
docs/usage/7-middleware/3-builtin-middlewares/1-cors-middleware.md
examples/application_hooks/before_send_hook.py
examples/middleware/base.py
starlite/app.py
starlite/config/app.py
starlite/config/static_files.py
starlite/connection/request.py
starlite/datastructures/response_containers.py
starlite/handlers/http.py
starlite/testing/create_test_client.py
starlite/testing/test_client/client.py
starlite/types/composite_types.py
starlite/utils/exception.py

This PR removes references to Starlette that are no longer required in our docs.

Cleanup `Starlette` references in docs.

---

docs/usage/0-the-starlite-app/3-static-files.md

Just tidying up some things I noticed as I read.

Fix links in docs, and small fixes.

---

docs/reference/config/9-allowed-hosts-config.md
docs/usage/7-middleware/3-builtin-middlewares/2-allowed-hosts-middleware.md
mkdocs.yml
starlite/__init__.py
starlite/app.py
starlite/config/__init__.py
starlite/config/allowed_hosts.py
starlite/config/app.py
starlite/middleware/allowed_hosts.py
starlite/testing/create_test_client.py
tests/middleware/test_allowed_hosts.py
tests/middleware/test_middleware_handling.py

add 'AllowedHostsMiddleware'

---

starlite/handlers/http.py
tests/compatibility/test_starlette_responses.py

fix resolving starlette responses

---

starlite/middleware/allowed_hosts.py
tests/middleware/session/test_middleware.py
tests/middleware/test_base_middleware.py

Remove some overlooked usages of starlette that are not needed anymore

Starlette dependency cleanup

---

tests/static_files/test_file_serving_resolution.py

Make test for mimetypes of StaticFiles response more reliable

---

.pre-commit-config.yaml
poetry.lock
starlite/asgi/routing_trie/mapping.py
starlite/asgi/routing_trie/types.py
starlite/handlers/http.py
starlite/middleware/session/sqlalchemy_backend.py
starlite/utils/scope.py
tests/handlers/http/test_head.py
tests/kwargs/test_layered_params.py
tests/middleware/test_exception_handler_middleware.py
tests/middleware/test_middleware_handling.py
tests/openapi/test_parameters.py
tests/openapi/test_responses.py
tests/plugins/sql_alchemy_plugin/test_sql_alchemy_models_openapi_generation.py
tests/test_controller.py
tests/test_guards.py
tests/utils/test_predicates.py

Update pre commit

---

tests/middleware/session/test_server_backends.py

Fixe a flaky SQLA-session-backend test

---

docs/usage/0-the-starlite-app/4-logging.md

I didn't run pre-commit since this is a very small doc update

fix logging example

---

starlite/asgi/routing_trie/traversal.py
starlite/handlers/base.py
starlite/handlers/http.py
starlite/response/base.py
starlite/utils/helpers.py
tests/conftest.py

- not casting return values from functions (use # type:ignore instead to save a function call)
- got rid of content_length @property and inlined the calculation.
- don't call get_plugin_for_value if there are no plugins
- don't build a list to pass to deque()

some micro optimizations.

---

starlite/signature.py
tests/conftest.py
tests/test_signature.py

Passes name of module where the handler/dependency is defined to `create_model()`
Closes #802

Resolve forward refs on signature models.

---

README.md
docs/usage/1-routing/5-mounting-asgi-apps.md

Just two simple edits.
First, mention in the README we support Piccolo ORM. 
Second, fix typo in path in the note about mounted apps.
Current text doesn't make sense

Fix mounting docs and readme

---

starlite/app.py
starlite/asgi/routing_trie/mapping.py
tests/middleware/test_allowed_hosts_middleware.py

Move AllowedHosts and CompressionMiddleware application to handler level

---

starlite/asgi/routing_trie/traversal.py
tests/routing/test_path_resolution.py

Fix 404 where cur node has handlers and child route has path param

---

starlite/testing/request_factory.py

Now that we are importing the testing utilities at the top-level again, we've been bootstrapping the route handlers and default app for `RequestFactory` on every startup, including openapi handlers.
This PR wraps them in factory functions to defer instantiation until they are needed.

Defer bootstrap of `request_factory.{_default_route_handler,default_app}`

---

examples/tests/openapi/test_customize_pydantic_model_name.py
starlite/routes/http.py

Hide automatically created OPTIONS routes in schema

---

starlite/handlers/http.py
starlite/response/base.py

optimize response creation

---

starlite/connection/request.py
starlite/datastructures/cookie.py
starlite/handlers/http.py
starlite/openapi/responses.py
starlite/response/base.py
starlite/response/streaming.py
tests/datastructures/test_cookie.py
tests/handlers/http/test_to_response.py
tests/openapi/test_responses.py
tests/utils/test_extractors.py

This PR adds default streaming of response data above or equal to 10KB (this value is configurable). Its meant to be tested, if we find it boosts performance: merged.

add default streaming

---

docs/usage/6-dependency-injection/3-the-provide-class.md
starlite/datastructures/provide.py
starlite/kwargs.py
starlite/routes/http.py
starlite/routes/websocket.py
tests/dependency_injection/test_request_local_caching.py
tests/kwargs/test_dependency_batches.py

PR by @ottermata - added to this branch to be benchmarked.

Rework dependencies (#815)

---

poetry.lock
starlite/asgi/routing_trie/mapping.py
starlite/asgi/routing_trie/traversal.py
starlite/routes/base.py
starlite/types/internal_types.py
tests/routing/test_path_resolution.py

Fix #854 incorrect path resolution of 'path' type parameters

---

starlite/middleware/logging.py
tests/middleware/test_logging_middleware.py

Fix #849 - Make LoggingMiddleware handle request bodies correctly

---

docs/benchmarks.md
docs/usage/0-the-starlite-app/4-logging.md
docs/usage/3-parameters/1-query-parameters.md
mkdocs.yml
starlite/middleware/session/memcached_backend.py

Just some minor fixes and updates. Also fixed #871

Minor docs update

---

examples/security/using_session_auth.py
starlite/__init__.py
tests/security/test_security.py

Remove the `SessionAuth` import from the main `starlite` module.

Remove `SessionAuth` import

---

starlite/config/logging.py
tests/logging_config/test_structlog_config.py

Swap StructLoggingConfing.processor type hint to List

---

starlite/handlers/http.py
tests/response/test_response_cookies.py

Honour documentation_only flag for cookies

---

starlite/datastructures/upload_file.py
starlite/openapi/schema.py
tests/openapi/test_request_body.py

fix: support legacy OpenAPI file upload format

---

starlite/app.py
starlite/config/openapi.py
starlite/router.py
tests/app/test_registering_route_handlers.py

Fix registering route handlers when dynamically registering route handlers

---

starlite/openapi/responses.py
tests/openapi/test_responses.py

fix OpenAPI support for custom responses with generic types

---

starlite/asgi/routing_trie/traversal.py
starlite/kwargs/dependencies.py
starlite/middleware/rate_limit.py
starlite/middleware/utils.py
starlite/routes/http.py
starlite/routes/websocket.py
starlite/signature.py
tests/middleware/test_base_middleware.py
tests/middleware/test_rate_limit_middleware.py
tests/routing/test_path_mounting.py

This PR applies fixes based on tests added by @jtraub. The fixes though are done in a way that does not impact performance. In fact, they are applied on top of a branch that actually increases performance by fixing some issues with the signature resolution.

Fix rate-limiting of mount paths

---

.pre-commit-config.yaml
poetry.lock
starlite/config/logging.py
test_apps/logging_test_app/main.py
tests/logging_config/test_logging_config.py
tests/middleware/test_logging_middleware.py

fix logger propagation causing duplicate messages in logging middleware

---

examples/routing/mounting_starlette_app.py
examples/tests/routing/test_mounting.py
poetry.lock
pyproject.toml
starlite/asgi/routing_trie/mapping.py
starlite/asgi/routing_trie/traversal.py
starlite/asgi/routing_trie/types.py
test_apps/piccolo_admin_app/home/piccolo_app.py
test_apps/piccolo_admin_app/home/schema.py
test_apps/piccolo_admin_app/home/tables.py
test_apps/piccolo_admin_app/main.py
test_apps/piccolo_admin_app/piccolo_conf.py
tests/routing/test_path_mounting.py

This PR changes path mounts (non-static only!) to have a trailing slash. This should resolve the problems with the piccolo admin. I encountered some other issues though, which require attention some attention in https://github.com/piccolo-orm/piccolo_admin/issues/211 before we get this merged.

716 bug mounting the piccolo admin asgi app not working

---

.pre-commit-config.yaml
starlite/cache/memcached_cache_backend.py
starlite/middleware/session/memcached_backend.py
starlite/response/base.py
starlite/utils/serialization.py
tests/datastructures/test_pagination.py
tests/response/test_serialization.py
tests/utils/test_serialization.py

Improve serialization support for custom pydantic by providing an encoders map for individual types.

Improve pydantic serialization

---

docs/reference/testing/0-test-client.md
docs/usage/9-testing/1-test-client.md
examples/testing/test_with_portal.py
starlite/testing/test_client/client.py

I have found the the blocking portal helper on `TestClient` to be extremely helpful with testing and thought it could use some documentation. Any feedback on the additions is welcome.
Cheers!
Kyle

Add documentation for TestClient.portal()

---

docs/usage/8-security/3-guards.md

Updated the documentation for Guards to match the current implementation using connection.

Updated documentation for Guards

---

starlite/cache/memcached_cache_backend.py
starlite/middleware/session/memcached_backend.py

Fix memcached typing

---

README.md
docs/css/color.css
docs/index.md
docs/migration.md
mkdocs.yml
tools/run_examples.py

Update migration guide, add framework feature comparison

---

docs/index.md

Fixes missing colon in feature comparison

docs: fix missing colons in framework feature comparison

---

starlite/dto.py
starlite/handlers/http.py
starlite/utils/__init__.py
starlite/utils/types.py
tests/response/test_dto_response.py
tests/utils/test_types.py

Add support for auto generation of DTOs from response data

---

starlite/handlers/http.py
starlite/response/base.py
tests/handlers/http/test_media_type.py

add media type inference to HTTP handlers

---

starlite/asgi/asgi_router.py
starlite/asgi/routing_trie/mapping.py
starlite/asgi/routing_trie/traversal.py
starlite/asgi/routing_trie/types.py
starlite/types/composite_types.py
tests/kwargs/test_path_params.py

add support for differently named path parameters on same route

---

starlite/openapi/schema.py
tests/openapi/test_schema.py

Render Enum params correctly in OpenAPI

---

.github/workflows/docs.yaml
mkdocs.yml
requirements-docs.txt

This add versioning using [mike](https://github.com/jimporter/mike).
Preview available [here](https://provinzkraut.github.io/starlite)
**Do not merge**. I need to set up some things manually before the new docs workflow can run and deploy properly.

Add docs versioning

---

CONTRIBUTING.md
docs/usage/9-testing/0-intro.md
starlite/testing/request_factory.py
starlite/testing/test_client/client.py
tox.ini

Fixes #997
This is an extension of the work done in #705

Remove references to 'testing' extra removed in 1.35

---

docs/reference/3-controller.md
docs/reference/config/0-app-config.md
docs/usage/0-the-starlite-app.md
docs/usage/5-responses/10-custom-responses.md
examples/responses/custom_responses.py
starlite/app.py
starlite/config/app.py
starlite/controller.py
starlite/handlers/http.py
starlite/response/base.py
starlite/router.py
starlite/types/__init__.py
starlite/types/composite_types.py
starlite/utils/deprecation.py
starlite/utils/scope.py
starlite/utils/serialization.py
tests/response/test_base_response.py
tests/response/test_type_encoders.py

Support layered `type_encoders`

---

starlite/openapi/path_item.py
tests/openapi/test_tags.py

Sort tags in open api schema

---

starlite/openapi/controller.py
tests/openapi/test_controller.py

Fix swagger check for schema

---

starlite/utils/serialization.py
tests/logging_config/test_structlog_config.py

Rename enc_hook in encode_json to fix structlog

---

starlite/response/base.py

Re-enable `super()` calls to `Response.serializer`

---

.github/workflows/ci.yaml
docs/usage/19-cli.md
starlite/cli.py
tests/test_cli.py

Support application factory pattern in CLI `run` command

---

starlite/openapi/schema.py
starlite/testing/test_client/client.py

Fix issues that were introduced in #1007 and subsequent fixes.

Fix issues introduces in #1007

---

examples/plugins/sqlalchemy_plugin/sqlalchemy_async.py

I found a wrong type hint in the SQLAlchemyPlugin example.

Fix type hint in example sqlalchemy_async.py

---

starlite/contrib/opentelemetry/middleware.py

Fix meter in OpenTelemetry Middleware being passed a meterprovider

---

README.md

(#1059) Add Starlite Subreddit to README

---

mkdocs.yml
poetry.lock

Update AutoPyTabs to be used as an mkdocs plugin instead of a markdown extension.

chore: update AutoPyTabs

---

poetry.lock
pyproject.toml
starlite/cli/commands/openapi.py
tests/cli/conftest.py
tests/cli/test_cli.py
tests/cli/test_env_resolution.py
tests/cli/test_openapi_commands.py

Fix openapi-typescript-generators CLI tests

---

starlite/cli/commands/schema.py
starlite/cli/main.py
tests/cli/test_schema_commands.py

Rename CLI command "openapi" > "schema"

---

poetry.lock
pyproject.toml
starlite/utils/serialization.py
tests/utils/test_serialization.py

Add msgspec typed decoding

---

pyproject.toml
tests/dto_factory/test_dto_factory_plugin_registratation.py

Fix #1080: Missing / wrong dependencies for Jinja2 extra 

---

poetry.lock
pyproject.toml

Fix jinja extra typo

---

starlite/asgi/asgi_router.py
starlite/cli/commands/core.py
starlite/cli/commands/sessions.py
starlite/cli/utils.py
starlite/datastructures/provide.py
starlite/kwargs/dependencies.py
starlite/kwargs/kwargs_model.py
starlite/logging/picologging.py
starlite/router.py
starlite/routes/asgi.py
starlite/routes/base.py
starlite/routes/http.py
starlite/routes/websocket.py
starlite/static_files/base.py
starlite/testing/client/async_client.py
starlite/testing/request_factory.py
starlite/types/file_types.py
starlite/types/partial.py

Updates remaining references not covered in #1051 (because the modules were either undocumented or the script the author wrote had a little bug that prevented it from detecting those references :upside_down_face:)

Fix docstring style and references

---

docs/migration/fastapi.rst

Co-authored-by: Tobi-De <tobidegnon@proton.me>

chore: updated example endpoint function called by Starlite app

---

.all-contributorsrc

Add missing contributions of maintainers to all-contributors

---

docs/_static/js/version_select.js
tools/publish_docs.py

Fix #1113: Version warning mike compatibility

---

.pre-commit-config.yaml
docs/examples/tests/parameters/test_header_and_cookies_parameters.py
docs/examples/tests/parameters/test_layered_parameters.py
pyproject.toml
starlite/middleware/session/base.py
tests/contrib/jwt/test_auth.py
tests/datastructures/test_file_container.py
tests/handlers/http/test_to_response.py
tests/response/test_dto_response.py
tests/testing/test_testing.py

Addresses various warnings raised from our test suite

Fix various test warnings

---

docs/examples/tests/responses/test_response_cookies.py

Removes xfail mark from passing test.

---

.flake8
starlite/app.py
starlite/config/app.py
starlite/types/composite_types.py
tests/app/test_app_config.py

This PR allows plugins to set initial state inside of on-app-init hooks.

Feature: allow on-app-init hooks to modify initial state.

---

.flake8
starlite/types/callable_types.py
starlite/types/composite_types.py
starlite/types/internal_types.py

This was started in #1122, however I forgot to finish it.

Ignore TC004 per file in types modules.

---

starlite/app.py
starlite/middleware/cors.py
starlite/middleware/exceptions/middleware.py
tests/middleware/test_cors_middleware.py
tests/middleware/test_exception_handler_middleware.py

fix missing CORS headers on exception responses

---

starlite/controller.py
tests/test_controller.py

implement validation of controller route handler methods

---

CONTRIBUTING.rst
README.md

Fixes:
- Move from `CONTRIBUTING.md` -> `CONTRIBUTING.rst` 
- Incorrect HTML file call `starlite-versions.html` -> `starlite-releases.html`

Documentation Link Fixes

---

starlite/handlers/asgi.py
starlite/handlers/base.py
starlite/handlers/http.py
starlite/handlers/websocket.py

Type encoders update

---

starlite/contrib/jwt/jwt_auth.py
starlite/security/base.py
tests/contrib/jwt/test_auth.py

add support to type encoders for JWT config

---

docs/reference/di.rst
docs/reference/index.rst
docs/reference/provide.rst
docs/reference/response_containers.rst
docs/reference/types.rst
docs/reference/upload_file.rst
docs/reference/utils/pagination.rst
docs/usage/middleware/builtin-middleware.rst

Fix warnings and broken links.

---

starlite/contrib/jwt/jwt_auth.py
tests/contrib/jwt/test_auth.py

1118 enhancement support returning token in response body with JWT auth

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/publish.yaml

PascalCase the GH actions so that when badges are rendered they are more clear (and nicer looking)
If the changes are not up to snuff or we only want single words I recommend maybe these instead:
Tests
Docs
Releases

Update GitHub actions for badge rendering

---

docs/benchmarks.rst
docs/conf.py

fix(bug): fix CoC link

---

docs/_static/style.css

Docs - update sidebar css

---

starlite/app.py
starlite/config/app.py

Closes #1120 
This PR adds the following features
- Adds a configuration object in Starlite constructor
- Adds sane defaults in AppConfig
- Updates pre-commits to fix isort issue
This PR was accidently closed. Follow previous discussion [here](https://github.com/starlite-api/starlite/pull/1173)

Added from_config classmethod for Starlite

---

tools/publish_docs.py
tools/sphinx_ext.py

Use __future__.annotations in tools/*.py

---

tools/sphinx_ext.py

Remove string quoted annotations.

---

Makefile
docs/conf.py
docs/lib/benchmarks.rst
docs/lib/index.rst
docs/lib/reference/app.rst
docs/lib/reference/handlers/index.rst
docs/lib/reference/response_containers.rst
docs/lib/usage/contrib/htmx.rst
starlite/contrib/htmx/request.py
starlite/contrib/htmx/response.py
starlite/contrib/htmx/utils.py

Fix docs warnings

---

.pre-commit-config.yaml
poetry.lock
starlite/asgi/routing_trie/validate.py
test_apps/piccolo_admin_app/main.py
test_apps/static_files_test_app/main.py
test_apps/static_files_test_app/public/index.html
tests/static_files/test_file_serving_resolution.py

Fix static path validation for `/`

---

docs/lib/index.rst

docs: fix typo

---

poetry.lock
starlite/app.py
starlite/utils/predicates.py
tests/app/test_registering_route_handlers.py
tests/openapi/test_parameters.py
tests/openapi/test_path_item.py
tests/openapi/test_schema.py
tests/openapi/typescript_converter/test_converter.py
tests/security/test_security.py

update app.openapi_schema to use lazy evaluation on first access

---

docs/lib/migration/fastapi.rst

docs: fix a typo in the "Migration from FastAPI" section

---

tests/contrib/jwt/test_auth.py

Removes extra test case assertion

fix: removed incorrect test case

---

docs/lib/reference/datastructures/index.rst
docs/lib/reference/datastructures/upload_file.rst
docs/lib/reference/index.rst
docs/lib/reference/types.rst
docs/lib/reference/upload_file.rst

Fix some references that broke with #1215.

Documentation: Fix references after refactoring

---

starlite/utils/extractors.py
tests/middleware/test_logging_middleware.py

This is the fix from [#1229](https://github.com/starlite-api/starlite/pull/1229) but for the `main` branch.
Cheers!
Kyle

Fix #1228: create a new dictionary of values in obfuscate()

---

test_apps/piccolo_admin_app/home/tables.py
test_apps/piccolo_admin_app/main.py
test_apps/piccolo_admin_app/piccolo_conf.py

Fixing Piccolo Admin test app #1235.

Fix Piccolo Admin test app

---

starlite/kwargs/dependencies.py
starlite/kwargs/kwargs_model.py
starlite/openapi/parameters.py
starlite/openapi/path_item.py
starlite/signature/models.py
starlite/signature/parsing.py
tests/openapi/test_parameters.py
tests/openapi/test_request_body.py
tests/openapi/test_schema.py
tests/test_signature.py

Signature refactors

---

docs/about/starlite-releases.rst

Docs: Update versioning and release documentation

---

mypy.ini
starlite/contrib/tortoise_orm.py

Fix type errors in tortoise contrib.

---

pyproject.toml

This PR does some fixes in the pyproject.toml file and removes jtraub from the maintainers. I'm afraid something bad happened to him... but in either case, he hasn't been around for several month and is not actively maintaining. I hope he will return and we will turn return him back in...

updated pyproject

---

.pre-commit-config.yaml
poetry.lock
starlite/_kwargs/extractors.py
starlite/connection/base.py
starlite/connection/request.py
starlite/dto.py
starlite/middleware/rate_limit.py
starlite/testing/request_factory.py
starlite/utils/predicates.py

Update deps and tooling.

---

pyproject.toml

Remove unused Ruff ruleset

---

poetry.lock
starlite/_asgi/routing_trie/traversal.py
tests/routing/test_path_resolution.py

This PR fixes a regression in path resolution that prevented 404's being raised for false paths.

fixed path resolution regression

---

starlite/response/base.py
starlite/serialization.py

Ref: https://github.com/starlite-api/starlite/pull/1329#discussion_r1137300870

Roll back changes in `serialization.py` introduced in #1329

---

pyproject.toml

Reverts a `ruff` ruleset change due to an upstream bug
Fixes #1332

fix(ci): revert ruleset change introduced in #1306

---

docs/usage/events.rst
docs/usage/index.rst

add event emitters docs

---

README.md

updated alpha version in readme

---

docs/reference/index.rst
docs/reference/status_codes.rst
starlite/exceptions/websocket_exceptions.py
starlite/status_codes.py

Fixes #1375.
Update the docstring of `WebSocketException` to be more clear and add missing documentation for status codes.

Document status codes and improve WebSocketException description

---

pyproject.toml

Moves `pytest-lazy-fixture` from a runtime dependency to development dependencies.
Noted on https://github.com/conda-forge/starlite-feedstock/pull/43

move pytest-lazy-fixture to dev dependencies

---

starlite/contrib/sqlalchemy/init_plugin/config/common.py
starlite/contrib/sqlalchemy/init_plugin/plugin.py

This is same fix as #1391, but the feature was omitted from this plugin implementation.

Call `update_app_state` in `on_startup` hook.

---

README.md
docs/index.rst

Adds a temporary announcement in the docs and `README.md` that notifies users of the upcoming change.
Closes https://github.com/starlite-api/starlite/issues/1437

Add Note/Announcement about Rename to Litestar

---

.github/workflows/ci.yaml

Adds a check to only run Snyk & Sonar on the upstream repository. 
Closes #1440

🍴's need love too. Update CI to only run Snyk & Sonar on upstream

---

litestar/app.py

Change default `preferred_validation_backend` to Pydantic

---

README.md
docs/index.rst

Update URL of Pydantic repo

---

litestar/partial.py
litestar/utils/predicates.py
tests/test_partial.py

This PR adds support for Partial[msgpsec.Struct]

Add msgspec.Struct Partial support

---

tests/template/test_template.py

Add more samples for testing template

---

starlite/cli/commands/core.py

This backports #1255 to the `v1.51` branch, fixing the `--reload` issue with uvicorn.

Backport #1255 to 1.51

---

starlite/cli/commands/core.py
tests/cli/conftest.py
tests/cli/test_run_command.py

Fix tests for CLI run command

---

docs/examples/data_transfer_objects/building_a_dto.py
litestar/_kwargs/extractors.py
litestar/dto/interface.py
litestar/handlers/http_handlers/_utils.py
litestar/serialization.py
tests/dto/__init__.py
tests/kwargs/test_dto_extractor.py
tests/test_serialization.py

This PR includes refactorings to better integrate DTO encoding with existing serialization patterns, and modifications to the interface to better support integration with websocket handlers.
`from_connection()` reverted back to `from_bytes()`, and receives both the already awaited raw data from the payload, and the connection instance.
Now that `from_bytes()` receives the raw payload data, already extracted from the connection, it no longer needs to be an async method, improving symmetry with the `from_data()` constructor method.
`from_data()` now also receives the connection instance, which further improves symmetry between the two constructor methods.
The `to_encodable_type()` method no longer receives the connection (this isn't required any more as the constructor methods receive it, …

Refactor `DTOInterface`.

---

litestar/dto/factory/__init__.py
litestar/dto/factory/field.py

No longer used but was not removed.
Closes #1527

Removes `dto.factory.field.Purpose`.

---

docs/index.rst

- removed Picologging reference from `standard` extra
- added `jwt`, `jinja`, `sqlalchemy`, `tortoise-orm`, and `attrs` extras
- consistent title case
- RedisStore now links to the usage page instead of api ref

Docs: update installation extras

---

litestar/exceptions/base_exceptions.py

Make `MissingDependencyException` a subclass of `ImportError`

---

litestar/contrib/sqlalchemy/base.py

Add ModelProtocol to `contrib.sqlalchemy.base.__all__`

---

docs/tutorials/todo-app/0-application-basics.rst
docs/tutorials/todo-app/2-interacting-with-the-list.rst

Fix a typo and a formatting issue in the basic application tutorial.

Docs: Fix typo / formatting in basic application tutorial

---

docs/reference/dto/factory/index.rst
docs/usage/dto/0-basic-use.rst
docs/usage/dto/1-dto-factory.rst
docs/usage/dto/2-dto-interface.rst
docs/usage/dto/index.rst

These are items from review of PR #1569 that I forgot to push up before merging.

Review items for PR #1569

---

pyproject.toml

Add Jacob Coffee as a maintainer to `pyproject.toml`.

Add Jacob Coffee as a maintainer

---

litestar/testing/websocket_test_session.py
tests/testing/test_sync_test_client.py

Add `block` and `timeout` parameters to `WebSocketTestSession` receive methods, to allow handling of cases where otherwise, the receive methods would block indefinitely.

Add `block` and `timeout` parameters to `WebSocketTestSession` receive methods

---

docs/tutorials/todo-app/1-accessing-the-list.rst

example's function name is `get_list` not `get_todo_list`

fix func typo

---

CONTRIBUTING.rst

Removes references to `CHANGELOG.md` from release process.

chore: update release process docs

---

.all-contributorsrc
README.md

I appreciate being added to the contributors list. I prefer to not commit my full name since, even if I set my Github profile to private, it will always remain available in this repo.

Removing proper name from contributors list

---

docs/examples/data_transfer_objects/factory/dto_data_problem_statement.py
docs/examples/data_transfer_objects/factory/dto_data_usage.py
docs/examples/tests/data_transfer_objects/factory/test_example_apps.py
docs/usage/dto/1-dto-factory.rst
litestar/dto/factory/__init__.py
litestar/dto/factory/_backends/abc.py
litestar/dto/factory/_backends/utils.py
litestar/dto/factory/abc.py
litestar/dto/factory/data_structures.py
litestar/dto/interface.py
tests/dto/factory/test_integration.py

A datastructure for interacting with DTO validated data in its unstructured form.
This utility is to support the case where the amount of data that is available from the client request is not complete enough to instantiate an instance of the model that would otherwise be injected.
```py
from __future__ import annotations
from dataclasses import dataclass
from uuid import UUID, uuid4
from litestar import post
from litestar.dto.factory import DTOConfig, DTOData
from litestar.dto.factory.stdlib.dataclass import DataclassDTO
@dataclass
class Person:
id: UUID
name: str
age: int
class WriteDTO(DataclassDTO[Person]):
"""Doesn't allow the client to set the id."""
config = DTOConfig(exclude={"id"})
@post("/person", dto=WriteDTO, return_dto=None)
def create_person(data: DTOData[Person]) -> Person: …
```

Feature: `DTOData` datastructure.

---

.pre-commit-config.yaml
litestar/_signature/models/attrs_signature_model.py
litestar/app.py
litestar/contrib/sqlalchemy/base.py
litestar/handlers/base.py
litestar/middleware/exceptions/_debug_response.py
litestar/routes/http.py
litestar/security/session_auth/middleware.py
poetry.lock
tests/contrib/sqlalchemy/models.py
tests/contrib/sqlalchemy/repository/test_async_generic_mock_repository.py
tests/contrib/sqlalchemy/test_dto_integration.py
tests/signature/test_signature_validation.py
tests/test_router_registration.py

fix attrs unstructuring of attrs models

---

litestar/response/base.py
tests/contrib/htmx/test_htmx_request.py
tests/contrib/htmx/test_htmx_response.py
tests/response/test_serialization.py

add validation to unknown media types

---

docs/reference/index.rst
docs/reference/typing.rst
litestar/contrib/sqlalchemy/dto.py
litestar/contrib/sqlalchemy/plugins/serialization.py
litestar/dto/factory/_backends/abc.py
litestar/dto/factory/_backends/types.py
litestar/dto/factory/abc.py
litestar/dto/factory/data_structures.py
litestar/dto/factory/stdlib/dataclass.py
litestar/dto/factory/utils.py
litestar/dto/interface.py
litestar/plugins.py
litestar/typing.py
litestar/utils/signature.py
tests/contrib/sqlalchemy/test_dto.py
tests/dto/factory/backends/test_abc.py
tests/dto/factory/backends/test_backends.py
tests/dto/factory/backends/test_utils.py
tests/dto/factory/test_abc.py
tests/dto/factory/test_stdlib.py
tests/utils/test_signature.py

Motivation is described in #1567.
Closes #1567

Exposes `ParsedType` as public api.

---

litestar/_signature/models/attrs_signature_model.py
poetry.lock
tests/kwargs/test_attrs_data.py

fix attrs converter unstructuring behavior for attrs models

---

README.md
pyproject.toml

- updates stale links for PyPI stale links
- updates branding on badges
- updates badge links
- adds Litestar announcement
- adds project links to pypi
[//]: # "Please add in issue …

Update 1.x Stale Links

---

docs/release-notes/migration_guide_2.rst

Adds DTOs to migration guide.

---

docs/conf.py
docs/reference/contrib/index.rst
docs/reference/contrib/msgspec.rst
docs/reference/contrib/pydantic.rst
litestar/contrib/msgspec.py
litestar/contrib/pydantic.py
litestar/contrib/sqlalchemy/dto.py
litestar/dto/factory/abc.py
litestar/dto/factory/stdlib/dataclass.py
tests/contrib/conftest.py
tests/contrib/sqlalchemy/test_dto.py
tests/contrib/test_msgspec.py
tests/contrib/test_pydantic.py

Msgspec and Pydantic dto factory implementations.

---

docs/PYPI_README.md
pyproject.toml

Creates a new PyPI-specific `README` that allows for correct rendering of images.
Also adds project link to pypi as done in #1707
Related …

docs: fix images in pypi readme

---

litestar/contrib/repository/testing/generic_mock_repository.py
litestar/middleware/compression.py
tests/conftest.py
tests/middleware/test_compression_middleware.py

Always flush after write for gzip.

---

docs/migration/flask.rst

[Docs] - Flask migration: Fix outdated litestar module imports

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
tests/channels/test_backends.py
tests/channels/test_plugin.py

Fix failing platform compatibility tests

---

litestar/contrib/msgspec.py
litestar/contrib/pydantic.py
litestar/contrib/sqlalchemy/dto.py
litestar/dto/factory/_backends/abc.py
litestar/dto/factory/_backends/types.py
litestar/dto/factory/_backends/utils.py
litestar/dto/factory/abc.py
litestar/dto/factory/data_structures.py
litestar/dto/factory/stdlib/dataclass.py
litestar/dto/factory/types.py
tests/contrib/conftest.py
tests/contrib/test_msgspec.py
tests/contrib/test_pydantic.py
tests/dto/factory/backends/test_abc.py
tests/dto/factory/test_stdlib.py

Moves `FieldDefinition` from `dto.factory.types` to `dto.factory.data_structures`

---

litestar/_openapi/schema_generation/schema.py
tests/openapi/test_schema.py

Handle nested Literal annotations for OpenApi schema generation

---

litestar/_openapi/schema_generation/schema.py
tests/openapi/test_spec_generation.py

Fix OpenApi schema for Dict[K, V]

---

docs/release-notes/whats-new-2.rst

Adds Response to "whats-new-2.rst".

---

docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_init_plugin.py
docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_plugin.py
docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_serialization_plugin.py
docs/examples/data_transfer_objects/factory/enveloping_return_data.py
docs/examples/data_transfer_objects/factory/paginated_return_data.py
docs/examples/data_transfer_objects/factory/response_return_data.py
docs/examples/tests/data_transfer_objects/factory/test_example_apps.py
docs/usage/dto/1-dto-factory.rst
litestar/dto/factory/_backends/abc.py
litestar/dto/factory/_backends/utils.py
litestar/dto/factory/abc.py
litestar/dto/factory/data_structures.py
litestar/dto/factory/utils.py
litestar/handlers/http_handlers/_utils.py
litestar/handlers/http_handlers/base.py
litestar/pagination.py
litestar/response/base.py
tests/dto/factory/backends/test_abc.py
tests/dto/factory/backends/test_backends.py
tests/dto/factory/test_integration.py
tests/dto/factory/test_utils.py

Where a handler returns a type that is not supported by the DTO, but:
- the return type is generic
- it has a generic type argument that is supported by the dto
- the type argument maps to an attribute on the return type
...we perform the DTO operations on the data retrieved from that attribute
of the instance returned from the handler, and return the instance.
The constraints are:
- that the type returned from the handler must be a type that litestar can
natively encode
- the annotation of the attribute that holds the data must be a type that DTOs
can otherwise manage
```py
from dataclasses import dataclass
from typing import Generic, List, TypeVar
from typing_extensions import Annotated
from litestar import Litestar, get
from litestar.dto.factory import DTOConfig
from …
```

DTO Factory: support for arbitrary generic wrappers

---

.pre-commit-config.yaml
litestar/_asgi/routing_trie/traversal.py
litestar/_signature/models/pydantic_signature_model.py
litestar/partial.py
litestar/types/protocols.py
litestar/utils/helpers.py
pyproject.toml
tests/asgi_router/routing_trie/test_path_param_resolution.py
tests/contrib/test_pydantic.py
tests/handlers/websocket/test_listeners.py

chore: fixed path parameter resolution

---

litestar/handlers/base.py
litestar/handlers/http_handlers/base.py
litestar/params.py
litestar/response/streaming.py
litestar/types/__init__.py
litestar/types/asgi_types.py
litestar/types/builtin_types.py
litestar/types/callable_types.py
litestar/types/composite_types.py
litestar/types/empty.py
litestar/types/file_types.py
litestar/types/helper_types.py
litestar/types/internal_types.py
litestar/types/serialization.py
litestar/typing.py
litestar/utils/predicates.py
litestar/utils/typing.py

chore: cleanup types

---

.github/workflows/publish.yaml

Run poetry run pytest docs/examples/tests/test_hello_world.py
ImportError while loading conftest '/home/runner/work/litestar/litestar/tests/conftest.py'.
tests/conftest.py:15: in <module>
from fakeredis.aioredis import FakeRedis
E   ModuleNotFoundError: No module named 'fakeredis'
Error: Process completed with exit code 4.
[//]: # "Please describe your pull request for …

fix: adds fake redis to publish pipeline

---

docs/usage/cli.rst

Update cli docs

---

.pre-commit-config.yaml
litestar/cli/commands/core.py
litestar/cli/main.py
poetry.lock
pyproject.toml
tests/unit/test_contrib/test_opentelemetry.py

This PR updates pre-commit and fixes issues

chore(infra): update and resolve pre-commit issues

---

.pre-commit-config.yaml

fix: revert pre-commit overwrite

---

docs/examples/contrib/sqlalchemy/sqlalchemy_async_repository.py
docs/examples/contrib/sqlalchemy/sqlalchemy_repository_crud.py
docs/examples/contrib/sqlalchemy/sqlalchemy_repository_extension.py
docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
docs/examples/responses/response_content.py
litestar/_openapi/schema_generation/schema.py
litestar/channels/backends/memory.py
litestar/channels/backends/redis.py
litestar/contrib/jwt/middleware.py
litestar/contrib/sqlalchemy/base.py
litestar/contrib/sqlalchemy/plugins/init/config/asyncio.py
litestar/contrib/sqlalchemy/plugins/init/config/sync.py
litestar/dto/factory/_backends/utils.py
litestar/security/session_auth/middleware.py
litestar/serialization/_pydantic_serialization.py
litestar/types/serialization.py
litestar/utils/scope.py
pyproject.toml
tests/unit/test_cli/test_cli.py
tests/unit/test_contrib/test_sqlalchemy/test_dto_integration.py
tests/unit/test_contrib/test_sqlalchemy/test_repository/conftest.py
tests/unit/test_controller.py
tests/unit/test_dto/test_factory/test_integration.py
tests/unit/test_handlers/test_http_handlers/test_signature_namespace.py
tests/unit/test_kwargs/test_reserved_kwargs_injection.py
tests/unit/test_static_files/test_file_serving_resolution.py

This PR does cleanup suggested by sourcery and intellij, it also fixes the mypy issues on main (due to a move from mypy.ini to pyproject.toml).

chore(refactor): cleanup

---

litestar/_openapi/schema_generation/schema.py
litestar/app.py
litestar/contrib/attrs/__init__.py
litestar/contrib/attrs/attrs_schema_plugin.py
litestar/contrib/piccolo.py
litestar/contrib/sqlalchemy/plugins/init/config/engine.py

This PR moves the attrs schema logic into a plugin

feat(internal): move attrs schema generation to plugin

---

.pre-commit-config.yaml
mypy.ini
starlite/asgi/asgi_router.py
starlite/cli/utils.py
starlite/config/logging.py
starlite/connection/base.py
starlite/connection/request.py
starlite/contrib/jwt/jwt_auth.py
starlite/datastructures/provide.py
starlite/dto.py
starlite/kwargs/extractors.py
starlite/middleware/rate_limit.py
starlite/middleware/session/sqlalchemy_backend.py
starlite/openapi/controller.py
starlite/plugins/tortoise_orm.py
starlite/signature/parsing.py
starlite/testing/request_factory.py
starlite/utils/predicates.py
tests/cli/conftest.py
tests/cli/test_cli.py
tests/contrib/open_telemetry/test_open_telemetry_middleware.py
tests/handlers/http/test_media_type.py
tests/kwargs/test_path_params.py
tests/plugins/tortoise_orm/__init__.py
tests/plugins/tortoise_orm/test_tortoise_orm_plugin_integration.py
tests/response/test_dto_response.py
tests/response/test_serialization.py
tests/test_controller.py
tests/test_typing.py
tests/third_party/test_beanie_integration.py

Update the pre-commit hooks in the `v1.51` branch and update typing accordingly.

chore(v1.51): Update pre-commit

---

docs/usage/cli.rst

This PR updates the CLI docs. I used chat GPT to improve the english quickly.

chore(docs): edited cli docs

---

litestar/_asgi/routing_trie/traversal.py
tests/e2e/test_routing/test_path_resolution.py

fix(routing): path parameter resolution matching sub-paths

---

README.md
docs/PYPI_README.md

- Bump to Beta 3
- Rename `pydantic-factories` to `polyfactory`
[//]: # "Examples: Fixes #4321 or …

docs: update readme

---

docs/index.rst

- Makes the `standard` and `cli` package installation options more visible 
- Fixes #2037

docs: make `standard` and `cli` options more visible

---

.github/workflows/docs.yaml
docs/_static/versions.json

-This aims to add a `dev` version to the docs to represent the current state of `main`
We had this before:
but we stopped building them
-

docs: add dev version

---

docs/_static/style.css

Refs: litestar-org/litestar#1687
Refs: litestar-org/litestar#2053
- Added dark-theme-specific styles for Mermaid diagrams with transparent backgrounds to make embedded text readable.
- Fixes litestar-org/litestar#1687

docs(style): add dark theme styles for mermaid diagrams

---

docs/examples/responses/sse_responses.py
pyproject.toml
tests/unit/test_app.py
tests/unit/test_connection/test_request.py
tests/unit/test_middleware/test_exception_handler_middleware.py
tests/unit/test_signature/test_validation.py

Fix a bunch of warnings that are being issued during test runs.

fix(tests): Fix assorted warnings

---

.github/workflows/test.yaml
CONTRIBUTING.rst
Makefile
docs/examples/contrib/sqlalchemy/plugins/tutorial/full_app_with_session_di.py
litestar/cli/commands/core.py
poetry.lock
pyproject.toml
tests/__init__.py
tests/conftest.py
tests/docker_service_fixtures.py
tests/e2e/test_option_requests.py
tests/examples/test_contrib/test_piccolo/test_piccolo_crud.py
tests/examples/test_contrib/test_sqlalchemy/plugins/test_example_apps.py
tests/examples/test_contrib/test_sqlalchemy/plugins/test_tutorial_example_apps.py
tests/helpers.py
tests/unit/piccolo_conf.py
tests/unit/test_channels/test_backends.py
tests/unit/test_channels/test_plugin.py
tests/unit/test_contrib/test_jwt/test_token.py
tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py
tests/unit/test_contrib/test_sqlalchemy/test_repository/conftest.py
tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_uuid.py
tests/unit/test_contrib/test_sqlalchemy/test_repository/test_sqlalchemy_oracledb_json.py
tests/unit/test_kwargs/test_validations.py
tests/unit/test_middleware/test_session/test_client_side_backend.py
tests/unit/test_stores.py

Add [pytest-xdist](https://pytest-xdist.readthedocs.io) to speed up the tests.
A few tests had to be adjusted along the way to eliminate race conditions and combat lack of isolation (=

feat(tests): Parallelize test suite with pytest-xdist

---

.github/workflows/ci.yaml
.github/workflows/qodona.yml

ci: qodona

---

litestar/_openapi/path_item.py
litestar/_openapi/schema_generation/schema.py
litestar/app.py
litestar/cli/_utils.py
litestar/handlers/base.py
litestar/plugins.py
tests/unit/test_app.py
tests/unit/test_plugins.py

Add a "plugin registry", that allows to retrieve plugins by their type.

feat: plugin registry

---

litestar/handlers/__init__.py

Fix a reference error in the docs that was introduced in #2088

docs: fix a docs reference error introduced in #2088

---

litestar/channels/plugin.py

Fix an issue with the base path on windows that would cause forward slashes to be escaped

fix(channels): Windows base path issue

---

.all-contributorsrc
litestar/middleware/exceptions/middleware.py
litestar/testing/request_factory.py
tests/unit/test_exceptions.py

This PR ensures that exceptions have the media type of the route handler - if a route handler is in place, and if it has a media type.

fix: pass media type from route handler to exception

---

litestar/routes/base.py

Add the offending path to the error message.

enhancement(validation): better error message for path param type validation 

---

litestar/routes/base.py

Reverts litestar-org/litestar#2136

Revert "enhancement(validation): better error message for path param type validation "

---

docs/usage/databases/sqlalchemy/models_and_repository.rst

- fix trailing slash that broke the URI fragment

1 char change: erraneous trailing comma in URL

---

litestar/controller.py

Currently the order of controller handlers (e.g. as listed in the generated OpenAPI schema) is not only random but unstable between different runs unless [PYTHONHASHSEED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) is fixed (which is typically not).
This PR ensures deterministic (even if somewhat arbitrary) order.
Potential future feature: Make handler ordering configurable by the user.

feat: Ensures deterministic ordering of handlers

---

litestar/_openapi/schema_generation/examples.py
poetry.lock
pyproject.toml
tests/unit/test_openapi/test_parameters.py

This PR fixes the issue with random seeding of the example factory.

fix(openapi): example factory random seed

---

.all-contributorsrc
.pre-commit-config.yaml
README.md
docs/PYPI_README.md
docs/usage/stores.rst
litestar/contrib/sqlalchemy/base.py
litestar/contrib/sqlalchemy/repository/_async.py
litestar/contrib/sqlalchemy/repository/_sync.py
tests/unit/test_dto/test_factory/test_base_dto.py
tests/unit/test_typing.py
tools/sphinx_ext/run_examples.py

Update pre-commit repos and apply resulting changes.

chore: update pre-commit

---

docs/usage/dto/0-basic-use.rst
docs/usage/dto/2-creating-custom-dto-classes.rst
docs/usage/dto/index.rst

docs(DTO): small typos

---

docs/usage/openapi.rst
litestar/_openapi/responses.py
litestar/controller.py
litestar/routes/base.py
tests/unit/test_openapi/test_responses.py

**DO NOT MERGE**
This PR tracks the `v2.1` feature branch. It will be merged into `main` once `2.0.0` is released.

chore: v2.1

---

.all-contributorsrc
docs/usage/htmx.rst

This PR updates the HTMX documentation to align with the parameter changes.  It also adds additional imports and the Litestar app for clarity.
-

docs: updates htmx docs

---

.github/workflows/ci.yaml

chore: remove snyk

---

.github/workflows/ci.yaml
tests/docker_service_fixtures.py
tests/examples/test_contrib/test_piccolo_orm.py
tests/examples/test_contrib/test_sqlalchemy/plugins/test_tutorial_example_apps.py
tests/examples/test_templating/test_returning_templates.py
tests/examples/test_templating/test_template_functions.py

Revert a few changes that broke platform compat tests

fix(tests): fix platform compat tests

---

litestar/contrib/sqlalchemy/base.py

- This PR adds an export that was overlooked for the base repo
-

fix: adds missing ORM registry export

---

litestar/openapi/spec/enums.py

-  Try add `binary format` for openapi
-

feat: Add `binary` to `OpenAPIFormat`

---

docs/release-notes/changelog.rst
poetry.lock
pyproject.toml

- Prepare for the 2.1.0 release
-

chore(release): prepare for v2.1.0

---

.github/workflows/publish.yaml

Small PR that runs `pre-commit` and applies resulting changes.

chore: fix formatting

---

docs/usage/applications.rst
litestar/app.py

- Remove old lifecycle hooks
- Closes #2375

fix(docs): remove stale hooks #2375

---

litestar/app.py
litestar/contrib/minijnja.py

ci: apply sourcery

---

CONTRIBUTING.rst
docs/conf.py

docs: Fix some missing references

---

CONTRIBUTING.rst

I think the doomsday thing is just a joke, if you click on the text it goes between:
- Polar Dinosaurs Museum
- Professionals Don't Mock
- Perpetually Dark Matter
- Potentially Deadly Monster
- Party Dancing Master
etc.
-
-

chore: update ``CONTRIBUTING.rst``

---

.pre-commit-config.yaml
litestar/cli/_utils.py
litestar/contrib/pydantic/pydantic_init_plugin.py
litestar/handlers/http_handlers/base.py
litestar/router.py
litestar/security/session_auth/middleware.py
pyproject.toml
tests/unit/test_cli/test_cli.py

Upgrades mypy to 1.6 & pyright to 1.331.
-
-

chore: upgrade tooling & type fixes.

---

.github/workflows/publish.yml

- I think this fixes this: https://github.com/litestar-org/litestar/actions/runs/6493735781
-

fix(ci): resolves issue with versionSpec param missing

---

.github/workflows/docs.yml

> Warning: Unexpected input(s) 'allowpython-prereleases'
[ref](https://github.com/litestar-org/litestar/actions/runs/6520536684/job/17708175205#step:4:1)
-
-

build: Fix unexpected PDM action input.

---

pdm.lock

PDM lock hash has drifted again which breaks the docs build.
-

chore: update pdm lock hash

---

.github/workflows/ci.yml
pdm.lock
pyproject.toml

uvloop does not support windows.
-

build: specify uvloop only for non-windows builds

---

.pre-commit-config.yaml
pdm.lock
pyproject.toml

This PR:
- updates lock file
- changes upper constraint of advanced-alchemy to 1.0
- updates pre-commit hooks
-

chore: update dependencies and tools

---

sonar-project.properties

Some stuff no longer exists, and add exclude for `litestar/__main__.py`
-

chore: update sonar exclusions.

---

docs/tutorials/sqlalchemy/index.rst

Not required
- Adds `aiosqlite` and `greenlet` to requirements for SQLAlchemy tutorial
fixes #2557

docs: add aiosqlite and greenlet to requirements for tutorial

---

litestar/contrib/pydantic/pydantic_schema_plugin.py

Remove an unused variable from the `PydanticSchemaPlugin`.

refactor(pydantic plugin): remove unused parameter

---

docs/usage/dependency-injection.rst

`update_user` (used in description) -> `get_user` (used int the code snippet)
-
-

docs: Fix Dependency keyword arguments example

---

.github/workflows/ci.yml
tests/unit/test_response/test_serialization.py

This PR fixes tests of `Path` serialization on windows (it is actually a fix of my last attempted fix, which actually made it worse :see_no_evil:).
-

fix: windows compatibility tests

---

litestar/contrib/pydantic/utils.py
tests/unit/test_contrib/test_pydantic/test_dto.py
tests/unit/test_contrib/test_pydantic/test_integration.py
tests/unit/test_contrib/test_pydantic/test_utils.py

This PR adds tests for coverage in the `contrib.pydantic` namespace.
For #2535

test: coverage for contrib.pydantic.

---

litestar/contrib/minijinja.py
tests/unit/test_contrib/test_minijinja.py

This PR extends test coverage for the minijinja contrib.
For: #2535
-
-

test: coverage for contrib.minijinja

---

docs/usage/responses.rst

- fixed tiny TYPOs I stumpled upon

docs: fix small typos

---

litestar/utils/helpers.py
litestar/utils/predicates.py
litestar/utils/sync.py
tests/unit/test_utils/test_helpers.py

Simplify `utils.helpers.unwrap_partials`

chore: simplify unwrap_partial

---

.github/workflows/pr-title.yml
CONTRIBUTING.rst
docs/conf.py
docs/index.rst
docs/tutorials/sqlalchemy/2-serialization-plugin.rst
docs/usage/logging.rst
pdm.lock

- Fix some documentation bugs on building
- Fixed duplicate link text but differing links in `CONTRIBUTING.rst` causing failed builds
- Fixed incorrect line selection causing index issue
- Specify the default pygment highlights
- Add suppressions to warning causing `docs-serve` to obliterate terminal
- Fix bad code block spacing causing build failure
- Fix wording on landing page for minimal examples
- Update lock file to pull the latest `litestar-sphinx-theme` changes to make the now-purple links not be purple
- Small unrelated ci fix for pr title validation (can move)
-

fix(docs): resolve duplicate link tag

---

README.md
docs/PYPI_README.md

- minify readme footprint
- fix(docs): fix various types
- feat(docs): add TOC
-

docs: adds collapsible elements to the readme to minify their length

---

docs/tutorials/repository-tutorial/01-modeling-and-features.rst
docs/tutorials/repository-tutorial/02-repository-introduction.rst
docs/tutorials/repository-tutorial/03-repository-controller.rst
docs/tutorials/repository-tutorial/04-repository-other.rst

- Reduces the walls of code shown for SQLA repo tutorial
- Utilize dropdowns and download links for particularly long segments
-

docs: move how much code is shown at once

---

litestar/contrib/pydantic/utils.py

This PR aims to improve the pydantic contrib's version checking to avoid breakage.
-
- Fixes #2672

fix: Improve pydantic version checking

---

docs/topics/deployment/manually-with-asgi-server.rst
litestar/plugins/base.py

This PR fixes two errors that occur when building the documentation.
Closes #2680

docs: fix build errors

---

litestar/contrib/pydantic/utils.py
litestar/utils/signature.py
tests/unit/test_di.py
tests/unit/test_utils/test_compat.py
tests/unit/test_utils/test_deprecation.py

Improve the coverage of the `litestar.utils` module

test: Improve coverage of `litestar.utils`

---

.gitignore
Makefile

- This PR limits the PDM configuration changes to the local folder.  It also adds `pdm.toml` to `.gitignore`
-

fix: set PDM settings to `--local`

---

litestar/contrib/piccolo.py
tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py

- This functionality has been moved to it's own plugin `litestar-piccolo` that includes all of the previous functionality and additional features.
-

feat: adds a deprecation warning for `litestar.contrib.piccolo`

---

litestar/typing.py
tests/unit/test_typing.py

test(typing): Improve `litestar.typing` coverage

---

docs/release-notes/changelog.rst

chore: add release notes for v2.4.1

---

.github/workflows/publish.yml

- Run the test with `pdm run` to ensure they're being run in the virtual environment.

ci: correct command to run pydantic v1 test

---

.pre-commit-config.yaml
pdm.lock
pyproject.toml

chore: update deps & tooling

---

docs/index.rst
docs/usage/middleware/creating-middleware.rst

- adjust wording for example app that was jumbled.
- fix link in middleware documentation
-

fix(docs): adjust wording for example app

---

docs/tutorials/sqlalchemy/0-introduction.rst
docs/tutorials/sqlalchemy/1-provide-session-with-di.rst
docs/tutorials/sqlalchemy/2-serialization-plugin.rst
docs/tutorials/sqlalchemy/3-init-plugin.rst
docs/tutorials/sqlalchemy/4-final-touches-and-recap.rst

- Fixes minor line emphasis inconsistencies with in the SQLAlchemy tutorial example code blocks.
- Closes #2763

fix(docs): Updating SQLAlchemy tutorial line emphasis

---

docs/conf.py
litestar/security/jwt/middleware.py

Fixes some and silences other docs warnings.
Closes @2726

fix(ci): docs build warnings

---

README.md
docs/PYPI_README.md
docs/index.rst

Add sponsors section to our readme and docs

docs: sponsors update

---

docs/usage/routing/handlers.rst

Fixes https://github.com/orgs/litestar-org/discussions/2880#discussioncomment-7822153

fix: headers type in docs

---

docs/examples/channels/run_in_background.py
pdm.lock

fix(docs): update the ``Channels`` example for ``run_in_background``

---

litestar/channels/backends/redis.py
litestar/connection/request.py
litestar/connection/websocket.py
litestar/contrib/mako.py
litestar/file_system.py
litestar/handlers/http_handlers/_utils.py
litestar/security/jwt/auth.py
litestar/security/session_auth/auth.py
litestar/utils/helpers.py
pdm.lock
tests/unit/test_handlers/test_websocket_handlers/test_listeners.py
tests/unit/test_middleware/test_middleware_handling.py
tests/unit/test_openapi/test_security_schemes.py

chore(typing): various pyright issues

---

.pre-commit-config.yaml

because https://github.com/sphinx-contrib/sphinx-lint/pull/106

fix(ci): upgrade sphinx-lint

---

litestar/channels/backends/asyncpg.py
litestar/channels/backends/memory.py
litestar/channels/backends/redis.py
tests/unit/test_channels/test_backends.py

Fix a bug that would allow a channels backend to receive messages from a channel it just unsubscribed from, for a short period of time, due to how the different brokers handle unsubscribes.
```python
await backend.subscribe(["foo", "bar"])  # subscribe to two channels
await backend.publish(b"something", ["foo"])  # publish a message to a channel we're subscribed to
event_generator = backend.stream_events()
await backend.unsubscribe(["foo"])
print(anext(event_generator))
```

fix(channels): Trailing messages after unsubscribes

---

tests/unit/test_openapi/test_controller.py

fix: syntax error has been fixed

---

litestar/cli/_utils.py
pyproject.toml

Fix 2 `rich_click` deprecation warnings.

test(refactor): Fix `rich_click` deprecation warnings

---

docs/migration/flask.rst

Corrected errors and improved code style in the Flask example code that [docs](https://docs.litestar.dev/2/migration/flask.html) present as a migration target.

docs: fix Flask example code

---

litestar/response/sse.py
tests/unit/test_response/test_sse.py
tests/unit/test_response/test_streaming_response.py

Bring test coverage for `ServerSentEventMessage` and `ServerSentEvent` to 100%

test: Improve SSE coverage

---

docs/conf.py

docs: Fix reference error

---

README.md
docs/PYPI_README.md
docs/index.rst

Add [Stock](https://www.stok.kr/) https://github.com/stok-team as a named sponsor to our Readme and docs

chore: Add Stok as a named sponsor

---

docs/usage/security/abstract-authentication-middleware.rst

This PR fixes some small issues in the documentation of `AbstractAuthenticationMiddleware`.

docs: fix reference and indentation

---

litestar/middleware/exceptions/_debug_response.py

Remove an unnecessary `is None` check in `create_debug_response`

refactor(create_debug_response): Remove redundant `None` check

---

litestar/_openapi/schema_generation/schema.py

Fixes https://sonarcloud.io/project/issues?id=litestar-org_litestar&open=AYz2nBZTXkJDQkY3JNbu

refactor(SchemaCreator): Make a few methods static

---

litestar/cli/commands/core.py
tests/unit/test_cli/test_core_commands.py

Refactor the CLI `routes` command and associated tests to reduce complexity. 
This should also fix the failing tests on Windows.
https://sonarcloud.io/project/issues?id=litestar-org_litestar&open=AYzgW0Tm5TPoZDnT_BAi

refactor(CLI): `routes` command and associated tests

---

litestar/plugins/base.py
litestar/utils/module_loader.py
tests/unit/test_plugins/test_base.py
tests/unit/test_utils/test_module_loader.py

feat: allow plugins to be found by dotted path string

---

.github/workflows/ci.yml
.github/workflows/test.yml

ci: Fix codecov coverage combine

---

pyproject.toml

Fixes https://github.com/litestar-org/litestar/issues/3023

fix: exceptiongroup import python < 3.11

---

docs/release-notes/changelog.rst
pyproject.toml

Release notes for the upcoming 2.5.4 release

chore(release): prepare for v2.5.4

---

litestar/static_files/config.py

Fix an issue with the path resolution on Windows introduced in #2960.

fix(static files): Path resolution for windows

---

litestar/_kwargs/extractors.py
litestar/_signature/model.py
tests/unit/test_kwargs/test_layered_params.py
tests/unit/test_signature/test_validation.py

feat: only display path in `ValidationException`s

---

docs/usage/applications.rst

Suggestions for better alignment between descriptions and code examples. Also attempted to fix stale link (but not used to rst, so not sure if that works like that).
Closes #3110
Closes #2688

docs: Fix minor issues in docs/usage/applications.rst

---

docs/usage/databases/sqlalchemy/models_and_repository.rst

- Changes the column names to match the actual ones defined

docs: correct UUIDAuditBase/BigIntAuditBase columns name.

---

docs/examples/request_data/custom_request.py
docs/usage/requests.rst
litestar/app.py
litestar/controller.py
litestar/handlers/http_handlers/base.py
litestar/handlers/http_handlers/decorators.py
litestar/router.py
litestar/routes/http.py
tests/unit/test_request_class_resolution.py
tests/unit/test_response_class_resolution.py

- Expose `request_class` to other layers

feat: expose request_class to other layers

---

docs/examples/websockets/custom_websocket.py
docs/usage/websockets.rst
litestar/app.py
litestar/controller.py
litestar/handlers/websocket_handlers/listener.py
litestar/handlers/websocket_handlers/route_handler.py
litestar/router.py
litestar/routes/websocket.py
tests/unit/test_websocket_class_resolution.py

Expose `websocket_class` to other layers

feat: expose websocket_class

---

docs/release-notes/changelog.rst
pyproject.toml

Prepare for patch release 2.6.3 (from 2.6.2)

chore(release): prepare for v2.6.3

---

docs/usage/responses.rst
litestar/response/__init__.py

- add some docs about sse message and how to use
nothing, came from a help thread on discord: https://discord.com/channels/919193495116337154/1213242966592856164/1214333782644105277

docs: mention how to use ServerSentEventMessage

---

.github/workflows/ci.yml

Enable running platform compat tests selectively in CI

ci: Enable running platform compat tests in CI

---

tests/examples/test_request_data.py
tests/examples/test_websockets.py

- Add tests for `request_class` and `websocket_class` doc examples

test: Add tests for `request_class` and `websocket_class` doc examples

---

tools/prepare_release.py

chore: Fix release script maybe

---

docs/release-notes/changelog.rst

Edits to change log for minor version 2.7.0

chore(release): 2.7.0

---

pdm.lock
pyproject.toml

- adds `codecov-cli` to run locally (requires tokens from https://app.codecov.io/gh/litestar-org/litestar/settings)

ci: add `codecov-cli` to the linting dev dependencies

---

litestar/openapi/config.py

- Adds deprecated directives for the deprecated parameters of the config.
- Adds some cross-references.
- Solves unclear/undocumented deprecation which led to #3234

docs: improvement for openapi router config.

---

docs/usage/applications.rst

- Add missing layered parameters

docs: Add missing layered parameters

---

docs/examples/testing/test_health_check_async.py
docs/examples/testing/test_health_check_sync.py
docs/usage/testing.rst

- Make it clearer that the test_client needs to be used as a contextmanager.
I didn't follow this example closely enough, and forgot the `with` statement in my tests.  I only realized it was already there after I made all of these changes and was reviewing everything to make sure it was all complete.  Since it's currently technically correct, these changes aren't as necessary as I thought, but I still think this is clearer than what's currently here.
This version also makes it easier to use since each test doesn't have to have a separate `with` block.
While I was at it, I fixed the "partially unknown" typing.

docs: Update test_client fixture documentation

---

.github/workflows/docs.yml
docs/_static/versions.json

- Adds `develop` branch docs build
- Adds `v3.0` branch docs build
- Closes #3221

docs: build develop and v3 branch docs

---

README.md
docs/PYPI_README.md
docs/index.rst

- Clarifies the preferred platform for sponsoring due to the blog subscription, built-in Discord integrations, and APIs that will save us time

docs: clarify preferred platforms for sponsoring

---

litestar/cli/__init__.py

- Removes duplicate config options from click cli

fix(cli): remove duplicate rich-click config options

---

docs/release-notes/whats-new-2.rst

docs: Expand the acronym for Data Transfer Object in `What's New in v2`

---

litestar/contrib/pydantic/pydantic_dto_factory.py
tests/unit/test_contrib/test_pydantic/test_integration.py

Fix a bug that would cause a `TypeError` when non-Pydantic errors are raised during Pydantic's validation process while using DTOs.
This is the case for example when using `field_validator`:
```python
class User(BaseModel):
user_id: int
@field_validator("user_id")
@classmethod
def validate_user_id(cls, user_id: int) -> None:
raise ValueError("user id must be greater than 0")
```
The exception on our side occurs because Pydantic v2 includes the raw error objects in their error report, which we in turn use to generate our error responses.
I've added a simple fix that stringifies the errors here. This does not address the root issue though, which is how we currently handle the different ways libraries throw errors at us. We should aim for a more permanent fix, but this is unfortunately not …

fix(DTO): Pydantic v2 error handling/serialization when for non-pydantic exceptions

---

litestar/datastructures/headers.py

`CacheControlHeader` is using `AbstractDTO` to access the inner type of an optional union in order to get at the instantiable type within.
This PR does that without needing an import from `litestar.dto` and helps to fix a circular import issue I've bumped into elsewhere.
-

refactor: remove CacheControlHeader dependency on AbstractDTO

---

CONTRIBUTING.rst

docs: update contribution guide

---

CONTRIBUTING.rst

- Adds tab sets to some sections missed in the contrib guide

docs: contrib guide update

---

CONTRIBUTING.rst

docs: Update CONTRIBUTING.rst

---

docs/release-notes/changelog.rst
pyproject.toml

chore(release): bump version, edit changelog

---

CITATION.cff

Adds a citation reference in the sidebar of the repository
- Adds `CITATION.cff`
See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

docs: add citation

---

.gitignore

These are created by our docs build when running the examples for [Static Files][1].
[1]: https://docs.litestar.dev/latest/usage/static-files.html#static-files
-

chore: add assets/ and html/ to .gitignore

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

- adds an automatic labeler for PRs for project and release automations

ci:  add labeler for prs

---

docs/release-notes/changelog.rst
pyproject.toml

Changelog and version bump from `v2.8.1` release branch.
-

chore(release): prepare release v2.8.1

---

docs/usage/applications.rst

- followup on https://github.com/litestar-org/litestar/pull/3302

docs: update ``usage/applications``

---

docs/release-notes/changelog.rst
pyproject.toml

Changelog and version bump from v2.8.2 release branch.

chore(release): prepare release v2.8.2

---

docs/release-notes/whats-new-2.rst

- It makes more sense to use `used` in this case.

docs: correct a word

---

docs/conf.py
tools/build_docs.py

- attempts to fix v3 docs builds

fix(docs): fix builds

---

docs/examples/request_data/custom_request.py
pyproject.toml
tests/unit/test_cli/test_core_commands.py
tests/unit/test_contrib/test_pydantic/conftest.py
tests/unit/test_contrib/test_pydantic/test_openapi.py
tests/unit/test_dto/conftest.py
tests/unit/test_dto/test_integration.py
tests/unit/test_openapi/test_schema.py

Fix about 900 warnings in our test suite when running on 3.12.

chore: Fix warnings in test suite

---

docs/examples/responses/sse_responses.py
tests/examples/test_responses/test_sse_responses.py

docs: improve sse

---

.github/ISSUE_TEMPLATE/config.yml

- Do not allow blank issues (require creation from template.)

fix(ci): adjust issue template to not allow blank issues

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

- Removes poetry and replaces it with ~~Personal Dismay~~ Python Dependency Manager in `.devcontainer/Dockerfile` and `.devcontainer/devcontainer.json` with relevant CLI changes,
Closes #3461

chore(infra): remove poetry in devcontainer.json

---

LICENSE

- Add 2024 to the copyright notice

chore: update copyright notice year

---

docs/release-notes/changelog.rst
litestar/static_files/base.py
pyproject.toml
tests/e2e/test_routing/test_path_resolution.py
tests/unit/test_static_files/test_file_serving_resolution.py
tests/unit/test_static_files/test_static_files_validation.py
tools/prepare_release.py

chore(release): prepare release v2.8.3

---

CITATION.cff

- Current CITATION.cff could not parsed, this PR attempts to fix it.

chore(citations): fix file so it can be parsed

---

pyproject.toml

chore: update maintainer emails

---

tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py

Fix timing issue when tests run over midnight.
Fixes #3481

fix: avoid failure due to timing

---

docs/usage/dependency-injection.rst

Small improvement for the docs
Fixes #3033

docs: TYPE_CHECKING for injected types

---

docs/usage/security/abstract-authentication-middleware.rst

Minor improvement to the docs
#3444

docs: use mapped_column

---

docs/release-notes/changelog.rst

chore: formatting fixes

---

litestar/exceptions/responses/__init__.py

We already have:
```
from litestar import MediaType, Request, Response
```

chore(exceptions): remove duplicated import

---

docs/usage/openapi/ui_plugins.rst

docs: update ui_plugins.rst

---

litestar/handlers/http_handlers/base.py
litestar/handlers/websocket_handlers/route_handler.py

Manually port the fix for #3593 to v3

chore: Port fix for #3593 to v3

---

docs/tutorials/dto-tutorial/06-receiving-data.rst

docs: Added Posting tool as an alternative to Postman in 06-receiving-data.rst 

---

.pre-commit-config.yaml
docs/conf.py
docs/usage/responses.rst
docs/usage/routing/parameters.rst
litestar/_openapi/schema_generation/schema.py
litestar/app.py
litestar/channels/backends/redis.py
litestar/cli/commands/core.py
litestar/contrib/opentelemetry/middleware.py
litestar/openapi/spec/base.py
litestar/plugins/core.py
litestar/utils/sync.py
pdm.lock
pyproject.toml
tests/helpers.py
tests/unit/test_contrib/test_opentelemetry.py
tests/unit/test_contrib/test_pydantic/test_integration.py
tests/unit/test_openapi/test_schema.py
tests/unit/test_response/test_response_to_asgi_response.py
tools/prepare_release.py
tools/sphinx_ext/run_examples.py

Update package dependencies :)

chore: update dependencies

---

litestar/security/jwt/token.py
pdm.lock
pyproject.toml
tests/unit/test_security/test_jwt/test_token.py

This PR adresses the abandoned/obsolete python package:  python-jose.
This package has not been maintained since 2021.
looking at several issues on that project there are a couple CVE's im not comfortable with.
I went looking for a "drop-in" replacement and found pyjwt.  (project last updated 3 weeks ago).
This pull requests addresses that problem.
hope you agree with this.
kind regards.

feat: switched abandonded python-jose to pyjwt

---

docs/usage/routing/parameters.rst

docs: stale reference to pydantic signature models

---

litestar/handlers/base.py
litestar/utils/signature.py
litestar/utils/warnings.py
tests/unit/test_utils/test_signature.py

fix: inconsistent behavior between `signature_namespace` and `signature_types`

---

litestar/middleware/_utils.py
pdm.lock
tests/unit/test_middleware/test_base_middleware.py

- I added a test that doesnt pass with the current implementation, that is wen you exclude `^/$`

fix(warnings): the exclude pattern matching warned too much

---

.github/workflows/docs.yml
.github/workflows/pr-merged.yml
docs/_static/versions.json

- Removes ``develop`` branch from docs building

docs: no more develop branch

---

litestar/types/builtin_types.py
tests/e2e/test_dependency_injection/test_http_handler_dependency_injection.py
tests/e2e/test_dependency_injection/test_websocket_handler_dependency_injection.py
tests/e2e/test_life_cycle_hooks/test_after_request.py
tests/e2e/test_life_cycle_hooks/test_before_request.py
tests/e2e/test_response_caching.py
tests/unit/test_app.py
tests/unit/test_connection/test_request.py
tests/unit/test_connection/test_websocket.py
tests/unit/test_openapi/test_responses.py

Add type parameters to some test cases where they were not used; partially fixes https://github.com/litestar-org/litestar/issues/2694.

refactor: Add types to some tests

---

.github/workflows/ci.yml

ci(docs): include hidden files for docs

---

docs/index.rst

docs(index): Add `litestar-fullstack-inertia` and remove `litestar-pg-redis-docker`

---

docs/examples/testing/test_health_check_async.py
docs/examples/testing/test_health_check_sync.py

- Removes unused code snippet that a fixture is used for instead
Closes: #3260

docs: remove unused code snippet

---

litestar/openapi/plugins.py

feat: bump `scalar` OpenAPI Plugin to `latest` release

---

docs/conf.py

- update copyright notice year from 2023 to 2024

docs: update copyright notice year to 2024

---

docs/usage/openapi/index.rst

Adds more links and fixes some wordings

docs: improve `openapi/index.rst` page

---

Makefile

fix: update Makefile

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

~~Obviously next is Poetry 2 (@Kumzy )~~

fix(devcontainers): Replace PDM with UV

---

docs/examples/contrib/sqlalchemy/sqlalchemy_declarative_models.py
litestar/contrib/sqlalchemy/base.py
tests/examples/test_contrib/test_sqlalchemy/test_sqlalchemy_examples.py
tests/unit/test_plugins/test_sqlalchemy.py
uv.lock

This PR updates the SQLAlchemy examples and documentation to align with current AA best practices.

fix(sqlalchemy): updates to documentation based on upstream changes

---

.github/workflows/test.yml

fix(ci): only install dev tools in ubuntu

---

docs/release-notes/changelog.rst

Updates the details of changes between versions

chore(release): updates change log for `v2.14.0`

---

docs/conf.py
docs/examples/testing/test_subprocess_sse.py
pyproject.toml
tests/unit/test_channels/test_subscriber.py
tests/unit/test_testing/test_sub_client/test_subprocess_client.py

Set the default loop scope for `pytest-asyncio`
Closes #3936

fix: configure default loop scope

---

LICENSE
docs/conf.py

Update the copyright and license files to reference 2025

chore: welcome to 2025

---

litestar/app.py

fix: corrected import of attrs

---

Makefile

allows multiple projects' docs to be served simultaneously

chore: let sphinx-autobuild automatically choose a port

---

litestar/app.py
tests/e2e/test_router_registration.py

Addition to #3900.
Remove unnecessary complexity and also add a nice performance boost for app startup :)
<hr>
There's a bunch of other stuff that we can remove due to the cleanup in #3900, but I'd rather add this in a separate PR as it doesn't strictly belong here.

feat(routing): simplify route creation

---

pyproject.toml

Add section in pyproject.toml file for pypi, it includes:
- funding
- discussions

chore: add funding and discussions to pyproject for pypi

---

docs/examples/deployment/nginx-unit/unit.json

fix spell mistake in nginx-unit (unit.json)
-

docs: fix spell mistake in nginx-unit

---

docs/migration/fastapi.rst

- adds some more differences found while migrating, hopefully this can help.

docs: fastapi migration

---

docs/index.rst
docs/release-notes/2.x-changelog.rst
docs/release-notes/whats-new-3.rst
docs/usage/static-files.rst
tests/e2e/test_routing/test_route_reverse.py

Fix some issues with the v3 docs and re-add a commit from #3324 that got lost somewhere :eyes:

docs(v3): fix some doc issues

---

docs/release-notes/2.x-changelog.rst
docs/release-notes/whats-new-2.rst
docs/release-notes/whats-new-3.rst
docs/usage/plugins/index.rst
litestar/app.py
litestar/config/app.py
litestar/plugins/__init__.py
litestar/plugins/base.py
pyproject.toml
uv.lock

Remove the deprecated `SerializationPluginProtocol` for v3.0.

feat(plugins): Remove deprecated `SerializationPluginProtocol`

---

docs/usage/middleware/creating-middleware.rst

docs: Fix `ASGIMiddleware` docs (#4031)

---

pyproject.toml

Add Julien to the list of maintainers and applies TOML lint to the pyproject.

chore: update maintainers and apply TOML lint to `pyproject.toml`

---

docs/topics/deployment/docker.rst
docs/topics/deployment/nginx-unit.rst
docs/tutorials/dto-tutorial/01-simple-dto-exclude.rst
docs/tutorials/dto-tutorial/index.rst
docs/tutorials/repository-tutorial/01-modelling-and-features.rst
docs/tutorials/repository-tutorial/02-repository-introduction.rst
docs/tutorials/repository-tutorial/03-repository-controller.rst
docs/tutorials/repository-tutorial/04-repository-other.rst
docs/tutorials/todo-app/0-application-basics.rst
docs/tutorials/todo-app/1-accessing-the-list.rst
docs/tutorials/todo-app/3-assembling-the-app.rst
docs/usage/databases/piccolo.rst
docs/usage/databases/sqlalchemy/models_and_repository.rst
docs/usage/dependency-injection.rst
docs/usage/middleware/builtin-middleware.rst
docs/usage/requests.rst
docs/usage/security/abstract-authentication-middleware.rst
docs/usage/security/guards.rst
docs/usage/security/secret-datastructures.rst
docs/usage/templating.rst
docs/usage/testing.rst

By submitting this pull request, I agree to:
Use monospace formatting in code block captions where applicable (mostly for filenames).
Not applicable.

docs: Use monospace in code captions where applicable

---

pyproject.toml

fix: change ruff TCH to TC

---

.pre-commit-config.yaml
litestar/dto/_backend.py
litestar/dto/dataclass_dto.py
litestar/handlers/websocket_handlers/_utils.py
litestar/router.py
pyproject.toml
test_apps/debugging/main.py
tests/unit/test_kwargs/test_layered_params.py
tests/unit/test_middleware/test_session/test_client_side_backend.py
tests/unit/test_params.py
tests/unit/test_response/test_base_response.py
tests/unit/test_response/test_file_response.py
typos.toml

- Recreation of https://github.com/litestar-org/litestar/pull/4078 targeting main instead for easier migration
- Updating config so doesn't target public classes

refactor: use typos

---

docs/examples/caching/cache_response_filter.py
docs/usage/caching.rst

-
https://github.com/litestar-org/litestar/issues/2589

docs: add example for cache_response_filter

---

docs/usage/cli.rst

-
https://github.com/litestar-org/litestar/issues/2778

docs: add usage of server_lifespan hook and motivations

---

docs/examples/security/guards.py
docs/usage/security/guards.rst

- used literalinclude as well
fixes #3189

docs: add mention in guard docs from where connection.user comes from

---

litestar/datastructures/upload_file.py

- Correct write() method docstring to specify int return value (bytes written)
- Update seek() method docstring to indicate int return value (new position)

docs: 📚 Fix return value for UploadFile

---

litestar/_openapi/schema_generation/utils.py
litestar/openapi/spec/example.py
tests/unit/test_openapi/test_responses.py

feat(openapi): add custom example ids support

---

docs/examples/exceptions/implicit_media_type.py
docs/usage/exceptions.rst
tests/e2e/test_exception_handlers/test_exception_handlers.py

docs: show exceptions raised aren't always JSON

---

litestar/dto/_codegen_backend.py

Doing this enables:
- Better tracebacks, that include references to the actual program source
- Introspection via e.g. `inspect.getsource`
**Before**
```
File "/home/.../projekte/litestar-django/.venv/lib/python3.13/site-packages/litestar/dto/base_dto.py", line 121, in data_to_encodable_type
return backend.encode_data(data)
~~~~~~~~~~~~~~~~~~~^^^^^^
File "/home/.../projekte/litestar-django/.venv/lib/python3.13/site-packages/litestar/dto/_codegen_backend.py", line 163, in encode_data
return cast("LitestarEncodableType", self._encode_data(data))
~~~~~~~~~~~~~~~~~^^^^^^
File "<string>", line 18, in func
TypeError: <something's wrong>
```
**After**
```
File "/home/john/projekte/litestar-django/.venv/lib/python3.13/site-packages/litestar/dto/_codegen_backend.py", line 163, in encode_data …
```

feat(DTO): Populate `linecache` for generated transfer functions

---

docs/usage/static-files.rst

docs: Correct typo in static-files.rst

---

tests/e2e/test_option_requests.py

- Adds tests for the bug described in #4169
- N.A.

test: Add more tests for default options handler

---

README.md
docs/PYPI_README.md
docs/index.rst
docs/migration/flask.rst
docs/release-notes/changelog.rst
docs/tutorials/todo-app/0-application-basics.rst
docs/usage/cli.rst
docs/usage/databases/sqlalchemy/plugins/sqlalchemy_plugin.rst
docs/usage/metrics/open-telemetry.rst
docs/usage/metrics/prometheus.rst
docs/usage/middleware/builtin-middleware.rst
docs/usage/security/jwt.rst
docs/usage/templating.rst
litestar/exceptions/base_exceptions.py
tests/unit/test_exceptions.py

It solves the same problem as in https://github.com/litestar-org/litestar/pull/4189

docs: always use `'`  for dependencies with groups

---

pyproject.toml

chore: use pypi readme

---

litestar/_kwargs/cleanup.py
tests/unit/test_kwargs/test_cleanup_group.py

fix: make dependency cleanup in reverse order

---

tools/prepare_release.py

- Improve GitHub release message.
- Preview from Advanced Alchemy

chore: improve release note

---

.github/workflows/docs.yml

- Add option for manual docs runs of any version

ci: add manual docs things with selective input

---

docs/migration/fastapi.rst

https://github.com/litestar-org/litestar/issues/4265
For reference, see the following two links:
https://docs.litestar.dev/2/usage/applications.html#lifespan-context-managers
https://fastapi.tiangolo.com/advanced/events/#lifespan

docs: fix lifespan migration from fastapi

---

litestar/plugins/base.py
litestar/plugins/pydantic/plugins/schema.py
litestar/plugins/pydantic/utils.py
tests/unit/test_plugins/test_pydantic/test_schema_plugin.py

fix: Support Pydantic root models

---

docs/usage/middleware/builtin-middleware.rst

- Add reference for advanced alchemy sessions

docs: add reference for advanced alchemy sessions

---

README.md
docs/PYPI_README.md
docs/getting-started.rst
docs/usage/middleware/builtin-middleware.rst

Update docs to include zstd compresison middleware

docs: update docs with zstd

---

litestar/_openapi/typescript_converter/schema_parsing.py
tests/unit/test_openapi/test_typescript_converter/test_converter.py

This PR closes #4198 and a new bug I reporterted in discord.

fix: typescript export not handling NotRequired and regression with handling of additional_properties

---

.github/workflows/cherry-pick-v2.yaml

So it can also be used on already closed PRs

ci: run cherry-pick action on PR labeled

---

docs/release-notes/changelog.rst
litestar/plugins/pydantic/__init__.py
litestar/plugins/pydantic/plugins/init.py
tests/unit/test_plugins/test_pydantic/test_integration.py

Closes https://github.com/litestar-org/litestar/issues/4349

feat(pydantic): add `round_trip` parameter to `PydanticPlugin`

---

docs/release-notes/changelog.rst
litestar/contrib/minijinja.py
tests/unit/test_deprecations.py

Closes https://github.com/litestar-org/litestar/issues/4355

feat(minijinja)!: Remove deprecated `minijinja.minijinja_from_state`

---

docs/release-notes/index.rst

Fix broken links to realse notes

docs: fix(docs/realse-notes): fix broken links to realse notes
