litestar-org/litestar

- tests/test_params.py
As per Discord discussion.
Here's the Starlette equivalent for context:
```python
from starlette import applications, requests, responses, routing, testclient
def test_request_body_multi_part_mixed_field_content_types_starlette() -> None:
async def test_method(request: requests.Request) -> responses.Response:
form = await request.form()
assert await form["file"].read() == b"file data"
assert form["tags"] == "tags=1&tags=2"
return responses.Response(status_code=201)
app = applications.Starlette(routes=[routing.Route("/", test_method, methods=["POST"])])
with testclient.TestClient(app) as client:
response = client.post(
"/",
files=[
("file", ("somefile.txt", b"file data")),
("tags", (None, b"tags=1&tags=2", "application/x-www-form-urlencoded")),
],
)
assert response.status_code == …
```
> test: add xfail test for non-file multipart request bodies

- tests/test_params.py
I think this is a better example.
This now represents the pretty common use case of uploading a file and some metadata.
This is describable by OpenAPI.
The Starlette equivalent would be:
```python
from starlette import applications, requests, responses, routing, testclient
def test_request_body_multi_part_mixed_field_content_types_starlette() -> None:
async def test_method(request: requests.Request) -> responses.Response:
form = await request.form()
assert await form["image"].read() == b"data"
assert [v for k, v in form.multi_items() if k == "tags"] == ["1", "2"]
return responses.Response(status_code=201)
app = applications.Starlette(routes=[routing.Route("/", test_method, methods=["POST"])])
with testclient.TestClient(app) as client:
response = client.post(
"/",
files=[ ("image", …
```
> test: better xfail test for multipart bodies

- docs/usage/8-authentication.md
Getting a mypy error otherwise:
`Return type "AuthenticationResult" of "authenticate_request" incompatible with return type "Coroutine[Any, Any, AuthenticationResult]" in supertype "AbstractAuthenticationMiddleware"
`
> authenticate_request example should be async

- .github/workflows/ci.yaml
I'm pretty sure this should work..
> ci: only allow sonarqube on pull requests from starlite-api branches

- CHANGELOG.md
- docs/usage/10-openapi.md
- pyproject.toml
- starlite/app.py
- starlite/config.py
- starlite/openapi/controller.py
- tests/openapi/test_integration.py
- tests/test_dependency_injection.py
This PR does the following:
1. enables OpenAPI by default
2. adds the OpenAPIController to the OpenAPIConfig so it no longer needs to be passed separately
3. simplifies the docs
> Update OpenAPI default

- starlite/openapi/controller.py
👋 First let me tell that `Starlite` is a really exciting project.
While working on a new project I found a small `bug` when working with `old` **orjson** version (which is pinned somewhere in my env 🤷‍♂️)
It seems that the new orjson version (>=3.6) enable import like `from orison.orjson import ...` but earlier version doesn't work.
with orjson <3.6 
```python
import orjson
orjson.__version__
>>> '3.5.2'
from orjson.orjson import OPT_INDENT_2, dumps
----> 1 from orjson.orjson import OPT_INDENT_2, dumps
ModuleNotFoundError: No module named 'orjson.orjson'; 'orjson' is not a package
from orjson import OPT_INDENT_2, dumps
print(OPT_INDENT_2)
>>> 1
```
with orjson >= 3.6 
```python
import orjson
orjson.__version__
>>> '3.6.5'
from orjson.orjson import OPT_INDENT_2, dumps
print(OPT_INDENT_2) …
```
> update orjson import to work with orjson <3.6

- poetry.lock
- starlite/__init__.py
- starlite/dto.py
- starlite/plugins/sql_alchemy.py
- tests/__init__.py
- tests/plugins/sql_alchemy_plugin/__init__.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_plugin_integration.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_relationships.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_table_types.py
- tests/test_dto.py
- tests/utils/test_model.py
- tests/utils/test_signature.py
This PR adds a DTOFactory class.
This class can be used to create DTOs from pydantic models, dataclasses and any other class supported via plugins:
Given a supported model class - either pydantic, dataclass or a class supported via plugins, create a DTO pydantic model class.
An instance of the factory must first be created, passing any plugins to it. It can then be used to create a DTO by calling the instance like a function. Additionally, it can exclude (drop) attributes specifies in the 'exclude' list and remap field names and/or field types.
For example, given a pydantic model
```python
class MyClass(BaseModel):
first: int
second: int
MyClassDTO = DTOFactory()(MyClass, exclude=["first"], field_mapping={"second": ("third", float)})
```
`MyClassDTO` is now equal to this:
```python
class …
```
> Add DTOFactory

- starlite/app.py
- starlite/controller.py
- starlite/handlers.py
- starlite/request.py
- starlite/routing.py
- starlite/testing.py
- starlite/types.py
- tests/test_connection_lifecycle_hooks.py
This PR adds ''before_request" and "after_request" hooks. 
These are directly borrowed from flask, with two differences:
1. Async support
2. You can define these functions on all layers - app, router,  controller, method/function, and the lowest level takes precedence.
> Add support for "before_request" and "after_request" hooks

- pyproject.toml
- starlite/app.py
- starlite/handlers.py
- starlite/openapi/responses.py
- starlite/routing.py
- tests/handlers/test_http_handlers.py
- tests/openapi/test_request_body.py
- tests/test_response_headers.py
- tests/test_route.py
- tests/test_router.py
This PR changes does the following:
1. Update the RouteHandler classes from being pydantic models to being custom classes. Although this adds a lot of code duplication, the advantage is allows us to use the `__slots__` attribute- reducing the memory usage of each handler instance and increasing access speed. 
2. Stop extending the starlette BaseRoute class - this is not required, and it makes our usage of `__slots__` less effective because starlette does not implement slots (hence a `__dict__` method is generated, although we use `__slots__`).
> Optimize slots

- CHANGELOG.md
- docs/usage/10-plugins.md
- pyproject.toml
- starlite/plugins/sql_alchemy.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_relationships.py
- updated SQLAlchemy plugin- all relationships are now typed as `Optional`
- updated SQLAlchemy plugin- all back-references are now typed as `Any`
> SQL Alchemy Plugin, iteration 2

- README.md
Was jumpstarting a project, and noticed a syntax error in the example code block.
> Remove "]" in README code block

- docs/usage/5-responses.md
- poetry.lock
- pyproject.toml
- starlite/__init__.py
- starlite/app.py
- starlite/config.py
- starlite/datastructures.py
- starlite/exceptions.py
- starlite/handlers.py
- starlite/openapi/responses.py
- starlite/response.py
- starlite/template.py
- starlite/testing.py
- tests/openapi/test_responses.py
- tests/test_template.py
This pr aims to bring templating support for Starlite by leveraging already existing template engine. Currently `mako` and `jinja2` are supported. 
```py 
from starlite import Starlite, TemplateConfig, Template, get
from starlite.template import JinjaTemplateEngine
@get(path="/")
def index() -> Template:
return Template(name="index.html", context={"test": "test"})
app = Starlite(
route_handlers=[heath_check], template_config=TemplateConfig(directory=["templates"], engine=JinjaTemplateEngine)
)
```
- write docs
- ~~write tests~~
-  OpenAPI integration
> Add templating

- starlite/types.py
Using `TypeVar("T", bound=Type[BaseModel])` as the type variable in `Partial` does not type-check. 
For example:
```python
class Person(BaseModel):
name: str
PartialPerson = Partial[Person]  # does NOT type-check
PartialPerson = Partial[Type[Person]]  # type-checks
```
This PR changes the type variable used in `Partial` from `TypeVar("T", bound=Type[BaseModel])` to `TypeVar("T", bound=BaseModel)` and subsequent types in `Partial` as needed to allow `PartialPerson = Partial[Person]` to type-check 🤡 
For context, I enjoy using Pyright in its strictest configuration. If somehow this was ok by MyPy, then please ignore this PR.
BTW, `Partial` is brilliant! Typescript has a similar idea:
```typescript
type Partial<T> = {
[P in keyof T]?: T[P];
};
```
It's unfortunate Python can't express it in …
> fix: proper Partial typing

- starlite/openapi/path_item.py
Make operation names in redoc more human friendly by converting underscores to spaces and title-casing the words.
> feat: normalize operation names to human friendly format

- .pre-commit-config.yaml
- tests/app/test_middleware_handling.py
A failing test addition for accessing Request body in the middleware.
And a version bump of `black` to pass pre-commit ([related black issue](https://github.com/psf/black/issues/2964)).
> Add a test for hanging body logging middleware

- poetry.lock
- pyproject.toml
- starlite/app.py
- starlite/response.py
- tests/app/test_middleware_handling.py
Currently middlewares provided by user are called in reverse order, my changes make them to be called in order provided by user.
Also changed addition of `TrustedHostMiddleware` and `CORSMiddleware` so that they called before custom middlewares.
> changed middleware call order

- starlite/openapi/parameters.py
- tests/kwargs/test_multipart_data.py
- tests/openapi/utils.py
- Fixes an issue where parameters are generated in OpenAPI schema for keyword arguments which are marked as "reserved keywords".
> Skip reserved keywords in parameter generation for OpenAPI schema

- starlite/types.py
- tests/test_guards.py
The issue:
When defining a guard function, its type should be [Guard](https://github.com/starlite-api/starlite/blob/13cdae1324c107f2bdf1683e08b273fe4e8a0927/starlite/types.py#L56-L58). That means that the first argument is of type `starlette.requests.HTTPConnection`. So when a guard function is defined that has the first argument of type `starlite.Request` - a subclass of `HTTPConnection` (similar to what is showcased [in the documentation](https://starlite-api.github.io/starlite/usage/9-guards/)), a typing error is raised by type checkers because that function type is actually a supertype of `Guard` (the arguments that the function accepts are more specific than the ones of `Guard` type).
This behaviour can be replicated by replacing request type `HTTPConnection` with `starlite.Request` …
> Add a bound type for the guard type to fix invalid type issue

- starlite/dto.py
- tests/test_dto_factory.py
- fields in `DTOFactory.__call__()` either come from a pydantic model, a dataclass or a plugin
- where fields come from a plugin, they most likely come from a model built with `create_model()`, and no-default defined with `...`
This patch uses `...` as well as `PydanticUndefined` to check whether a field has a default value.
> DTOFactory.__call__(): `...` equivalent to `PydanticUndefined` in checking for default

- starlite/dto.py
- tests/test_dto_factory.py
Where a field is neither excluded, nor mapped the least surprising thing would be that the field stays the same.
This PR puts the key, value pair `field_name` and `(field_type, model_field.field_info)` into the `field_definitions` dict which is later unpacked into `Pydantic.create_model()`.
> Pass `FieldInfo` straight through to `create_model()` if no need to change

- docs/usage/1-routers-and-controllers.md
- docs/usage/12-openapi.md
- mypy.ini
- starlite/openapi/utils.py
- tests/openapi/test_tags.py
PR #89 added the `tags` slot to `Router` in ef02e8e015b1f42e3390073f0785305a4a1c5838, but `openapi.utils.extract_tags_from_route_handler()` only checks the handler and it's immediate owner (from 7e5610825377c8299845d4429bf669a9ca667d78).
This implementation returns the union of the route handler's tags, and any ancestor tags.
I also made a few changes to the docs:
- `docs/usage/12-openapi.md` - `tags` documented as accepting `Tag` objects but is typed as `Optional[List[str]]`.
- `docs/usage/1-routers-and-controllers` - add `tags` to controller class variables.
- `docs/usage/1-routers-and-controllers` - add `tags` to router kwargs.
> Fix `Router.tags` ignored.

- starlite/openapi/parameters.py
- tests/openapi/test_schema.py
Instead of simply ignoring dependencies that are mentioned in the method definition, this change resolves them and adds the dependency's parameters to the schema. IMHO this behavior makes more sense, as any time a dependency is active, its own path/header/query parameters are taken into account when invoking the endpoint, so they should also show up in the OpenAPI schema.
Since this is my first PR for this project i'm not a 100% on all the things I need to do to upstream something (nor am I that familiar with the codebase), so this is a tentative start to test the waters and to gauge whether this even makes any sense.
> Take resolved dependencies into account when generating OpenAPI schema

- starlite/openapi/parameters.py
- tests/openapi/test_parameters.py
Ignores duplicate parameters that are equal in name and type.
Raises ImproperlyConfiguredException for duplicate parameters that differ in type.
For #127
> Selective deduplication of openapi parameters.

- mypy.ini
- poetry.lock
- tests/app/test_middleware_handling.py
- tests/handlers/http/test_defaults.py
- tests/handlers/http/test_kwarg_handling.py
- tests/handlers/http/test_sync.py
- tests/handlers/http/test_to_response.py
- tests/handlers/http/test_validations.py
- tests/kwargs/test_cookie_params.py
- tests/kwargs/test_header_params.py
- tests/kwargs/test_multipart_data.py
- tests/kwargs/test_path_params.py
- tests/kwargs/test_query_params.py
- tests/kwargs/test_reserved_kwargs_injection.py
- tests/kwargs/test_validations.py
- tests/openapi/test_constrained_fields.py
- tests/plugins/sql_alchemy_plugin/__init__.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_plugin_integration.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_table_types.py
- tests/response/test_serialization.py
- tests/route/test_validations.py
- tests/test_connection_lifecycle_hooks.py
- tests/test_controller.py
- tests/test_dto_factory.py
- tests/test_exceptions.py
- tests/test_path_resolution.py
- tests/test_provide.py
- tests/test_response_class.py
- tests/test_testing.py
- tests/utils/test_url.py
Allows to remove many `# type:ignore...`s.
> Disable `disallow_untyped_decorators` mypy directive for test suite.

- poetry.lock
- starlite/provide.py
- tests/test_provide.py
Fix for #142 where `Provide` wasn't working for `@classmethod`s.
Adds tests for each type of callable that might be given to provide.
> Fix `Provide` for `@classmethod`

- docs/usage/14-testing.md
In this PR I added mini-tutorial for using pydantic-factories in tests.
Also corrected markup and made subtitles on Testing page more consistent.
Fixes #143
> Add pydantic-factories testing examples

- starlite/response.py
- tests/handlers/http/test_delete.py
Where a handler returns `None` and the status is 204 we assume the response content should be empty, `b''` rather than JSON `null`.
> Empty response content for 204 status and `None` handler return value

- .gitignore
`site/` directory created by `mkdocs build`
> Add `site/` to `.gitignore`

- .pre-commit-config.yaml
- docs/usage/0-the-starlite-app.md
- docs/usage/1-routers-and-controllers.md
- docs/usage/2-route-handlers/1_http_route_handlers.md
- starlite/app.py
- starlite/controller.py
- starlite/handlers/http.py
- starlite/openapi/utils.py
- starlite/router.py
- starlite/routes.py
- starlite/utils/exception.py
- tests/test_exception_handlers.py
- tests/utils/test_exceptions.py
This PR updates exception handling by allowing users to define exception handlers on the `Router`, `Controller` or `HTTPRouteHandler` (e.g. `get`, `delete` etc.). This closes #159.
I decided to restrict this to http route handlers because both `@websocket` and `@asgi` do not fall into the same kind of category.
Please let me know what you think of the implementation.
> Issue 159 exception handlers

- starlite/handlers/asgi.py
- starlite/handlers/base.py
- starlite/handlers/http.py
- starlite/handlers/websocket.py
- starlite/provide.py
- starlite/routes.py
- starlite/utils/__init__.py
- starlite/utils/helpers.py
- tests/test_utils.py
`is_async_callable()` is a replacement for `iscoroutinefunction()` that detects more cases and handles partial objects.
> Adds `utils.is_async_callable()` `tests.test_utils` module.

- starlite/app.py
- starlite/openapi/responses.py
- tests/app/test_error_handling.py
- tests/test_template.py
Fixes #167 by adding `status_code` to the response body when dealing with exceptions in the default exception handler.
> Conform exceptions to the existing OpenAPI schema

- docs/usage/14-testing.md
- poetry.lock
- pyproject.toml
- starlite/__init__.py
- starlite/testing.py
- tests/test_imports.py
Closes #130
```py
>>> from starlite import Starlite
>>> Starlite
<class 'starlite.app.Starlite'>
>>> from starlite import TestClient
...
MissingDependencyException: To use starlite.testing, install starlite with 'testing' extra, e.g. `pip install starlite[testing]`
```
> Import testing dynamically, install requests as extra dependency

- starlite/testing.py
- tests/app/test_lifecycle.py
- tests/kwargs/test_reserved_kwargs_injection.py
- tests/openapi/test_integration.py
- tests/openapi/test_schema.py
- tests/test_caching.py
- types our `TestClient` such that it should support subclassing downstream.
- remove redundant casts and ignores from our own source.
Closes #182
> Override `TestClient.__enter__()` to support downstream typing.

- starlite/app.py
- starlite/signature.py
- starlite/utils/dependency.py
- tests/handlers/http/test_to_response.py
- tests/openapi/test_parameters.py
- tests/test_signature.py
- Should be no logical changes.
- Breaks out detailed logic into methods.
- High-level business logic in `.model()` method.
- Added a type to hold interesting properties of the parameters as we iterate over them.
- Docstrings everywhere.
> Refactor of `model_function_signature()` to address complexity limits.

- starlite/routes.py
- tests/kwargs/test_path_params.py
Fixes #204 
Proposed changes to handling duplicate / repeated path parameters in routes.  Raises `ImproperlyConfiguredException` while building the kwargs model for the route that contains the repeated params.
> Raise exception on routes with duplicate path parameters (#204)

- starlite/handlers/http.py
- tests/handlers/http/test_to_response.py
simple refactor which was mentioned as needed by #203 
i've run sonar locally and it doesn't scream anymore on that function
i've extracted the first and outermost `if` since it had the biggest `ifs` battery but i don't think the second one -data that is not starlite-like- should be also extracted, but i will  if you think i should
> Extract `HTTPRouteHandler.to_response`'s ifs battery and after_request hook into two different methods

- starlite/app.py
- tests/test_path_resolution.py
This PR addresses two edge cases that were unhandled and not covered by tests.
1. Route resolution within `construct_route_map()` was affected by the order in which paths were given to a route handler. Specifically, if the root path, `/`, was added to `route_map` after parameters paths had already been added (nested under the `/` key in `route_map`), these paths would be lost.
2. Paths with conflicting parameters were allowed, leading to undefined behavior.  This undefined behavior results from paths with conflicting params (see example test) creating a difference between the `expected_path_parameters` for a route and the actual path parameters that exist in a requested path.
```python
def test_conflicting_paths() -> None:
@get(path=["/foo/{a:int}/{b:int}", "/foo/{c:int}/{d:int}"], …
```
> Route path edge case handling

- README.md
The all-contributors badge currently doesn't render in the github interface. This PR fixes that.
Also introduced a logo variable to make it easy to inline the badge if you ever want to move it down.
> Make the all-contributors badge render

- starlite/routes.py
- tests/kwargs/test_path_params.py
- Adds more test cases for path parameter validation.
- Splits out parameter validation logic from `parse_path`, creating new `validate_path_parameters` method, and adds checks for new test cases within this method.
> Improve path param validation during registration

- starlite/app.py
- tests/middleware/test_exception_handler_middleware.py
Exception handlers provided as parameter to `Starlite` were not getting forwarded to `Router.__init__()`.
`Router.__init__()` triggers `Starlite.construct_route_map()` via calls to `self.register()`.
`construct_route_map()` builds the middleware stack which adds the exc handling middleware, which was occurring before the exception handlers are set to `self.exception_handlers` on the `Starlite` instance.
Fix passes `exception_handlers` to `Router.__init__()`.
> Fixes route exception handler resolution.

- starlite/app.py
Addresses #203 
- Quick refactor of `construct_route_map` that extracts the logic into three separate methods.
- Fixes the sonar issue related to code complexity.
- Only real logic change is checking for conflicting path parameters (e.g. /foo/{a:int} vs /foo/{b:int}) by comparing the preexisting `_path_parameters` key on the terminating trie node of a route path to the `route.path_parameters` attribute on the route being added to the trie.  Previously used a set of previously seen paths.
Clearly there's more that can be done here, but still more context to learn before I attempt deeper changes! 
Seems to be an opportunity to take a class-based approach whereby we have a RouteMap and PathSegmentNode's that could simplify some of this logic, but I'm not sure it's worth doing given that the …
> Refactor `Starlite.construct_route_map`

- tests/test_path_resolution.py
Vscode test discovery caches the test case names including parametrized values.
The behavior makes having dynamic `uuid4()` calls in the parametrized test cases an issue as vscode shows test case failures when the test case names that it previously resolved cannot be found.
The change doesn't affect the utility of the test, so better to fix the case for vscode users so we don't get the same issue reported in the future.
> Removes `uuid4()` from within parametrized test cases.

- tests/route/test_route_map.py
This fixes the acute issue raised in #275.   I would also love to hear any tips on forcing hypothesis to run a strategy continuously locally in order to find problems like these ahead of time.  I like the library, but it seems to fight you (even if just from a performance standpoint) if you want to run large test sets.
> Fix route-map path existence test logic (#275)

- starlite/exceptions.py
- tests/test_exceptions.py
This PR addresses #188 by calling `super().__init__(...)` in the exception constructors, and handling *args and **kwargs.
> Issue 188: resolve exceptions swallowing args

- starlite/kwargs.py
- starlite/parsers.py
- tests/kwargs/test_query_params.py
- tests/test_parsers.py
Resolves #255 
Query parameters declared as `List[T]` will be parsed in as arrays even if they only have one element.
> Issue #255: allow single element query param in sequence types

- .gitignore
- CONTRIBUTING.md
- starlite/openapi/parameters.py
- tox.ini
once again a simple refactor which was mentioned as needed by https://github.com/starlite-api/starlite/issues/203 and fixes [this](https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&id=starlite-api_starlite&open=AYH3kLXqoMi-EPUvUENi)
the first filter, which extracts params that are `not in layered_parameters`, had its logic moved to a method called `_get_unlayered_params` but i'm not sure if it's the best naming decision
> Split `openapi.create_paramter_for_handler` into several methods to reduce complexity

- starlite/openapi/controller.py
As per #300, this adds basic support for SwaggerUI by monkey-patch-downgrading the version to one that is not instantly rejected by the default SwaggerUI bundle. This is valid because 3.1 support for SwaggerUI is largely blocked by the newly-introduced JSON schema support, which we don't use in Starlite (it's all YAML). More info in the tracking issue [here](https://github.com/swagger-api/swagger-ui/issues/5891).
Other than that I tried to stick as close as possible to the ReDoc implementation, leaving out things like extra config values or OAuth support to be added at a later time.
One thing that may be slightly weird for developers using this functionality is the route where this is currently served at `/schema/swagger`. Since `/schema` is already taken by ReDoc (and I assume we can't …
> Support for SwaggerUI

- tests/openapi/test_openapi_ui.py
Tests for #303 / #302
These tests check whether the UI handlers:
- don't throw an Exception
- return 200 OK
- return HTML of some form
> Add basic sanity check tests for ReDoc and Swagger UI routes

- docs/usage/11-data-transfer-objects.md
- starlite/types.py
- tests/test_types.py
> Allow Partial to annotate fields of nested classes

- docs/usage/12-openapi.md
- starlite/app.py
- starlite/config.py
- starlite/openapi/controller.py
- starlite/openapi/path_item.py
- tests/openapi/test_path_item.py
- tests/openapi/utils.py
Adds ability to configure openapi schema generation to use the route handler docstring for operation description.
If `False` docstrings are ignored, this is default behavior for backward compatibility.
If `True`, `HTTPRouteHandler.description` takes precedence if set, otherwise the docstring is used.
> OpenAPIConfig.use_handler_docstrings

- extensions/rust/Cargo.toml
- poetry.lock
- starlite/app.py
Fixes some issues with the current state of the Rust bindings. Testing can now be run as described here: https://github.com/starlite-api/starlite/pull/270#issuecomment-1190713507, but with a small change:
What was previously (under my own system directories)
```
env PYTHONPATH="/Users/haxi/Documents/code/starlite/nramos-starlite/.venv/lib/python3.10/site-packages" cargo test --no-default-features
```
should be changed to 
```
env PYTHONPATH="/Users/haxi/Documents/code/starlite/nramos-starlite/.venv/lib/python3.10/site-packages" cargo test --no-default-features -F auto-initialize
```
PyO3's auto-initialize feature also needs to be behind a feature flag in our own crate that is off by default, otherwise building it for those that don't want to run tests (ex. normal Starlite users) won't be …
> Fix issues with Rust route map bindings

- docs/usage/0-the-starlite-app/0-the-starlite-app.md
- docs/usage/1-routing/2-routers.md
- docs/usage/1-routing/3-controllers.md
- docs/usage/2-route-handlers/1_http_route_handlers.md
- docs/usage/7-middleware.md
The existing links to the `17-exceptions` page are currently broken. This PR fixes them
> Docs - fix link to `exception-handlers`

- starlite/utils/url.py
- tests/utils/test_url.py
`normalize_path` is supposed to make sure the path does not end in a
slash, but it only removes the last character if it is a slash.
Additionally, replace all strings of 2+ slashes with a single slash in
one pass, rather than replacing groups of two iteratively
> Remove all trailing slashes when normalizing paths

- .docker/Dockerfile
- CONTRIBUTING.md
- docker-compose.yaml
- docs/reference/connection.md
- docs/reference/datastructures.md
- docs/reference/enums.md
- docs/reference/types.md
- poetry.lock
- pyproject.toml
- starlite/app.py
- starlite/connection.py
- starlite/datastructures.py
- starlite/handlers/http.py
- starlite/middleware/csrf.py
- starlite/response.py
- tests/connection/websocket/test_websocket.py
- tests/handlers/http/test_to_response.py
This is a followup PR that cleans the `to_response` method and implements @peterschutt's suggestions for datastructures.  I additionally add some docs and a docker compose setup to run the docs locally (didnt work due to plugins).
You'll note i removed the `validate_arguements` from the respone classes. This was causing a lot of problems with typing, and it additionally hurts performance I think.
> Update `to_response` and datastructures

- starlite/app.py
- tests/static_files/test_static_files.py
This avoids re-adding routes which are already in the route map.
Before, every route would be re-added on each call to `construct_route_map` (which is called on each call to `register`). `register` was called once per route handler in `Router.__init__`, once for the openapi handler (if configured), and once per static files configuration, as well as whenever a new route is registered outside the `__init__` call. Instead, this keeps a set of routes which have already been added to the route_map, and avoids re-adding them when calling `construct_route_map`
This also avoids a bug when `register` is called after a static path has been registered (when more than one static path is registered, or `.register` is called to add an additional handler), where `ImproperlyConfiguredException` with …
> Only add new routes to the route_map

- CONTRIBUTING.md
- docs/reference/exceptions.md
- starlite/asgi.py
- starlite/exceptions/exceptions.py
- starlite/exceptions/utils.py
- Removes `**kwargs` from `StarLiteException.__init__()` - `Exception.__init__()` doesn't accept kwargs
- Removes `**kwargs` downstream from `StarLiteException`
- docsstrings and include in reference docs.
- small tidyup in `asgi.py`
For #341
> Exceptions tidy up and docs

- README.md
- docs/index.md
- docs/usage/1-routing/3-controllers.md
- docs/usage/5-responses/2-status-codes.md
- poetry.lock
- starlite/handlers/http.py
- starlite/response.py
- tests/handlers/http/test_delete.py
- tests/handlers/http/test_validations.py
- tests/test_controller.py
This PR updates the handling of 204, 304 and <100 status codes by raising an exception when route handlers specify a route annotation. It also updates the serialization to return a 0 length byte string, which will prevent uvicorn from raising an issue.
See: https://github.com/encode/starlette/issues/1764 for context.
> Update handling of status code <100, 204 or 304

- docs/usage/12-openapi.md
- starlite/openapi/controller.py
- tests/openapi/test_controller.py
Issue #356.
This PR splits `redoc` and the base path/root handlers. The `root` handler serves the original `redoc` content, but enables easier overriding of the rendering and routing on the `OpenAPIController`.
- separate UI rendering and routing
- add routed `root` method
- separate testing of `/` and `redoc`
-  add `root` override example
> Separate OpenAPIController routes and rendering

- docs/reference/datastructures.md
- docs/usage/4-request-data/3-multipart-form-data.md
- docs/usage/5-responses/8-streaming-responses.md
- starlite/__init__.py
- starlite/datastructures.py
- starlite/openapi/schema.py
- starlite/parsers.py
- tests/handlers/http/test_to_response.py
- tests/kwargs/test_multipart_data.py
- tests/openapi/test_request_body.py
This PR fixes `Stream` not handling callables correctly and being mistyped.
Resolves #361
> Issue-#361: Fix stream 'iterator' typing

- docs/usage/1-routing/4-registering-components-multiple-times.md
Fixed some typos in the routing docs.
> Docs typo fix in `4-registering-components-multiple-times.md`

- starlite/app.py
- starlite/asgi.py
- starlite/routes/base.py
- starlite/utils/url.py
- tests/route/test_route_map.py
- tests/test_path_resolution.py
- Instead of using "*" as the key in the route map for path params, use a sentinel object which will never be equal to any other value
- When creating routes, parse the route path into a sequence of strings and parameter definitions. Re-use this when building the route map instead of parsing the path again.
- Allow starlite.utils.url.join_paths to accept an iterable of strings.
This should fix some of the issues in #373. In another PR I will look at making a proper class for route map nodes, so that their config can use slots and not share the same dict key space as path components.
> Fix bugs involving "*" and path params in routes

- CONTRIBUTING.md
The contributing docs [here](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.md#testing-multiple-python-versions) say to run `poetry install --extra testing`, but outputs this error after being run: `The "--extra" option does not exist.`
I believe it needs to be changed to `poetry install --extras testing`.
> Fixed poetry option typo in `CONTRIBUTING.md`

- starlite/exceptions/exceptions.py
- tests/test_exceptions.py
Fixes where calling `str` on an `HTTPException` would cause a duplicated error message, e.g.,:
> starlite.exceptions.exceptions.ImproperlyConfiguredException: 500: Provider for key first is already defined under the different key third. If you wish to override a provider, it must have the same key. Provider for key first is already defined under the different key third. If you wish to override a provider, it must have the same key.
> Fix for duplicated detail in http exception str

- starlite/handlers/http.py
- starlite/utils/predicates.py
- starlite/utils/sync.py
- makes `utils.predicates.is_async_callable()` a type guard
- makes `AsyncCallable` generic on `P` and `T`.
I've been able to remove all the type ignores except for the `partial()` assignment one.
> Changes for improved typing in `AsyncCallable`.

- starlite/params.py
As per https://github.com/pydantic/pydantic/issues/4253 (change in https://github.com/pydantic/pydantic/pull/4252) an empty alias `''` is now treated differently from `None` - e.g. no alias.
Therefore for starlite to be be compatible with pydantic v1.10, we need to remove these empty alias values.
This should be backwards compatible with earlier versions of pydantic since until v.10 an empty alias was treated as identical to `''`.
> remove empty aliases

- starlite/handlers/http.py
This is in prep for `v3.0.3` to be removed from pydantic-openapi-schema.
> Removes import from pydantic-openapi-schema `v3_0_3` subpackage.

- poetry.lock
- starlite/app.py
- starlite/asgi.py
- starlite/routes/base.py
- tests/kwargs/test_path_params.py
- tests/routing/test_route_map.py
- [wip] Have you updated the prose documentation?
- [wip] Have you updated the reference documentation?
This PR resolves #371. It updates the supported types of path parameters, to include the following:
```python
param_type_map = {
"str": str,
"int": int,
"float": float,
"uuid": UUID,
"decimal": Decimal,
"date": date,
"datetime": datetime,
"time": time,
"timedelta": timedelta,
"path": Path,
}
```
All of them except `Path` have been previously supported, but not in a verbose way, so its just a bit of UX improvement there.
The type `Path` though was more complex. What it does is regard the path from the point at which the parameter is declared to be a value. Example:
```python
def test_path_param_type_resolution() -> None:
@get("/some/test/path/{my_param:path}")
def handler(my_param: Path) …
```
> Issue 371 add path type query parameter

- docs/reference/middleware.md
- docs/usage/7-middleware/2-creating-middleware/2-using-middleware-protocol.md
- poetry.lock
- starlite/handlers/http.py
- starlite/middleware/base.py
- starlite/plugins/base.py
- starlite/plugins/tortoise_orm.py
- starlite/provide.py
Changes `**kwargs: Dict[str, Any]` to `**kwargs: Any` in `MiddlewareProtocol.__init__()` signature.
---
> Fixes annotation of `**kwargs` across the library

- .github/workflows/publish.yaml
Action was failing due to there being no independent job in the workflow.
> Removes `needs: validate` dependency from `test_minimal_app`.

- starlite/plugins/sql_alchemy.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_table_types.py
The Sybase and Firebird have been removed from the default SQL alchemy dialects in the 2.0 branch causing the plugin to fail when loading.
Given that the amount of usage for Sybase and Firebase is very small (and probably zero overlap with Starlite users), this PR removes this from Starlite.
> Enhancement: Remove Firebird and Sybase for SQL Alchemy 2.0 support

- starlite/datastructures.py
- starlite/handlers/http.py
- tests/response/test_serialization.py
Support setting `media_type` on `ResponseContainer`.
A specific use-case is returning files where the media type is unknown at time of route handler definition.
Closes #482
> Issue #482 set media type on response container

- tests/middleware/test_rate_limit.py
Increases the limit duration so no chance of crossing the duration boundary mid-test.
Closes #500
> Fix for flaky test where rate limiter failed to fire when expected.

- .github/workflows/ci.yaml
- CONTRIBUTING.md
This avoids warnings from temp files created in project root during test.
Closes #503
> Specify specific dirs for test cov.

- starlite/kwargs.py
- starlite/parsers.py
- starlite/router.py
- starlite/types/__init__.py
- starlite/types/internal_types.py
- starlite/typing.py
- tests/kwargs/test_layered_params.py
- tests/test_parsers.py
This PR reduces the cognitive complexity as flagged by SonarCloud (see #203) in the following modules:
- typing.py
- router.py
- parsers.py
- kwargs.py
> Reduce cognitive complexity

- .github/workflows/ci.yaml
Added a cache key prefix so that caches can be manually invalidated where necessary (the alternative is to use the GitHub REST API, but this could be quicker)
Also added some restore-keys so that we can fall back to older caches to speed up poetry installs (the poetry install command will still be run in these cases)
> Add CI cache versioning and restore-keys

- starlite/config/logging.py
- tests/logging_config/test_logging.py
- tests/logging_config/test_picologging.py
This PR does some cleanup in the logging configs and improves the init of the handlers - so picologging is initialized properly on default.
> Cleanup logging config and fix default handlers

- docs/usage/14-testing.md
- starlite/testing.py
- tests/__init__.py
- tests/test_parsers.py
- tests/test_signature.py
- tests/test_testing.py
- Refactor `create_test_request` to use `RequestFactory`
- Add `scheme` to `RequestFactory` (which was missing in the previous PR)
- Change all internal uses of `create_test_request` to use `RequestFactory`
> Refactor `create_test_request` to use `RequestFactory`

- docs/reference/config.md
- docs/reference/types.md
- docs/usage/0-the-starlite-app/6-application-init-hook.md
- examples/application_hooks/on_app_init.py
- examples/tests/application_hooks/test_on_app_init.py
- mkdocs.yml
- poetry.lock
- starlite/app.py
- starlite/config/__init__.py
- starlite/config/app.py
- starlite/router.py
- starlite/types/__init__.py
- starlite/types/callable_types.py
- tests/app/test_app_config.py
- The `Plugin.on_app_init()` callback occurs before route handler registration, so plugins do not 
have the opportunity to receive the handlers passed to the application before they are applied to 
the app.
- Certain application attributes have pre-processing applied to them on assignment to self. 
Therefore, if a plugin wants to manage or modify these attributes, the plugins need to perform this
step of pre-processing, or at least understand it, before they can operate on these configuraion 
attributes. E.g., `as_async_callable_list()`.
- Difficult to be confident in longevity of implementations. Simple things like order of 
configuration/attribute changes, or changes to wrapper objects in later releases may impact the way 
plugins need to work to operate on certain configuration values. …
> Feature: Implements `on_app_init` hook

- starlite/utils/url.py
- tests/utils/test_url.py
Hello there ! 
This is a small contribution, I was planning on working on #406, but when browsing the code I saw an opportunity to make a small improvement on a function (`normalize_path` )  that seems to be called often. 
Here's the script I used to compared the speed, I dumped the output each time and put it in the comment.
There's a ~7.5% improvement speed.
```python
import re
def normalize_path(path: str) -> str:
"""Normalizes a given path by ensuring it starts with a slash and does not
end with a slash.
Args:
path: Path string
Returns:
Path string
"""
path = path.rstrip("/")
if not path.startswith("/"):
path = "/" + path
path = re.sub("//+", "/", path)
return path
def new_normalize_path(path: str) -> str:
"""Normalizes a given path by ensuring it starts with a slash and does not
end …
```
> Improve `normalize_path` function speed

- docs/usage/10-plugins/2-tortoise-orm-plugin.md
At the moment example on Tortoise ORM plugin doesn't work properly as it doesn't close db connections on app shutdown.
Tortoise ORM states that it is [very important to do clean up](https://tortoise.github.io/setup.html?h=close_connections#the-importance-of-cleaning-up) or otherwise there will be problems with program termination. Indeed, when you try to run the example under uvicorn it will hang on Ctrl-C (see screenshot) forcing user to kill the program.
You can check yourself with the following piece (I simply added `uvicorn.run` to the example code) with python test.py
<details>
<summary>test.py</summary>
```
import uvicorn
from typing import cast
from tortoise import Model, Tortoise, fields
from tortoise.connection import connections
from starlite import Starlite, get, post
from …
```
> Proper clean up in Tortoise ORM plugin example

- poetry.lock
- pyproject.toml
Starlette 0.21 requires httpx 0.22+, and we depend on both.
> Pin starlette to `>=0.21` and httpx to `>=0.22`.

- docs/usage/8-authentication/1-abstract-authentication-middleware.md
In [the docs](https://starlite-api.github.io/starlite/usage/8-authentication/1-abstract-authentication-middleware/#starlite.middleware.session.SessionCookieConfig.secure), there is a typo for the keyword arguments passed into `AbstractAuthenticationMiddleware`. This PR corrects the typo.
> Small typo fix

- README.md
- starlite/plugins/sql_alchemy/plugin.py
Makes detection of declarative model types and instances compatible with 1.x and 2.0.
Closes #548
> Updates SQLAlchemy plugin type detection.

- docs/reference/config/0-app-config.md
- docs/reference/connection/0-asgi-connection.md
- docs/reference/connection/1-request.md
- docs/reference/connection/2-websocket.md
- starlite/app.py
- starlite/config/app.py
- starlite/connection/base.py
- starlite/connection/request.py
- starlite/connection/websocket.py
- starlite/middleware/csrf.py
- starlite/middleware/logging.py
- starlite/middleware/rate_limit.py
- starlite/routes/http.py
- starlite/routes/websocket.py
- starlite/testing/test_client.py
- tests/app/test_app_config.py
- tests/connection/request/test_request.py
- tests/connection/test_base_properties.py
- tests/connection/websocket/test_websocket.py
This PR adds support for using custom subclasses of `Request` and `WebSocket` in the application by passing these to the Starlite constructor. It forms a solid basis for extension further via plugins. For example, consider an `SQLAlchemyRequest` class that has properties to access the session etc.
> Add support for using custom `Request` and `WebSocket` classes.

- starlite/plugins/sql_alchemy/config.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_config.py
- tests/plugins/sql_alchemy_plugin/test_sqlalchemy_plugin.py
- tests/test_testing.py
One of either `connection_string` or `engine_instance` must be set.
Adds some tests for #549.
Closes #555
> Makes SQLAlchemyConfig.connection_string optional.

- starlite/connection/base.py
- starlite/middleware/session.py
If in case a user wants to add new keys to session after clearing it, its default value should be an empty dictionary.
> Clear Session Should Assign Empty Dict

- docs/usage/14-testing.md
Testing docs were missing a quote and thus did not render a code block correctly.
> Add missing quotes to testing docs

- docs/reference/openapi/0-openapi-controller.md
- docs/usage/12-openapi/3-openapi-controller.md
- starlite/openapi/controller.py
- tests/openapi/test_controller.py
i was working on migrating a project from fastapi to starlite and was missing this function
it is inspired on how FastAPI handles the offline usage for the OpenAPI pages.
specifally inspired of the following from FastAPI.
functions:
get_swagger_ui_html
get_redoc_html
google_font:
https://github.com/tiangolo/fastapi/pull/481
*full transparency. im a self learned "programmer" so if something is incorrect bear with me*
> OpenAPI (redoc/swagger/spotlight elements) usage in environments that cant access CDN's

- docs/usage/2-route-handlers/4-route-handler-indexing.md
- tests/routing/test_route_indexing.py
This PR updates docs about default name for route handlers.
Also noticed that test for default handler name is a bit inconsistent trying to use `handler.name` first. I highly doubt that there will be some changes affecting `name` property but anyway lets keep tests straightforward
> Fix docs about default name for route handlers in HandlerIndex

- starlite/openapi/schema.py
- starlite/plugins/sql_alchemy/plugin.py
- tests/kwargs/test_multipart_data.py
I am experimenting a lot now and failing mypy checks/tests are so irritating so I decided to fix them at least locally. If you've already fixed it in your code then close the PR.
Due to recent change signature change of `ModelFactory.is_constrained_field` (went from `bool` to `TypeGuard`) in pydantic-factories mypy was able to pickup that `is_constrained_field` actually has been returning true for `ConstrainedFrozenSet` for almost a year :-) while union in the appropriate type annotation in Starlite didn't include it.
Also, test is fixed which is now failing due to changes in starlite-multipart. I went and fixed the test itself since according to RFCS (https://www.rfc-editor.org/rfc/rfc7230#section-3.2 and https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2 ) header names are case …
> Fix mypy and tests failure

- README.md
- docs/index.md
- docs/usage/1-routing/3-controllers.md
- docs/usage/5-responses/2-status-codes.md
- poetry.lock
- pyproject.toml
- starlite/handlers/http.py
- starlite/response.py
- tests/handlers/http/test_delete.py
> Fix `NoReturn` as allowed return typing for `delete` decorators

- poetry.lock
- starlite/openapi/schema.py
- tests/openapi/test_constrained_fields.py
- tests/openapi/utils.py
This PR adds support for `ConstrainedDate` in OA schema generation
> Add support for ConstrainedDate in OpenAPI schema generation

- starlite/config/logging.py
- starlite/logging/picologging.py
- starlite/logging/standard.py
Removes logging to `StringIO` and removes `console` handler as handler to `root` logger.
Closes #593
> QueueListenerHandler log to stderr by default.

- starlite/signature.py
- starlite/utils/dependency.py
- tests/test_dependency.py
Where a parameter is marked as a dependency with `Dependency` function and also provided a default value, the handler was receiving `Ellipsis` as the value for the parameter.
This change ensures that the signature model respects the default value provided for the parameter.
Closes #592
> Fix signature model for dependency with skip_validaiton and default.

- docs/reference/1-app.md
- docs/reference/config/6-static-files-config.md
- docs/reference/connection/0-asgi-connection.md
- docs/usage/0-the-starlite-app/3-static-files.md
- docs/usage/16-templating/0-template-engines.md
- docs/usage/16-templating/2-template-functions.md
- starlite/app.py
- starlite/config/static_files.py
- starlite/connection/base.py
- starlite/template/base.py
- starlite/template/jinja.py
- starlite/template/mako.py
- tests/connection/request/test_request.py
- tests/routing/test_asset_url_path.py
- tests/routing/test_route_indexing.py
- tests/template/test_builtin_functions.py
This PR adds:
* `name` kwarg to `StaticFilesConfig` which has the same behavior as `name` kwarg in route handlers;
* `app.asset_url_path` to generate url paths to files under given `StaticFiles`.
* `request.asset_url` to generate absolute urls to files.
* `asset_url_path` function for templates
Sample piece of code
```python
from starlite import Starlite, StaticFilesConfig
app = Starlite(
route_handlers=[...],
static_files_config=[
StaticFilesConfig(
directories=["static"], path="/complex/static/path", name="static"
),
],
)
url_path = app.asset_url_path("static", "file.pdf")
```
First I was thinking about extending `app.route_reverse` function since its internal behavior is similar but decided to create a separate function because `route_reverse` interface would have to be extended making …
> Add url_for_static_asset to app and templates

- starlite/router.py
- starlite/types/callable_types.py
- starlite/utils/exception.py
This allows handlers to be registered that receive sub classes of `Exception` without type error.
Closes #619
> Use TypeVar for ExceptionHandler exception parameter.

- docs/css/extra.css
I am using dark theme for docs and seeing admonition blocks (notes/hints) is simply painful for my eyes :-)
Before
After
> Fix admonition for dark theme in docs

- docs/css/extra.css
Let me know if you like the idea and the new colours.
> docs: reduce contrast in light mode code blocks

- CONTRIBUTING.md
I was reading the contribution guidelines and I did not find a mention of how to
add the examples to the Docs, as mentioned in #343. Let me know if this is the
correct place to put this information.
-------
> docs: mention self contained examples as per #343

- starlite/middleware/rate_limit.py
- tests/middleware/test_rate_limit.py
The test was randomly failing because it was time sensitive. Adding `freeze_time` should solve it.
Also - in the rate limit middleware cache expiration was not set so any unit of more than 60 seconds would not work correctly.
> Issue #611 - Fix randomly failing rate limit test + bugfix

- starlite/app.py
- starlite/asgi.py
- starlite/cache/base.py
- starlite/cache/simple_cache_backend.py
- starlite/connection/base.py
- starlite/connection/websocket.py
- starlite/exceptions/http_exceptions.py
- starlite/middleware/exceptions.py
- starlite/openapi/path_item.py
- starlite/openapi/responses.py
- starlite/parsers.py
- starlite/response/base.py
- starlite/routes/asgi.py
- starlite/routes/http.py
- starlite/routes/websocket.py
- starlite/utils/__init__.py
- starlite/utils/exception.py
- starlite/utils/extractors.py
- starlite/utils/helpers.py
- starlite/utils/sync.py
- tests/asgi_router/test_asgi_router.py
- tests/test_parsers.py
This PR removes the dependency on Starlette to handle "lifespan" events. Its part of #612
> Update ASGI router

- docs/reference/utils/0-predicate-utils.md
- docs/reference/utils/1-sync-utils.md
- docs/usage/5-responses/11-background-tasks.md
- mkdocs.yml
- starlite/datastructures/background_tasks.py
- starlite/datastructures/provide.py
- starlite/handlers/http.py
- starlite/utils/__init__.py
- starlite/utils/predicates.py
- starlite/utils/sync.py
- tests/datastructures/test_background_task.py
- tests/test_utils.py
This PR replaces `BackgroundTask` and `BackgroundTasks` with our own implementation, including support for running in task group. It additionally moves the `AsyncCallable` in the datastructures package from utils, due to circular import issues. 
Relates to #634 and #612
> Replace background tasks

- tests/__init__.py
- tests/dto_factory/test_dto_factory_partials.py
🚨 First PR Alert 🚨
Hopefully the code I'm proposing is ok.  Feedback is very welcome.  
This pull request adds tests for a bug I opened: https://github.com/starlite-api/starlite/issues/655
Changes include:
- Extending [tests/__init__.py](https://github.com/starlite-api/starlite/compare/main...ThinksFast:starlite:test_partial_dto?expand=1#diff-001e61d97d9dee27d0c5aa1f23ba6c1972cd8a2e8320bac839656b0ab935b84d) to include a SQL Alchemy model
- Added new file [tests/dto_factory/test_dto_factory_partials.py](https://github.com/starlite-api/starlite/compare/main...ThinksFast:starlite:test_partial_dto?expand=1#diff-a2273ea7335f9bbf8a33caed2ca0c8c0fe52c4377e3edfc8f37b95bcf3086d2c), which tests the creation of `Partial[DTO]` objects using Pydantic and SQLAlchemy models.
> Tests for creation of Partial DTO's.  One test fails due to an open bug.

- docs/css/extra.css
At the moment it is very hard to use search and quoted links with light theme.
See attached video
<details><summary>light theme before</summary>
https://user-images.githubusercontent.com/153191/197404906-0d879023-b43e-40ba-8946-31256c03301f.mp4
</details>
I suggest to revert changes to background-color of links in onhover state.
<details><summary>light theme after</summary>
https://user-images.githubusercontent.com/153191/197405187-b2b2c48e-eab4-4184-81aa-388427101a57.mp4
</details>
Also I've added onhover link color change in the dark theme so it is consistent with light theme which had onhover effect.
We can pick better colors later but right now lets fix what actually makes it hard to work with the docs
> Fix link colors in the docs

- tests/response/test_streaming_response.py
anyio.Event.set() does not need to be awaited anymore after anyio 3. Since we only support anyio > 3, we can simply drop the await here.
> Drop await for anyio.Event.set (deprecated)

- starlite/testing/test_client/client.py
Pytest will try to collect `TestClient` in some circumstances. This can be prevented by adding a `__test__ = False` to the TestClient
> Add `__test__ = False` to TestClient

- .gitignore
- starlite/middleware/session/sqlalchemy_backend.py
- tests/middleware/session/test_server_backends.py
Previously some SQLAlchemy sessions in `AsyncSQLAlchemySessionBackend` weren't properly closed due to not being used as a context manager / explicitly closed. This was flaky because closing via garbage collection only works sometimes in an async context and with certain database drivers.
> Use a context-manager to handle SQLA sessions in session-backend

- docs/usage/14-testing.md
- poetry.lock
- pyproject.toml
- starlite/__init__.py
- starlite/testing/test_client/client.py
- starlite/types/__init__.py
- starlite/types/helpers.py
- tests/conftest.py
- tests/testing/test_test_client.py
- tests/testing/test_testing.py
- Removes `cryptography` as a dependency of the `testing` package-extra
- Moves `TestClient` async session-backend methods to run in `TestClient.portal` instead of `anyio.run` directly
- Ensures `TestClient` tests in `tests/testing` run with both `asyncio`and `trio` backend
> Test client cleanup

- .github/workflows/publish.yaml
- starlite/connection/base.py
- starlite/middleware/session/base.py
- starlite/testing/test_client/client.py
- tests/middleware/session/test_middleware.py
- tests/testing/test_testing.py
This changes the implementations of the session-related methods in `TestClient` to use the actual middleware by constructing fake "Scope" and "ASGIConnection" objects
> Fix transient cryptography dependency in testing.test_client.client

- starlite/testing/create_test_client.py
- starlite/testing/test_client/client.py
- tests/connection/request/test_request.py
- tests/middleware/test_logging.py
- tests/response/test_redirect_response.py
- tests/test_signature.py
- tests/testing/test_test_client.py
- tests/testing/test_testing.py
This addresses #706 by changing its base_url default from `http://testserver` to `http://testserver.local`. It also adds a check  in `TestClient` that emits a warning when a possibly problematic `base_url` is being used.
> Fix #706: Change base_url of TestClient

- docs/reference/config/0-app-config.md
- docs/reference/handlers/0-base-handler.md
- docs/usage/2-route-handlers/5-handler-opts.md
- docs/usage/5-responses/4-response-headers.md
- starlite/app.py
- starlite/config/app.py
- starlite/controller.py
- starlite/handlers/asgi.py
- starlite/handlers/base.py
- starlite/handlers/http.py
- starlite/handlers/websocket.py
- starlite/router.py
- tests/app/test_app_config.py
- tests/handlers/base/test_opt.py
Since #718 adds bypassing a middleware based on a flag in `opt` dictionary of a route handler it makes sense to apply layering for `opt` too.
> Layering for opt dictionary

- docs/usage/7-middleware/3-builtin-middlewares/6-rate-limit-middleware.md
- examples/middleware/rate_limit.py
- examples/tests/middleware/test_rate_limit_middleware.py
- starlite/__init__.py
- starlite/asgi/routing_trie/utils.py
I noticed that example on the RateLimit middleware is incorrect. Middleware should be created by accessing `middleware` property on config object.
> Fix Rate-Limit middleware example in the docs

- .github/workflows/ci.yaml
- PRs run CodeQL w/out dependencies installed.
- Push to main runs CodeQL with dependencies installed.
This makes sure we aren't waiting too long for CI on PRs but gives us a run with the full dependency tree on any code that is merged into main.
> CodeQL configuration.

- docs/usage/6-dependency-injection/3-the-provide-class.md
- starlite/datastructures/provide.py
- starlite/kwargs.py
- tests/dependency_injection/test_request_local_caching.py
This avoids executing a dependency multiple times, if it's used more than once in the dependency tree.
Still unsure about the following:
* using `request.state` for the cache
* the key `"_dependency_cache"` in general, without the leading underscore perhaps?
Basically: Should this be part of the public interface?
* is there still a use case for `use_cache`?
> Added per request caching of dependencies

- CONTRIBUTING.md
It's easier if we have one clear guideline, instead of different rules for internal vs. external code.
> Simplify docstring requirements.

- starlite/asgi/routing_trie/traversal.py
- tests/asgi_router/test_routing_trie_traversal.py
The logging middleware doesn't log if 404/405 is raised during routing, so I'm using a before send handler instead. 
If the connection data extractor is called on a connection where a 404 is raised we get the below exception.
This PR moves the setting of `scope["path_params"]` so that it exists irrespective of the result of the routing.
```python-traceback
2022-11-07 12:42:29,033 loglevel=ERROR  logger=uvicorn.error run_asgi() L412  Exception in ASGI application
File "/home/peter/.cache/pypoetry/virtualenvs/tmpl-starlite-saqlalchemy-ar_RcmG--py3.11/lib/python3.11/site-packages/starlite/middleware/exceptions.py", line 46, in __call__
await self.app(scope, receive, send)
File "/home/peter/.cache/pypoetry/virtualenvs/tmpl-starlite-saqlalchemy-ar_RcmG--py3.11 …
```
> Ensures `path_params` key always exists in scope.

- docs/reference/datastructures/7-form-multi-dict.md
- docs/reference/datastructures/7-multi-dicts.md
- mkdocs.yml
- poetry.lock
- starlite/config/cache.py
- starlite/connection/base.py
- starlite/connection/request.py
- starlite/datastructures/__init__.py
- starlite/datastructures/multi_dicts.py
- starlite/kwargs.py
- starlite/parsers.py
- starlite/utils/extractors.py
- tests/connection/request/test_request.py
- tests/connection/websocket/test_websocket.py
- tests/datastructures/test_multi_dicts.py
- tests/test_parsers.py
- tests/testing/test_testing.py
- tests/utils/test_extractors.py
This PR adds a multi dict for query params. 
It might be that this implementation will degrade performance a bit, so we need to test and see how it stacks vis-a-vis the previous one. I will run some benchmarks tomorrow to see.
> add `QueryMultiDict`

- starlite/types/protocols.py
- tests/logging_config/test_logging_config.py
This PR extends the `Logger` protocol to include overrides for `*args`.  This prevents `logger.info("%s finished",my_var)` from being reported as a typing error.
> Add `*args` override to `Logger` protocol

- starlite/openapi/path_item.py
- tests/openapi/test_path_item.py
- tests/openapi/utils.py
This PR closes #770 
Apply `inspect.cleandoc` to handler docstring when generating description for OpenAPI.
Difference can be seen in the example below.
```python
from inspect import cleandoc
def f():
"""Multiline docstring example.
Line 3.
Line 4.
"""
pass
print(f.__doc__)
print(cleandoc(f.__doc__))
```
```bash
> python test.py 
Multiline docstring example.
Line 3.
Line 4.
Multiline docstring example.
Line 3.
Line 4.
```
> Remove leading whitespaces from docstrings in OpenAPI description

- starlite/static_files/base.py
- tests/static_files/test_file_serving_resolution.py
- tests/static_files/test_html_mode.py
Passing a `filename` is required for mimetype detection, without which static files were always served with `content-type: application/octet-stream`
> Ensures `filename` parameter to `FileResponse` set for `StaticFiles` response.

- docs/reference/config/3-csrf-config.md
- docs/reference/config/4-compression-config.md
- docs/reference/middleware/3-rate-limit-middleware.md
- starlite/config/allowed_hosts.py
- starlite/config/compression.py
- starlite/middleware/authentication.py
- starlite/middleware/base.py
- starlite/middleware/csrf.py
- starlite/middleware/logging.py
- starlite/middleware/rate_limit.py
- starlite/middleware/session/base.py
- starlite/middleware/utils.py
- tests/middleware/test_logging.py
- tests/middleware/test_rate_limit.py
Here I add `exclude_opt_key` to all middlewares (logging, rate_limiting) and do some code cleanup by reusing code either from utils or AbstractMiddleware where applicable, fixing typos in docstrings and unifying parameter typing.
I need to write a few tests (while we have tests for exclusion for AbstractMiddleware we need to make sure that params from config are properly wired to __init__ args and we need at least one test per middleware for that) and update docs that all builtin middleware support exclusion via pattern list or opt key
Also, there is another question that needs to be discussed I think.
At the moment `AbstractAuthenticationMiddleware`  uses `exclude_from_auth_key` param with the default value of `exclude_from_auth`. `CSRFMiddleware` uses `exclude_from_csrf_key` config …
> Cleanup builtin middlewares

- starlite/static_files/base.py
- tests/static_files/test_file_serving_resolution.py
- tests/static_files/test_html_mode.py
This fixes #783, by correctly setting the `Content-Disposition` header to `inline` instead of `attachment`.
> Fix #783 by setting content-disposition to inline in html_mode

- docs/reference/config/6-static-files-config.md
- docs/usage/0-the-starlite-app/3-static-files.md
- starlite/config/static_files.py
- starlite/static_files/base.py
- tests/static_files/test_file_serving_resolution.py
This flag can be used to set the `content-disposition` to be either `inline` (`False`) or `attachment` (`True`). It defaults to `True`, mimicking the default behaviour of known web servers and frameworks.
> Introduce `send_as_attachment` flag for `StaticFiles`.

- starlite/kwargs.py
- tests/test_dependency.py
Updates `sequence_query_parameter_names` of the kwargs model with the values of same from dependencies.
> fix: parsing of sequence query for nested dependency.

- starlite/middleware/session/sqlalchemy_backend.py
Fixes #840
Some deletion methods didn't `commit()` properly, which lead to changes sometimes not being persisted.
> Fix #840 - Always commit changes properly after deleting session data

- starlite/middleware/session/sqlalchemy_backend.py
The previously used `BLOB` did not render correctly for a database drivers. `LargeBinary` renders as the appropriate binary column type for each driver.
> Fix #841 - Change `middleware.session.sqlalchemy_backend.SessionModelMixin.data` to LargeBinary.

- docs/usage/6-dependency-injection/3-the-provide-class.md
- starlite/datastructures/provide.py
- starlite/kwargs.py
- starlite/routes/http.py
- starlite/routes/websocket.py
- tests/dependency_injection/test_request_local_caching.py
- tests/kwargs/test_dependency_batches.py
Dependencies currently have two problems:
1. They are resolved sequentially
2. They may be resolved multiple times within a single request
In order to solve the first without introducing locks, the resolution algorithm was changed to:
1. Recursively getting a list of all dependencies, with their required sub-dependencies
2. Creating a sequence of dependency batches. The dependencies per batch can run concurrently, but depend on values from the previous batches. Each batch is created by:
a. Getting all unaccounted for dependencies without remaining sub-dependencies
b. Removing those dependencies from the list of overall dependencies
c. Removing them from the remaining sub-dependencies of the other dependencies
This way the following dependency graph will be split into these batches: `(A, …
> Rework dependencies

- starlite/middleware/session/memcached_backend.py
This method is an unsound, hacky workaround for a missing memcached functionality. Users are advised to just use redis instead if they need this.
> Deprecate `delete_all` of memcached session backend

- docs/usage/5-responses/4-response-headers.md
- docs/usage/5-responses/5-response-cookies.md
In the recent docs update (#798) some paths contained typos so at the moment our docs look like this
Here I simply fix typos
> Fix path to example files in the docs

- .pre-commit-config.yaml
- starlite/datastructures/provide.py
- starlite/routes/http.py
- tests/kwargs/test_generator_dependencies.py
Fix #899 by not wrapping the response but instead calling the cleanup after all response processing is done. This maintains the current order of execution.
> Fix #899 - Generator based dependencies with cached responses

- starlite/openapi/controller.py
- tests/openapi/test_controller.py
I was testing a _Starlite_ app with _uvicorn_'s _--root-path_ option, and found (what appears to be) a bug.
`OpenAPIController` compares `request.url.path` to the path given by the client to determine if the request is asking for something openapi-related but `request.url.path` can have an ASGI _root_path_ prepended to it if it is given. This was causing all openapi routes to throw a 404.
I think I found an elegant solution to address this issue.
Cheers!
Kyle
> Fix issue with OpenAPI Controller and ASGI root_path

- docs/usage/0-the-starlite-app/2-using-application-state.md
- docs/usage/1-routing/0-routing.md
Following changes to documentation
- Removes a reference to Starlette in the ["Routing" section](https://starlite-api.github.io/starlite/usage/1-routing/0-routing/) as Starlite is no longer dependant on Starlette.
- Fixes a typo and links to the correct class in ["Note" section](https://starlite-api.github.io/starlite/usage/0-the-starlite-app/2-using-application-state/)
> Minor docs update

- .pre-commit-config.yaml
- starlite/testing/test_client/transport.py
- tests/kwargs/test_query_params.py
- tests/test_parsers.py
> fix TestClient handling of escapted ampersands in query params

- starlite/security/session_auth/auth.py
- tests/security/test_security.py
- tests/security/test_session_auth.py
When SessionAuth is implemented in project open api security scheme cookie key is generated as `Set-Cookie`. 
This PR makes cookie name as user-defined cookie key.
<details>
<summary>Starlite 1.45.1 samples</summary>
>  Swagger
> <img width="230" alt="Swagger" src="https://user-images.githubusercontent.com/16171942/207762768-a8a81767-bb51-463c-bb79-d4d411b1ffde.png">
> Redoc
> <img width="262" alt="스크린샷 2022-12-15 오후 12 03 14" src="https://user-images.githubusercontent.com/16171942/207762709-52b17b7b-2297-45c4-abf9-bc7d5f506c76.png">
> Element 
> <img width="782" alt="스크린샷 2022-12-15 오후 12 02 40" src="https://user-images.githubusercontent.com/16171942/207762732-5e0ba8cc-2c51-458d-b1b8-a37321f8b8fd.png">
</details>
<details>
<summary>Current PR sample</summary>
>  Swagger
> …
> fix: make SessionAuth openapi_schema use backend_config.key

- docs/usage/15-caching/0-cache-backends.md
- docs/usage/8-security/3-guards.md
_No PR is too small, right?_ Adding a minor spacing fix to the cache backend usage docs so that mkdocs can render an admonition correctly
> docs: fix note block spacing in cache usage

- .pre-commit-config.yaml
- CONTRIBUTING.md
- docs/usage/3-parameters/1-query-parameters.md
- examples/hello_world.py
- examples/parameters/query_params.py
- examples/parameters/query_params_default.py
- examples/parameters/query_params_optional.py
- examples/parameters/query_params_remap.py
- examples/parameters/query_params_types.py
- mkdocs.yml
- requirements-docs.txt
- tools/run_examples.py
Introduce an mkdocs hook that can automatically run requests against example apps based on simple comment instructions and inject the output into the docs.
Why?
Including an input/output (e.g. "run this curl command > this is the result") example alongside the code examples makes them more easily digestible. By doing it this way we can ensure that the output work, are up-to-date and follow a consistent format without having to perform all those tasks manually.
> Autorun examples 

- starlite/parsers.py
- tests/test_parsers.py
Currently UTF-8 form data cannot be parsed and results in an internal server error.  
I added a test which test that and included the fix.
> fix: support utf-8 encoded strings in form data

- .github/workflows/docs.yaml
#943 Was missing the inclusion of dependencies needed to run in the CI. This fixes it :upside_down_face:
> Install dependencies needed for tools/run_examples.py in docs GH action

- examples/responses/response_cookies_4.py
- examples/responses/response_cookies_5.py
- starlite/response/base.py
- tests/response/test_base_response.py
Add support for setting `Cookie` instances in `Response.set_cookie` alongside of keyword arguments.
Implements #961
> Support `Cookie` instances in `Response.set_cookie`

- starlite/utils/serialization.py
- tests/utils/test_serialization.py
Fixes #1003, by adding support for subclassed stdlib types. Also simplifies some of the pydantic-specific type conversion logic.
> Extend serializable types

- starlite/utils/serialization.py
- tests/utils/test_serialization.py
Remove some unnecessary default type encoders.
> Cleanup type encoders

- docs/usage/9-testing/1-test-client.md
Fix typo in the "Test Client" section.
set_session_data appears two times
> Fix typo in the docs (Testing. Test Client)

- docs/usage/5-responses/4-response-headers.md
This PR provides a small fix with a broken example in the ["Response Headers" section of the docs](https://starlite-api.github.io/starlite/1.48/usage/5-responses/4-response-headers/).
> Fix a broken example for the "Response Headers" docs

- docs/usage/5-responses/11-background-tasks.md
- examples/responses/background_tasks_1.py
- examples/responses/background_tasks_2.py
- examples/responses/background_tasks_3.py
- examples/tests/responses/test_background_tasks.py
The reason why I opened this PR is that I did not understand how to pass route handler arguments to background tasks, but discussion #765 was helpful, and I thought that adding a few examples, as suggested within the discussion, might help other users.
This PR contains the following items:
- Moved existing example into a separate file.
- Added tests for new and previous examples.
- Name of kwarg was incorrectly documented as `background_task`, it should be `background`, if I am not mistaken.
- Given more visibility to new examples, because I thought that the use case in which a background task has to receive route handler arguments might be more common. I also emphasized the fact that background tasks passed into route decorators cannot use handler arguments.
Of course, I am open to any …
> Add examples about background tasks usage with responses

- starlite/handlers/http.py
- tests/response/test_dto_response.py
The implementation of the automatic `DTO` response converter has a small bug. If the response type is an iterable DTO, a check is made weather the first element in the iterable data is a `DTO`. This check will result in an `Indexerror` as the iterable data might have no elements at all.
> Fix issue when response is an empty iterable of DTOs

- docs/reference/exceptions/0-base-exceptions.md
- docs/reference/exceptions/1-http-exceptions.md
- starlite/exceptions/__init__.py
- starlite/exceptions/base_exceptions.py
- starlite/exceptions/http_exceptions.py
- starlite/multipart.py
- starlite/routes/http.py
- starlite/utils/serialization.py
- tests/connection/request/test_request.py
- tests/kwargs/test_reserved_kwargs_injection.py
- tests/utils/test_serialization.py
At the point of parsing the `data` kwarg, this PR looks for a deserialization error and raises a client error http response.
Adds a new exception, `SerializationException` which wraps the `msgspec` operations. I think this better encapsulates the 3rd-party code.
Adds a new HTTP exception `ClientException` and makes other `4xx` errors a subclass.
Makes `ServiceUnavailableException` a subclass of `InternalServerException`.
Closes #1047
> Ensure http requests with invalid payloads return 400.

- poetry.lock
- tests/openapi/test_config.py
Fix expected OpenAPI components for [this PR](https://github.com/starlite-api/pydantic-openapi-schema/pull/18). Removed the `explode` element, because now `explode` is `None` by default.
> Fix expected OpenAPI components in `test_merged_components_correct`

- docs/examples/contrib/jwt/using_oauth2_password_bearer.py
- starlite/contrib/jwt/__init__.py
- starlite/contrib/jwt/jwt_auth.py
- tests/contrib/jwt/test_auth.py
This enhancement sets the default response for the `OAuth2PasswordBearerAuth` login to a valid [RFC-6749 response](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.4):
The RFC specifies the following fields to be included on a response (any others can be appended to this list): 
```json
{
"access_token":"2YotnFZFEjr1zCsicMWpAA",
"token_type":"bearer",
"expires_in":3600,
"refresh_token":""
}
```
If you do not specify a `response_body` when calling the login function, it will return an `OAuth2Login` response.
> feat: return valid OAuth2 response body by default

- docs/_static/js/version_select.js
- docs/_static/style.css
Add a warning banner when viewing a documentation version for an outdated or development version of Starlite.
> Docs: Add version warning for outdated / development versions.

- docs/examples/datastructures/pagination/using_offset_pagination_with_sqlalchemy.py
- docs/usage/responses.rst
- starlite/datastructures/provide.py
- tests/test_utils.py
Currently, the `Provide` class takes a callable and accordingly calls it based on if it is a sync callable or an async callable. But when the class with an async `__call__` method is given to Provide, it awaits its `__init__` method. Class is callable but not awaitable so I have added a condition to always call the class as a sync object.
The offset pagination with sqlalchemy depends on this fix as I am passing the paginator class directly to Provide to create its dependency.
> Class As Dependency

- starlite/app.py
- starlite/config/logging.py
- tests/app/test_app_config.py
Implement the proposal made in https://github.com/starlite-api/starlite/pull/976#issuecomment-1410297133.
1. Configure a `starlite` logger in debug mode if no `LoggingConfig` was given, and `logging_config` was not explicitly set to `None`
2. Set the level of the `starlite` logger to `DEBUG` when in debug mode
This generally makes the use of `debug` more intuitive, especially in combination with #976: Setting `debug=True` will the result in exceptions being logged without having to specify any additional configuration.
> Configure logger and force "DEBUG" level in debug mode

- starlite/middleware/logging.py
- tests/middleware/test_logging_middleware.py
Fixes issue reported in #1149 related to explicitly defining response_log_fields and request_log_fields
> Bug: Fix LoggingMiddlewareConfig log fields #1139

- starlite/contrib/jwt/jwt_auth.py
- starlite/security/base.py
If the on-app-init hook handler is passed to the application, and the `type_encoders` is not explicitly set on the config, we grab the custom encoders from the application config.
> Moves `type_encoders` config onto `AbstractSecurityConfig`.

- .github/CODEOWNERS
Codeowners allows for automatic assignment to review pull requests
> feat(meta): Create CODEOWNERS

- starlite/openapi/path_item.py
- tests/openapi/test_config.py
- tests/openapi/test_path_item.py
add support for setting openapi operation summary to normalized callable name
> add support for setting openapi operation summary to normalized callable name

- CHANGELOG.rst
- docs/usage/plugins/index.rst
- starlite/__init__.py
- starlite/app.py
- starlite/cli/utils.py
- starlite/config/app.py
- starlite/dto.py
- starlite/handlers/http_handlers.py
- starlite/openapi/path_item.py
- starlite/openapi/request_body.py
- starlite/openapi/responses.py
- starlite/openapi/schema.py
- starlite/plugins/__init__.py
- starlite/plugins/base.py
- starlite/plugins/piccolo_orm.py
- starlite/plugins/sql_alchemy/plugin.py
- starlite/plugins/tortoise_orm.py
- starlite/routes/http.py
- starlite/signature/parsing.py
- starlite/testing/helpers.py
- starlite/types/__init__.py
- starlite/types/builtin_types.py
- starlite/types/protocols.py
- tests/openapi/test_config.py
- tests/openapi/test_path_item.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_relationships.py
- tests/plugins/sql_alchemy_plugin/test_sql_alchemy_table_types.py
- tests/plugins/test_base.py
> refactor plugin protocol

- starlite/parsers.py
- tests/test_parsers.py
This bug addresses a bug when parsing HTTP headers from `scope["headers"]`.
Currently, the `parse_headers` function is decorated with `lru_cache` which can't hash lists. 
This is problematic because lists (not tuples) are what the ASGI protocol allows for since they're serializable. 
The ASGI server will pass lists of lists to `parse_headers` leading to `TypeError`.
We are currently running into this bug with starlite `1.51.0`
> Because these messages could be sent over a network, they need to be serializable, and so they are only allowed to contain the following types:
Byte strings
Unicode strings
Integers (within the signed 64-bit range)
Floating point numbers (within the IEEE 754 double precision range; no Nan or infinities)
Lists (tuples should be encoded as lists)
Dicts (keys must be …
> Fix critical bug in parsing headers

- starlite/contrib/jwt/jwt_auth.py
- tests/contrib/jwt/test_auth.py
The JWT Cookie Auth configuration was missing the parameter for `domain` when setting the response cookie.  This PR adds that parameter.
> fix: JWT Auth correctly handles `domain` configuration value.

- starlite/utils/extractors.py
- tests/middleware/test_logging_middleware.py
It looks like this issue can be resolved by simply passing a copy of `connection.cookies` to the `obfuscate()` function in [starlite/utils/extractors.py](https://github.com/starlite-api/starlite/blob/e21052705875d0657cbe3aeeeadc1a074e7b354e/starlite/utils/extractors.py#L218). The addition of `copy()` allows the test I created to pass, and it fixes the issue in the application in which the bug was original observed.
> Fix #1228: create a new dictionary of values in obfuscate()

- docs/lib/usage/route-handlers.rst
> docs: rename `operationId` to `operation_id` to avoid ambiguity

- poetry.lock
- pyproject.toml
When Starlite is installed with `starlite[full]` and `starlite run` is used, the following exception is raised
```
ModuleNotFoundError: No module named 'jsbeautifier'
```
This PR adds `jsbeautifier` to the "full" section in pyproject.toml and also does `poetry update`
> Adding jsbeautifier to pyproject.toml to fix ModuleNotFoundError

- starlite/cli/commands/core.py
- tests/cli/test_run_command.py
Fixes #1191 by invoking uvicorn with `subprocess.run`. This is the only actual workaround due to https://github.com/encode/uvicorn/issues/1045.
> Fix CLI `--reload` flag not working as expected

- starlite/signature/parsing.py
- starlite/signature/utils.py
- starlite/static_files/base.py
- starlite/utils/compat.py
- tests/compatibility/test_starlette_responses.py
- tests/signature/test_parsing.py
- tests/signature/test_utils.py
- tests/utils/test_compat.py
We currently rely on pydantic to resolve forward references for signature models. However, in order to continue our migration away from pydantic we should do this ourselves.
This change is a pre-cursor to add checks for improper use of reserved kwargs, such as 'state'. In order to check the type that is annotated against the reserved kwargs in function signatures, we need to have resolved any forward references to their types first.
> De-referencing forward referenced annotations for signature models.

- docs/conf.py
- tools/sphinx_ext.py
Due to a change in AutoPyTabs our custom directive is overridden. This fixes it by using AutoPyTab's compatibility mode.
> Docs: Fix autorun examples

- tests/test_file_system.py
There are two tests that are currently failing under windows, but seem to be difficult to reproduce. They pass when I tested it on my Windows installation (Windows 10 in a VirtualBox) but fail in the CI (which runs them on Windows Server 2022).
I have `xfail`ed them for now, so our CI runs properly. This needs some investigation though, preferably from someone who has access to the right platform.
> Xfail suspected fsspec windows issue

- starlite/__init__.py
- starlite/cli/_utils.py
- starlite/utils/version.py
- tests/utils/test_version.py
Add utilities to parse the package version defined in `pyproject.toml` into a `NamedTuple` and expose the version information in `starlite.__version__`.
> Add package version parsing utils and `starlite.__version__`

- tests/template/test_builtin_functions.py
`xfail` `tests/template/test_builtin_functions.py::test_jinja_url_for_static_asset` on windows because for some reason it is flaky there.
> xfail flaky windows test: test_jinja_url_for_static_asset

- .github/workflows/ci.yaml
- .github/workflows/codeql.yml
Remove CodeQL (with dependencies) from the regular CI and set up a workflow that runs CodeQL with dependencies once a day.
Reasoning is that CodeQL with dependencies regularly takes 20+ minutes, which can quite bothersome if you're depending on the workflow to finish.
> Run CodeQL with dependencies on a schedule instead of within CI

- starlite/middleware/session/__init__.py
- starlite/template/__init__.py
Corrects an incorrect name check in `starlite/middleware/session/__init__.py` that was causing a deprecation error  to be thrown for the wrong type.
Closes #1284
> Fix raising deprecation warning for wrong name.

- starlite/app.py
Fixes a typo `startlite` in the core Starlite application `from_config` class method.
Resolves #1287
> fix(docs): typo in core Starlite app

- tests/template/test_builtin_functions.py
Xfail `tests/templates/test_builtin_functions.py::test_jinja_url_for` because it is flaky on windows.
Follow up to #1282
> Xfail windows flaky test

- .pre-commit-config.yaml
As per [ruff-pre-commit guidance](https://github.com/charliermarsh/ruff-pre-commit):
> Note that Ruff's pre-commit hook should run before Black, isort, and other formatting tools.
This is because:
> If you're not running autofix on pre-commit, then you should run Black, isort, etc. first
The issue is that Ruff's autofixes aren't guaranteed to produce Black-stable code
> So if you run Black, then Ruff... then run Black again, you might see changes on that second Black invocation, because we might've produced some code that Black wants to reformat when we applied our autofixes
Black, for example, has really specific rules around when and how it wraps lines. So if we autofix something and introduce a tuple, Black might end up wanting to wrap that in a way that differs from what Ruff did by …
> chore(ci): ruff should be run before all other formatting tools

- starlite/contrib/repository/abc.py
- starlite/contrib/repository/testing/generic_mock_repository.py
- starlite/contrib/sqlalchemy/repository.py
Fixed and issue where `RepositoryNotFoundException` was renamed to `NotFoundError` but was not updated in the docstrings.
> chore: update docstrings to use new exception error class name

- tests/contrib/sqlalchemy/repository/test_sqlalchemy_asyncpg.py
Skips `tests/contrib/sqlalchemy/repository/test_sqlalchemy_asyncpg.py` on non-linux platforms, since they require docker which is currently not available in our MacOS and Windows CI setup.
> Skip tests for asyncpg repository on non-linux platforms

- starlite/contrib/sqlalchemy_1/config.py
This PR seeks to make the linter error suppression less wide in scope. `# noqa` by itself is quite disruptive and can generally be made more granular by specifying a specific rule to suppress. 
This PR adds `# noqa: F821` from [pyflakes](https://beta.ruff.rs/docs/rules/#pyflakes-f)
F821 | undefined-name | Undefined name {name}
-- | -- | --
Resolves #1326
> fix: add granular noqa to allow linting to catch other issues

- .github/workflows/test.yaml
- tests/cli/conftest.py
Fixes tests.
Changes references from `matrix.python-version` in CI to `inputs.python-version`.
Adds `__future__.annotations` to `tests/cli/conftest.py` and associated linting fixes.
> Fix py38 tests

- starlite/_signature/parsing.py
- starlite/_signature/utils.py
- starlite/handlers/http_handlers/base.py
- starlite/response/base.py
- starlite/serialization.py
- starlite/types/protocols.py
- starlite/utils/pydantic.py
These are various refactors that I've pulled out of the DTO refactor branch in order to keep that more focused.
- uses signature model return annotation for creating response handlers - it has had forward refs resolved.
- adds `serialization.encode_for_media_type()` utility.
- refactor `create_pydantic_signature_model()`, no functional change.
- changes `DataclassProtocol.__dataclass_fields__` to `ClassVar`.
- adds ability to provide extra namespace names to `_signature.utils.get_fn_type_hints()` utility.
> Various refactors.

- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
it is good practice to pin poetry so poetry updates don't break ci
Pin poetry to 1.4.0 in CI.
fixes https://github.com/starlite-api/starlite/actions/runs/4462113125/jobs/7836421937
> fix: pin poetry to 1.4.0 in CI

- starlite/_asgi/asgi_router.py
- starlite/events/emitter.py
- starlite/events/listener.py
- tests/conftest.py
- tests/events/test_listener.py
This PR updates the `EventEmitterBackend` abstract class and the `SimpleEventEmitter` concrete implementation to be more useful. I used the `Broadcaster` library from encode as a source of inspiration for the implementation, which uses the worker pattern. It appears to be working with trio, without an issue.
> update simple event emitter to use worker pattern

- poetry.lock
- pyproject.toml
This is a workaround for https://github.com/cunla/fakeredis-py/issues/130.
`redis-py`'s latest release removed their dependency on `async_timeout` for python 3.11. `fakeredis-py` is relying on that dependency transitively, so fails on import in 3.11.
This PR adds `async_timeout` to our dependencies to get tests running again, but should be removed once the aforementioned issue is resolved. …
> Adds `async_timeout` as dev dep for py 3.11+.

- .pre-commit-config.yaml
- starlite/contrib/sqlalchemy_1/plugin.py
You would get an error when using the SQL Alchemy plugin with a `Uuid` type from SQLAlchemy.  This enhancement adds it to the provider map to prevent this error.
> fix: adds SQL Alchemy UUID map

- starlite/openapi/controller.py
This fix wraps the exported OpenAPI JSON with a single quote so that `JSON.parse` does not fail.
> fix: `JSON.parse` fails to parse an Object.  

- docs/examples/signature_namespace/app.py
- docs/examples/signature_namespace/controller.py
- docs/examples/signature_namespace/domain.py
- docs/examples/tests/test_signature_namespace.py
- docs/usage/route-handlers.rst
- docs/usage/the-starlite-app.rst
- starlite/_signature/parsing.py
- starlite/app.py
- starlite/config/app.py
- starlite/controller.py
- starlite/handlers/asgi_handlers.py
- starlite/handlers/base.py
- starlite/handlers/http_handlers/base.py
- starlite/handlers/http_handlers/decorators.py
- starlite/handlers/websocket_handlers.py
- starlite/router.py
- starlite/testing/helpers.py
- tests/handlers/asgi/test_handle_asgi.py
- tests/handlers/http/test_signature_namespace.py
- tests/handlers/http/test_to_response.py
- tests/handlers/websocket/test_handle_websocket.py
- tests/openapi/test_parameters.py
- tests/signature/test_parsing.py
When we parse the signature models for handlers, names of the parameter types must be available. However, when using linters, names that are only referenced in type annotations will be flagged as being unnecessary at runtime and suggested to move into an `if TYPE_CHECKING` block.
This parameter will allow names to be declared outside the scope that handlers are defined, allowing modules defining handlers and dependencies to better integrate with tooling.
For example:
```py
from starlite import Router
from domain.thing import Thing
from .controller import ThingController
router = Router("/", route_handlers=[ThingController], signature_namespace={"Thing": Thing})
```
```py
from __future__ import annotations
from typing import TYPE_CHECKING
from starlite import Controller, post
if …
```
> Adds `signature_namespace` layered parameter.

- .pre-commit-config.yaml
- docs/usage/events.rst
- starlite/app.py
- starlite/events/emitter.py
- tests/events/test_listener.py
Change the `BaseEventEmitterBackend.emit` to be synchronous. Also update 
- `Starlite.emit`
- `SimpleEventEmitter.emit` accordingly
This change allows events to be emitted from synchronous handlers. Performance won't be impacted, and this method simply enqueues an event in a non-blocking way. This can be implemented for any future backends as well.
[//]: # "Examples: Fixes #4321 or …
> Enhancement: Make `BaseEventEmitterBackend.emit` synchronous

- starlite/events/emitter.py
- tests/events/test_listener.py
With the PR #1346 introduced a bug to `SimpleEventEmitter` where keyword arguments would not be handled correctly. This adds missing tests covering this case and implements a fix.
> Fix SimpleEventEmitter kwarg handling

- starlite/contrib/sqlalchemy_1/plugin.py
- tests/contrib/sqlalchemy_1/sql_alchemy_plugin/test_sql_alchemy_config.py
When using the SQLAlchemy 1 plugin, repeatedly running through the application lifecycle (as done when testing an application not provided by a factory function), causes a KeyError on the second pass.
This is caused be the plugin's on_shutdown handler deleting the engine_app_state_key from the application's state on application shutdown, but only adding it on application init.
This PR adds `SQLAlchemyConfig.update_app_state` to application `on_startup` hooks so that state removed in `on_shutdown` is reset for each test.
Closes #1368
- follow Starlite's [Code of …
> Call SQLAlchemyConfig.update_app_state in `on_startup` hook.

- starlite/plugins.py
- tests/test_plugins.py
`get_plugin_for_value()` unconditionally checks the first value returned from `get_args()`, which I've presumed is to detect if an annotation is for a homogeneous iterable of a plugin supported type, e.g., `List[User]`.
This PR ensures that the type _is_ an iterable type before inspecting the args so that arbitrary non-iterable generic types are tested against their outer type, not the type of their first generic arg, e.g, `Request[User, ...]` would be checked against `Request` not `user`.
Closes #1388
- follow Starlite's [Code of Conduct](https://github.com/starlite-api/.github/blob/main/CODE_OF_CON …
> Fix `get_plugin_for_value()` for arbitrary generic types.

- CONTRIBUTING.rst
Hi, I was taking a look at the contributing guides to see if and how to contribute to the project and I found a small typo, which this pr should correct. Maybe a PR for just a dot is overkill, so no problems if you want to close/ignore this and batch the work later down the line into a meatier PR!
> chore: fix a small typo in CONTRIBUTING.rst

- docs/conf.py
- starlite/app.py
- starlite/contrib/sqlalchemy_1/plugin.py
- starlite/plugins.py
- tests/test_plugins.py
- tools/sphinx_ext/missing_references.py
This PR modifies `InitPluginProtocol.on_app_init()` to receive and return the `AppConfig` instance, as opposed to the application instance itself.
The `Starlite.__init__()` method is modified to call the `on_app_init()` method of all registered `InitPluginProtocol` plugins immediately after calling the `on_app_init` hooks.
This PR supersedes RFC PR #1381 which examined the effects of removing `InitPluginProtocol` in favor of `on_app_init` hooks. From discussion in that PR it was resolved that there is merit in having both `on_app_init` hooks and `InitPluginProtocol`, even if they essentially do the same thing, due to improved ergonomics of the application interface that this affords.
[//]: # "Please review the [Starlite contribution …
> Modify the `InitPluginProtocol` to interact with `AppConfig`.

- starlite/app.py
- starlite/middleware/session/client_side.py
- starlite/middleware/session/server_side.py
- starlite/utils/dataclass.py
- tests/utils/test_dataclass.py
Renames `extract_dataclass_fields` to `extract_dataclass_items`. I chose "items" as it returns name/value pairs like `dict.items()`.
Broadens the api to include `exclude_empty` and `exclude` params.
Adds `extract_dataclass_fields` which embellishes the standard lib `fields()` function with various filtering parameters.
Adds `simple_asdict()` as an alternative to the stdlib `asdict()` function. It does not deepcopy values and does not recurse into collections.
- follow Starlite's [Contribution …
> Refactor: dataclass utils

- starlite/_openapi/schema_generation/schema.py
- tests/openapi/test_schema.py
From inspecting annotations directly via `__annotations__` when generating parameters for model openapi fields, openapi schema generation would fail for those fields when the type was wrapped with `Annotated`, `Required` and `NotRequired`.
This PR uses `get_type_hints(obj, include_extras=False)` to access the object annotations, ensuring that the types we use to generate the openapi schemas have had those "wrapper" types removed first.
Closes #1372
- follow Starlite's [Contribution …
> Fix generating schemas for models with annotated attributes.

- starlite/_signature/utils.py
- tests/signature/test_parsing.py
Params with `Annotated` types in handler signatures are parsed inconsistently, depending on whether the annotation is stringized.
If the type annotation is a string, it is passed to `get_type_annotations()` which unwraps any `Annotated` types. If the annotation is not a string, it remains as-is, with `Annotated` in place.
This PR ensures that we parse `Annotated` types the same, irrespective of whether the user has `__future__.annotations` imported, or not, by setting `include_extras=True` on the call to `get_type_annotations()`.
We could consider explicitly unwrapping the annotated types and storing any metadata on the `ParsedSignatureParameter` in a future PR.
[//]: # "Please review the [Starlite contribution guidelines](https://github.com/starlite-api/starlite/blob/main/CONTRIBUTING.rst …
> Fix inconsistent parsed parameter annotations.

- starlite/_openapi/schema_generation/constrained_fields.py
- starlite/contrib/jinja.py
- starlite/contrib/mako.py
- starlite/contrib/opentelemetry/_utils.py
- starlite/contrib/opentelemetry/config.py
- starlite/contrib/opentelemetry/middleware.py
- starlite/contrib/piccolo_orm.py
- starlite/contrib/sqlalchemy_1/config.py
- starlite/contrib/sqlalchemy_1/plugin.py
- starlite/contrib/tortoise_orm.py
- starlite/exceptions/base_exceptions.py
- starlite/logging/config.py
- starlite/logging/picologging.py
- starlite/middleware/compression.py
- starlite/middleware/session/client_side.py
- starlite/testing/client/async_client.py
- starlite/testing/client/base.py
- starlite/utils/helpers.py
- test_apps/logging_test_app/main.py
- test_apps/openapi_test_app/main.py
- test_apps/piccolo_admin_app/main.py
- test_apps/static_files_test_app/main.py
- tests/test_exceptions.py
Update the usage of `MissingDependencyException` to not mask import errors and be more detailed in the error message.
Closes #1340
> Refactor: Update `MissingDependencyException` usages

- docs/examples/stores/registry_configure_integrations.py
- docs/examples/stores/registry_default_factory_namespacing.py
- docs/examples/tests/test_stores.py
- docs/usage/stores.rst
- starlite/config/response_cache.py
- tests/test_response_caching.py
Fix a typo in the default value of `ResponseCacheConfig.store`.
> Fix `ResponseCacheConfig` default store name

- starlite/_openapi/responses.py
- starlite/_signature/parsing.py
- tests/openapi/test_responses.py
Ensures that the signature model return annotation is retrieved from de-referenced type hints.
Uses the signature model's `return_annotation` for generation of success responses.
Closes #1409
[//]: # "Examples: Fixes #4321 or Closes …
> Ensure openapi responses generated from de-stringized return annotation.

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- starlite/plugins/sql_alchemy/plugin.py
- starlite/routes/http.py
- tests/caching/test_response_caching.py
When setting `cache=True` in a route handler, we are passing the boolean value as the expiration time to the backend as-is. This causes errors when being used with the redis backend.
This PR implements a fix by explicitly checking for `True` before passing along the value.
[//]: # "Please add in issue numbers this …
> Fix (v1.51): Wrong value being passed to cache backend when `cache=True` in route handler

- starlite/handlers/http_handlers/base.py
- starlite/response_containers.py
- tests/handlers/http/test_validations.py
- tests/test_response_containers.py
Fixes #1371.
We currently only allow "static" redirects, i.e. setting a redirect status code on the handler, and then returning a `Redirect`. This does not support use cases where a redirect may be returned conditionally, see #1371.
This issue runs into a larger underlying problem with how we handle status codes in HTTP handlers, since we generally lack support of setting them dynamically / multiple, therefore I had to remove validation logic that checked if the status code on the handler was in the accepted range for redirects if a handler returns a `Redirect`, as this validation would fail if no status code was set on the handler.
By …
> Enhancement: Support setting status codes in `Redirect` container

- starlite/contrib/sqlalchemy_1/plugin.py
This reverts commit d19c0e11003b7fffd3be7954609d9675af4f246e.
These types are not available in SQLAlchemy 1.4, making the SQLAlchemy 1 plugin incompatible with SQLAlchemy 1.
Closes #1387 
[//]: # "Examples: Fixes #4321 or Closes …
> Revert "fix: adds SQL Alchemy UUID map (#1355)"

- poetry.lock
- pyproject.toml
They are yet to release for the 4.3 series: https://github.com/redis/redis-py/pull/2672 - maybe we need to wait.
> Restrict minimum redis versions for CVE-2023-28858 & CVE-2023-28859.

- tests/test_option_requests.py
This test is responsible for the last couple of hypothesis timing consistency errors.
Replaced using a solution with stdlib components and `pytest.mark.parametrize`.
> Remove hypothesis permutations from test.

- starlite/handlers/asgi_handlers.py
- starlite/handlers/base.py
- starlite/handlers/http_handlers/base.py
- starlite/handlers/websocket_handlers.py
- starlite/router.py
Same logic was repeated 3 times for each handler type, PR moves common logic into `BaseRouteHandler`.
> De-duplicates handler `__call__()` method logic.

- starlite/types/__init__.py
- starlite/types/serialization.py
`AbstractDTOInterface.to_encodable_type()` needs a type for its return value.
Alternative is to just type it `Any`, I don't know if we are tying a rod for our backs trying to strong type this stuff, but then again, maybe it's ok. …
> RFC: Attempt at a `StarliteEncodableType` type alias.

- starlite/handlers/base.py
- tests/handlers/base/test_validations.py
This allows raising `ImproperlyConfiguredException` whenever `BaseRouteHandler.fn` is accessed before having decorated a handler function.
> Adds `BaseRouteHandler.fn` property.

- starlite/_signature/utils.py
- starlite/handlers/asgi_handlers.py
- starlite/handlers/http_handlers/base.py
- starlite/handlers/websocket_handlers.py
- starlite/types/parsed_signature.py
- tests/types/test_parsed_signature.py
A few utility functions to centralize type identification logic.
Determine if the `ParsedType` is a sub-type of some provided type, e.g, `ParsedType.from_annotation(bool).is_type_of(int) == True`
Does the `is_subclass_of()` check on any inner types held by the `ParsedType`.
[//]: # "Please add in issue numbers …
> Parsed signature utils

- docs/examples/responses/response_content.py
- docs/usage/responses.rst
- starlite/connection/request.py
- starlite/datastructures/__init__.py
- starlite/datastructures/headers.py
- tests/connection/request/test_request.py
- tests/datastructures/test_headers.py
First iteration to implement Accept header parsing and content negotioation. Documentation is missing until the code is stable.
- I'm not sure where to put the helper types, `Accept` might reside in request.py, the other I don't know.
- Should `MediaType` be exposed or only used internally?
- Are the tests appropiate?
- Is the ordering correct based on [RFC 2616](https://www.rfc-editor.org/rfc/rfc2616#section-14.1)?
Exposing the results as `str` is obviously easier. But when paramters are involved it gets more complicated:
```
Accept("text/plain,text/plain;p=test").best_match(["text/plain", "text/html"]) == "text/plain;p=test"
```
In a handler you would do:
```
preferred_type = request.accept.best_mach(["text/plain", "text/html"])
if preferred_type == "text/plain":
return text_response …
```
> Implement #1299: Accept header parsing and content negotiation

- docs/conf.py
- starlite/handlers/asgi_handlers.py
- starlite/handlers/http_handlers/base.py
- starlite/handlers/websocket_handlers.py
- starlite/routes/http.py
- starlite/types/builtin_types.py
- starlite/utils/sync.py
- tests/template/test_template.py
- tests/utils/test_sync.py
Fix incorrect handler type annotations.
`HTTPRouteHandler.{resolve_after_response(),resolve_after_request()}` were 
annotated to return their `__init__()` param type, failing to recognise that they
are wrapped with `AsyncCallable` before being assigned to the handler instance.
In addition to correcting the return types of those methods, this PR adds the
ability to optionally generate a `ParsedSignature` for the `AsyncCallable` type,
and does so for `before_request` handlers. The return type annotation handling is
then refactored around this.
TODO: what happens if a `before_request` handler has an optional return type?
Original PR message:
When using a before request handler with a route with  a `Template` response, the return annotation is set to `T` which causes the the response to be …
> Fix incorrect handler type annotations

- docs/examples/websockets/dependency_injection_simple.py
- docs/examples/websockets/dependency_injection_yield.py
- docs/examples/websockets/listener_class_based.py
- docs/examples/websockets/listener_class_based_async.py
- docs/examples/websockets/mode_receive_binary.py
- docs/examples/websockets/mode_receive_text.py
- docs/examples/websockets/mode_send_binary.py
- docs/examples/websockets/mode_send_text.py
- docs/examples/websockets/receive_bytes.py
- docs/examples/websockets/receive_json.py
- docs/examples/websockets/receive_str.py
- docs/examples/websockets/sending_bytes.py
- docs/examples/websockets/sending_json_dataclass.py
- docs/examples/websockets/sending_json_dict.py
- docs/examples/websockets/sending_str.py
- docs/examples/websockets/socket_access.py
- docs/usage/dependency-injection.rst
- docs/usage/index.rst
- docs/usage/route-handlers.rst
- docs/usage/websockets.rst
- litestar/__init__.py
- litestar/handlers/__init__.py
- litestar/handlers/websocket_handlers.py
- litestar/router.py
- litestar/types/asgi_types.py
- litestar/types/parsed_signature.py
- tests/handlers/websocket/test_listeners.py
- tests/types/test_parsed_signature.py
Add enhanced websocket support, making websocket handling a lot easier and feel more "Starlite".
The main features are two new classes:
1. The `websocket_listener`: A special websocket handler, listening and sending incoming data in a loop
2. `WebsocketListener`: An abstract base class building upon `websocket_listener` and allowing to define things in a more OOP way
<hr>
```python
from starlite.handlers.websocket_handlers import websocket_listener
@websocket_listener("/")
async def handler(data: str) -> str:
return data
```
this is equivalent to:
```python
from starlite import websocket, WebSocket
from starlite.exceptions import WebSocketDisconnect
@websocket("/")
async def handler(socket: WebSocket) -> str:
await socket.accept()
while True:
try:
data = await socket.receive_text()
await …
```
> Better websockets

- poetry.lock
- pyproject.toml
Pydantic has been made an optional dependency in #1431, but Litestar still depends on Pydantic in various places (some datastructures and as a default signature modelling backend). This PR reverts Pydantic to a non-optional dependency. …
> Revert Pydantic to a non-optional dependency

- litestar/app.py
- litestar/types/protocols.py
- tests/app/test_app.py
This fixes the behaviour reported in #1476.
- Make `Litestar.debug` into a property which updates the logging level and config of `litestar` logger accordingly when being set
- Add `Logger.setLevel` to the `Logger` protocol
[//]: # …
> Update `Litestar.logger` levels when setting `Litestar.debug`

- litestar/contrib/htmx/response.py
- tests/contrib/htmx/test_htmx_response.py
The HTMXTemplate class currently does not pass the context to `Template`  in the `to_response` method, making it difficult to server render templates with dynamic data.
> Pass context to HTMX Template response

- litestar/_signature/models/attrs_signature_model.py
- tests/signature/test_attrs_signature_modelling.py
Timestamp parsed as date with pydantic returns UTC date, while cattrs implementation was returning local date.
Correct issue in tests where UTC dates were compared to local dates.
Closes #1491
> Fix inconsistent parsing of unix timestamp between pydantic and cattrs.

- .pre-commit-config.yaml
- litestar/_openapi/schema_generation/schema.py
- litestar/testing/client/async_client.py
- litestar/testing/client/sync_client.py
- poetry.lock
- pyproject.toml
- tests/__init__.py
- tests/contrib/tortoise_orm/test_tortoise_orm_plugin_openapi_specs.py
- tests/openapi/test_spec_generation.py
- tests/openapi/typescript_converter/test_converter.py
This PR does as the title says - it adds OpenAPI Schema support for msgspec.Struct and attrs decorated classes. Additionally it ensures we generate identical schemas for all data container types, disregarding variations between dataclasses and pydantic etc.
> Support schema generation for attrs and msgspec classes

- litestar/contrib/repository/abc.py
- litestar/contrib/sqlalchemy/base.py
- litestar/contrib/sqlalchemy/repository.py
This PR aims to relax the SQLAlchemy contrib repository typing. This allows subclassing the repository while providing a Protocol based on declarative mixins as a type parameter, where the end-user model definition is not known.
As a side effect, the repository will accept any SQLAlchemy declarative model with a …
> Add SQLAlchemy repository model protocol

- litestar/utils/signature.py
- tests/utils/test_signature.py
This PR fixes an issue where accessing the `__module__` attribute of `object.__init__()` would fail with `'wrapper_descriptor' object has no attribute '__module__'`.
This occurs where the callable that is inspected is a class object without a user-defined `__init__()` method.
Closes #1504
[//]: # "Please add in issue …
> Fix retrieve type hints from class with no `__init__` method.

- docs/examples/conftest.py
- docs/examples/tests/application_hooks/test_application_after_exception_hook.py
- docs/examples/tests/application_state/test_using_application_state.py
- docs/examples/tests/middleware/test_logging_middleware.py
- docs/examples/tests/responses/test_background_tasks.py
- litestar/testing/client/async_client.py
- litestar/testing/client/sync_client.py
- tests/conftest.py
- tests/middleware/test_logging_middleware.py
A change was introduced in #1487 that would globally alter HTTPX' logging configuration, potentially breaking user code.
This PR changes this to use fixtures instead which restore the default configuration on cleanup.
[//]: # "Examples: …
> Move httpx log suppression into a fixture

- tests/contrib/jwt/test_token.py
- tests/dependency_injection/test_http_handler_dependency_injection.py
- tests/dependency_injection/test_websocket_handler_dependency_injection.py
- tests/life_cycle_hooks/test_after_response.py
- tests/middleware/session/test_server_side_backend.py
- tests/middleware/test_cors_middleware.py
- tests/test_stores.py
Speed up some tests by removing delays and improving patterns.
Two notoriously slow tests remain which are
https://github.com/litestar-org/litestar/blob/bab2ad40005b4e45c20ea8880a65126357828ee4/tests/contrib/jwt/test_auth.py#L40
and https://github.com/litestar-org/litestar/blob/bab2ad40005b4e45c20ea8880a65126357828ee4/tests/contrib/jwt/test_auth.py#L139
They both use hypothesis to generate a bunch of inputs. These should probably be integration tests that can be toggled selectively, and replaced with simpler unit tests for regular runs, but this is left as an exercise to the reader.
- follow …
> Speed up some tests

- litestar/_kwargs/extractors.py
- litestar/_kwargs/kwargs_model.py
- tests/dto/test_integration.py
- tests/kwargs/test_dto_extractor.py
This is something that can always be added back in if it turns out to be wanted, however, the original case for this was when DTO types were pydantic models. Now that they can be declared on the layers, I don't think it should be supported until we find a concrete use-case for it.
Additionally, if a user did want to interact with the DTO type directly, they could use DI and inject it.
Closes #1525. …
> Remove support for declaring DTOs as handler types.

- .github/workflows/docs.yaml
Fix an issue with the docs workflow that prevented it from running on pushes to `main`.
> Infra: Fix docs workflow not building on main

- litestar/app.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- tests/handlers/asgi/test_validations.py
- tests/handlers/http/test_head.py
- tests/handlers/http/test_media_type.py
- tests/handlers/http/test_validations.py
- tests/handlers/websocket/test_validations.py
Discussed in #1518 - this will allow route handler subtypes to customize production of the signature model. Aside from that, both of these methods reference the handler more than they reference the app, so homing them on the handler makes sense.
Changes route handler `on_registration()` callback to receive the app instance.
[//]: # "Please describe your pull request for new release changelog …
> `_set_runtime_callables()`/`_create_handler_signature_model()` as handler methods

- docs/release-notes/migration_guide_2.rst
- docs/usage/openapi.rst
- docs/usage/the-litestar-app.rst
- litestar/app.py
- litestar/middleware/logging.py
During development I noticed some inconsistencies in the docs with regards to importing
- `BaseLoggingConfig`
- `LoggingConfig`
- `StructLoggingConfig`
- `OpenAPIConfig`
- `StaticFilesConfig`
- `TemplateConfig`
These are not imported from `litestar.config.X` but rather `litestar.logging`. I'm not sure if `litestar.logging` is sufficient or if `litestar.logging.config` should be used.
[//]: # …
> Corrected several litestar.config imports in docs

- litestar/dto/factory/abc.py
- litestar/dto/factory/backends/abc.py
- litestar/dto/factory/backends/msgspec/backend.py
- litestar/dto/factory/backends/msgspec/utils.py
- litestar/dto/factory/config.py
- litestar/dto/factory/types.py
- tests/contrib/sqlalchemy/test_dto.py
- tests/dto/factory/backends/test_utils.py
- tests/dto/factory/test_abc.py
- tests/dto/factory/test_integration.py
- removes `include` parameter: as yet not totally clear to me how this should interact with `exclude`, especially once dotted excludes are introduced.
- `field_mapping` becomes `rename_fields`. `field_mapping` was also able to remap field types, but I'd rather separate the two behaviors.
- `field_definitions` removed - this needs more thought, as extra fields cannot just be marshalled into a model that doesn't have them defined. I believe this functionality will be replaced with a `ComputedField` that will allow multiple field definitions to be added to the ser/de model, and a callable that transforms them into a value for a model field. See #1563.
Also this PR fixed a bug where renamed fields weren't handled by the msgspec backend.
[//]: # "Please review the [Litestar contribution …
> Simplifies DTO config options.

- starlite/response/file.py
- tests/plugins/piccolo_orm/endpoints.py
- tests/static_files/test_file_serving_resolution.py
Backport of #1577 for v1.51
> Fix content-encoding headers for gzip/brotli compressed files not being set
Closes #1576
> Backport #1577 to v1.51

- poetry.lock
- pyproject.toml
The latest release of fakeredis (2.11.1) introduce a bug that causes state to be shared across instances, which makes some of our tests fail.  
This pins fakeredis to 2.11.0 to temporarily resolve this issue.
An issue has been opened in the fakeredis repo for this bug: https://github.com/cunla/fakeredis-py/issues/140 …
> Pin fakeredis to 2.11.0

- docs/examples/websockets/setting_custom_connection_headers.py
- docs/usage/websockets.rst
- litestar/handlers/websocket_handlers/_utils.py
- litestar/handlers/websocket_handlers/listener.py
- tests/handlers/websocket/test_listeners.py
This provides an avenue for parameters to be passed to `WebSocket.accept()`.
Closes #1571
> Adds `connection_accept_handler` to `websocket_listener`.

- docs/examples/data_transfer_objects/factory/excluding_fields.py
- docs/usage/dto/1-dto-factory.rst
- litestar/dto/factory/abc.py
- litestar/dto/factory/config.py
- litestar/dto/factory/types.py
- tests/dto/factory/test_abc.py
This PR adds support for excluding nested model fields using dot-notation, e.g., `"a.b"` excludes field `b` from nested model field `a`.
Closes #1197
> DTO Factory nested field exclusion.

- litestar/dto/factory/_backends/abc.py
- litestar/dto/factory/_backends/msgspec/backend.py
- litestar/dto/factory/_backends/msgspec/utils.py
- litestar/dto/factory/_backends/pydantic/backend.py
- litestar/dto/factory/_backends/pydantic/utils.py
- litestar/dto/factory/_backends/types.py
- litestar/dto/factory/_backends/utils.py
- litestar/dto/factory/abc.py
- litestar/dto/factory/types.py
- litestar/dto/factory/utils.py
- tests/dto/factory/backends/test_backends.py
- tests/dto/factory/test_abc.py
This PR moves the bulk of the logic for parsing a model type from `AbstractDTOFactory` to `AbstractDTOBackend`. This is purely a refactor - no functionality change - just moves functions (that were private anyway) to within the `_backend` module.
The immediate motivation for this is to move the implementation of `renaming_strategy` from the frontend to the backend. Our configuration for this closely mirrors that of msgspec, and so by making the field parsing part of the backend, this will allow us to defer field renaming to msgspec, or use our own implementation of the renaming strategy for other backend types.
By submitting this issue, …
> Moves model parsing into `AbstractDTOBackend`.

- docs/conf.py
Fix an error where v1.51 docs were still referencing the old domain and theme
> Docs v1.51: Update theme and branding

- litestar/connection/base.py
The `url_for` function types its kwargs unpack using the container type of `dict[str, Any]`. This should just use `Any`.
- [N/A] New code has 100% test coverage
- [N/A] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [N/A] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
[//]: # "Please …
> Fix the typing for `url_for` kwargs unpack

- litestar/handlers/websocket_handlers/_utils.py
- litestar/handlers/websocket_handlers/listener.py
- tests/handlers/websocket/test_listeners.py
Change the way a socket's lifespan - accepting the connection and calling the appropriate event hooks - to use a context manager. 
In addition to simplifying the code a bit, this also gives the opportunity to optionally supply a custom context manager, enabling to easily integrate functionalities that require context which outlives the lifespan of a socket. An example of this would be the functionality to be introduced in #1587. 
With this PR we could do
```python
async def socket_lifespan(socket: WebSocket) -> None:
await socket.connect()
async with channels_plugin.start_subscription("some_channel" as subscriber:
async with subscriber.run_in_background(socket.send_data):
yield
@websocket_listener("/ws")
def socket_handler(data: str, channels: ChannelsPlugin) -> None: …
```
> Enhancement: Managing a socket's lifespan using a context manager in websocket listeners

- .github/workflows/docs.yaml
- tools/build_docs.py
- tools/sphinx_ext/run_examples.py
We are currently experiencing a quite frequently failing CI because the examples run from the documentation sometimes don't produce output. This can be safely ignored during preview and CI builds.
[//]: # "Examples: Fixes #4321 or Closes …
> Docs: Don't fail preview builds when example output is missing

- litestar/handlers/websocket_handlers/_utils.py
- litestar/handlers/websocket_handlers/listener.py
- tests/handlers/websocket/test_listeners.py
Fix #1615.
The bug was caused by the positional `self` argument used in the handler methods, and the listener not passing on position arguments. 
> Fix #1615: Using `websocket_listener` in controller causes `TypeError: .handler_fn() got multiple values for argument 'socket'`

- tools/build_docs.py
Fix a misspelled argument name in `tools/build_docs.py`: `ignore_missing_output` > `ignore_missing_examples_output`
[//]: # "Please add in issue numbers this pull request will …
> Docs: Fix wrong CLI argument name

- litestar/connection/websocket.py
- litestar/serialization.py
- litestar/testing/websocket_test_session.py
- tests/connection/test_websocket.py
Add the following methods to `WebSocket`:
- `send_msgpack`: Send data as MessagePack
- `receive_msgpack`: Receive data and decode as MessagPack 
- `iter_data`: an async generator over data supporting `text` and `binary`
- `iter_json`: Like `iter_data` but decodes data as JSON
- `iter_msgpack`: Like `iter_data` but decodes data as MessagePack and only supports `binary` mode
Add the following methods to `WebSocketTestSession`:
- `send_msgpack`: Send data as MessagePack
- `receive_msgpack`: Receive data and decode as MessagPack 
[//]: # "- follow Litestar's [Code of …
> Enhancement: Add MessagePack support and generator methods to `WebSocket`

- docs/examples/application_state/using_application_state.py
- docs/examples/dependency_injection/dependency_skip_validation.py
- docs/examples/dependency_injection/dependency_validation_error.py
- docs/usage/dependency-injection.rst
- litestar/channels/plugin.py
- litestar/contrib/sqlalchemy/plugins/init/plugin.py
- litestar/di.py
- litestar/exceptions/__init__.py
- litestar/exceptions/base_exceptions.py
- tests/dependency_injection/test_dependency_validation.py
- tests/dependency_injection/test_http_handler_dependency_injection.py
- tests/dependency_injection/test_injection_of_classes.py
- tests/dependency_injection/test_injection_of_generic_models.py
- tests/dependency_injection/test_inter_dependencies.py
- tests/dependency_injection/test_request_local_caching.py
- tests/dependency_injection/test_websocket_handler_dependency_injection.py
- tests/handlers/websocket/test_listeners.py
- tests/kwargs/test_dependency_batches.py
- tests/kwargs/test_generator_dependencies.py
- tests/kwargs/test_query_params.py
- tests/kwargs/test_validations.py
- tests/openapi/test_parameters.py
- tests/openapi/test_schema.py
- tests/security/test_security.py
- tests/signature/test_parsing.py
- tests/test_dependency.py
- tests/test_parameters.py
- tests/test_provide.py
As discussed in https://github.com/litestar-org/litestar/pull/1638#discussion_r1188482488, this changes the functionality of `Provide` to issue a warning if used with a synchronous callable without setting `sync_to_thread` explicitly. 
This is meant to prevent pitfalls where a user might pass a synchronous dependency which is blocking and inadvertently blocks their whole application. Since the other option would be to use `sync_to_thread` by default, which would introduce a performance loss in cases where this isn't needed, simply issuing a warning is seen as a reasonable approach.
> Enhancement: Warn about sync dependencies without an explicit `sync_to_thread` value

- docs/conf.py
- litestar/handlers/websocket_handlers/_utils.py
- litestar/handlers/websocket_handlers/listener.py
- tests/handlers/websocket/test_listeners.py
Dependencies can be request an will be injected using the standard DI system.
This enables patterns like
```python
@asynccontextmanager
async def connection_lifespan(channel_name: str, socket: WebSocket, channels: ChannelsPlugin):
await socket.accept()
async with channels.start_subscription(channel_name) as subscriber:
async with subscriber.run_in_backgroun(socket.send_data):
yield
@websocket_listener("/{channel_name:str}", connection_lifespan=connection_lifespan)
def handler(data: str) -> None:
... # do something with data here
```
[//]: # "- follow Litestar's [Code of …
> Enhancement: Support dependencies in WS listener hooks

- litestar/_openapi/parameters.py
- litestar/config/app.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/http_handlers/decorators.py
- litestar/router.py
- litestar/types/composite_types.py
- tests/handlers/base/test_resolution.py
As discussed in #1305, add support for declaring dependencies without using `Provide`. The usage of `Provide` internally remains unchanged, and dependencies declared without `Provide` will simply be wrapped in it upon resolution.
[//]: # "Example: 'This pr adds the capability to use …
> Enhancement: Declaring dependencies without Provide

- docs/examples/data_transfer_objects/factory/patch_requests.py
- docs/examples/tests/data_transfer_objects/factory/test_example_apps.py
- docs/usage/dto/1-dto-factory.rst
- litestar/dto/factory/_backends/abc.py
- litestar/dto/factory/_backends/types.py
- litestar/dto/factory/_backends/utils.py
- litestar/dto/factory/config.py
- litestar/dto/factory/data_structures.py
- litestar/utils/signature.py
- tests/dto/factory/test_integration.py
This allows a DTO to be configured to handle PATCH requests by creating a union of the field definition with an empty sentinel.
We filter any unset values when extracting data from transfer models.
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in …
> Feature: Partial dtos

- litestar/contrib/repository/filters.py
Pydantic is unable to identify the type because it is nested in the `TYPE_CHECKING` block.  This change pins and ignores the warnings so that the "Unable to find forward references" …
> fix: fix filter `forward-ref` issues

- litestar/channels/plugin.py
- tests/channels/test_plugin.py
Fix a bug that would raise an error when repeatedly subscribing to and unsubscribing from the same channel while `arbitrary_channels_allowed=False`.
> Fix channels repeated unsubscribe bug

- pyproject.toml
Add a missing `sqlalchemy_aiosqlite` marker to the pytest configuration.
> Tests: Add missing aiosqlite marker

- litestar/di.py
- litestar/handlers/http_handlers/base.py
- litestar/utils/warnings.py
- tests/conftest.py
- tests/dependency_injection/test_dependency_validation.py
- tests/handlers/http/test_sync.py
- tests/kwargs/test_generator_dependencies.py
- tests/test_provide.py
- tests/test_response_caching.py
Add a warning when using `sync_to_thread=True` or `sync_to_thread=False` with asynchronous callables, as it will have no effect.
> Enhancement: Warn about `sync_to_thread` with async callables

- .github/workflows/test.yaml
Recently we've been introducing more integration tests that might hang indefinitely (behaviour observed multiple times already) due to a misconfigured tests, resource cleanup issues, issues with the docker containers being used etc. This PR introduces a hard limit of 10 minutes for the tests workflow, after which it will be cancelled.
> Infra: Set a timout for test workflow

- docs/usage/events.rst
- litestar/app.py
- litestar/events/emitter.py
- tests/events/test_listener.py
The changes introduced in #1635 allow a refactoring of event emitters to be trio-compatible, by removing `asyncio.Task` and `asyncio.Queue` and replacing them with task groups and streams.
Additional changes:
- `BaseEventEmitterBackend` now inherits from `AbstractAsyncContextManager` to make use of the lifespan context manager. The `on_startup` and `on_shutdown` methods have been subsequently removed.
> Enhancement: Trio compatible event-emitters

- litestar/_openapi/schema_generation/schema.py
- litestar/_signature/field.py
- tests/openapi/test_schema.py
> fix handling of pydantic field info in openapi schema

- litestar/contrib/sqlalchemy/types.py
When migrations are generated for models with a `GUID` type, it automatically adds in the `length=16` on the input.  However, we do not have this parameter on the `__init__` method. …
> fix: correction for alembic generated migrations.

- litestar/datastructures/state.py
- tests/datastructures/test_state.py
App state can be created using `deep_copy=False`, however state is then deep copied again for dependency injection.
This PR memoizes the value of `deep_copy` when state is created, and reuses it when copying the state.
Closes #1674
[//]: # "Example: 'This pr adds the capability to use …
> Store and reuse state `deep_copy` directive when copying state.

- litestar/handlers/http_handlers/base.py
- litestar/typing.py
- tests/utils/test_signature.py
When `ParsedType` was introduced, `is_subclass_of()` any union was deliberately left to return `False` with the intention of waiting for some use-cases to arrive.
This PR closes #1652 where a handler may be typed to return a union of multiple response types. If all response types are `Response` subtypes then the correct response handler will be applied.
If any of the union types are not response subtypes then behavior is still incorrect, but we should either handle that with validation or a special union response handler.
[//]: # "- follow Litestar's [Code of …
> `ParsedType.is_subclass_of(X)` true for union if all union types are subtypes of X.

- docs/usage/cli.rst
- litestar/cli/_utils.py
- litestar/cli/commands/core.py
- tests/cli/test_core_commands.py
This PR facilitates a command such as:
```sh
$ litestar run --reload-dir=. --reload-dir=../litestar/litestar
```
If `--reload-dir` is provided, `--reload` is implied.
If `--reload` is provided, and `--reload-dir` is not provided the behavior is same as before.
[//]: # "Example: 'This pr adds …
> Feature: add `--reload-dir` to `litestar run`

- .github/workflows/ci.yaml
- tools/build_docs.py
- tools/sphinx_ext/run_examples.py
Attempt to mitigate the various timeout related application example failures during the documentation building process.
1. Fix a bug that would lead to application servers not being killed properly
2. Cycle through ports rather than re-use them immediately
3. Ignore missing outputs when building the preview
> Infra: Fix run examples timeout

- litestar/contrib/mako.py
- tests/template/test_template.py
This PR configures the mako template engine to autoescape expressions, making it consistent with config of jinja template engine.
Closes #1699
[//]: # "Please add in issue numbers …
> Consistent template autoescape behavior.

- litestar/channels/plugin.py
- tests/channels/test_plugin.py
Adds `ChannelsPlugin` name to signature namespace when plugin inits the app.
Closes #1691
[//]: # …
> Channels plugin signature namespace population.

- litestar/dto/factory/_backends/utils.py
- tests/dto/factory/test_integration.py
This PR fixes an issue where data that should be transferred to builtin types on instantiation of `DTOData` was being instantiated into a model type for nested models.
Closes #1726  …
> Fix: premature transfer to nested models with DTOData

- docs/examples/application_hooks/after_exception_hook.py
- docs/examples/application_hooks/before_send_hook.py
- litestar/app.py
- litestar/contrib/sqlalchemy/plugins/init/config/asyncio.py
- litestar/contrib/sqlalchemy/plugins/init/config/sync.py
- litestar/middleware/exceptions/middleware.py
- litestar/types/callable_types.py
- litestar/utils/__init__.py
- litestar/utils/sync.py
- tests/app/test_before_send.py
- tests/middleware/test_exception_handler_middleware.py
Remove the `state` paremeter from `AfterExceptionHookHandler` and `BeforeMessageSendHookHandler`.
This was largely unnecessary, as both already receive the `scope`, via which the state is accessible. It also makes them conform to the rest of the handler signatures, from which the `state` has been removed either in favour of `scope` or `app`, both of which make it possible t access the application's state.
[//]: # "- follow Litestar's [Contribution …
> Unify hook handler signatures

- tests/kwargs/test_generator_dependencies.py
Remove the `sync_to_thread` parameter from generator dependency tests.
Because of the warning introduced in #1716, these tests would raise a warning. 
[//]: # "Please add in issue …
> Fix `sync_to_thread` usage in generator dependency tests

- litestar/_openapi/schema_generation/schema.py
- litestar/app.py
- litestar/di.py
- litestar/file_system.py
- litestar/handlers/asgi_handlers.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/websocket_handlers/route_handler.py
- litestar/partial.py
- litestar/utils/__init__.py
- litestar/utils/dataclass.py
- litestar/utils/predicates.py
- litestar/utils/sync.py
- tests/test_utils.py
- tests/utils/test_dataclass.py
Moved predicates in `utils/` to `utils.predicates.py` for consistency
This PR moves predicates from `utils/sync.py` and `utils/dataclass.py` to `utils.predicates.py` for consistency
This PR closes #1730
> Refactor: Move all util predicates to utils.predicates.py

- litestar/contrib/sqlalchemy/dto.py
- litestar/dto/factory/_backends/utils.py
- tests/contrib/sqlalchemy/test_dto_integration.py
This PR adds support for SQLAlchemyDTO field generation to recognize hybrid properties and association proxies.
In either case, the generated `FieldDefinition` is marked read-only.
Closes #1752 
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the …
> Feature: SQLAlchemyDTO support for hybrid properties and association proxies.

- sonar-project.properties
The reason for this duplication is due to having sync and async versions of the same code. We've discussed using tools to autogenerate one from the other in discord, but in the meantime this feels reasonable to exclude from checks.
[//]: # "Example: 'This pr adds the capability to use …
> Chore: exclude repository modules from sonar duplication checks.

- litestar/dto/factory/_backends/utils.py
- litestar/typing.py
- litestar/utils/typing.py
- tests/dto/factory/test_integration.py
The generic collection is substituted with a concrete instantiable type.
Closes #1763
[//]: # …
> Support transfer to generic collection types.

- .pre-commit-config.yaml
- litestar/contrib/repository/filters.py
- litestar/dto/exceptions.py
- litestar/dto/factory/abc.py
Ref: https://flake8-dunder-all.readthedocs.io/en/latest/usage.html#cmdoption-ensure-dunder-all-use-tuple
[//]: # "Please add in issue numbers this pull request will close, if …
> Add `--use-tuple` arg to dunder-all check.

- docs/conf.py
Fix links in the "About" menu, which currently lead to non-existing pages
> Docs: Fix "about" section links

- litestar/contrib/msgspec.py
- litestar/contrib/pydantic.py
- litestar/contrib/sqlalchemy/dto.py
- litestar/dto/factory/_backends/abc.py
- litestar/dto/factory/_backends/types.py
- litestar/dto/factory/_backends/utils.py
- litestar/dto/factory/field.py
- litestar/dto/factory/stdlib/dataclass.py
- litestar/dto/factory/types.py
- tests/contrib/conftest.py
- tests/contrib/sqlalchemy/test_dto_integration.py
- tests/dto/factory/backends/test_abc.py
- tests/dto/factory/backends/test_backends.py
- tests/dto/factory/test_stdlib.py
In addition to the read-only `FieldDefinition` generated for the getter method of the hybrid property, if a setter method is defined an additional write-only `FieldDefinition` is generated that is typed to the argument of the setter callable.
Fixes issue where expression method names were being added to the DTO fields as field types (closes #1769).
Adds the `Mark.WRITE_ONLY` field mark for write-only fields.
Adds `FieldDefinition.dto_for`. This property allows the field definitions to declare whether they should be used for inbound or outbound transfer, and is intended to support cases where inbound data transfer may accept a different type than is delivered
by outbound data transfer.
[//]: # "Please review the [Litestar contribution …
> SQLAlchemyDTO: Improved handling of `hybrid_property`.

- litestar/contrib/sqlalchemy/types.py
- tests/contrib/sqlalchemy/repository/oracledb/test_sqlalchemy_oracledb_json.py
This change is an Oracle specific enhancement that ensures a JSON check constraint is created when creating a JSON column.
Co-authored-by: Alc-Alc <45509143+Alc-Alc@users.noreply.github.com>
[//]: # "Example: 'This pr adds the capability to use server-sent events, and documents it in the …
> feat: create JSON check constraint for Oracle dialect.

- pyproject.toml
Intended to filter warnings like ```DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.```
[//]: # "Please add in issue numbers this pull request …
> Fix filterwarnings for pkg_resources.

- litestar/types/composite_types.py
Typed as `Mapping` makes it difficult to interact with downstream, e.g., on `AppConfig`.
Closes #1442 
[//]: # "Please add in issue numbers this pull request will close, if …
> Change `ExceptionHandlersMap` to `MutableMapping`.

- tests/cli/test_core_commands.py
Reduce the exponential growth of CLI tests by grouping related parametrisations that don't necessarily need to be tested in all possible combinations.
> Reduce exponentially growth of CLI tests

- docs/examples/data_transfer_objects/factory/excluding_fields.py
- docs/examples/tests/data_transfer_objects/factory/test_example_apps.py
- docs/usage/dto/1-dto-factory.rst
Expands the DTO Factory usage docs for Excluding Fields to include description of how to exclude from nested and collections of nested fields.
Closes #1639
[//]: # "Please add in …
> DTO usage docs: excluding from nested fields.

- litestar/dto/factory/_backends/abc.py
- litestar/dto/factory/_backends/utils.py
- litestar/typing.py
- litestar/utils/typing.py
- tests/contrib/sqlalchemy/test_dto.py
- tests/dto/factory/test_integration.py
DTO would fail where a builtin collection type was used as an annotation without any generic arguments, e.g., `a: dict`.
This PR corrects this by inferring the inner types as `Any` if they don't otherwise exist.
[//]: # "Example: 'This pr adds the capability to use server-sent events, and …
> Data transfer for non-generic builtin collection annotations.

- litestar/contrib/sqlalchemy/base.py
- tests/contrib/sqlalchemy/repository/test_sqlalchemy_async.py
- tests/contrib/sqlalchemy/repository/test_sqlalchemy_sync.py
Currently, when calling `to_dict` on a model, it includes all columns that haven't been excluded.  If a column has been excluded with `load_only` it will cause an exception to be raised on an `AsyncSession`.  This PR excludes any column that hasn't been loaded.
[//]: # "Example: 'This pr …
> feat: exclude unloaded columns on `to_dict`

- tests/contrib/htmx/test_htmx_request.py
- tests/contrib/htmx/test_htmx_response.py
- remove redundant `media_type` declarations on handlers. Handlers were
returning responses that have their own media type defaults.
- where appropriate, return values direct from handlers, without wrapping in `Response`.
I noticed these while doing some prep work for #1790.
[//]: # …
> Refactor: HTMX contrib tests

- docs/usage/security/abstract-authentication-middleware.rst
The documentation for the v2 contains
```python
from litestar.authentication import (
AbstractAuthenticationMiddleware,
AuthenticationResult,
)
```
which is not existing.
The correct imports are `from litestar.middleware`.
AbstractAuthenticationMiddleware,  AuthenticationResult are imported in : https://github.com/litestar-org/litestar/blob/main/litestar/middleware/__init__.py
> Fix: Documentation for Authentication middleware has wrong imports

- litestar/handlers/asgi_handlers.py
- litestar/handlers/base.py
- litestar/handlers/http_handlers/base.py
- litestar/handlers/websocket_handlers/route_handler.py
- tests/handlers/base/test_validations.py
It appears this pattern was to support annotation of the `ownership_layers` property, but this would more conventionally be done with `Self`.
[//]: # "Please add in issue numbers …
> Refactor: remove generic base from BaseRouteHandler.

- docs/usage/the-litestar-app.rst
- litestar/_signature/utils.py
- litestar/app.py
- litestar/config/app.py
- litestar/handlers/base.py
- litestar/handlers/websocket_handlers/listener.py
- litestar/testing/helpers.py
- pyproject.toml
- sonar-project.properties
- tests/app/test_app_config.py
- tests/dto/test_attrs_fail.py
- tests/dto/test_integration.py
- tests/openapi/test_parameters.py
- tests/signature/test_parsing.py
- tests/signature/test_utils.py
- tests/test_parameters.py
- Make the `preferred_validation_backend` parameter private
- Make the `Litestar.preferred_validation_backend` attribute private
- Remove the `preferred_validation_backend` from `AppConfig`
- Simplify logic for selecting a validation backend: If the preferred backend is set to `attrs`, or the signature contains attrs types, `attrs` is selected. In all other cases, Pydantic will be used.
This exposes less of the implementation details to the user, so that we can more easily implement the proposed changes in preparation of the 2.0 release, while keeping current functionality intact.
> Make `preferred_validation_backend` private

- litestar/middleware/logging.py
- litestar/response/base.py
- litestar/serialization.py
- litestar/utils/scope.py
- tests/response/test_base_response.py
- tests/utils/test_scope.py
This is prep for #1790, I've split the change out for clearer discussion.
The PR removes the `Response.get_serializer()` method in favor of a `get_serializer()` function in `serialization.py`.
In the current `Response` implementation, `get_serializer()` is called on the response inside `Response.__init__()`, and the merging of class-level `type_encoders` with `Response` argument `type_encoders` is done inside the `get_serializer()` method.
In the #1790 version of `Response`, the response body is not encoded until after the response object has been returned from the handler, and it is converted into a low-level `ASGIResponse` object. Due to this, there is still opportunity for the handler layer resolved `type_encoders` object to be merged with the `Response` defined `type_encoders` - hence …
> Refactor: moves `Response.get_serializer()` to `serialization.get_serializer()`.

- litestar/_openapi/parameters.py
- litestar/_openapi/request_body.py
- litestar/_openapi/responses.py
- litestar/_openapi/schema_generation/constrained_fields.py
- litestar/_openapi/schema_generation/schema.py
- litestar/dto/factory/_backends/abc.py
- litestar/dto/factory/abc.py
- litestar/dto/interface.py
- tests/dto/factory/backends/test_backends.py
- tests/dto/factory/test_abc.py
- tests/dto/test_interface.py
- tests/openapi/test_config.py
- tests/openapi/test_constrained_fields.py
- tests/openapi/test_request_body.py
- tests/openapi/test_responses.py
- tests/openapi/test_schema.py
- Add a `prefer_alias` parameter to `litestar._openapi.schema_generation.create_schema` & friends
- Set it to False for response schemas and True otherwise.
Fixes #1809
> Fix OpenAPI schema generation for aliased Pydantic field in responses

- litestar/_openapi/responses.py
This PR introduces two behavioural differences:
1. template response media types aren't necessarily always HTML.
2. don't mutate the state of the handler media type configuration during schema generation.
Regarding the first change. If the return annotation of the handler is a `Template` response, currently we use `MediaType.HTML` for the response content, ignoring what may have already been defined on the handler. This PR only defaults to `MediaType.HTML` if it isn't already defined. I believe this is correct, as template documents don't have to be HTML, although that would be the most common.
Regards the 2nd change, instead of mutating the handler inside the openapi generation, this PR introduces a local variable to carry the media type for the function. This is not fixing a known …
> Refactor: openapi handler media types

- litestar/handlers/http_handlers/_utils.py
- litestar/handlers/http_handlers/base.py
- tests/handlers/http/test_to_response.py
Current behavior is to set cookies on asgi responses from handlers if the response type has a `set_cookie()` method. This looks like it is specific handling for starlette responses, as they are the only tests that broke on its removal.
If we want to continue to explicitly support this for starlette response types, we can create a specific response handler for them that does set cookies, however, IMO we have diverged far enough from starlette to not warrant the specific logic.
[//]: # "- follow Litestar's [Code of Conduct](https://github.com/litestar-org/.github/blob/main/CODE_OF_CONDUCT.md) …
> Refactor: remove set-cookie ops on genric asgi responses.

- litestar/testing/client/async_client.py
- litestar/testing/client/sync_client.py
- litestar/testing/helpers.py
- litestar/testing/transport.py
- tests/testing/test_sync_test_client.py
Add a `timeout` parameter to `TestClient`, `AsyncTestClient`, `create_test_client` and `create_async_test_client`. The value is passed down to the underlying HTTPX client and serves as a default timeout for all requests.
> Add `TestClient` default timeout

- .pre-commit-config.yaml
- litestar/contrib/sqlalchemy/repository/_async.py
- litestar/contrib/sqlalchemy/repository/_sync.py
- pyproject.toml
Remove some unnecessary imports from the SQLA repositories, which were needed to a previous limitation of unasyncd.
> Simplify SQLA repo imports

- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_sqlalchemy_oracledb_json.py
Add a missing `sqlalchemy_integration` marker to the SQLA repository tests for oracledb
> Add missing marker to SQLA oracle JSON tests

- litestar/middleware/exceptions/middleware.py
- tests/examples/test_dto/test_example_apps.py
- tests/examples/test_dto/test_tutorial.py
- tests/unit/test_exceptions.py
- tests/unit/test_kwargs/test_generator_dependencies.py
- tests/unit/test_middleware/test_base_authentication_middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
- tests/unit/test_middleware/test_session/test_middleware.py
- tests/unit/test_signature/test_parsing.py
- tests/unit/test_template/test_built_in.py
- tests/unit/test_template/test_template.py
Always use "Internal Server Error" as default detail for 500 errors so that our default behavior limits leaking implementation detail.
Closes #1856 
[//]: # "Please add in issue …
> Fix: Internal Server Error detail

- litestar/_signature/models/attrs_signature_model.py
- litestar/_signature/models/base.py
- litestar/_signature/models/pydantic_signature_model.py
- litestar/_signature/utils.py
- tests/unit/test_signature/test_parsing.py
This PR updates the keys in validation error responses to include the full path to the field with the issue. This gives the developer a better sense of where the failure happened.
It also adds an optional `source` key that designates whether the value is from the body, a cookie, a header, or a query param.
With the following controller
```python
from litestar import Controller
from pydantic import BaseModel, ValidationError
class Child(BaseModel):
my_value: str
class Parent(BaseModel):
child: Child
class SomeController(Controller):
@post('/some-route')
def some_route(
self,
data: Parent,
int_param: int,
int_header: int = Parameter(header="X-SOME-INT"),
int_cookie: int = Parameter(cookie="int-cookie"), 
) -> Parent:
return data
```
and the request
```bash
http POST …
```
> Increase verbosity of validation error response keys

- .pre-commit-config.yaml
- litestar/_signature/models/pydantic_signature_model.py
- poetry.lock
- tests/unit/test_params.py
This PR fixes a small regression in the pydantic signature model logic, which was caused by the renaming of `regex` -> `pattern` (pattern is used by pydantic v2 and everyone else).
> chore: fix pydantic v1 regex validation

- litestar/contrib/sqlalchemy/dto.py
- litestar/dto/factory/_backends/utils.py
- tests/unit/test_contrib/test_sqlalchemy/test_dto.py
If type annotations aren't available for a given column/relationship we make an effort to infer a type annotation from the relevant SQLAlchemy object.
For columns, we use the `Column.type.python_type` attribute as the type of the column, and the `Column.nullable` property to determine if the field should have a `None` union.
For relationships, where the `RelationshipProperty.direction` is `ONETOMANY` or `MANYTOMANY`, we use the `RelationshipProperty.collection_class` and the `RelationshipProperty.mapper.class_` attribute to construct an annotation for the collection.
For `ONETOONE` relationships, we use the `RelationshipProperty.mapper.class_` to get the type annotation, and make the type a union with `None` if all of the foreign key columns are nullable.
Closes #1853
[//]: # "Please …
> SQLAlchemyDTO: column/relationship type inference.

- litestar/contrib/sqlalchemy/base.py
This PR changes the `AuditColumns` mixin to the desired behavior. Currently, the default value is whatever `datetime.now(timezone.utc)` evaluates to when `AuditColumns` is first evaluated.
I can create one if you want.
> Make audit columns not always default to app startup time

- poetry.lock
- pyproject.toml
- tests/unit/test_channels/test_plugin.py
This PR pins the redis version to the 4.4.4+ range, because the tests fail on redis 4.5.* and above.
Note- py-redis is about to release v5.0.0 in the near future, and we will need to tackle this.
> Pin Redis version

- litestar/contrib/sqlalchemy/base.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_bigint.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_uuid.py
Fixes #1905
Updates the column name attribute from `updated` to `updated_at`.
The existing test case to verify this was incorrect, so we didn't catch this earlier.
[//]: # "Please …
> fix: SQL Alchemy repository `updated` vs `updated_at` column reference.

- litestar/contrib/sqlalchemy/repository/_async.py
- litestar/contrib/sqlalchemy/repository/_sync.py
- tests/unit/test_contrib/test_sqlalchemy/models_bigint.py
- tests/unit/test_contrib/test_sqlalchemy/models_uuid.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/conftest.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_bigint.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_uuid.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_sqlalchemy_async.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_sqlalchemy_sync.py
Fixes #1895
This PR does the following:
- exposes the `attribute_names` and `with_for_update` parameters on functions that execute `session.refresh`
- Adds `auto_commit` parameter.  When this is true, the session will `commit` instead of `flush` before returning (default=False).
- Adds `auto_refresh` parameters.  When this is true, the session will execute `refresh` objects  before returning (default=True).
- Adds `auto_expunge` parameters.  When this is true, the session will execute `expunge` on all objects before returning (default=True).(default=True).
[//]: # "- follow Litestar's …
> feat: Make repository `refresh` and `expunge` optional, Adds `auto_commit` option.

- pyproject.toml
I've detailed my reasons inside the maintainer discord channel, however the primary reason for my decision is to hopefully find a place where I can once again enjoy the investment that I make with my free time toward the project.
I still intend to contribute in all aspects of the project as any interested contributor to an open source project would, as time allows. …
> Remove self from maintainer list.

- .pre-commit-config.yaml
- docs/conf.py
- litestar/datastructures/headers.py
- poetry.lock
- tests/unit/test_datastructures/test_headers.py
This PR does after merge cleanup of headers- removing the unnecessary .dict method (legacy of pydantic), and resolving the documentation failures.
> chore(refactor): clean-up headers

- .github/workflows/pr-title.yaml
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- docs/conf.py
- poetry.lock
- pyproject.toml
This PR does the following:
1. it adds conventional-commit pre-commit hook. This follows [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
2. it add s the semantic-PR github action, which enforces conventional PR titles following the same style guide.
3. it updates the readme and contribution guidelines to explain this.
4. it comments our the poetry action, since it currently bugs out.
> feat(infra): add conventional commit pre-commit and semantic pull request workflow

- Makefile
I agree to:
See docs about `.PHONY` targets and why it is important: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
Usually changes like this do not need a changelog entry
No issue exists, I can open one if needed.
> chore: Add proper `.PHONY` markers to all targets in `Makefile`

- litestar/types/helper_types.py
All other files in https://github.com/litestar-org/litestar/tree/main/litestar/types use explicit `TypeAlias` annotations.
The only one that does not is now fixed :)
P.S. I am reading though the code base right now, I really like the project. Thanks for creating it! 👏 
Do you welcome small contributions like this? Or do you value decreasing code churn more?
> style: Use explicit `TypeAlias` type in `helper_types`

- litestar/config/response_cache.py
- litestar/types/empty.py
mypy soon will have special narrowing for `@final` singleton types: https://github.com/python/mypy/pull/15646
So, it is a good idea to use `@final` for such types.
> style: Mark `Empty` and `CACHE_FOREVER` as `@typing.final`

- .pre-commit-config.yaml
- litestar/contrib/jwt/jwt_token.py
- mypy.ini
The problem is that `additional_dependencies` are usually out of sync with `pyproject.toml`.
Plus, for some reason `ignore_missing_imports = True` is implied in `pre-commit`, but because I am not a user of `pre-commit`, I have no idea why this happens :)
After my changes:
```
» mypy litestar                                      
Success: no issues found in 303 source files
```
Closes #1960
> chore(infra): fix local run of mypy

- tests/unit/test_channels/test_plugin.py
#1896 introduced some changes that would cause some individual channels tests to run for 30+ seconds. This has been reverted and the underlying cause addressed by giving the flaky tests more attempts to re-run.
> test(channels): Fix long-running channels plugin tests.

- pyproject.toml
Follow up to https://github.com/litestar-org/litestar/pull/1976
I forgot this section from `mypy.ini`: https://github.com/litestar-org/litestar/commit/11f0235ce1c0eec31b92a367d976e4903cef659a#diff-6f2d4ba9ca9a357d31014946667b7bed1bfdbc6d2530afc77778fa0a36bee457L21-L23
Please, see this comment to see the failure results: https://github.com/litestar-org/litestar/pull/1976#issuecomment-1637067589
> fix(infra): mypy should ignore untyped decorators in tests

- docs/release-notes/changelog.rst
Add the missing changelog for the `2.0.0beta2` release.
> chore: Add missing changelog entry for `2.0.0beta2`

- litestar/_openapi/schema_generation/examples.py
- litestar/contrib/pydantic/__init__.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/testing/request_factory.py
- tests/e2e/test_routing/test_path_resolution.py
- tests/unit/test_contrib/test_jwt/test_auth.py
- tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py
- tests/unit/test_controller.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_handlers/test_http_handlers/test_to_response.py
- tests/unit/test_kwargs/test_json_data.py
- tests/unit/test_kwargs/test_multipart_data.py
- tests/unit/test_kwargs/test_reserved_kwargs_injection.py
- tests/unit/test_kwargs/test_url_encoded_data.py
- tests/unit/test_response/test_serialization.py
- tests/unit/test_security/test_session_auth.py
- tests/unit/test_testing/test_request_factory.py
We now have two internal compat helpers to call `.model_dump` or `.dict`, and `.model_dump_json` or `.json` methods.
Closes #1996
> fix(pydantic): `.json` and `.dict` deprecation warnings for `pydantic@2`

- docs/index.rst
> docs: Use `dict[str, int]` instead of `JSONResponse`

- .pre-commit-config.yaml
- docs/examples/pagination/using_offset_pagination_with_sqlalchemy.py
- litestar/_multipart.py
- litestar/_signature/model.py
- litestar/datastructures/headers.py
- litestar/dto/_backend.py
- litestar/typing.py
- poetry.lock
- tests/docker_service_fixtures.py
- tests/unit/test_contrib/test_sqlalchemy/models_bigint.py
- tests/unit/test_contrib/test_sqlalchemy/models_uuid.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_generic_mock_async_repository.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_generic_mock_sync_repository.py
- tests/unit/test_data_extractors.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_handlers/test_http_handlers/test_kwarg_handling.py
- tests/unit/test_kwargs/test_multipart_data.py
- tests/unit/test_testing/test_async_test_client.py
This PR fixes a bug with multipart handling, where empty string values raised a validation error.
> fix(multipart): serialization on multipart form

- litestar/contrib/sqlalchemy/repository/_async.py
- litestar/contrib/sqlalchemy/repository/_sync.py
- Replace the `**kwargs` usages in the repository methods with typed parameters
- Add docstrings for the newly added parameters
> feat(sqla-repo): replace **kwargs usage with typed parameters

- litestar/_openapi/schema_generation/constrained_fields.py
- litestar/_openapi/schema_generation/examples.py
- litestar/_openapi/schema_generation/schema.py
- litestar/contrib/piccolo.py
- tests/unit/test_contrib/test_piccolo_orm/test_piccolo_orm_dto.py
- tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py
This PR updates the import for decimal to `decimal` from `_decimal`.  This was incorrectly causing import errors in certain installation.
-
-
> fix: updates import to `decimal` from `_decimal`

- litestar/contrib/repository/abc/_async.py
- litestar/contrib/repository/abc/_sync.py
- litestar/contrib/sqlalchemy/repository/_async.py
- litestar/contrib/sqlalchemy/repository/_sync.py
The PR allows the `id_attribute` setting to be overridden without changing the entire class configuration.
This is useful if you want to quickly use the `get` or `delete` method by another candidate/surrogate key such as `slug`.
-
[//]: # "Examples: …
> feat(repo): allow `id_attribute` to be customized per method

- docs/usage/cli.rst
- litestar/app.py
- litestar/cli/_utils.py
- litestar/cli/commands/core.py
- litestar/cli/main.py
- litestar/plugins.py
- tests/unit/test_cli/conftest.py
- tests/unit/test_cli/test_cli_plugin.py
Add a new `CLIPluginProtocol` that can be used to create CLI plugins.
These contain a single method `on_cli_init`, which will be called when the CLI is initialised. This allows to dynamically register commands, without having to deal with the optional click dependency.
```python
from litestar import Litestar
from litestar.plugins import CLIPluginProtocol
class CLIPlugin(CLIPluginProtocol):
def on_cli_init(self, cli):
@cli.command()
def is_debug_mode(app: Litestar):
print(app.debug)
app = Litestar(plugins=[CLIPlugin()])
``` 
```shell
$ litestar is-debug-mode
Using Litestar app from app:app
False
```
> feat(cli): CLI plugins

- litestar/middleware/session/server_side.py
- tests/unit/test_middleware/test_session/test_middleware.py
Fix a bug that would cause the `ServerSideSessionBackend` to override existing cookies.
Closes #2033
> fix(sessions): Fix #2033 - Server-side session middleware overrides CSRF cookies

- litestar/_signature/model.py
- litestar/_signature/types.py
- litestar/_signature/utils.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/handlers/base.py
- litestar/handlers/websocket_handlers/listener.py
- poetry.lock
- pyproject.toml
- tests/examples/test_contrib/test_sqlalchemy/plugins/test_tutorial_example_apps.py
- tests/unit/test_kwargs/test_cookie_params.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_response/test_response_to_asgi_response.py
- tests/unit/test_signature/test_parsing.py
- tests/unit/test_signature/test_validation.py
This PR improves our deserialization by pre-calculating the required decoders for the signature. 
I added a hack to bypass msgspec, which strips Annotated before hitting the hooks. I hope this is temporary - see: https://github.com/jcrist/msgspec/issues/497
> feat: pre-calculate decoders in signature model

- pyproject.toml
- tests/examples/test_todo_app.py
- Move tests located in `docs/examples` to `tests/examples` that were overlooked when refactoring the tests in #1850.
- Remove some unused pytest configuration from `pyproject.toml`
> refactor(tests): Move tutorial example tests to tests directory

- litestar/contrib/repository/abc/_async.py
- litestar/contrib/repository/abc/_sync.py
- litestar/contrib/sqlalchemy/repository/_async.py
- litestar/contrib/sqlalchemy/repository/_sync.py
- litestar/contrib/sqlalchemy/repository/_util.py
- tests/unit/test_contrib/test_sqlalchemy/test_repository/test_repo_bigint.py
> feat(sqla-repo): Support InstrumentedAttribute

- litestar/utils/__init__.py
- litestar/utils/sequence.py
Remove the unused and undocumented `utils.sequence.compact` function
> chore(utils): remove unused and undocumented `compact` function

- litestar/events/emitter.py
- tests/unit/test_events.py
Change listeners in the `SimpleEventEmitter` to run concurrently within an `anyio.TaskGroup`
> feat(events): run listeners concurrently

- tests/examples/test_contrib/test_piccolo/test_piccolo_crud.py
- tests/examples/test_contrib/test_sqlalchemy/plugins/test_example_apps.py
- tests/examples/test_plugins/test_sqlalchemy_init_plugin.py
Refactor test that use SQLite (SQLAlchemy / piccolo) to use an in-memory SQLite database instead of a file
> refactor(tests): use in-memory SQLite databases for testing where possible

- litestar/testing/life_span_handler.py
- tests/unit/test_testing/test_lifespan_handler.py
- Replace the `AssertionError` in `LifeSpanHandler.wait_startup` and `LifeSpanHandler.wait_shutdown` with a `RuntimeError`, providing a useful error message
- Add tests for `wait_startup` and `wait_shutdown`
> fix(testing): Remove `AssertionErrors` in LifeSpanHandler wait_startup and wait_shutdown methods

- docs/reference/index.rst
- docs/reference/partial.rst
Remove references in the docs to the removed `partial.py` module
> docs: remove references to removed `partial` module

- tests/docker_service_fixtures.py
Removes the usage of `shell=True` for docker related subprocess calls on macOS. Implementation is same as the one here https://github.com/cofin/litestar-fullstack/pull/40
-
-
> test(docker-service-fixture): Remove usage of `shell=True`

- tests/docker_service_fixtures.py
Modify the subprocess call to utilize the preferred method of running docker compose instead of using the docker-compose executable.
-
-
> test(docker-service-fixture): Replace `docker-compose` with `docker compose`

- .github/CODEOWNERS
- starlite/config/logging.py
- This PR is to fix #1948, but the only way I have been able to resolve it is through changing the type hint to `Any`. I do not think this is the right resolution, i have tried do a couple of other things but nothing has worked... would like input so I can learn.
[//]: # "Please add in issue numbers this pull request will close, if …
> fix(v1.51): #1948 passing wrapper class to struct logging config causes pydantic exception

- litestar/dto/_backend.py
- tests/unit/test_dto/test_factory/test_backends/test_utils.py
- tests/unit/test_dto/test_factory/test_integration.py
`DTOData` `create_instance` does not support renaming strategies. This should be a hacky fix.
-
-
> fix: renamed fields in DTOData create instance 

- litestar/contrib/sqlalchemy/dto.py
- tests/unit/test_contrib/test_sqlalchemy/test_dto_integration.py
- SQLAlchemy `composite` types were not support for SQLAlchemy DTOs
- In addition to including the composite type in the DTO, the columns that make up the composite types are now hidden. This is the desired behaviour.
[//]: # "Examples: Fixes #4321 or …
> feat: support composite type for SQLAlchemy DTO

- litestar/dto/_backend.py
- tests/unit/test_dto/test_factory/test_backends/test_backends.py
The attributes were accessed prematurely during the transfer process. This has been fixed by moving the check to after it has already been determined that the attribute is included.
- #2125
> fix(dto): Fix #2125 - excluded attributes being accessed during transfer

- .all-contributorsrc
- litestar/_openapi/responses.py
- poetry.lock
- tests/unit/test_openapi/test_responses.py
This PR fixes a bug in the response schema where `contentEncoding` had a default of `application/octet-stream`, which actually should be the default of `contentMediaType`.
> fix: moved application/octet-stream from contentEncoding to contentMediaType

- litestar/contrib/sqlalchemy/plugins/init/config/common.py
- tests/unit/test_contrib/test_sqlalchemy/test_init_plugin/test_common.py
This pr adds proper handling for SQLAlchemy dialects that do not support JSON types
Fixes #2137
> fix: handle dialects that don't support json

- litestar/dto/_backend.py
- litestar/dto/data_structures.py
- tests/unit/test_dto/test_factory/test_backends/test_utils.py
- tests/unit/test_dto/test_factory/test_integration.py
Implementing a fix for `DTOData` #2065  introduced a new bug. Originally, fields passed to `DTOData.create_instance` were handled using their serialized names. For example, when using camel case for an excluded field `entity_id`, `data.create_instance(entityId="1")` would work  but `data.create_instance(entity_id="A")` wouldn't. …
> fix: DTOData bug with renamed fields

- litestar/_openapi/path_item.py
- tests/unit/test_openapi/test_config.py
As brought up on Discord few weeks ago, the generated OpenAPI schema should agree with the actual response for aliased Pydantic fields but it doesn't since [this change](https://github.com/litestar-org/litestar/commit/702037026719c2c7af65735f04c70fd845db403a#diff-271e0f4f9a138cb2276b567323c4695a6e8ef6eff01395cd799b50ae9bcf6420L91).
> fix: set model response to NOT prefer alias

- litestar/cli/commands/core.py
- litestar/middleware/exceptions/middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Change `ExceptionHandlerMiddleware` to use the current application's debug value rather than assigning it statically at creation / startup time.
-
- #2147
> fix(exception-handling): Fix #2147 - setting app debug does not propagate to exception handling middleware

- .pre-commit-config.yaml
- litestar/_asgi/routing_trie/traversal.py
- litestar/security/session_auth/middleware.py
- poetry.lock
- pyproject.toml
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_openapi/test_parameters.py
- tests/unit/test_static_files/test_file_serving_resolution.py
This PR fixes an issue with static routing where static file serving failed if a route handler was defined for the base path of the static file serving.
Additionally two fixes for tests are added.
> fix(routing): support serving static files from a route used by a route handler

- litestar/contrib/htmx/request.py
I noticed there seemed to be an issue setting the apps `request_class` to `HTMXRequest`.
The CSRF middleware doesn't initialize the `request_class` with a `send` argument, which causes the `HTMXRequest` class to fail its initialization since it expects `send` to exist.
This PR simply adds the `empty_receive` and `empty_send` functions as default vaules, which is consistent with the signature in the request class it derives from.
> fix: add default receive and send parameter values for HTMXRequest

- litestar/contrib/jwt/jwt_auth.py
- litestar/contrib/jwt/middleware.py
- litestar/middleware/_utils.py
- litestar/middleware/authentication.py
- litestar/security/base.py
- poetry.lock
- tests/unit/test_contrib/test_jwt/test_integration.py
This PR fixes an issue where OPTIONS requests got 401. This issue emerged due to a fix for the OPTIONS handler registration - which surfaced it. The solution was to add configuration for the HTTP methods to exclude from authentication and give defaults to the JWT auth middleware that mirrors the previous (buggy) behavior.
> fix(auth-middleware): add configuration for HTTP methods to skip when authenticating

- docs/usage/openapi.rst
Fix a broken link in the OpenAPI docs that made our docs builds fail
> docs(openapi): Fix stdlib link

- litestar/_openapi/schema_generation/examples.py
- litestar/openapi/controller.py
- tests/unit/test_openapi/test_integration.py
- tests/unit/test_openapi/test_parameters.py
- This PR corrects the encoding of the OpenAPI schema into JSON and YAML when the `create_examples` flag is set to `True` in the `OpenAPIConfig`
- Fixes #2133
> fix: openapi schema generation when creating examples with Pydantic models

- litestar/_asgi/routing_trie/mapping.py
- litestar/_asgi/utils.py
- litestar/app.py
- litestar/security/session_auth/middleware.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
> chore(backport): #2192 - remove usages of deprecated ExceptionHandlerMiddleware `debug` parameter

- docs/index.rst
…itestar.dev/latest/tutorials/dto-tutorial/09-updating.html\#patch-handlers
This PR fixes an apparent typo in the Extended Example on the index.rst homepage.
When running the hello world Extended Example, I was unable to proceed due to this error:
```litestar.exceptions.dto_exceptions.InvalidAnnotationException: DTO narrowed with …
```
> docs(DTO): Replace PartialDataDTO with DTOData

- litestar/_openapi/parameters.py
- tests/unit/test_kwargs/test_path_params.py
- tests/unit/test_openapi/test_integration.py
This PR does the following:
1. fix #2222 - where optional path parameters caused a 500 error to be raised.
2. fix another bug where a query parameter was created for an optional path parameter.
> fix(schema): handling of optional path parameters

- litestar/stores/file.py
- tests/unit/test_stores.py
- This PR uses `os.replace` instead of `shutil.move` for renaming files to ensure atomicity.
> fix: use os.replace instead of shutil.move for renaming file

- litestar/exceptions/base_exceptions.py
- litestar/exceptions/http_exceptions.py
- tests/unit/test_exceptions.py
1. Set correctly the `detail` attribute on `LitestarException` and `HTTPException` regardless of whether it's passed positionally or by name.
Main branch:
```py
In [1]: from litestar.exceptions import LitestarException, HTTPException
In [2]: LitestarException(detail="foo").detail
Out[2]: 'foo'
In [3]: LitestarException("foo").detail
Out[3]: ''
In [4]: HTTPException(detail="").detail
Out[4]: 'Internal Server Error'
In [5]: HTTPException("").detail
Out[5]: ''
```
This branch:
```py
In [1]: from litestar.exceptions import LitestarException, HTTPException
In [2]: LitestarException(detail="foo").detail
Out[2]: 'foo'
In [3]: LitestarException("foo").detail
Out[3]: 'foo'
In [4]: HTTPException(detail="").detail
Out[4]: 'Internal Server Error'
In [5]: HTTPException("").detail
Out[5]: 'Internal …
```
> fix: Exception detail attribute

- litestar/contrib/sqlalchemy/base.py
- This PR allows importing from `litestar.contrib.sqlalchemy.base` even if `pydantic` is not installed.
> fix: add pydantic types to sqlalchemy registry only if pydantic is installed

- litestar/cli/_utils.py
- litestar/cli/main.py
- tests/unit/test_cli/test_cli.py
- tests/unit/test_cli/test_core_commands.py
- tests/unit/test_cli/test_env_resolution.py
- This PR fixes a bug which caused the `--app-dir` option to the `litestar` CLI to not be propagated during autodiscovery.
- Fixes #2266 
I am unclear what kind of tests should be written for this, since …
> fix: Ensure app-dir is appended to path during autodiscovery.

- README.md
- docs/index.rst
Litestar fullstack by Cofin It's a great job of reference and It had help many people that where looking how to implement `x` thing.
-
> docs: Add `litestar-fullstack` to README and docs

- docs/topics/sync-vs-async.rst
- Hopefully make the note more clear/accurate
- #2275
> chore: Make Async Docs Note More Clear

- litestar/response/base.py
- litestar/response/streaming.py
- tests/unit/test_response/test_base_response.py
- tests/unit/test_response/test_redirect_response.py
- This PR sets the `content-length` header by default even if the length of the body is 0.
> fix: set content length header by default

- .pre-commit-config.yaml
This isn't feasible as it requires everyone updating the `poetry.lock` to have the exact same version of poetry.
> chore: remove poetry lock from pre-commit

- docs/examples/contrib/sqlalchemy/sqlalchemy_async_repository.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_declarative_models.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_extension.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
- Fixed documentation examples under /contrib/sqlalchemy
- Added `expire_on_commit=False` to prevent errors from mixing sync and async context
- Updated Pydantic usage for V2
-
No issues on GitHub but two threads on Discord
> docs: Fix async sessions, Pydantic V2

- docs/examples/templating/returning_templates_jinja.py
- docs/examples/templating/returning_templates_mako.py
- docs/examples/templating/template_functions_jinja.py
- docs/examples/templating/template_functions_mako.py
- docs/examples/templating/template_functions_minijinja.py
Adds a missing `sync_to_thread=False` for the template docs examples
> docs(templates): Add missing sync_to_thread for examples

- litestar/handlers/http_handlers/_utils.py
- litestar/response/base.py
- litestar/response/file.py
- litestar/response/redirect.py
- litestar/response/streaming.py
- litestar/response/template.py
- litestar/utils/__init__.py
- litestar/utils/deprecation.py
- litestar/utils/helpers.py
- tests/unit/test_datastructures/test_headers.py
- tests/unit/test_response/test_base_response.py
- tests/unit/test_response/test_file_response.py
- tests/unit/test_response/test_response_to_asgi_response.py
- tests/unit/test_response/test_streaming_response.py
Update `ASGIResponse`, `Response` and friends to address a few issues related to headers:
- If `encoded_headers` were passed in at any point, they were mutated within responses, leading to a growing list of headers with every response
- While mutating `encoded_headers`, the checks performed to assert a value was (not) already present, headers were not treated case-insensitive
- Unnecessary work was performed while converting cookies / headers into an encoded headers list
This was fixed by:
- Removing the use of and deprecate `encoded_headers`
- Handling headers on `ASGIResponse` with `MutableScopeHeaders`, which allows for case-insensitive membership tests, `.setdefault` operations etc
Closes #2196.
<hr>
Please review this one thoroughly as it changes some low level stuff that we don't …
> fix: #2196 - incorrect handling of mutable headers in ASGIResponse

- docs/examples/contrib/jwt/using_jwt_auth.py
- litestar/contrib/jwt/jwt_auth.py
- tests/unit/test_contrib/test_jwt/test_auth.py
- tests/unit/test_contrib/test_jwt/test_token.py
This PR adds `token_extras` to both `login()` and `create_token()` methods, to allow the definition of the `extras` JWT field.
> feat(contrib-jwt): Add parameters to set the JWT `extras` field

- pyproject.toml
Looking at https://github.com/litestar-org/litestar/pull/2325 I've noticed that `noww` is not a registered marker. Later, I've noticed that `pytest` does not check any existing markers or any existing configuration options. I propose to fix that.
See:
```
Unregistered marks applied with the @pytest.mark.name_of_the_mark decorator will always emit a warning in order to avoid silently doing something surprising due to mistyped names. As described in the previous section, you can disable the warning for custom marks by registering them in your pytest.ini file or using a custom pytest_configure hook.
When the --strict-markers command-line flag is passed, any unknown marks applied with the @pytest.mark.name_of_the_mark decorator will trigger an error. You can enforce this validation in your …
```
> test: use stricter pytest config

- docs/usage/routing/handlers.rst
- Renders the code block without removing the imports so that the necessity of the feature is better conveyed.
Before 
After
- Closes #2320
> docs(signature-namespace): Fix code block to render without removing the imports

- .github/workflows/ci.yaml
- pyproject.toml
- tests/unit/test_file_system.py
- tests/unit/test_template/test_builtin_functions.py
One more check that I forgot in https://github.com/litestar-org/litestar/pull/2327
Looks like we have several `xfail` tests: 
```
» ag xfail
tests/unit/test_file_system.py
27:@pytest.mark.xfail(sys.platform == "win32", reason="permissions equivalent missing on windows")
53:@pytest.mark.xfail(sys.platform == "win32", reason="Suspected fsspec issue")
85:@pytest.mark.xfail(sys.platform == "win32", reason="permissions equivalent missing on windows")
tests/unit/test_template/test_builtin_functions.py
18:@pytest.mark.xfail(sys.platform == "win32", reason="For some reason this is flaky on windows")
78:@pytest.mark.xfail(sys.platform == "win32", reason="For some reason this is flaky on windows")
183:@pytest.mark.xfail(sys.platform == "win32", reason="For some reason this is flaky on windows") …
```
> test: use `xfail_strict` for pytest config

- tests/unit/test_response/test_file_response.py
Before:
```
» pytest -k test_asgi_response_encoded_headers
=================================== test session starts ===================================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/sobolev/Desktop/litestar
configfile: pyproject.toml
plugins: anyio-4.0.0, rerunfailures-12.0, hypothesis-6.86.2, timeout-2.1.0, cov-4.1.0, asyncio-0.21.1, mock-3.11.1, xdist-3.3.1, time-machine-2.12.0, Faker-19.6.1, lazy-fixture-0.6.3
asyncio: mode=Mode.AUTO
collected 3268 items / 3265 deselected / 3 selected                                       
tests/unit/test_response/test_base_response.py .                                    [ 33%]
tests/unit/test_response/test_file_response.py .                                    [ 66%] …
```
> test: silence `ResourceWarning` in `test_file_response`

- litestar/middleware/authentication.py
- litestar/types/asgi_types.py
- tests/unit/test_middleware/test_base_authentication_middleware.py
- This PR sets `OPTIONS` as the default value for `exclude_http_methods` in the base authentication middleware class.
- Fixes #2205
> fix: set proper default for `exclude_http_methods` in auth middleware

- .github/workflows/ci.yaml
- .github/workflows/test.yaml
Since we're no longer running integration tests for databases, we don't need long timeouts of 15/30 minutes anymore. This PR drops those.
> chore(ci): drop timeout to 10 minutes, remove integration setup

- tests/unit/test_stores.py
Fixes a `RedisStore` test that would hang with `time-machine` version 2.13.0, because since this version `time.sleep` and `asyncio.sleep` are affected by its patching as well, causing the tests to sleep indefinitely.
Closes #2338.
> fix(tests): `RedisStore` test for `time-machine` 2.13.0

- tests/unit/test_openapi/test_integration.py
Before:
```
tests/unit/test_openapi/test_integration.py::test_pydantic_schema_generation[True]
tests/unit/test_openapi/test_integration.py::test_pydantic_schema_generation[True]
tests/unit/test_openapi/test_integration.py::test_pydantic_schema_generation[False]
tests/unit/test_openapi/test_integration.py::test_pydantic_schema_generation[False]
/home/runner/work/litestar/litestar/.venv/lib/python3.10/site-packages/pydantic/fields.py:792: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'example'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.3/migration/
warn(
```
> test: Fix pydantic warning in `tests/unit/test_openapi/test_integration.py`

- litestar/status_codes.py
There are several differences:
- `Final` does not need value duplication, it is inferenced by type-checkers to be `Literal[value]` automagically
- `Final` does not allow value re-assigning (`x: Literal[1] = 1; x = 1` is allowed)
> chore: use `Final` instead of `Literal` for constants

- litestar/response/base.py
Remove the default value for `encoded_headers` in `Response.to_asgi_response`, that resulted in a `DeprecationWarning` always being raised.
> fix(response): remove encoded_headers default value

- litestar/app.py
Invariance of `list` is too restrictive, for example:
```py
from __future__ import annotations
from typing import Any
from litestar import Litestar
class AioCtxMgr:
"""A dummy context manager."""
async def __aenter__(self) -> None:
pass
async def __aexit__(self, *args: Any) -> None:
pass
ctx_mgrs = [AioCtxMgr()]
Litestar(route_handlers=[], lifespan=ctx_mgrs)
```
Would result in:
```
app.py:20: error: Argument "lifespan" to "Litestar" has incompatible type "list[AioCtxMgr]"; expected "list[Callable[[Litestar], AbstractAsyncContextManager[Any]] | AbstractAsyncContextManager[Any]] | None"  [arg-type]
app.py:20: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
app.py:20: note: Consider using "Sequence" instead, which is covariant
```
Closes …
> fix: app `listeners` param typed as `Sequence`.

- tests/conftest.py
- tests/docker_service_fixtures.py
Before:
```
/home/runner/work/litestar/litestar/tests/conftest.py:316: DeprecationWarning: Call to deprecated close. (Use aclose() instead) -- Deprecated since version 5.0.0.
await client.close()
```
Source: https://github.com/redis/redis-py/blob/cc4bc1a544d1030aec1696baef2861064fa8dd1c/redis/asyncio/client.py#L568-L573
> test: fix `AsyncRedis.close()` deprecation warning

- litestar/types/callable_types.py
- litestar/types/internal_types.py
This PR replaces this pattern:
```py
from typing import TYPE_CHECKING, Any
if TYPE_CHECKING:
from typing_extensions import TypeAlias
from litestar import Thing
ThingAlias: TypeAlias = Thing
else:
ThingAlias: TypeAlias = Any
```
My best guess is that this pattern was some workaround for circular dependencies before we introduced `__future__.annotations`.
I believe these changes will be beneficial as:
- the current pattern is non-standard (at least in my experience)
- the current pattern causes the types to be documented as `Any` in the API docs.
Example of current API docs for alias types:
[//]: # "- follow Litestar's …
> fix: remove runtime assignment of type aliases to `Any`.

- litestar/middleware/exceptions/_debug_response.py
- tests/unit/test_middleware/test_exception_handler_middleware.py
Avoid implicit conversion to `bool` in `_debug_response.py` as this causes problems with some sqlalchemy classes, where instead of the original DB error being propagated, a `TypeError` is raised. See #2381 
Closes #2381
> fix: avoid conversion to bool in debug response

- docs/examples/contrib/sqlalchemy/sqlalchemy_async_repository.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_declarative_models.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_repository_extension.py
- docs/examples/contrib/sqlalchemy/sqlalchemy_sync_repository.py
- docs/examples/pagination/using_offset_pagination_with_sqlalchemy.py
- Remove references to `SQLAlchemyAsyncConfig.create_engine` from docs; use `SQLAlchemyAsyncConfig.get_engine` in examples instead.
- Closes #2374
> docs: remove references to `SQLAlchemyAsyncConfig.create_engine`

- litestar/_openapi/schema_generation/schema.py
Only import function to create OpenAPI examples when needed; In the case where users have turned off generating examples this import is not needed at all.
This cuts the time it takes to `import litestar` in half by avoiding an expensive `polyfactory` import and is the first step in making polyfactory optional.
> feat(OpenAPI): lazy import example creator

- litestar/_asgi/routing_trie/mapping.py
- litestar/constants.py
- litestar/middleware/compression.py
- litestar/middleware/response_cache.py
- litestar/routes/http.py
- tests/e2e/test_response_caching.py
- tests/unit/test_middleware/test_compression_middleware.py
Fix #1301 by introducing a moving caching to a hybrid approach that records outgoing ASGI messages within a middleware and hydrates them within the route when responding to a request.
There are some additional benefits to this approach:
- Improved performance and reduced size of the stored responses by switching from pickle to MessagePack and storing already compressed responses and only compressing them once
- Reduced overhead because the middleware can be applied ahead of time to only those routes that have caching enabled instead of checking each request
- Every response can now be cached without issues; Previously only those that could be pickled could be cached
> fix: #1301 - Apply compression before caching

- .github/PULL_REQUEST_TEMPLATE.md
- litestar/app.py
- litestar/contrib/pydantic/__init__.py
- litestar/contrib/pydantic/pydantic_init_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- tests/unit/test_contrib/test_pydantic/test_plugin_serialization.py
- tests/unit/test_openapi/test_config.py
- This PR adds a new `PydanticPlugin` that allows for customization of the Pydantic integration.  Currently, the only feature is to let a user export a model by alias.  When setting this, it applies to OpenAPI and responses.
- Closes #2373
> feat: allow customization of Pydantic integration

- docs/migration/flask.rst
- docs/usage/middleware/creating-middleware.rst
- docs/usage/responses.rst
- docs/usage/routing/handlers.rst
- Updates a stale parameter found in #2407/#2409. ``url`` to ``path`` in ``Redirect``
- Closes #2409
> fix(docs): update ``url`` to ``path`` in ``Redirect`` to resolve #2407

- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- Makefile
- docs/usage/stores.rst
- pdm.lock
- pyproject.toml
- tests/docker-compose.yml
- tests/docker_service_fixtures.py
This PR does a variety of PDM cleanup activities
- Applies TOML linting to the `pyproject.toml` and validated against the `PyProject` specification
- Removed unsupported group attribute and pinned dev install of `exceptiongroup` to `<3.11`
- Removes `pre-commit install` from `Makefile`
- add `pdm install -G:all` to PDM installation to grab optional dev dependencies
- Remove PDM lock check from pre-commit.  This has a similar issue as with poetry and leads to many failures due to hash conflicts
- Adds `README.md` to codespell.  The latest updates a raising errors for proper names
- Adds `httptools` and `uvloop` to the `standard` group.  These are both performance optionals for `uvicorn` that normal come with the `standard` package.  `websockets` is the only `standard` dependency from …
> chore: additional CI and PDM cleanup

- litestar/_kwargs/extractors.py
- tests/unit/test_kwargs/test_layered_params.py
Add the source of the expected parameter to the error message.
Before:
```json
{
"status_code": 400,
"detail": "Missing required parameter foo for url http://testerver.local"
}
```
After:
```json
{
"status_code": 400,
"detail": "Missing required header parameter 'foo' for url http://testerver.local"
}
```
> feat(params): Improve error messages for missing required parameters

- litestar/_kwargs/extractors.py
- litestar/_parsers.py
- litestar/connection/base.py
- litestar/datastructures/headers.py
- litestar/datastructures/multi_dicts.py
- tests/unit/test_parsers.py
~~- Use `MultiDict` instead of a `dict[str, str]` to inject into route handlers. This is non-breaking as `MultiDict` behaves exactly like a regular dict outside for its additional methods~~ (Turns out this is not non-breaking)
- Remove redundancies in headers parsing
> fix(connection): Simplify connection header parsing

- docs/usage/testing.rst
The last code example at the docs/usage/testing has a little code formating error: wrong indent
It is just a little fix for it
> docs: fix docs/usage/testing code indent

- litestar/dto/msgspec_dto.py
As suggested [here](https://github.com/jcrist/msgspec/pull/566#pullrequestreview-1671507706), the `type_info()` function is overkill for this application.
-
-
> refactor: replace `msgspec.inspect.type_info()` with `msgspec.structs.fields()`

- litestar/types/asgi_types.py
- litestar/types/callable_types.py
- litestar/types/internal_types.py
- tests/unit/test_deprecations.py
`LitestarType` currently exists as an alias for `Litestar`, though the rationale behind its existence is unclear. This alias might introduce confusion as the name would more appropriately alias `type[Litestar]`.
This PR removes internal use of, and deprecates `LitestarType`.
-
-
> refactor: Deprecate `LitestarType`.

- .gitignore
- litestar/types/internal_types.py
- pdm.lock
- pyproject.toml
- Puts the `full` group back how it was
- Update lockfile
- Move `__getattr__` deprecation warning from `2.3.0` to `2.2.1`
- Fix mypy CI issue
- Closes #2434
> fix(infra): add ``full`` back to optional dependencies

- .github/workflows/ci.yml
Right now the name of the job is quite cryptic (especially the `1` / `2` part):
With this change it will be a bit more verbose and readable.
> ci: use better name for `test` job

- .github/workflows/test.yml
- pdm.lock
- pyproject.toml
Due to piccolo extra, we lock to pydantic v1 which causes v1 to be installed into development environments when using `pdm install`.
This PR forces pydantic v2 for dev environments at the expense of locking to an earlier version of piccolo.
-
-
> build: add pydantic>2 to dev deps.

- pdm.lock
I believe this is the cause of the current error building dev docs: https://github.com/litestar-org/litestar/actions/runs/6520536684/job/17708175205#step:8:116
-
-
> chore: Updates pdm.lock content hash.

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .pre-commit-config.yaml
- litestar/logging/config.py
- litestar/logging/standard.py
- litestar/middleware/logging.py
- pdm.lock
- pyproject.toml
- sonar-project.properties
- tests/unit/test_cli/test_session_commands.py
- tests/unit/test_logging/test_logging_config.py
- tests/unit/test_logging/test_structlog_config.py
- Add Python 3.12 as a target - [3.12 Release Schedule](https://peps.python.org/pep-0693/#schedule) is slated to arrive within the next 3 months, with RC 1 coming at the first of next week
- Closes #1862
> feat: add support for `Python@3.12`

- docs/examples/signature_namespace/app.py
- docs/usage/routing/handlers.rst
- litestar/app.py
- litestar/config/app.py
- litestar/controller.py
- litestar/handlers/base.py
- litestar/router.py
- litestar/testing/helpers.py
- litestar/utils/signature.py
- tests/unit/test_connection/test_websocket.py
- tests/unit/test_dto/test_factory/test_integration.py
- tests/unit/test_dto/test_integration.py
- tests/unit/test_handlers/test_websocket_handlers/test_listeners.py
- tests/unit/test_openapi/test_integration.py
- tests/unit/test_utils/test_signature.py
- This PR adds a new argument to the app and layers, `signature_types`.
Types in this collection are added to `signature_namespace` using the type's `__name__` attribute.
The objective is to provide a nicer interface when adding names to the signature namespace without modifying the type name, e.g.: `signature_namespace={"Model": Model}` is equivalent to `signature_types=[Model]`.
The implementation makes it an error to supply a type in `signature_types` that has a value for `__name__` already in the signature namespace.
It will also throw an error if an item in `signature_types` has no `__name__` attribute.
-
> feat: `signature_types` application arg.

- litestar/response/template.py
- Remove the unused `template_engine` parameter from the docstring of `Template` response class.
- Closes #2454
> docs: remove unused parameter from 'Template' response

- litestar/logging/config.py
Only add "console" handler to `default_handlers["queue_listener"]` in >= 3.12.
Closes #2477
-
-
> fix: logging default handler compat.

- .gitignore
- Makefile
Use the [mypy daemon](https://mypy.readthedocs.io/en/stable/mypy_daemon.html) to speed up type checking when running locally.
> chore: use dmypy to speed up local type checking

- docs/examples/templating/engine_instance_minijinja.py
- docs/examples/templating/returning_templates_minijinja.py
- docs/examples/templating/template_engine_minijinja.py
- docs/examples/templating/template_functions_minijinja.py
- litestar/contrib/minijinja.py
- litestar/contrib/minijnja.py
- tests/unit/test_deprecations.py
- tests/unit/test_template/test_built_in.py
- tests/unit/test_template/test_builtin_functions.py
- tests/unit/test_template/test_context.py
- tests/unit/test_template/test_csrf_token.py
- tests/unit/test_template/test_template.py
This PR corrects the misspelled module name, while leaving the incorrect namespace available but deprecated.
Closes #2484
> fix: rename `contrib.minijnja` to `contrib.minijinja`

- litestar/contrib/jinja.py
- litestar/contrib/mako.py
- litestar/contrib/minijinja.py
- litestar/template/base.py
This PR swaps use of `pydantic.DirectoryPath` for `pathlib.Path` as annotation for our `TemplateEngineProtocol`'s directory parameter.
Motivation is to decouple pydantic from template use.
-
> refactor: remove pydantic DirectoryPath from TemplateEngineProtocol

- litestar/_openapi/schema_generation/schema.py
- litestar/contrib/attrs/attrs_schema_plugin.py
- litestar/contrib/pydantic/pydantic_schema_plugin.py
- litestar/typing.py
- tests/unit/test_contrib/test_attrs/test_schema_plugin.py
- tests/unit/test_contrib/test_pydantic/test_schema_plugin.py
- tests/unit/test_openapi/test_schema.py
- makes `_get_type_schema_name()` receive the field definition. This removes the need to call `get_args()` on the annotation as we've already done it.
- removed a use of `get_origin_or_inner_type()`
- fixed type error
-
> refactor: my last pass

- litestar/_openapi/parameters.py
- tests/unit/test_openapi/test_parameters.py
Parameter examples should be a mapping of example names mapped to `Example` objects.
This PR builds such a mapping for parameters that have examples defined.
This PR does not modify existing behavior that adds examples to the parameter's schema object.
Before PR:
After PR:
swagger:
redoc:
elements:
Closes #2494
> fix: rendering of openapi parameter examples

- litestar/utils/signature.py
- tests/unit/test_utils/test_signature.py
Prior to python 3.11, if a func or method param has a default of `None`, then `get_type_hints()` will automagically wrap the annotation in `Union[T, NoneType]`.
Sometimes this is flattened out before we receive the type back:
```python-console
Python 3.8.17 (default, Sep 14 2023, 13:58:34)
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing import Optional
>>> from typing_extensions import Annotated, get_type_hints
>>>
>>> def simple(p: Optional[str] = None) -> None: ...
...
>>> get_type_hints(simple)
{'p': typing.Union[str, NoneType], 'return': <class 'NoneType'>}
```
However, if that type is annotated:
```python-console
>>> def annotated(p: Annotated[Optional[str], ...] = None) -> None: ...
...
>>> get_type_hints(annotated)
{'p': …
```
> fix: get_type_hints() optional param compatibility
